import fs from 'node:fs';

const bankPath='public/banco/tratamientos_adultos.json';
const manifestPath='public/banco/manifest.json';
const bank=JSON.parse(fs.readFileSync(bankPath,'utf8'));
const topic='Tratamientos transdiagnósticos';
const F='Fonseca-Pedrero, E. (coord.). Manual de tratamientos psicológicos: adultos. Pirámide, cap. 4, pp. 117-157.';
const FP='Fonseca-Pedrero, E. (coord.). Manual de tratamientos psicológicos: adultos. Pirámide, cap. 6, pp. 201-224; Penadés, R., López-Santiago, J. y Belloch, A. (coords.) (2024). Manual de tratamientos en psicología clínica: guía práctica en adultos. McGraw Hill, cap. 31, pp. 739-762.';
const q=(n,e,o,c,x,r=F)=>({id:`R0PIR_TA_TRANSDIAG_20260831_${String(n).padStart(3,'0')}`,s:'Tratamientos Adultos',t:[topic],origen:'creada',convocatoria:null,pa:null,e,o:{a:o[0],b:o[1],c:o[2],d:o[3]},c,x,r,v:'VALIDADA_ORIGINAL'});
const add=[
q(1,'¿Qué consecuencia del aumento de categorías diagnósticas impulsó especialmente el enfoque transdiagnóstico?', ['La desaparición de la comorbilidad.','El incremento de la comorbilidad y el cuestionamiento de límites categoriales rígidos.','La identificación de marcadores biológicos para todos los trastornos.','La sustitución de la evaluación clínica por pruebas de laboratorio.'],'b','La b es correcta: la elevada comorbilidad mostró que muchos trastornos comparten procesos. La a afirma lo contrario; la c es falsa porque no existen marcadores para la mayoría; y la d no se deriva del enfoque transdiagnóstico.'),
q(2,'¿Cuáles son los tres supuestos clásicos del modelo categorial que se han cuestionado?', ['Que las categorías sean discretas, mutuamente excluyentes y exhaustivas.','Que sean dimensionales, contextuales y funcionales.','Que integren procesos comunes, específicos y protectores.','Que dependan de antecedentes, respuestas y consecuencias.'],'a','La a es correcta. La b describe rasgos de alternativas dimensionales; la c mezcla tipos de procesos clínicos; y la d corresponde a componentes de un análisis funcional, no a supuestos categoriales.'),
q(3,'Desde la teoría de redes aplicada a la psicopatología, ¿cómo se entienden los trastornos?', ['Como enfermedades latentes que causan todos los síntomas.','Como categorías naturales con fronteras exactas.','Como patrones formados por síntomas conectados que pueden influirse mutuamente.','Como errores de medición sin relación clínica.'],'c','La c es correcta: la red se centra en conexiones entre síntomas. La a mantiene el modelo de entidad latente; la b presupone límites rígidos; y la d niega indebidamente la relevancia clínica de los síntomas.'),
q(4,'¿Qué crítica se formula a los tratamientos empíricamente validados excesivamente protocolizados?', ['Que impiden utilizar cualquier técnica psicológica.','Que pueden favorecer una aplicación inflexible y reducir la atención a la persona concreta.','Que carecen siempre de ensayos controlados.','Que solo pueden administrarse en grupo.'],'b','La b es correcta: la crítica se dirige a la mentalidad rígida de “libro de cocina”. La a es absoluta y falsa; la c ignora que muchos TEV se apoyan en ECA; y la d confunde protocolización con formato grupal.'),
q(5,'Según Jerome Frank, ¿qué característica comparten quienes acuden a distintas prácticas terapéuticas?', ['Desmoralización.','Psicosis.','Baja inteligencia.','Ausencia de apoyo social.'],'a','La a es correcta: Frank sitúa la desmoralización, pérdida de ánimo y esperanza, como elemento común. La b, c y d pueden aparecer en algunos casos, pero no constituyen la característica compartida por todas las personas que buscan ayuda.'),
q(6,'¿Cuál de los siguientes NO pertenece a los cuatro factores curativos comunes descritos por Jerome Frank?', ['Una relación de confianza con un agente sanador reconocido.','Un lugar de curación.','Un mito explicativo y un rito terapéutico.','Un diagnóstico categorial idéntico para todos los pacientes.'],'d','La d es correcta porque no forma parte del modelo. La relación de confianza, el lugar de curación, el mito que explica el problema y el rito o procedimiento constituyen los cuatro factores comunes.'),
q(7,'En el modelo de Frank, ¿qué significan respectivamente “mito” y “rito”?', ['Diagnóstico y pronóstico.','Marco explicativo del problema y procedimientos empleados para aliviarlo.','Alianza y empatía.','Lugar de tratamiento y credenciales del terapeuta.'],'b','La b es correcta. La a no recoge el sentido de los términos; la c enumera componentes relacionales; y la d alude a otros factores comunes, pero no al mito y al rito.'),
q(8,'¿Quiénes utilizaron primero el término “transdiagnóstico” en el ámbito de los tratamientos psicológicos descrito en el manual?', ['Barlow et al. en 1990, para el pánico.','Fairburn et al. en 2003, para los trastornos alimentarios.','Frank en 1982, para los factores comunes.','Powers en 1973, para el control perceptivo.'],'b','La b es correcta: Fairburn y colaboradores lo aplicaron a los TCA en 2003; Barlow lo empleó después para los trastornos emocionales. Frank trabajó factores comunes y Powers desarrolló la PCT, por lo que a, c y d no responden al origen terminológico señalado.', 'Fairburn, C. G., Cooper, Z. y Shafran, R. (2003). Cognitive behaviour therapy for eating disorders: a transdiagnostic theory and treatment. Behaviour Research and Therapy, 41, 509-528; '+F),
q(9,'En el modelo transdiagnóstico de Fairburn para los TCA, ¿cuál es un proceso mantenedor adicional o genérico?', ['Perfeccionismo clínico.','Alucinaciones auditivas.','Amnesia disociativa.','Fuga de ideas.'],'a','La a es correcta. Junto con baja autoestima, intolerancia emocional y dificultades interpersonales, el perfeccionismo clínico puede mantener el TCA. Las opciones b, c y d pertenecen a otros dominios psicopatológicos.'),
q(10,'¿Qué secuencia terapéutica propusieron Clark y Taylor cuando coexisten procesos comunes y específicos?', ['Aplicar únicamente el tratamiento específico.','Comenzar por un tratamiento transdiagnóstico y añadir después uno específico si es necesario.','Evitar cualquier intervención hasta eliminar la comorbilidad.','Administrar simultáneamente todos los protocolos disponibles.'],'b','La b es correcta: se interviene primero sobre procesos comunes y después sobre lo específico. La a ignora los mecanismos compartidos; la c pospone injustificadamente la ayuda; y la d aumenta complejidad sin una formulación funcional.'),
q(11,'¿En qué teoría se basa el Método de los Niveles (MOL)?', ['Teoría del apego.','Teoría del control perceptivo de Powers.','Teoría bifactorial de Mowrer.','Teoría de los marcos relacionales.'],'b','La b es correcta. La teoría del apego sustenta especialmente EFT; Mowrer explica aprendizaje del miedo; y la teoría de los marcos relacionales fundamenta ACT, no MOL.'),
q(12,'Según la teoría del control perceptivo, ¿cuáles son los tres componentes esenciales del control?', ['Percepción, comparación y acción.','Emoción, cognición y motivación.','Antecedente, conducta y consecuencia.','Atención, memoria y lenguaje.'],'a','La a es correcta: sensor, comparador y efector se traducen en percepción, comparación y acción. La b y d son agrupaciones psicológicas generales; la c corresponde al análisis funcional, no a los componentes de la PCT.'),
q(13,'En la teoría del control perceptivo, el feedback negativo sirve para:', ['Aumentar la discrepancia entre la percepción y el estándar.','Reducir la diferencia entre la situación percibida y el estado preferido.','Eliminar cualquier meta de orden superior.','Reforzar positivamente una respuesta observable.'],'b','La b es correcta: el sistema actúa para reducir el error. La a describe feedback positivo; la c no es objetivo del control; y la d confunde feedback sistémico con reforzamiento operante.'),
q(14,'¿Cómo explica MOL el origen de buena parte de la angustia psicológica?', ['Por un déficit intelectual general.','Por el conflicto entre dos metas o sistemas de control incompatibles.','Por falta de reforzadores primarios exclusivamente.','Por una lesión neurológica necesaria.'],'b','La b es correcta: cada sistema intenta corregir su error y agrava el del otro. La a, c y d reducen indebidamente el problema a causas que no definen el modelo.'),
q(15,'En MOL, ¿qué diferencia hay entre niveles inferiores y superiores de la jerarquía de control?', ['Los inferiores expresan el para qué y los superiores el cómo.','Los inferiores se refieren a acciones y estados perceptivos; los superiores, a valores y principios que indican el para qué.','Los inferiores son conscientes y los superiores siempre inconscientes.','Los niveles no guardan ninguna relación jerárquica.'],'b','La b es correcta. La a invierte cómo y para qué; la c establece una separación consciente-inconsciente que MOL no exige; y la d niega la organización jerárquica central del modelo.'),
q(16,'¿Qué es la reorganización en MOL?', ['Un aprendizaje verbal impartido por el terapeuta.','Un proceso automático que modifica la jerarquía de control ante un conflicto persistente.','Una técnica de exposición con prevención de respuesta.','Una forma de castigo de pensamientos disfuncionales.'],'b','La b es correcta: la reorganización puede generar soluciones novedosas y no necesita aprendizaje directo. La a atribuye el cambio a instrucción; la c pertenece a otros tratamientos; y la d no forma parte de MOL.'),
q(17,'¿Qué función cumplen las preguntas breves y claras del terapeuta en MOL?', ['Imponer una interpretación diagnóstica.','Mantener la conciencia del cliente en la fuente del conflicto y favorecer la subida de nivel.','Distraer de cualquier emoción intensa.','Comprobar si el cliente memoriza el manual.'],'b','La b es correcta. La a contradice la curiosidad genuina del terapeuta; la c evita el material relevante; y la d convierte la intervención en una prueba de conocimientos.'),
q(18,'En MOL, una mueca, una pausa repentina o un cambio de tono mientras el cliente habla se consideran:', ['Disrupciones que pueden señalar un cambio en la conciencia.','Conductas que deben extinguirse.','Pruebas de simulación.','Efectos adversos farmacológicos.'],'a','La a es correcta: se exploran porque pueden indicar ascenso de nivel y proximidad a la reorganización. La b, c y d atribuyen funciones no sustentadas por MOL.'),
q(19,'¿Qué rasgo caracteriza el formato del Método de los Niveles?', ['El terapeuta fija siempre 40 sesiones.','El cliente puede decidir número, frecuencia, duración y tema de las sesiones.','Solo puede aplicarse en hospitalización.','Requiere que el terapeuta conozca todos los detalles del problema.'],'b','La b es correcta y refleja su flexibilidad. La a contradice su posible brevedad; la c restringe falsamente el contexto; y la d es falsa porque puede trabajarse incluso usando un término neutro para preservar detalles confidenciales.'),
q(20,'¿Cuál es la principal limitación señalada para MOL?', ['No puede aplicarse a problemas emocionales.','Su implementación depende mucho de la habilidad clínica para detectar y trabajar disrupciones.','Necesita medicación en todos los casos.','Carece por completo de base teórica.'],'b','La b es correcta: los principios son generales y su aplicación exige entrenamiento sénior, dificultando la replicabilidad. La a y c son falsas; la d ignora su fundamento en la PCT.', 'Mansell, W., Carey, T. A. y Tai, S. J. (2012). A Transdiagnostic Approach to CBT Using Method of Levels Therapy. Routledge; '+F),
q(21,'¿Cómo se clasifica la Terapia Centrada en las Emociones (EFT)?', ['Humanista-experiencial.','Psicodinámica clásica exclusivamente.','Conductismo radical.','Terapia farmacológica.'],'a','La a es correcta. EFT integra prácticas centradas en el cliente y Gestalt. La b recoge solo un parentesco parcial; la c no describe su orientación; y la d no es una psicoterapia.'),
q(22,'¿Qué autores desarrollaron originalmente EFT integrando aportaciones de Rogers y Perls?', ['Sue Johnson y Les Greenberg.','Barlow y Farchione.','Powers y Carey.','Fairburn y Shafran.'],'a','La a es correcta. Barlow y Farchione se asocian al PU; Powers y Carey a PCT/MOL; y Fairburn y Shafran al enfoque transdiagnóstico de los TCA.'),
q(23,'¿Qué teoría proporciona una base central para EFT?', ['Teoría del apego de Bowlby.','Teoría de detección de señales.','Modelo de indefensión aprendida.','Teoría de la identidad social.'],'a','La a es correcta y fundamenta el vínculo emocional. Las opciones b, c y d pertenecen a otros ámbitos teóricos y no constituyen la base central de EFT.'),
q(24,'Según EFT, ¿cuándo pueden volverse problemáticas las emociones?', ['Cuando se experimenta cualquier emoción intensa.','Cuando traumas previos o aprendizajes llevan a ignorarlas, descartarlas o responder de forma desadaptativa.','Solo cuando son positivas.','Únicamente si no pueden verbalizarse en la primera sesión.'],'b','La b es correcta. La a patologiza la intensidad por sí sola; la c excluye sin fundamento las emociones negativas; y la d establece una condición temporal y verbal inexistente.'),
q(25,'En EFT, un “esquema emocional” se concibe como:', ['Una entidad fija y puramente verbal.','Una organización dinámica, frecuentemente preverbal y orientada a la acción.','Un diagnóstico DSM.','Una lista inmutable de pensamientos automáticos.'],'b','La b es correcta. La a y d niegan su carácter dinámico; la c confunde un proceso experiencial con una categoría diagnóstica.'),
q(26,'¿Qué distingue la resolución completa de la parcial en EFT?', ['La completa evita reexperimentar emociones.','La completa añade revisión de autoesquemas, nuevas respuestas emocionales y empoderamiento para el cambio.','La parcial exige siempre más de 40 sesiones.','La parcial elimina definitivamente toda emoción negativa.'],'b','La b es correcta. La a contradice el reprocesamiento; la c confunde nivel de resolución con duración; y la d plantea un objetivo imposible y ajeno a EFT.'),
q(27,'¿Cuál es el orden inicial correcto de las fases de reprocesamiento emocional en EFT?', ['Identificación, reexperimentación y exploración de los dos aspectos de la experiencia.','Empoderamiento, diagnóstico y castigo.','Exposición interoceptiva, habituación y prevención de respuesta.','Interpretación, medicación y seguimiento.'],'a','La a es correcta. Las restantes mezclan procedimientos ajenos o alteran la secuencia del reprocesamiento emocional.'),
q(28,'¿Para qué se utiliza principalmente el diálogo de la silla vacía en EFT?', ['Para asuntos inconclusos y sentimientos duraderos hacia otra persona significativa.','Para medir la inteligencia.','Para inducir sensaciones físicas de pánico.','Para establecer una jerarquía de exposición interoceptiva.'],'a','La a es correcta. La b es evaluación psicométrica; la c y d corresponden a exposición interoceptiva y no al trabajo de silla vacía.'),
q(29,'¿Cuál es el objetivo del diálogo de las dos sillas en EFT?', ['Integrar aspectos opuestos del yo implicados en un conflicto interno.','Confrontar a dos familiares reales.','Eliminar el vínculo terapéutico.','Comparar dos diagnósticos categoriales.'],'a','La a es correcta. La b confunde una técnica imaginaria con terapia familiar; la c contradice el marco empático; y la d no constituye el objetivo de la técnica.'),
q(30,'¿Qué nivel de evidencia diferencia el manual para EFT?', ['1+/A en problemas de pareja y 2+/C como tratamiento transdiagnóstico.','3/D en pareja y 1++/A en todo trastorno.','1++/A exclusivamente en psicosis.','No se ha evaluado en ningún ámbito.'],'a','La a es correcta. La b invierte y altera los niveles; la c atribuye evidencia exclusiva no descrita; y la d ignora los estudios revisados.', 'Greenberg, L. S. et al. (2015). Emotion-Focused Therapy; '+F),
q(31,'¿Qué trastornos incluye principalmente el concepto de “trastornos emocionales” del Protocolo Unificado?', ['Trastornos de ansiedad y trastornos del estado de ánimo.','Solo esquizofrenia y trastornos neurocognitivos.','Únicamente trastornos de personalidad.','Solo trastornos por consumo de sustancias.'],'a','La a es correcta. Las demás restringen el concepto a grupos que no constituyen su núcleo original, aunque el PU se haya estudiado en problemas adicionales.',FP),
q(32,'¿Cuál es el denominador común central que aborda el Protocolo Unificado?', ['Déficits de regulación emocional y respuestas evitativas ante emociones intensas.','Pérdida de memoria episódica.','Ausencia de cualquier emoción.','Dependencia exclusiva de reforzadores materiales.'],'a','La a es correcta. La b pertenece a neuropsicología; la c confunde regulación con ausencia emocional; y la d no define el modelo transdiagnóstico del PU.',FP),
q(33,'¿Qué componentes integran la triple vulnerabilidad de los trastornos emocionales?', ['Biológica generalizada, psicológica generalizada y psicológica específica.','Genética, farmacológica y social exclusivamente.','Atencional, mnésica y lingüística.','Manía, depresión y psicosis.'],'a','La a es correcta. Las otras opciones agrupan factores o síntomas distintos, pero no reproducen el modelo de triple vulnerabilidad.',FP),
q(34,'En el PU, ¿qué instrumento breve evalúa gravedad e interferencia de la ansiedad durante la última semana?', ['OASIS.','ODSIS.','PANSS.','WAIS-IV.'],'a','La a es correcta. ODSIS evalúa depresión; PANSS síntomas de esquizofrenia; y WAIS-IV capacidad intelectual.',FP),
q(35,'En el PU, ¿qué instrumento breve evalúa gravedad e interferencia de la depresión durante la última semana?', ['OASIS.','ODSIS.','Y-BOCS.','MMPI-2.'],'b','La b es correcta. OASIS se centra en ansiedad; Y-BOCS evalúa síntomas obsesivo-compulsivos; y MMPI-2 es un inventario amplio de personalidad y psicopatología.',FP),
q(36,'¿Cuál es el primer paso de la formulación de caso desde el PU?', ['Identificar problemas actuales, emociones intensas, reacciones aversivas y estrategias de evitación emocional.','Aplicar exposición sin evaluación previa.','Asignar un único diagnóstico y omitir la comorbilidad.','Eliminar todos los objetivos personales del cliente.'],'a','La a es correcta. La b omite formulación y preparación; la c contradice el enfoque transdiagnóstico; y la d es incompatible con el establecimiento colaborativo de metas.',FP),
q(37,'¿Qué módulos del PU se consideran nucleares por entrenar estrategias específicas de regulación emocional?', ['1, 2 y 8.','3, 4, 5, 6 y 7.','Solo 6 y 7.','Todos excepto el 4.'],'b','La b es correcta: conciencia emocional, flexibilidad cognitiva, oposición a conductas emocionales y exposiciones interoceptiva y emocional. La a reúne módulos introductorios/cierre; la c es incompleta; y la d excluye indebidamente flexibilidad cognitiva.',FP),
q(38,'¿Qué se trabaja principalmente en el módulo 1 del PU?', ['Objetivos, motivación y balance decisional.','Exposición interoceptiva.','Prevención de recaídas farmacológica.','Reestructuración de recuerdos autobiográficos.'],'a','La a es correcta. La exposición interoceptiva corresponde al módulo 6; la c no define un módulo; y la d no es el foco del módulo 1.',FP),
q(39,'¿Qué significa el acrónimo ARCO utilizado en el módulo 2 del PU?', ['Antecedente, Respuesta y Consecuencia.','Atención, Reevaluación, Conducta y Objetivo.','Ansiedad, Regulación, Cognición y Observación.','Activación, Refuerzo, Castigo y Omisión.'],'a','La a es correcta. Las demás expansiones no corresponden al análisis funcional empleado por el PU.',FP),
q(40,'¿Qué objetivo caracteriza el módulo 3 del PU?', ['Conciencia emocional centrada en el presente y sin juzgar.','Suprimir todos los pensamientos intrusivos.','Clasificar diagnósticos DSM.','Entrenar únicamente habilidades sociales.'],'a','La a es correcta. La b contradice la aceptación y atención plena; la c no es una habilidad de regulación; y la d no constituye el objetivo central del módulo.',FP),
q(41,'¿Qué procedimiento caracteriza el módulo 4 del PU?', ['Flexibilizar interpretaciones y generar alternativas cognitivas.','Administrar reforzadores primarios.','Practicar exclusivamente relajación muscular.','Analizar sueños.'],'a','La a es correcta. Las opciones b, c y d no describen el trabajo de flexibilidad cognitiva del PU.',FP),
q(42,'¿Qué pretende el módulo 5 del PU?', ['Identificar las conductas impulsadas por emociones y practicar acciones opuestas o alternativas.','Aumentar las conductas de seguridad.','Evitar cualquier sensación desagradable.','Establecer el diagnóstico diferencial neurológico.'],'a','La a es correcta. La b y c mantienen la evitación emocional; la d pertenece a evaluación médica, no a este módulo.',FP),
q(43,'¿Qué técnica corresponde al módulo 6 del PU?', ['Exposición interoceptiva a sensaciones físicas.','Silla vacía.','Balance decisional.','Entrenamiento en memoria autobiográfica.'],'a','La a es correcta. La silla vacía pertenece a EFT; el balance decisional al módulo 1; y la d no constituye un módulo del PU.',FP),
q(44,'¿Qué caracteriza el módulo 7 del PU?', ['Construcción y práctica repetida de exposiciones emocionales.','Únicamente psicoeducación diagnóstica.','Supresión inmediata de emociones.','Finalización sin prevención de recaídas.'],'a','La a es correcta. La b es insuficiente; la c contradice el propósito de tolerar emociones; y la d corresponde de forma incorrecta al cierre.',FP),
q(45,'¿Cuál es el objetivo principal del módulo 8 del PU?', ['Revisar logros y elaborar un plan de práctica y prevención para el futuro.','Iniciar la evaluación diagnóstica.','Inducir por primera vez sensaciones físicas.','Determinar si las emociones son verdaderas o falsas.'],'a','La a es correcta. La b pertenece al inicio; la c al módulo 6; y la d plantea una valoración ajena al enfoque funcional del PU.',FP),
q(46,'En las exposiciones emocionales del PU para adultos, el objetivo principal es:', ['Esperar siempre hasta que la emoción desaparezca por habituación.','Aumentar la capacidad de tolerar el malestar y actuar de forma flexible pese a la emoción.','Evitar todas las situaciones que produzcan ansiedad.','Demostrar que ninguna sensación física existe.'],'b','La b es correcta. La a no refleja el énfasis del PU, que no exige habituación; la c refuerza la evitación; y la d niega experiencias físicas reales.',FP),
q(47,'¿Qué cambio introdujo la segunda edición del PU respecto al ejercicio del “oso blanco”?', ['Lo mantuvo como único ejercicio obligatorio.','Lo sustituyó por recordar una situación embarazosa e intentar no pensar en ella.','Lo trasladó al módulo de metas.','Lo convirtió en una prueba de inteligencia.'],'b','La b es correcta: conserva la demostración del rebote de la supresión. La a ignora su eliminación; la c lo sitúa en un módulo incorrecto; y la d cambia por completo su función.',FP),
q(48,'¿Cuál es el formato habitual del PU individual para adultos?', ['12-16 sesiones de 50-60 minutos.','Una única sesión de 15 minutos.','40 sesiones obligatorias de tres horas.','Solo tratamiento online asincrónico.'],'a','La a es correcta. Las demás opciones no corresponden al formato individual manualizado, aunque existen modalidades grupales y online.',FP),
q(49,'¿Cuál es el formato habitual del PU grupal para adultos?', ['12-14 sesiones de 90-120 minutos, generalmente con 6-8 participantes.','Dos sesiones individuales de 20 minutos.','Sesiones diarias sin límite de participantes.','Un retiro residencial obligatorio.'],'a','La a es correcta. Las opciones b, c y d no corresponden al formato grupal descrito.',FP),
q(50,'¿Qué nivel de recomendación recibe el PU para trastornos emocionales en las fuentes del tema?', ['Recomendación A y consideración de tratamiento de primera elección, aunque el nivel se expresa como 1+ o 1++ según el sistema utilizado.','Recomendación D en todas las fuentes.','Ausencia total de evidencia controlada.','Uso contraindicado como primera línea.'],'a','La a es correcta: Fonseca informa 1+/A con SIGN y Penadés 1++/A con guías del SNS. La b y c infravaloran la evidencia; la d contradice su consideración como primera elección.',FP)
];

if(add.length!==50) throw new Error(`Se esperaban 50, hay ${add.length}`);
const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const allFiles=fs.readdirSync('public/banco').filter(f=>f.endsWith('.json')&&f!=='manifest.json');
const all=allFiles.flatMap(f=>{const x=JSON.parse(fs.readFileSync(`public/banco/${f}`,'utf8'));return Array.isArray(x)?x:[]});
const existingIds=new Set(all.map(x=>x.id));
const existingTexts=new Map(all.map(x=>[norm(x.e||''),x.id]));
for(const item of add){if(existingIds.has(item.id))throw new Error(`ID existente ${item.id}`);const dup=existingTexts.get(norm(item.e));if(dup)throw new Error(`Duplicado exacto ${item.id} con ${dup}`);if(!['a','b','c','d'].includes(item.c)||!item.x||!item.r||Object.values(item.o).some(v=>!v.trim()))throw new Error(`Esquema inválido ${item.id}`)}
bank.push(...add);
fs.writeFileSync(bankPath,JSON.stringify(bank));
const manifest=JSON.parse(fs.readFileSync(manifestPath,'utf8'));
manifest.total+=50;
manifest.subjects['Tratamientos Adultos'].count+=50;
if(!manifest.subjects['Tratamientos Adultos'].topics.includes(topic))manifest.subjects['Tratamientos Adultos'].topics.push(topic);
fs.writeFileSync(manifestPath,JSON.stringify(manifest,null,2)+'\n');
console.log(JSON.stringify({added:50,topic,totalSubject:bank.length,totalGlobal:manifest.total}));
