import fs from 'node:fs';
const bankPath='public/banco/tratamientos_adultos.json';
const manifestPath='public/banco/manifest.json';
const bank=JSON.parse(fs.readFileSync(bankPath,'utf8'));
const topic='Tratamientos transdiagnósticos';
const F='Fonseca-Pedrero, E. (coord.). Manual de tratamientos psicológicos: adultos. Pirámide, cap. 4, pp. 117-157.';
const FP='Fonseca-Pedrero, E. (coord.). Manual de tratamientos psicológicos: adultos. Pirámide, cap. 6, pp. 201-224; Penadés, R., López-Santiago, J. y Belloch, A. (coords.) (2024). Manual de tratamientos en psicología clínica: guía práctica en adultos. McGraw Hill, cap. 31, pp. 739-762.';
const q=(n,e,o,c,x,r=FP)=>({id:`R0PIR_TA_TRANSDIAG_20260831_${String(n).padStart(3,'0')}`,s:'Tratamientos Adultos',t:[topic],origen:'creada',convocatoria:null,pa:null,e,o:{a:o[0],b:o[1],c:o[2],d:o[3]},c,x,r,v:'VALIDADA_ORIGINAL'});
const add=[
q(51,'Respecto a la ausencia de marcadores biológicos diagnósticos en psicopatología, señale la afirmación correcta:', ['No existe ninguna excepción descrita.','El manual menciona como excepciones la narcolepsia y las demencias.','Solo constituyen excepciones los trastornos de ansiedad.','La respuesta a un psicofármaco demuestra por sí sola la etiología biológica del trastorno.'],'b','La b es correcta: el texto señala narcolepsia y demencias como excepciones. La a las ignora; la c atribuye marcadores a trastornos de ansiedad; y la d confunde respuesta terapéutica con demostración etiológica.',F),
q(52,'Según la propuesta de factores comunes de Frank, ¿qué elementos serían probablemente los más influyentes en el éxito terapéutico?', ['El lugar de curación y las credenciales académicas.','El mito explicativo y el rito terapéutico.','El diagnóstico y la duración del tratamiento.','La medicación y la hospitalización.'],'b','La b es correcta: mito y rito proporcionan una explicación y un procedimiento coherentes. La a recoge aspectos contextuales, pero no los señalados como más influyentes; la c y d no forman esa pareja de factores comunes.',F),
q(53,'Acerca de la relación entre procesos transdiagnósticos y procesos específicos, señale la opción correcta:', ['Son incompatibles: aceptar unos obliga a negar los otros.','Todos los procesos psicopatológicos son necesariamente transdiagnósticos.','Pueden coexistir procesos compartidos por varios trastornos y procesos específicos de un problema.','El enfoque transdiagnóstico exige abandonar toda formulación individual.'],'c','La c es correcta. La a plantea una falsa incompatibilidad; la b universaliza sin fundamento; y la d contradice el análisis funcional y la adaptación individual.',F),
q(54,'¿Qué correspondencia entre proceso transdiagnóstico y problemas asociados es correcta?', ['Fusión pensamiento-acción: exclusivamente esquizofrenia.','Sensibilidad a la ansiedad: ansiedad, depresión, adicciones y espectro psicótico.','Alexitimia: únicamente trastorno bipolar.','Anhedonia: solo fobia específica.'],'b','La b es correcta. La fusión pensamiento-acción se observa, entre otros, en TOC, ansiedad, depresión y TCA; la alexitimia atraviesa múltiples problemas; y la anhedonia aparece en depresión, esquizofrenia y fobia social, por lo que a, c y d son restrictivas.',F),
q(55,'En MOL, ¿cómo puede preservarse la confidencialidad cuando la persona no desea revelar el contenido de un problema?', ['Se suspende el tratamiento hasta que revele todos los detalles.','Se trabaja con un término neutro, manteniendo el foco en el proceso de control.','El terapeuta inventa el contenido que falta.','Se sustituye la intervención por una prueba proyectiva.'],'b','La b es correcta: puede emplearse una etiqueta neutra, como “manzanas verdes”. La a impone una condición innecesaria; la c vulnera la curiosidad genuina; y la d no pertenece al procedimiento MOL.',F),
q(56,'¿Qué combinación refleja la evidencia atribuida al Método de los Niveles en el manual?', ['Nivel 1++ y recomendación A.','Nivel 1+ y recomendación B.','Nivel 2++ y recomendación C.','Nivel 3 y recomendación D.'],'d','La d es correcta debido al número reducido y naturaleza de los estudios. Las opciones a, b y c asignan niveles de evidencia superiores a los disponibles para MOL.',F),
q(57,'Respecto al formato del Método de los Niveles, señale la afirmación correcta:', ['Exige un mínimo de 20 sesiones.','Una o dos sesiones pueden ser suficientes y la duración aproximada de cada sesión es de 45 minutos.','Solo se aplica en grupos de ocho personas.','Su duración debe fijarse antes de conocer las preferencias del cliente.'],'b','La b es correcta y refleja su posible carácter muy breve. La a sobredimensiona la duración; la c confunde MOL con otros formatos; y la d contradice la accesibilidad y control del cliente sobre la programación.',F),
q(58,'Según EFT, ¿qué relación entre emoción, necesidad y tendencia de acción es correcta?', ['El miedo señala peligro y orienta hacia la seguridad.','La tristeza impulsa necesariamente el alejamiento de los demás.','El asco favorece la aproximación a lo desagradable.','La ira carece siempre de función adaptativa.'],'a','La a es correcta. La tristeza puede favorecer acercamiento y consuelo; el asco aleja de lo desagradable; y la ira puede cumplir una función de autoprotección, por lo que b, c y d son falsas.',F),
q(59,'¿Cuál de los siguientes NO es uno de los tres tipos de funcionamiento emocional problemático descritos en EFT?', ['Reacción directa asociada a experiencias traumáticas previas.','Reacción secundaria ante una emoción primaria adaptativa.','Emoción instrumental orientada a influir en otras personas.','Ausencia congénita e irreversible de toda respuesta emocional.'],'d','La d es correcta porque no pertenece a la clasificación. Las opciones a, b y c corresponden, respectivamente, a reacciones aprendidas, reacciones a la reacción y emociones instrumentales.',F),
q(60,'Durante el reprocesamiento emocional de EFT, ¿qué se busca específicamente en la fase de reexperimentación?', ['Identificar con detalle el momento exacto en que comenzó la reacción emocional.','Evitar recordar la escena para reducir el malestar.','Aplicar una exposición interoceptiva sin relato.','Establecer inmediatamente un diagnóstico categorial.'],'a','La a es correcta: se reconstruye vívidamente la escena y sus antecedentes. La b bloquea la exploración; la c corresponde a otro procedimiento; y la d no es el objetivo de esta fase.',F),
q(61,'La “dialéctica terapéutica” de EFT alude al equilibrio entre:', ['Un enfoque directivo de raíz gestáltica y otro rogeriano centrado en la iniciativa del cliente.','Psicoanálisis y farmacoterapia.','Exposición interoceptiva y prevención de respuesta.','Terapia individual y hospitalización.'],'a','La a es correcta. Las opciones b, c y d emparejan componentes que no definen la tensión creativa propia de EFT.',F),
q(62,'Respecto a la duración y formato de EFT, señale la afirmación correcta:', ['Las sesiones duran siempre 30 minutos y solo son individuales.','Las sesiones suelen durar 50-60 minutos y pueden ampliarse a 90 en situaciones de crisis.','Los problemas concretos requieren obligatoriamente más de 40 sesiones.','Las dificultades interpersonales graves nunca superan 20 sesiones.'],'b','La b es correcta. La a restringe duración y formato; la c invierte la recomendación de no superar normalmente 20 sesiones en problemas concretos; y la d ignora que los casos complejos pueden superar 40 sesiones.',F),
q(63,'¿Qué correspondencia entre adaptación de EFT y población es correcta?', ['EFTC: parejas.','EFTT: tratamiento del insomnio.','EFFT: exposición interoceptiva individual.','EFTC: trauma exclusivamente.'],'a','La a es correcta: EFTC se dirige a parejas. EFTT se orienta al trauma y EFFT a familias, por lo que b, c y d asignan poblaciones o técnicas incorrectas.',F),
q(64,'Según el modelo de triple vulnerabilidad, ¿qué perfil temperamental incrementa especialmente la probabilidad de un trastorno emocional?', ['Bajo neuroticismo y alta extraversión.','Alto neuroticismo y baja extraversión.','Alta extraversión sin afecto negativo.','Bajo neuroticismo y baja evitación.'],'b','La b es correcta: combina elevada tendencia al afecto negativo y menor acceso a afecto positivo. Las otras combinaciones no constituyen el perfil de riesgo señalado.',FP),
q(65,'Una persona aprende, tras un ataque de pánico en el metro, a asociar las sensaciones corporales y el transporte con peligro y comienza a evitarlos. ¿Qué vulnerabilidad representa más directamente?', ['Biológica generalizada.','Psicológica generalizada.','Psicológica específica.','Ausencia de vulnerabilidad.'],'c','La c es correcta: el aprendizaje vincula malestar con objetos, situaciones y estados internos concretos. La a es temperamental; la b se refiere a impredecibilidad e incontrolabilidad aprendidas de forma general; y la d ignora el patrón descrito.',FP),
q(66,'En el modelo procesual de regulación emocional de Gross, ¿cuál es la secuencia correcta?', ['Selección de la situación, modificación de la situación, despliegue atencional, cambio cognitivo y modulación de la respuesta.','Modulación de respuesta, diagnóstico, exposición, habituación y alta.','Atención, memoria, lenguaje, razonamiento y conducta.','Antecedente, respuesta, consecuencia, balance y prevención.'],'a','La a es correcta y reproduce las cinco fases. Las demás mezclan procesos clínicos o cognitivos que no forman la secuencia de Gross.',FP),
q(67,'En el contexto del Protocolo Unificado, la sigla CIE puede significar:', ['Clasificación Internacional de Enfermedades exclusivamente.','Conductas Impulsadas por la Emoción, cuando se describen respuestas dirigidas a evitar el malestar.','Control Inhibitorio Emocional.','Cognición Interpersonal Específica.'],'b','La b es correcta en este contexto. La a es la trampa terminológica; c y d no son expansiones utilizadas por el PU.',FP),
q(68,'Respecto al MEDI, señale la afirmación correcta:', ['Consta de 49 ítems y evalúa nueve dimensiones del modelo híbrido, todas salvo manía.','Consta de cinco ítems y evalúa únicamente ansiedad.','Evalúa diez dimensiones, incluida manía, mediante una escala dicotómica.','Es una entrevista estructurada administrada exclusivamente por psiquiatras.'],'a','La a es correcta. La b describe parcialmente OASIS; la c añade la dimensión no incluida y cambia la escala; y la d confunde un autoinforme con una entrevista.',FP),
q(69,'¿Qué combinación de punto de corte es correcta para OASIS y ODSIS en población clínica?', ['OASIS 5 y ODSIS 4.','OASIS 10 y ODSIS 10.','OASIS 15 y ODSIS 20.','Ninguna dispone de punto de corte.'],'b','La b es correcta: ambas emplean 10 como corte clínico. Los valores 4 y 5 corresponden a referencias en población no clínica, no a los cortes clínicos; c y d son falsas.',FP),
q(70,'La Escala de Inadaptación de Echeburúa evalúa:', ['Adaptación general e interferencia laboral, social, en ocio, pareja y familia.','Solo síntomas fisiológicos de ansiedad.','Únicamente ideación suicida.','Las diez dimensiones del modelo híbrido.'],'a','La a es correcta. La b se aproxima a otros instrumentos de ansiedad; la c no es su finalidad; y la d corresponde al marco evaluado por MEDI, no a la Escala de Inadaptación.',FP),
q(71,'¿Cuál de los siguientes pasos NO forma parte de la estructura habitual de cada sesión del PU?', ['Evaluar las emociones intensas de la semana y registrar el progreso.','Introducir contenido nuevo y practicarlo en sesión.','Responder al cuestionario verdadero/falso al finalizar un módulo.','Asignar obligatoriamente un diagnóstico nuevo en cada sesión.'],'d','La d es correcta porque no forma parte de la estructura. La evaluación semanal, el contenido y práctica, y el cuestionario al cierre de módulo sí están incluidos.',FP),
q(72,'¿Qué combinación de ejercicios pertenece al módulo 3 del PU?', ['Meditación, inducción emocional y anclaje en el presente.','Balance decisional, silla vacía y exposición interoceptiva.','Reestructuración de delirios, economía de fichas y relajación.','Jerarquía de exposición, medicación y prevención de respuesta.'],'a','La a es correcta. Las otras opciones mezclan técnicas de distintos módulos o tratamientos y no representan el entrenamiento en conciencia emocional plena.',FP),
q(73,'En el módulo 4 del PU, “abrir el abanico” significa:', ['Generar tantas interpretaciones alternativas como sea posible.','Aumentar deliberadamente la evitación.','Construir una jerarquía de sensaciones físicas.','Eliminar las emociones positivas.'],'a','La a es correcta y se practica, entre otros ejercicios, con una imagen ambigua. La b contradice el tratamiento; la c corresponde a exposición; y la d no es un objetivo del PU.',FP),
q(74,'¿Qué afirmación describe mejor el módulo 5 del PU?', ['Es principalmente preparatorio y busca comprender la función y consecuencias de las conductas emocionales.','Es el único módulo dedicado a la exposición interoceptiva.','Su objetivo es clasificar perfectamente cada conducta.','Se limita a discutir medicación.'],'a','La a es correcta. La exposición interoceptiva corresponde al módulo 6; la c confunde comprensión funcional con etiquetado rígido; y la d no define el módulo.',FP),
q(75,'Al construir una jerarquía de exposición emocional en el PU, ¿por qué se recomienda comenzar con un ítem de malestar y evitación 4-5 sobre 10?', ['Porque no debe provocar ninguna emoción.','Porque debe generar una emoción suficientemente intensa para practicar las habilidades sin comenzar necesariamente por el máximo.','Porque la exposición termina cuando la puntuación llega a cero.','Porque 4-5 representa el punto de corte diagnóstico.'],'b','La b es correcta. La a impediría entrenar tolerancia; la c vuelve a centrar el objetivo en desaparición del malestar; y la d confunde graduación de jerarquía con diagnóstico.',FP),
q(76,'En el ECA multicéntrico español del PU grupal en el Sistema Nacional de Salud, señale la afirmación correcta:', ['Incluyó 533 participantes y el PU no fue inferior al tratamiento habitual.','Incluyó 44 participantes y mostró inferioridad clínica.','Aplicó una sola sesión individual.','El seguimiento mostró pérdida completa de las mejoras antes de seis meses.'],'a','La a es correcta. La b mezcla otro estudio de satisfacción; la c contradice las 12 sesiones grupales; y la d es falsa porque los cambios se mantuvieron hasta 12 meses.',FP),
q(77,'Según los metaanálisis recogidos en el manual, ¿cómo se compara el PU con una TCC específica para cada trastorno?', ['Presenta diferencias enormes a favor del PU, con g superior a 2.','Ofrece resultados equivalentes o ligeramente superiores, con diferencias muy pequeñas.','Es claramente inferior en todos los resultados.','No se ha realizado ninguna comparación.'],'b','La b es correcta: los tamaños diferenciales son cercanos a cero. La a exagera; la c contradice los resultados; y la d ignora las comparaciones disponibles.',FP),
q(78,'¿Cómo suele adaptarse el PU cuando se aplica a trastornos mentales graves?', ['En formato extendido e individual, aproximadamente 15-33 sesiones, con excepciones estudiadas.','En una única sesión grupal obligatoria.','Eliminando siempre los módulos centrales.','Se considera contraindicado en todos los casos.'],'a','La a es correcta. La b y c no reflejan las adaptaciones descritas; la d ignora estudios en bipolaridad, esquizofrenia resistente y estados de alto riesgo.',FP),
q(79,'¿Qué rasgos suelen compartir las adaptaciones preventivas del PU?', ['Duración breve de 4-6 sesiones y frecuente uso de formatos no presenciales.','Hospitalización prolongada y 40 sesiones.','Ausencia de objetivos de regulación emocional.','Aplicación exclusiva tras un diagnóstico grave consolidado.'],'a','La a es correcta. Las opciones b, c y d contradicen el carácter preventivo, breve y flexible de estas adaptaciones.',FP),
q(80,'Respecto al efecto del PU sobre extraversión y afecto positivo, señale la afirmación correcta:', ['Todos los estudios muestran mejoras idénticas y concluyentes.','Los resultados no son concluyentes: algunos estudios encuentran mejoras y otros no.','El PU está diseñado exclusivamente para aumentar extraversión.','Nunca se ha evaluado esta cuestión.'],'b','La b es correcta. La a exagera la consistencia; la c confunde un posible efecto con la diana principal, que es neuroticismo/afecto negativo; y la d ignora los estudios existentes.',FP)
];
if(add.length!==30)throw new Error(`Se esperaban 30, hay ${add.length}`);
const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const files=fs.readdirSync('public/banco').filter(f=>f.endsWith('.json')&&f!=='manifest.json');
const all=files.flatMap(f=>{const x=JSON.parse(fs.readFileSync(`public/banco/${f}`,'utf8'));return Array.isArray(x)?x:[]});
const ids=new Set(all.map(x=>x.id));const texts=new Map(all.map(x=>[norm(x.e||''),x.id]));
for(const x of add){if(ids.has(x.id))throw new Error(`ID existente ${x.id}`);const d=texts.get(norm(x.e));if(d)throw new Error(`Duplicado ${x.id} con ${d}`);if(!['a','b','c','d'].includes(x.c)||Object.values(x.o).some(v=>!v.trim())||!x.x||!x.r)throw new Error(`Registro inválido ${x.id}`)}
bank.push(...add);fs.writeFileSync(bankPath,JSON.stringify(bank));
const m=JSON.parse(fs.readFileSync(manifestPath,'utf8'));m.total+=30;m.subjects['Tratamientos Adultos'].count+=30;fs.writeFileSync(manifestPath,JSON.stringify(m,null,2)+'\n');
console.log(JSON.stringify({added:30,topic,totalSubject:bank.length,totalGlobal:m.total}));
