import fs from 'node:fs';

const path = 'public/banco/psicologia_clinica.json';
const bank = JSON.parse(fs.readFileSync(path, 'utf8'));
const byId = new Map(bank.map((q) => [q.id, q]));
const ref = 'Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. II (4.ª ed.). McGraw Hill.';
const set = (id, values) => Object.assign(byId.get(id), values, { v: 'VALIDADA_ORIGINAL' });

set('PERSEV_AGO25_U1_034', { e: 'Señale la opción correcta sobre la relación entre experiencias traumáticas y síntomas psicóticos:', o: { a: 'Las personas que sufrieron abuso físico y sexual en la infancia informaron más voces que comentaban y daban órdenes sobre hacer o hacerse daño.', b: 'Las alucinaciones no se relacionan con la experiencia traumática.', c: 'El abuso sexual infantil se relaciona específicamente con alucinaciones visuales.', d: 'Las alucinaciones imperativas de daño se relacionan más con abuso sexual que físico.' }, c: 'a', x: 'La opción a es correcta. El estudio citado halló más voces que comentaban y voces imperativas de daño en quienes habían sufrido ambos tipos de abuso. La b niega una relación documentada; la c confunde el hallazgo, que se refiere a alucinaciones auditivas; y la d invierte la asociación observada para las voces imperativas.', r: ref });
set('PERSEVER___SIMULACRO_COMENTADO_JULIO-DOS-23_075', { e: 'Las experiencias traumáticas aumentan la probabilidad de experimentar alucinaciones auditivas. Señale la afirmación correcta:', o: { a: 'El abuso psicológico infantil es el predictor específico indicado para las alucinaciones auditivas.', b: 'El abuso físico infantil multiplica por cuatro la probabilidad de sufrir alucinaciones.', c: 'Los contenidos de las alucinaciones pueden relacionarse con la experiencia de abuso.', d: 'La relación dosis-efecto entre abuso y síntomas es necesariamente lineal.' }, c: 'c', x: 'La opción c es correcta: en supervivientes de trauma, el contenido de las alucinaciones puede guardar relación con la experiencia de abuso. La a atribuye el hallazgo al tipo de abuso equivocado; la b sobredimensiona la estimación descrita; y la d es falsa porque la relación dosis-efecto no se presenta como lineal.', r: ref });
set('PERSEVER___SIMULACRO_COMENTADO_JUNIO-DOS-23_068', { e: '¿Cuál de las siguientes afirmaciones describe un aspecto del pronóstico de la esquizofrenia?', o: { a: 'El predominio y la duración de síntomas negativos se asocian a una evolución florida y breve.', b: 'El período crítico para intervenir favorablemente no supera un año desde la detección.', c: 'La recuperación completa se estima aproximadamente en el 30 % de los casos, y hasta un 50 % puede presentar recuperación parcial con recaídas.', d: 'La crítica, hostilidad y sobreimplicación familiar no favorecen las recaídas.' }, c: 'c', x: 'La opción c es correcta. El manual recoge una recuperación completa aproximada del 30 % y recuperación parcial con recaídas hasta en el 50 %. La a invierte la asociación de los síntomas negativos persistentes; la b acorta indebidamente el período crítico; y la d es falsa porque la emoción expresada elevada se asocia a recaídas.', r: ref });
set('PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-UNO-23_101', { e: '¿Qué característica corresponde al trastorno delirante según el DSM-5-TR?', o: { a: 'El deterioro psicosocial puede estar más circunscrito que en la esquizofrenia y la conducta no es manifiestamente extravagante o extraña.', b: 'Al margen de las consecuencias del delirio, el funcionamiento está muy alterado y la conducta es manifiestamente extravagante.', c: 'Su prevalencia vital es aproximadamente 0,2 % y el subtipo más frecuente es el celotípico.', d: 'Es más prevalente en personas jóvenes.' }, c: 'a', x: 'La opción a es correcta. En el trastorno delirante, salvo el impacto del delirio y sus consecuencias, el funcionamiento no suele estar muy alterado ni la conducta es manifiestamente extravagante. La b invierte este criterio; la c identifica erróneamente como más frecuente el subtipo celotípico; y la d contradice su mayor prevalencia en edades más avanzadas.', r: 'American Psychiatric Association (2022). DSM-5-TR, «Trastorno delirante», criterios diagnósticos y desarrollo y curso. Editorial Médica Panamericana.' });
set('PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-UNO-23_107', { e: 'Según Belloch, señale la afirmación correcta sobre la dimensión desorganizada o cognitiva del espectro de la esquizofrenia:', o: { a: 'El deterioro cognitivo y la metacognición predicen principalmente el funcionamiento social.', b: 'El abuso o la negligencia se han relacionado con alteraciones del habla y pensamiento desorganizado, mediadas por déficit de teoría de la mente y anomalías de memoria de trabajo, especialmente en varones.', c: 'La forma más frecuente de catatonía es la inhibición motora, no la excitación.', d: 'El modelo esquizotaxia-esquizotipia de Meehl se formuló para explicar los síntomas desorganizados.' }, c: 'b', x: 'La opción b es correcta. El manual relaciona abuso o negligencia con alteraciones del habla y pensamiento desorganizado mediante teoría de la mente y memoria de trabajo. La a confunde predictores de funcionamiento social con los vocacionales y residenciales; la c invierte el predominio descrito; y la d atribuye erróneamente el modelo de Meehl a la dimensión desorganizada.', r: ref });
set('PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-UNO-23_113', { e: '¿Cuál es la afirmación INCORRECTA sobre los especificadores del trastorno delirante?', o: { a: 'Si el tema delirante dominante no se determina claramente o no corresponde a los tipos específicos, no puede especificarse.', b: 'Los delirios referenciales sin componente persecutorio o de grandeza importante pueden recibir el especificador «no especificado».', c: 'El tipo mixto se aplica cuando no predomina ningún tema delirante.', d: 'La creencia de sustitución indetectable de órganos internos constituye un delirio de contenido extravagante.' }, c: 'a', x: 'La opción a es incorrecta: precisamente en ese supuesto se utiliza el tipo «no especificado». La b ilustra ese tipo; la c define correctamente el tipo mixto; y la d ejemplifica contenido extravagante, por ser claramente inverosímil y ajeno a experiencias ordinarias.', r: 'American Psychiatric Association (2022). DSM-5-TR, «Trastorno delirante», especificadores. Editorial Médica Panamericana.' });
set('SM_ABRIL_1_SOL_1_053', { e: 'El sesgo de salto a conclusiones (JTC) es la tendencia a tomar decisiones con pocos datos. Señale la afirmación correcta:', o: { a: 'Predice la respuesta al tratamiento y se asocia con el riesgo de desarrollar psicosis en población general.', b: 'Corresponde al proceso tipo II, rápido e independiente de la memoria de trabajo.', c: 'Corresponde al proceso tipo I, lento, analítico y dependiente de la memoria de trabajo.', d: 'Consiste en ignorar la información contraria a una hipótesis.' }, c: 'a', x: 'La opción a es correcta. JTC presenta respaldo en psicosis y se asocia a respuesta al tratamiento y riesgo poblacional. La b y la c intercambian las propiedades de los procesos I y II; y la d define BADE, el sesgo contra la evidencia desconfirmatoria.', r: ref });
set('SM_ABRIL_2_SOL_1_062', { e: 'Señale la opción correcta sobre el trastorno delirante:', o: { a: 'Tiene una prevalencia vital del 0,3 %.', b: 'Se evidencia en la adolescencia tardía o adultez temprana, sin comienzo definido.', c: 'En mujeres predomina el subtipo celotípico.', d: 'El curso es habitualmente crónico, con tendencia al enquistamiento de la actividad delirante.' }, c: 'd', x: 'La opción d es correcta. El curso puede ser crónico, con persistencia o enquistamiento de la actividad delirante. La a corresponde al trastorno esquizoafectivo; la b describe el inicio propio del trastorno esquizotípico; y la c invierte la mayor frecuencia masculina del delirio celotípico.', r: ref });
set('SM_ABRIL_2_SOL_1_083', { e: 'Kasanin describió la «tercera psicosis» para referirse a lo que hoy se denomina:', o: { a: 'Trastorno esquizoafectivo.', b: 'Trastorno esquizotípico.', c: 'Trastorno delirante.', d: 'Trastorno obsesivo-compulsivo.' }, c: 'a', x: 'La opción a es correcta. La «tercera psicosis» de Kasanin es un antecedente del concepto de trastorno esquizoafectivo, situado históricamente entre la esquizofrenia y los trastornos afectivos. Las demás alternativas no corresponden a esa formulación.', r: ref });

fs.writeFileSync(path, JSON.stringify(bank));
console.log('Validadas 9 preguntas clínicas del tramo 4.');
