import fs from 'node:fs';

const path = 'public/banco/psicologia_clinica.json';
const bank = JSON.parse(fs.readFileSync(path, 'utf8'));
const byId = new Map(bank.map((q) => [q.id, q]));
const ref = 'Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. II (4.ª ed.). McGraw Hill.';
const set = (id, values) => Object.assign(byId.get(id), values, { v: 'VALIDADA_ORIGINAL' });

set('SM_DICIEMBRE_1_SOL_1_025', { e: 'Señale la alternativa correcta sobre el trastorno psicótico breve:', o: { a: 'No puede presentarse catatonía, pero sí síntomas negativos.', b: 'Las manifestaciones pueden ser cambiantes, incluso en horas o días, con presentación polimorfa.', c: 'Predominan síntomas más próximos a la esquizofrenia en mujeres.', d: 'La conversión posterior a esquizofrenia ocurre aproximadamente en la mitad de los casos.' }, c: 'b', x: 'La opción b es correcta. El trastorno psicótico breve puede presentar síntomas variables o polimorfos en poco tiempo. La a es falsa porque puede incluir catatonía y no se define por síntomas negativos persistentes; la c invierte la asociación descrita; y la d sobrestima la conversión posterior a esquizofrenia.', r: 'American Psychiatric Association (2022). DSM-5-TR, «Trastorno psicótico breve». Editorial Médica Panamericana. ' + ref });
set('SM_DICIEMBRE_1_SOL_1_029', { e: 'Los sesgos de salto a conclusiones (JTC) y contra la evidencia desconfirmatoria (BADE) pueden afectar al razonamiento en los delirios. Señale la afirmación correcta:', o: { a: 'El JTC consiste en decidir sin buscar evidencia suficiente que confirme o apoye la decisión.', b: 'El BADE se evalúa mediante la tarea probabilística de las bolitas.', c: 'El BADE solo se observa durante los episodios psicóticos agudos.', d: 'El JTC es el constructo de orden superior denominado flexibilidad de la creencia.' }, c: 'a', x: 'La opción a es correcta: JTC implica alcanzar una conclusión con pocos datos. La b describe la tarea clásica de JTC; la c es falsa porque BADE puede persistir tras la recuperación; y la d confunde JTC con un constructo más amplio de flexibilidad de la creencia.', r: ref });
set('SM_DICIEMBRE_2_SOL_1_019', { e: '¿Qué hallazgo es una alteración neurofisiológica descrita en esquizofrenia?', o: { a: 'Aumento del volumen del tálamo.', b: 'Menor amplitud del potencial evocado P300.', c: 'Asimetría hemisférica inversa.', d: 'Aumento del perímetro craneal.' }, c: 'b', x: 'La opción b es correcta. La reducción de la amplitud del P300 es un hallazgo neurofisiológico. Las opciones a, c y d se refieren a características anatómicas o morfológicas, no a un registro neurofisiológico.', r: ref });
set('SM_DICIEMBRE_2_SOL_1_091', { e: 'El modelo esquizotaxia-esquizotipia de Meehl se diseñó originalmente para explicar:', o: { a: 'La dimensión negativa de la esquizofrenia.', b: 'La dimensión desorganizada de la esquizofrenia.', c: 'La dimensión positiva de la esquizofrenia.', d: 'La dimensión afectiva de la esquizofrenia.' }, c: 'a', x: 'La opción a es correcta. El modelo de Meehl destacó el papel etiológico de déficits y síntomas negativos en el desarrollo de esquizotipia y esquizofrenia. Las dimensiones desorganizada, positiva y afectiva no constituyen su objeto explicativo original.', r: ref });
set('SM_ENERO_1_SOL_1_073', { e: 'Según Jaspers, ¿qué tipo de delirio primario consiste en atribuir un significado delirante y personal a una percepción normal?', o: { a: 'Recuerdo delirante.', b: 'Humor delirante.', c: 'Delirio autóctono.', d: 'Percepción delirante.' }, c: 'd', x: 'La opción d es correcta. La percepción delirante parte de una percepción normal a la que se atribuye un significado delirante inmediato y personal. El recuerdo delirante altera un recuerdo; el humor delirante es una atmósfera de significación; y el delirio autóctono aparece como una idea súbita sin derivarse de una percepción.', r: ref });

fs.writeFileSync(path, JSON.stringify(bank));
console.log('Validadas 5 preguntas clínicas del tramo 6.');
