import fs from 'node:fs';

const dir = 'public/banco';
const files = {
  'Psicología Clínica': 'psicologia_clinica.json',
  'Psicopatología Infantil': 'psicopatologia_infantil.json',
  'Psicología Social': 'psicologia_social.json',
  'Psicobiología': 'psicobiologia.json'
};
const banks = Object.fromEntries(Object.entries(files).map(([s, f]) => [s, JSON.parse(fs.readFileSync(`${dir}/${f}`, 'utf8'))]));
const find = (id) => {
  for (const [s, bank] of Object.entries(banks)) {
    const i = bank.findIndex((q) => q.id === id);
    if (i >= 0) return { s, bank, i, q: bank[i] };
  }
  throw new Error(`No existe ${id}`);
};
const set = (id, data, targetSubject, targetTopic) => {
  const hit = find(id);
  const q = hit.q;
  Object.assign(q, data, { v: 'VALIDADA_ORIGINAL' });
  if (targetSubject) {
    hit.bank.splice(hit.i, 1);
    q.s = targetSubject;
    q.t = [targetTopic];
    banks[targetSubject].push(q);
  }
};
const belloch = 'Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. II (4.ª ed.). McGraw Hill, capítulo 11: Esquizofrenia y otros trastornos psicóticos.';
const dsm = 'American Psychiatric Association (2022). DSM-5-TR. Trastornos del espectro de la esquizofrenia y otros trastornos psicóticos.';

set('PERSEV_JUL25_D2_083', {e:'En la esquizofrenia de inicio en la infancia, señale la afirmación correcta:',o:{a:'La mayor frecuencia en varones se mantiene sin cambios durante la adolescencia.',b:'El inicio infantil suele ser abrupto y el adolescente necesariamente insidioso.',c:'Las alucinaciones visuales son más frecuentes que las auditivas.',d:'Los delirios son menos frecuentes y elaborados que en adultos; entre sus contenidos habituales se encuentran los persecutorios y somáticos.'},c:'d',x:'La d es correcta: en la infancia los delirios suelen ser simples, poco sistematizados y menos frecuentes, con contenidos persecutorios y somáticos habituales. La a es falsa porque la diferencia por sexo se reduce en la adolescencia; la b invierte el patrón típico, pues el inicio infantil suele ser insidioso; y la c es falsa porque predominan las alucinaciones auditivas.',r:'Wicks-Nelson, R. e Israel, A. C. (2010). Psicopatología del niño y del adolescente (3.ª ed.). Prentice Hall, pp. 322-327.'},'Psicopatología Infantil','Trastornos psicóticos infantojuveniles');

set('AGOSTO2_034',{e:'Según Read et al. (2003), ¿qué patrón se observó entre los antecedentes de abuso y las voces que comentan?',o:{a:'Las personas con antecedentes de abuso físico y sexual presentaron la mayor frecuencia, seguidas por quienes habían sufrido solo abuso sexual, solo abuso físico y, finalmente, quienes no tenían abuso documentado.',b:'En todos los grupos fueron más frecuentes las voces imperativas que las voces que comentan.',c:'En el grupo con abuso físico y sexual, las voces que comentan fueron menos frecuentes que las imperativas.',d:'El estudio demostró que el abuso sexual causaba voces imperativas y que el abuso físico causaba voces que comentan.'},c:'a',x:'La a reproduce el patrón observado. La b y la c invierten la mayor frecuencia de las voces que comentan frente a las imperativas en esos grupos. La d es falsa porque invierte las asociaciones descritas y, además, un estudio observacional permite hablar de asociación, no demostrar causalidad.',r:'Read, J., Agar, K., Argyle, N. y Aderhold, V. (2003). Sexual and physical abuse during childhood and adulthood as predictors of hallucinations, delusions and thought disorder. Psychology and Psychotherapy, 76(1), 1-22. https://doi.org/10.1348/14760830260569210'});

set('PERSEVER___SIMULACRO_COMENTADO_ABRIL-DOS-23_127',{e:'Señale la afirmación correcta sobre la esquizofrenia:',o:{a:'DSM-5-TR y CIE-11 exigen en ambos casos una duración mínima de seis meses.',b:'Las dificultades atencionales son el predictor diferencial característico en los hombres.',c:'Todos los cambios relevantes para la recuperación se producen exclusivamente durante los tres primeros años.',d:'La esperanza de vida puede reducirse aproximadamente entre 10 y 20 años respecto a la población general.'},c:'d',x:'La d es correcta: la esquizofrenia se asocia con una reducción marcada de la esperanza de vida, relacionada con enfermedad física, suicidio y factores asistenciales y conductuales. La a es falsa porque DSM-5-TR exige seis meses, mientras CIE-11 exige al menos un mes; la b atribuye incorrectamente un patrón diferencial por sexo; y la c formula un límite temporal absoluto que no está respaldado.',r:dsm+'; '+belloch});

set('PERSEVER___SIMULACRO_COMENTADO_ABRIL-UNO-23_067',{e:'Respecto a la dimensión desorganizada o cognitiva del espectro de la esquizofrenia, señale la afirmación INCORRECTA:',o:{a:'En el trastorno bipolar predominan los problemas de memoria verbal y velocidad de procesamiento, mientras en la esquizofrenia predominan exclusivamente los ejecutivos.',b:'La cognición social se relaciona con la alogia y sus déficits pueden persistir durante la remisión.',c:'El deterioro cognitivo puede comenzar antes del primer episodio psicótico y no se explica únicamente por la intensidad de los síntomas clínicos.',d:'Se han descrito diferencias por sexo en algunas alteraciones formales del pensamiento, con mayor incoherencia en mujeres.'},c:'a',x:'La a es incorrecta porque invierte el patrón comparativo: en la esquizofrenia destacan especialmente la memoria verbal y la velocidad de procesamiento, mientras en el trastorno bipolar sobresalen relativamente los problemas ejecutivos. La b, c y d recogen asociaciones descritas para cognición social, curso del deterioro cognitivo y diferencias en el habla desorganizada.',r:belloch});

set('PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-DOS-23_028',{e:'Respecto a la dimensión desorganizada o cognitiva del espectro de la esquizofrenia, señale la afirmación correcta:',o:{a:'El deterioro cognitivo global es mayor en el trastorno bipolar que en la esquizofrenia.',b:'Tangencialidad, descarrilamiento e incoherencia se clasifican como alteraciones negativas del pensamiento.',c:'La cognición social muestra relaciones relevantes con la alogia y sus déficits pueden persistir durante la remisión.',d:'En la esquizofrenia solo se alteran la vigilancia y la solución de problemas, manteniéndose la memoria verbal y la velocidad de procesamiento.'},c:'c',x:'La c es correcta. La a invierte la mayor afectación global observada en la esquizofrenia; la b clasifica como negativas alteraciones positivas del habla/pensamiento desorganizado; y la d omite dos dominios especialmente afectados: memoria verbal y velocidad de procesamiento.',r:belloch});

set('PERSEVER___SIMULACRO_COMENTADO_JUNIO-UNO-23_081',{e:'Respecto al riesgo de suicidio en los trastornos del espectro psicótico, señale la afirmación correcta:',o:{a:'La conciencia de enfermedad siempre reduce el riesgo de suicidio.',b:'El riesgo se limita al primer año y desaparece después.',c:'Los síntomas depresivos y la desesperanza carecen de valor clínico para estimar el riesgo.',d:'El riesgo es especialmente elevado en las fases iniciales y aumenta ante intentos previos, depresión y desesperanza.'},c:'d',x:'La d es correcta: el riesgo se concentra especialmente al inicio, pero debe valorarse durante todo el curso, y aumentan su relevancia los intentos previos, la depresión y la desesperanza. La a es falsa por su carácter absoluto: el mayor insight puede aumentar el riesgo si se acompaña de desesperanza; la b limita indebidamente el periodo de riesgo; y la c niega factores clínicos bien establecidos.',r:'Fonseca-Pedrero, E. (coord.) (2021). Manual de tratamientos psicológicos: adultos. Pirámide, capítulo sobre psicosis; '+dsm});

set('PERSEVER___SIMULACRO_COMENTADO_MAYO-DOS-23_003',{e:'Respecto a las diferencias entre personas que escuchan voces con y sin diagnóstico psicótico, señale la afirmación INCORRECTA:',o:{a:'Las personas sin diagnóstico suelen informar de una edad de inicio más temprana.',b:'El grupo con diagnóstico refiere, en promedio, mayor recurrencia y duración de las voces.',c:'El grupo sin diagnóstico identifica más las voces con personajes públicos o sobrenaturales, y el grupo clínico con familiares o consigo mismo.',d:'El grupo sin diagnóstico refiere menos comentarios devaluativos sobre sí mismo y más comentarios sobre otras personas.'},c:'c',x:'La c es la incorrecta porque invierte el patrón descrito: el grupo clínico identifica más las voces con personajes públicos o sobrenaturales, mientras el grupo sin diagnóstico las vincula más con familiares o consigo mismo. La a, b y d reflejan diferencias medias descritas entre ambos grupos; no implican que una sola característica determine el diagnóstico.',r:'Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. I (4.ª ed.). McGraw Hill, capítulo de psicopatología de la percepción.'});

set('PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-DOS-23_055',{e:'¿Cuál de las siguientes comorbilidades es especialmente frecuente en la esquizofrenia?',o:{a:'Trastorno por consumo de tabaco.',b:'Anorexia nerviosa.',c:'Trastorno neurocognitivo debido a enfermedad de Parkinson.',d:'Trastorno de identidad disociativo.'},c:'a',x:'La a es correcta: más de la mitad de las personas con esquizofrenia fuma y el trastorno por consumo de tabaco es una comorbilidad especialmente frecuente. Las opciones b, c y d pueden coexistir en casos individuales, pero no constituyen comorbilidades características ni especialmente prevalentes de la esquizofrenia.',r:dsm});

set('PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-UNO-23_128',{e:'En los estudios sobre perfiles de esquizotipia en adolescentes de población general, señale la afirmación correcta:',o:{a:'Solo se distinguen baja, positiva, negativa y alta esquizotipia.',b:'La alta esquizotipia es siempre el grupo más numeroso.',c:'La anhedonia social, la ausencia de amistades íntimas, el lenguaje extraño y la ansiedad social definen un perfil denominado exclusivamente «esquizotipia negativa».',d:'El perfil de esquizotipia positiva incluye pensamiento mágico, ideas de referencia y experiencias perceptivas inusuales, indicadores de susceptibilidad a trastornos psicóticos.'},c:'d',x:'La d es correcta. La a omite el perfil de desorganización social y añade una categoría que no coincide con la clasificación descrita; la b es falsa porque la alta esquizotipia constituye el grupo menos numeroso; y la c denomina incorrectamente como negativa el perfil de desorganización social.',r:'Izquierdo, A., Cuéllar, I. y Padilla, D. (2021). Manual de psicología clínica de la infancia y la adolescencia. McGraw Hill, p. 290.'},'Psicopatología Infantil','Trastornos psicóticos infantojuveniles');

set('SM_DICIEMBRE_1_SOL_1_030',{e:'Al comparar personas que escuchan voces con y sin diagnóstico psicótico, señale la afirmación correcta:',o:{a:'Las personas sin diagnóstico refieren menos comentarios devaluativos sobre sí mismas y más comentarios sobre otras personas.',b:'Las personas con diagnóstico identifican con mayor frecuencia las voces como familiares o similares a sí mismas.',c:'Las personas sin diagnóstico escuchan necesariamente más voces femeninas.',d:'Las personas con diagnóstico oyen con mayor frecuencia a Dios que a figuras sobrenaturales amenazantes.'},c:'a',x:'La a es correcta según las diferencias medias descritas. La b invierte el patrón de identidad atribuido a las voces; la c es falsa porque no se establece una diferencia consistente en el género de las voces; y la d invierte el patrón religioso descrito. Estas diferencias son grupales y no permiten diagnosticar por sí solas.',r:'Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. I (4.ª ed.). McGraw Hill, capítulo de psicopatología de la percepción.'});

set('SM_JUNIO_2_SOL_1_038',{e:'En el modelo transdiagnóstico del espectro de la esquizofrenia se distinguen las dimensiones psicótica, desorganizada o cognitiva, negativa y afectiva. Señale la afirmación correcta:',o:{a:'Los déficits en la monitorización de la fuente explican exclusivamente la dimensión desorganizada o cognitiva.',b:'El funcionamiento vocacional y residencial depende únicamente de la cognición social.',c:'La dimensión afectiva se relaciona con las dimensiones psicótica, negativa y desorganizada, además de con recaídas y funcionamiento.',d:'La dimensión negativa se define solo por la presencia de delirios y alucinaciones.'},c:'c',x:'La c es correcta: los síntomas afectivos se relacionan con las demás dimensiones y con resultados clínicos y funcionales. La a es falsa porque los déficits de monitorización de la fuente se han vinculado a la dimensión psicótica; la b reduce indebidamente el funcionamiento a un único predictor; y la d confunde síntomas negativos con los síntomas positivos de la dimensión psicótica.',r:belloch});

set('SM_JUNIO_2_SOL_1_072',{e:'¿Qué característica apoya el diagnóstico de trastorno del espectro autista frente a esquizofrenia de inicio infantil?',o:{a:'La presencia aislada de intereses atípicos.',b:'La aparición de alucinaciones y delirios tras un periodo de desarrollo normal.',c:'La existencia de alguna dificultad social inespecífica.',d:'Déficits tempranos y marcados en el desarrollo de la comunicación social y del lenguaje, junto con patrones restrictivos y repetitivos.'},c:'d',x:'La d es correcta: un patrón temprano y persistente de alteraciones de comunicación social y conductas restrictivas/repetitivas apoya TEA. La a y la c son inespecíficas; la b apoya más una esquizofrenia de inicio infantil cuando aparecen síntomas psicóticos tras un desarrollo previo relativamente normal.',r:'American Psychiatric Association (2022). DSM-5-TR, trastorno del espectro autista y esquizofrenia; Wicks-Nelson, R. e Israel, A. C. (2010). Psicopatología del niño y del adolescente (3.ª ed.).'},'Psicopatología Infantil','Trastorno del espectro autista');

set('3Simulacro2018Comentarios_116',{e:'¿Qué dos grandes categorías de síndromes distingue la clasificación empírica de Achenbach en psicopatología infantil?',o:{a:'Afectivos y de conducta.',b:'Socializados y no socializados.',c:'Internalizantes y externalizantes.',d:'Retraimiento y problemas sociales.'},c:'c',x:'La c es correcta: el sistema empírico de Achenbach organiza los problemas en dos agrupaciones amplias, internalizantes y externalizantes. La a no corresponde a las dos dimensiones de banda ancha; la b pertenece a otras clasificaciones conductuales; y la d enumera síndromes específicos, no las dos categorías generales.',r:'Achenbach, T. M. y Rescorla, L. A. (2001). Manual for the ASEBA School-Age Forms & Profiles. University of Vermont, Research Center for Children, Youth, & Families.'},'Psicopatología Infantil','Introducción a la psicopatología infantil');

set('Simu 31 comentado Hardcore 1_107',{e:'Según el estudio EU-GEI sobre edad de migración y primer episodio psicótico, ¿qué periodo migratorio mantuvo una asociación significativa con la psicosis después de ajustar también por identidad etnorracial?',o:{a:'La adolescencia, entre los 11 y 17 años.',b:'La infancia, entre los 5 y 10 años.',c:'La edad adulta, a partir de los 18 años.',d:'El lugar de nacimiento, independientemente de la edad de migración.'},c:'a',x:'La a es correcta: tras el ajuste completo, la migración durante la adolescencia conservó una asociación significativa con la psicosis. La b y la c mostraron asociaciones en modelos menos ajustados, pero no conservaron esa significación tras incluir la identidad etnorracial; la d no representa la variable temporal analizada.',r:'Andleeb, H. et al. (2024). Age-at-migration, ethnicity and psychosis risk: Findings from the EU-GEI case-control study. PLOS Mental Health, 1(5), e0000134. https://doi.org/10.1371/journal.pmen.0000134'});

const austinRef='Austin, S. F. et al. (2015). Long-term trajectories of positive and negative symptoms in first episode psychosis: A 10-year follow-up study in the OPUS cohort. Schizophrenia Research, 168, 84-91. https://doi.org/10.1016/j.schres.2015.07.021';
set('SmCm08PIR2025_152',{e:'En el estudio de Austin et al. (2015) sobre trayectorias de síntomas positivos tras un primer episodio psicótico, señale la afirmación correcta:',o:{a:'La trayectoria de respuesta positiva apareció en el 15 %.',b:'La trayectoria de recaída apareció en el 47 %.',c:'La trayectoria de no respuesta apareció en el 25 %.',d:'La trayectoria de respuesta episódica apareció en el 13 %.'},c:'d',x:'La d es correcta. Las cinco trayectorias fueron respuesta (47 %), respuesta tardía (12 %), recaída (15 %), no respuesta (13 %) y respuesta episódica (13 %). Por ello, a intercambia respuesta con recaída, b intercambia recaída con respuesta y c atribuye un 25 % inexistente a la no respuesta.',r:austinRef});

set('SmCm22PIR2025_016',{e:'Según la teoría de la identidad social, ¿cómo se denomina la estrategia colectiva dirigida a superar al exogrupo en la misma dimensión en la que este aventaja al endogrupo?',o:{a:'Movilidad individual.',b:'Creatividad social.',c:'Competición social.',d:'Descategorización.'},c:'c',x:'La c es correcta: la competición social busca cambiar la posición relativa del endogrupo comparándose en la misma dimensión valorada. La a implica abandonar individualmente el grupo; la b redefine dimensiones o comparaciones para favorecer al endogrupo; y la d reduce la saliencia de las categorías, no describe esa competición.',r:'Tajfel, H. y Turner, J. C. (1979). An integrative theory of intergroup conflict. En W. G. Austin y S. Worchel (eds.), The Social Psychology of Intergroup Relations. Brooks/Cole.'},'Psicología Social','Relaciones intergrupales');

set('SmCm23PIR2025_004',{e:'¿Cuál de las siguientes alteraciones NO presenta un patrón de herencia ligado al cromosoma X?',o:{a:'Daltonismo rojo-verde.',b:'Síndrome de insensibilidad a los andrógenos (síndrome de Morris).',c:'Hemofilia A.',d:'Leucemia mieloide crónica.'},c:'d',x:'La d es correcta: la leucemia mieloide crónica es una neoplasia adquirida asociada habitualmente a la translocación BCR::ABL1 y no sigue herencia ligada al sexo. El daltonismo rojo-verde y la hemofilia A suelen heredarse como rasgos recesivos ligados al X; el síndrome de insensibilidad a los andrógenos se debe habitualmente a variantes del gen del receptor de andrógenos, situado también en el cromosoma X.',r:'Nussbaum, R. L., McInnes, R. R. y Willard, H. F. (2016). Thompson & Thompson Genetics in Medicine (8.ª ed.). Elsevier.'},'Psicobiología','Aproximación a la genética');

set('SmCm26PIR2025_117',{e:'¿Cuál de los siguientes problemas es especialmente frecuente en la esquizofrenia crónica y debe evaluarse de forma sistemática?',o:{a:'Hipocondría como síntoma nuclear.',b:'Ausencia de enfermedad física comórbida.',c:'Trastornos por consumo de sustancias, incluido el tabaco.',d:'Conducta agresiva en la mayoría de los pacientes.'},c:'c',x:'La c es correcta: el consumo de sustancias, especialmente tabaco, es muy frecuente y empeora el curso y la salud física. La a no constituye un síntoma nuclear; la b es falsa porque la comorbilidad física es elevada; y la d estigmatiza y generaliza indebidamente, ya que la mayoría de las personas con esquizofrenia no presenta conducta violenta.',r:dsm});

set('SmCm11PIR2025_137',{e:'Según Austin et al. (2015), ¿qué trayectoria de síntomas positivos se observó en personas con primer episodio psicótico?',o:{a:'El 47 % mostró un incremento inicial mantenido durante cinco años.',b:'El 12 % mostró únicamente un aumento constante desde el inicio.',c:'El 13 % presentó una trayectoria de no respuesta, con síntomas positivos relevantes durante el seguimiento.',d:'El 13 % mostró solo disminución inicial y aumento continuo durante los diez años.'},c:'c',x:'La c es correcta: la trayectoria de no respuesta agrupó al 13 %. La a invierte la trayectoria de respuesta, que implicó reducción inicial; la b describe incorrectamente la respuesta tardía; y la d no recoge el patrón episódico de disminución, aumento y nueva disminución.',r:austinRef});

set('Simu 14 comentado _064',{e:'Según la clasificación de Sims de los trastornos del curso y la forma del pensamiento, ¿cuál NO constituye una de sus categorías globales?',o:{a:'Aceleración del pensamiento.',b:'Retardo del pensamiento.',c:'Descarrilamiento.',d:'Cambios en el flujo o continuidad del pensamiento.'},c:'c',x:'La c es correcta: el descarrilamiento es una alteración formal específica del pensamiento, no una de las categorías globales del esquema citado. La aceleración, el retardo y los cambios en el flujo o continuidad sí se incluyen como agrupaciones generales.',r:'Sims, A. (1995). Symptoms in the Mind: An Introduction to Descriptive Psychopathology (2.ª ed.). Saunders; Vallejo Ruiloba, J. (2025). Introducción a la psicopatología y la psiquiatría (9.ª ed.), p. 490.'});

set('Simu 15 comentado_046',{e:'¿Qué hallazgo neuroquímico se ha propuesto en algunos modelos de la esquizofrenia?',o:{a:'Hipoactividad dopaminérgica uniforme en todas las vías cerebrales.',b:'Reducción de la función GABAérgica, que puede disminuir el control inhibitorio sobre otros sistemas neuronales.',c:'La noradrenalina baja en líquido cefalorraquídeo como causa demostrada de todas las recaídas.',d:'Ausencia completa de participación del neurodesarrollo.'},c:'b',x:'La b es correcta: se han descrito alteraciones de interneuronas GABAérgicas y del control inhibitorio. La a es falsa porque la hipótesis dopaminérgica distingue vías y no propone una hipoactividad uniforme; la c atribuye causalidad y universalidad no demostradas a la noradrenalina; y la d contradice la sólida contribución de los modelos del neurodesarrollo.',r:belloch});

set('SmCm28PIR2025_205',{e:'En el modelo de vulnerabilidad-estrés de Zubin y Spring aplicado a la esquizofrenia, señale la afirmación correcta:',o:{a:'La vulnerabilidad es relativamente estable, mientras el episodio psicótico es un estado temporal que emerge cuando los estresores superan el umbral individual.',b:'La vulnerabilidad aparece únicamente después del primer episodio.',c:'La personalidad premórbida es el único moderador posible.',d:'Una vez iniciado, el episodio nunca puede remitir aunque disminuya el estrés.'},c:'a',x:'La a es correcta: el modelo diferencia una vulnerabilidad relativamente duradera de episodios temporales precipitados cuando las demandas superan el umbral. La b invierte la secuencia del modelo; la c reduce a una sola variable los factores protectores y moderadores; y la d niega que la reducción del estrés y los recursos de afrontamiento puedan contribuir a la remisión.',r:'Zubin, J. y Spring, B. (1977). Vulnerability: A new view of schizophrenia. Journal of Abnormal Psychology, 86(2), 103-126. https://doi.org/10.1037/0021-843X.86.2.103'});

for (const [s, file] of Object.entries(files)) fs.writeFileSync(`${dir}/${file}`, JSON.stringify(banks[s]));
const manifestPath=`${dir}/manifest.json`;
const manifest=JSON.parse(fs.readFileSync(manifestPath,'utf8'));
for(const [s, bank] of Object.entries(banks)){
  manifest.subjects[s].count=bank.length;
  const topics=[...new Set(bank.flatMap(q=>q.t||[]))];
  manifest.subjects[s].topics=topics;
}
manifest.total=Object.values(manifest.subjects).reduce((n,s)=>n+s.count,0);
fs.writeFileSync(manifestPath,JSON.stringify(manifest,null,2)+'\n');
console.log('Auditadas las 22 preguntas pendientes.');
