import fs from 'node:fs';
const path='public/banco/psicologia_clinica.json';const bank=JSON.parse(fs.readFileSync(path,'utf8'));const m=new Map(bank.map(q=>[q.id,q]));const ref='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. II (4.ª ed.). McGraw Hill.';const set=(id,v)=>Object.assign(m.get(id),v,{v:'VALIDADA_ORIGINAL'});
set('Simu 7 comentado _095',{e:'¿Qué especificador puede añadirse al diagnóstico de trastorno psicótico breve según DSM-5-TR?',o:{a:'De inicio demorado.',b:'Con desencadenante leve.',c:'Con características de buen pronóstico.',d:'Con inicio en el posparto.'},c:'d',x:'La opción d es correcta. El DSM-5-TR permite especificar «con inicio en el posparto». Las otras alternativas no son especificadores de trastorno psicótico breve.',r:'American Psychiatric Association (2022). DSM-5-TR, «Trastorno psicótico breve», especificadores. Editorial Médica Panamericana.'});
set('SmCm15PIR2025_021',{e:'Según los criterios propuestos del DSM-5-TR para el síndrome de psicosis atenuado, señale la afirmación correcta:',o:{a:'Los síntomas deben estar presentes tres veces por semana durante el último mes.',b:'Los síntomas deben haber comenzado o empeorado en el último año.',c:'Los síntomas deben mantenerse al menos seis meses.',d:'No existe criterio temporal.'},c:'b',x:'La opción b es correcta. El criterio temporal exige inicio o empeoramiento en el último año. La a altera la frecuencia requerida; la c fija una duración que no se exige; y la d es falsa.',r:'American Psychiatric Association (2022). DSM-5-TR, Sección III, «Síndrome de psicosis atenuado», criterios propuestos. Editorial Médica Panamericana.'});
set('SmCm16PIR2025_055',{e:'¿Cuál NO es una característica de buen pronóstico del trastorno esquizofreniforme?',o:{a:'Inicio de síntomas psicóticos notables dentro de las primeras cuatro semanas.',b:'Confusión o perplejidad durante el episodio.',c:'Que el episodio se desencadene con un episodio maníaco.',d:'Ausencia de afecto aplanado o embotado.'},c:'c',x:'La opción c es correcta. Un episodio maníaco no es un especificador de buen pronóstico del trastorno esquizofreniforme. Las opciones a, b y d sí forman parte de las características de buen pronóstico.',r:'American Psychiatric Association (2022). DSM-5-TR, «Trastorno esquizofreniforme», características de buen pronóstico. Editorial Médica Panamericana.'});
set('SmCm12PIR2024 2_017',{e:'Según DSM-5-TR, ¿a partir de qué edad se suele hablar de esquizofrenia de inicio tardío?',o:{a:'45 años.',b:'50 años.',c:'60 años.',d:'70 años.'},c:'a',x:'La opción a es correcta. El DSM-5-TR usa la expresión inicio tardío para los casos que comienzan después de los 45 años. Las edades superiores pueden describir subgrupos de inicio muy tardío, pero no el umbral general indicado.',r:'American Psychiatric Association (2022). DSM-5-TR, «Esquizofrenia», desarrollo y curso. Editorial Médica Panamericana.'});
set('Simu 8 comentado _043',{e:'¿Cuál afirmación es INCORRECTA sobre la esquizofrenia según la CIE-11?',o:{a:'Las experiencias de influencia, pasividad o control no se consideran síntomas centrales.',b:'La sintomatología debe estar presente durante al menos un mes.',c:'Los delirios y las alucinaciones se consideran síntomas centrales.',d:'Las alteraciones del comportamiento no se consideran síntomas centrales.'},c:'a',x:'La opción a es incorrecta. La CIE-11 incluye las experiencias de influencia, pasividad o control entre los síntomas centrales. Las opciones b y c son compatibles con sus requisitos; y las alteraciones conductuales no forman por sí solas un síntoma central.',r:'World Health Organization (2024). ICD-11 for Mortality and Morbidity Statistics, «Schizophrenia or other primary psychotic disorders». https://icd.who.int/browse/2024-01/mms/en'});
set('SmCm17PIR2025_096',{e:'Señale la afirmación correcta sobre el curso del trastorno esquizoafectivo:',o:{a:'El tipo bipolar es más frecuente en adultos mayores.',b:'El tipo depresivo es más frecuente en adultos jóvenes.',c:'Su evolución suele ser mejor que la de la esquizofrenia.',d:'Su evolución suele ser mejor que la de los trastornos afectivos.'},c:'c',x:'La opción c es correcta. El pronóstico del trastorno esquizoafectivo suele ser mejor que el de la esquizofrenia, aunque peor que el de los trastornos afectivos. Las demás alternativas no describen el patrón de curso establecido.',r:ref});
fs.writeFileSync(path,JSON.stringify(bank));console.log('Validadas 6 preguntas DSM/CIE de Psicosis.');
