const fs=require('fs'),P='public/banco/';
const ev=JSON.parse(fs.readFileSync(P+'evaluacion_psicologica.json')),child=JSON.parse(fs.readFileSync(P+'clinica_infantojuvenil.json')),soc=JSON.parse(fs.readFileSync(P+'psicologia_social.json'));
const W='Wechsler, D. (2014). WISC-V. Escala de inteligencia de Wechsler para niños-V. Manual técnico y de interpretación. Pearson; Wechsler, D. (2012). WAIS-IV. Manual técnico y de interpretación. Pearson.';
const M='Moreno Rosset, C. y Ramírez Uclés, I. (2019). Evaluación psicológica: proceso, técnicas y aplicaciones en áreas y contextos. Sanz y Torres.';
const U={
'Simu 14 comentado _138':['Tests de inteligencia','Para obtener el CI total del WISC-V se administran siete pruebas principales. ¿Cuál de las siguientes forma parte de ese conjunto?',{a:'Puzles visuales.',b:'Búsqueda de símbolos.',c:'Balanzas.',d:'Span de dibujos.'},'c','La c es correcta: Balanzas es una de las siete pruebas que contribuyen al CI total. Puzles visuales, Búsqueda de símbolos y Span de dibujos son pruebas principales de sus índices, pero no integran el conjunto básico de siete empleado para calcular el CI total.',W],
'Simu 15 comentado_034':['Tests de inteligencia','¿Qué instrumento es el más adecuado para evaluar de forma amplia la inteligencia de un niño de 8 años?',{a:'WPPSI-IV.',b:'Escalas McCarthy.',c:'WISC-V.',d:'K-BIT.'},'c','La c es correcta: el WISC-V está diseñado para una evaluación amplia de la capacidad intelectual entre 6 años y 16 años y 11 meses. El WPPSI-IV y McCarthy se dirigen a edades más tempranas; el K-BIT es una prueba breve de cribado y no una batería exhaustiva.',W],
'Simu 15 comentado_209':['Tests de inteligencia','Según Cattell, ¿qué caracteriza mejor a la inteligencia fluida?',{a:'La capacidad de razonar y resolver problemas nuevos con escasa dependencia del aprendizaje previo.',b:'El repertorio de conocimientos adquirido mediante educación y experiencia.',c:'El dominio del vocabulario y la información cultural.',d:'Una habilidad que aumenta de forma sostenida durante toda la adultez.'},'a','La a es correcta: la inteligencia fluida permite identificar relaciones y resolver problemas novedosos. Las opciones b y c describen inteligencia cristalizada; la d es falsa, pues la fluida suele alcanzar antes su máximo y es más vulnerable al envejecimiento.', 'Cattell, R. B. (1963). Theory of fluid and crystallized intelligence: A critical experiment. Journal of Educational Psychology, 54, 1–22. https://doi.org/10.1037/h0046743.'],
'Simu 15 comentado_210':['Tests de inteligencia','¿Qué evalúa principalmente el Test de Dominós de Anstey?',{a:'Razonamiento no verbal vinculado al factor g.',b:'Conocimientos culturales acumulados.',c:'Comprensión y fluidez verbal.',d:'Inteligencia cristalizada.'},'a','La a es correcta: el test exige descubrir relaciones y completar series de fichas, estimando razonamiento general no verbal. Las opciones b, c y d implican conocimientos o lenguaje adquiridos, que no constituyen su objetivo principal.', 'Anstey, E. (1955). Dominoes: Test for the Measurement of Non-Verbal Intelligence. National Foundation for Educational Research.'],
'Simu 32 comentado hardcore 2_025':['Tests de inteligencia','¿Cuál de las siguientes NO es una prueba de la escala de memoria de las Escalas McCarthy?',{a:'Memoria pictórica.',b:'Memoria de cuentas.',c:'Memoria numérica.',d:'Secuencia rítmica.'},'b','La b es correcta porque «Memoria de cuentas» no es una subprueba McCarthy. Memoria pictórica, Memoria numérica y Secuencia rítmica sí aportan a la escala de memoria.', 'McCarthy, D. (1972). Manual for the McCarthy Scales of Children’s Abilities. Psychological Corporation.'],
'Simu 8 comentado _003':['Tests de inteligencia','¿Cuál NO es uno de los cinco índices primarios del WISC-V?',{a:'Razonamiento fluido.',b:'Memoria de trabajo.',c:'Memoria de trabajo auditiva.',d:'Visoespacial.'},'c','La c es correcta: Memoria de trabajo auditiva es un índice secundario. Razonamiento fluido, Memoria de trabajo y Visoespacial son índices primarios, junto con Comprensión verbal y Velocidad de procesamiento.',W],
'Simu 8 comentado _174':['Tests de inteligencia','En el WAIS-IV, Puzles visuales contribuye principalmente al índice de:',{a:'Memoria de trabajo.',b:'Razonamiento perceptivo.',c:'Velocidad de procesamiento.',d:'Comprensión verbal.'},'b','La b es correcta: Puzles visuales requiere análisis y síntesis visoespacial y forma parte de Razonamiento perceptivo. No pertenece a Memoria de trabajo, Velocidad de procesamiento ni Comprensión verbal.',W],
'Simu 8 comentado _175':['Tests de inteligencia','¿Qué instrumento incluye tareas de memoria de cuentas, frases, dígitos y objetos?',{a:'WMS-IV.',b:'RIAS.',c:'Stanford-Binet, cuarta edición.',d:'Escalas McCarthy.'},'c','La c es correcta: esas tareas pertenecen al área de memoria a corto plazo de Stanford-Binet IV. La WMS-IV usa otra organización; RIAS incorpora un índice de memoria mucho más breve; McCarthy no contiene esa combinación de tareas.', 'Thorndike, R. L., Hagen, E. P. y Sattler, J. M. (1986). Stanford-Binet Intelligence Scale: Fourth Edition. Riverside.'],
'Simu 8 comentado _184':['Tests de inteligencia','En la K-ABC original, ¿en qué escala se incluye Vocabulario expresivo?',{a:'Procesamiento secuencial.',b:'Procesamiento simultáneo.',c:'Rendimiento.',d:'Escala no verbal.'},'c','La c es correcta: Vocabulario expresivo evalúa conocimientos adquiridos y pertenece a Rendimiento. No es una tarea de procesamiento secuencial o simultáneo y requiere lenguaje, por lo que no pertenece a la escala no verbal.', 'Kaufman, A. S. y Kaufman, N. L. (1983). K-ABC Interpretive Manual. American Guidance Service.'],
'Simu 8 comentado _192':['Tests de inteligencia','El Test de factor g de Cattell fue construido principalmente mediante metodología:',{a:'Racional.',b:'Factorial.',c:'Proyectiva.',d:'Clínica.'},'b','La b es correcta: se deriva de la tradición psicométrica y del análisis factorial del factor general. Las metodologías racional, proyectiva y clínica no describen su procedimiento principal de construcción.', 'Cattell, R. B. y Cattell, A. K. S. (1973). Measuring Intelligence with the Culture Fair Tests. Institute for Personality and Ability Testing.'],
'Simulacro06.2018Comentarios_063':['Tests de inteligencia','¿Qué pruebas principales componían el índice de Razonamiento perceptivo del WISC-IV?',{a:'Búsqueda de símbolos, Cubos y Dígitos.',b:'Cubos, Conceptos y Matrices.',c:'Búsqueda de símbolos, Letras y números y Conceptos.',d:'Matrices, Claves y Conceptos.'},'b','La b es correcta: Cubos, Conceptos y Matrices eran las pruebas principales del índice. Búsqueda de símbolos y Claves pertenecían a Velocidad de procesamiento; Dígitos y Letras y números, a Memoria de trabajo.', 'Wechsler, D. (2005). WISC-IV. Escala de inteligencia de Wechsler para niños-IV. Manual técnico. TEA Ediciones.'],
'Simulacro06.2018Comentarios_068':['Tests de inteligencia','¿Qué autor constituye un antecedente teórico fundamental de la evaluación dinámica del potencial de aprendizaje?',{a:'Thorndike.',b:'Binet.',c:'Vygotski.',d:'Kelly.'},'c','La c es correcta: la zona de desarrollo próximo de Vygotski fundamenta la valoración del rendimiento con ayuda y del potencial de cambio. Thorndike se asocia al aprendizaje y medición, Binet a la evaluación intelectual tradicional y Kelly a los constructos personales.', 'Vygotsky, L. S. (1978). Mind in Society. Harvard University Press, pp. 84–91.'],
'SM_JULIO_1_SOL_1_175':['Técnicas subjetivas','En la técnica de pensamiento en voz alta, ¿qué afirmación es correcta?',{a:'Es necesariamente una técnica estructurada.',b:'La verbalización ocurre al mismo tiempo que la conducta o tarea examinada.',c:'Es equivalente al autorregistro de conductas privadas.',d:'Se aplica habitualmente sin registrar las verbalizaciones.'},'b','La b es correcta: el participante verbaliza concurrentemente su flujo de pensamiento mientras ejecuta la tarea. No tiene que ser estructurada; no equivale al autorregistro; y las verbalizaciones se registran para su análisis.',M],
'SmCm06PIR2025_155':['Tests de inteligencia','En WAIS-III y WAIS-IV, ¿a qué índice contribuye Clave de números o Claves?',{a:'Memoria de trabajo.',b:'Comprensión verbal.',c:'Velocidad de procesamiento.',d:'Organización perceptiva.'},'c','La c es correcta: Claves exige asociación rápida símbolo-número, atención y velocidad grafomotora. No forma parte de Memoria de trabajo ni Comprensión verbal; Organización perceptiva fue una denominación de otros índices, pero no incluye Claves.',W],
'SmCm08PIR2025_001':['Técnicas subjetivas','¿Qué característica corresponde a las técnicas subjetivas?',{a:'Son siempre altamente estructuradas.',b:'Sus respuestas son objetivas e imposibles de falsear.',c:'Suelen ser no estructuradas o semiestructuradas.',d:'Su finalidad es enmascarar por completo lo evaluado.'},'c','La c es correcta: permiten que la persona describa o clasifique su experiencia con grados variables de estructura. No son siempre estructuradas ni inmunes a sesgos; el enmascaramiento caracteriza mejor a otros procedimientos y no define estas técnicas.',M],
'SmCm08PIR2025_049':['Técnicas objetivas','¿Qué prueba exige responder cada vez que aparece un estímulo diana y permite evaluar atención sostenida o vigilancia?',{a:'Aparato del fenómeno phi.',b:'Ilusión de Müller-Lyer.',c:'Polirreactígrafo.',d:'Test de ejecución continua (CPT).'},'d','La d es correcta: un CPT registra respuestas y omisiones ante estímulos diana durante una secuencia prolongada. Las opciones a y b estudian percepción; el polirreactígrafo registra respuestas psicofisiológicas.', 'Conners, C. K. (2014). Conners Continuous Performance Test 3rd Edition Manual. Multi-Health Systems.'],
'SmCm09PIR2025_134':['Observación','Cuando los registros de un observador difieren sistemáticamente de un criterio objetivo conocido, ¿qué fuente de error debe revisarse primero?',{a:'La reactividad de la persona observada.',b:'La formación y calibración del observador.',c:'La gravedad clínica del caso.',d:'La deseabilidad social en un autoinforme.'},'b','La b es correcta: la discrepancia frente a un criterio objetivo revela problemas de exactitud y exige revisar entrenamiento y calibración. La reactividad es el cambio de conducta por saberse observado; la gravedad no define error; la deseabilidad social afecta autoinformes.',M],
'SmCm10PIR2025_161':['Tests de inteligencia','¿Qué forma de las Matrices Progresivas de Raven se utiliza habitualmente con niños pequeños, aproximadamente entre 5 y 11 años?',{a:'APM.',b:'SPM.',c:'SCL.',d:'CPM o escala coloreada.'},'d','La d es correcta: CPM facilita la evaluación de niños y personas con menor capacidad mediante matrices coloreadas. APM se dirige a capacidad superior; SPM es la forma general; SCL no es una forma de Raven.', 'Raven, J., Raven, J. C. y Court, J. H. (1998). Manual for Raven’s Progressive Matrices and Vocabulary Scales. Oxford Psychologists Press.'],
'SmCm11PIR2025_070':['Tests de personalidad','¿Qué instrumento clásico evalúa el patrón de conducta tipo A?',{a:'Kuder-C.',b:'Inventario de Intereses de Strong.',c:'Escala de Actividad de Jenkins (JAS).',d:'Ways of Coping Checklist.'},'c','La c es correcta: JAS fue diseñada para medir componentes del patrón tipo A. Kuder y Strong evalúan intereses; Ways of Coping evalúa estrategias de afrontamiento.', 'Jenkins, C. D., Zyzanski, S. J. y Rosenman, R. H. (1979). Jenkins Activity Survey Manual. Psychological Corporation.'],
'SmCm11PIR2025_072':['Tests de inteligencia','¿Qué instrumento evalúa las habilidades analítica, creativa y práctica de la teoría triárquica?',{a:'K-ABC.',b:'Terman-Merrill.',c:'Sternberg Triarchic Abilities Test (STAT).',d:'LPAD.'},'c','La c es correcta: STAT operacionaliza las tres habilidades propuestas por Sternberg. K-ABC evalúa procesamiento y rendimiento; Terman-Merrill deriva de Stanford-Binet; LPAD valora potencial de aprendizaje.', 'Sternberg, R. J. (1993). Sternberg Triarchic Abilities Test. Yale University.'],
'SmCm12PIR2024 2_163':['Tests de inteligencia','¿Cómo se clasifica principalmente el Test de Matrices Progresivas de Raven?',{a:'Test específico de aptitud mecánica.',b:'Test de desarrollo psicomotor.',c:'Test no verbal de factor g.',d:'Test de personalidad.'},'c','La c es correcta: Raven estima razonamiento eductivo y capacidad general mediante relaciones figurativas. No mide una aptitud mecánica específica, desarrollo psicomotor ni personalidad.', 'Raven, J., Raven, J. C. y Court, J. H. (1998). Manual for Raven’s Progressive Matrices and Vocabulary Scales. Oxford Psychologists Press.'],
'SmCm13PIR2025_169':['Tests de inteligencia','En el WAIS, la prueba Semejanzas:',{a:'Es una prueba poco relacionada con la capacidad general.',b:'Es un buen indicador de razonamiento verbal y capacidad intelectual.',c:'Mide principalmente velocidad grafomotora.',d:'Evalúa primordialmente el juicio ante situaciones sociales.'},'b','La b es correcta: Semejanzas exige abstracción y formación verbal de conceptos y suele cargar en capacidad general. La a invierte esa relación; la c describe Claves; la d corresponde mejor a Comprensión.',W],
'SmCm14PIR2025_192':['Tests de inteligencia','¿Quién propuso originalmente calcular el cociente intelectual dividiendo la edad mental entre la edad cronológica?',{a:'Wechsler.',b:'Binet.',c:'Stern.',d:'Terman.'},'c','La c es correcta: Stern propuso el cociente entre edad mental y cronológica. Binet desarrolló escalas y el concepto de edad mental; Terman popularizó el CI y su expresión multiplicada por 100; Wechsler adoptó posteriormente el CI de desviación.', 'Stern, W. (1912). Die psychologischen Methoden der Intelligenzprüfung. Barth; Terman, L. M. (1916). The Measurement of Intelligence. Houghton Mifflin.'],
'SmCm23PIR2025 (2)_019':['Tests de inteligencia','En WAIS-III y WAIS-IV, Vocabulario contribuye al índice de:',{a:'Memoria de trabajo.',b:'Comprensión verbal.',c:'Velocidad de procesamiento.',d:'Razonamiento perceptivo.'},'b','La b es correcta: Vocabulario mide conocimiento léxico y formación verbal de conceptos y pertenece a Comprensión verbal. No pertenece a Memoria de trabajo, Velocidad de procesamiento ni Razonamiento perceptivo.',W],
'SmCm23PIR2025 (2)_027':['Tests de inteligencia','¿Qué batería de evaluación dinámica incluye, entre otras tareas, Matrices de Raven, organización de puntos, plataformas y variaciones de la figura compleja?',{a:'H-NTLA.',b:'LPAD.',c:'K-ABC.',d:'BAT-7.'},'b','La b es correcta: LPAD de Feuerstein reúne instrumentos para observar modificabilidad cognitiva mediante evaluación mediada. H-NTLA evalúa aprendizaje en personas sordas; K-ABC es una batería de inteligencia; BAT-7 es una batería de aptitudes.', 'Feuerstein, R., Feuerstein, R. S., Falik, L. H. y Rand, Y. (2002). The Dynamic Assessment of Cognitive Modifiability. ICELP Press.'],
'SmCm23PIR2025_090':['Tests de inteligencia','¿Qué afirmación es correcta sobre las Escalas McCarthy?',{a:'Se aplican hasta los 12 años y 5 meses.',b:'Constan únicamente de cuatro escalas y dieciséis subpruebas.',c:'Son una prueba construida exclusivamente para medir factor g.',d:'Proporcionan un Índice General Cognitivo como estimación global.'},'d','La d es correcta: las escalas producen un Índice General Cognitivo. Su rango llega aproximadamente hasta 8 años y medio, no 12; contienen seis escalas y dieciocho pruebas; y su construcción y resultados no se reducen exclusivamente al factor g.', 'McCarthy, D. (1972). Manual for the McCarthy Scales of Children’s Abilities. Psychological Corporation.'],
'SmCm23PIR2025_093':['Tests de inteligencia','¿Cuáles son los cinco índices primarios del WISC-V?',{a:'Razonamiento cuantitativo, Memoria auditiva, No verbal, Capacidad general y Competencia cognitiva.',b:'Verbal, Perceptivo-manipulativo, Numérico, Memoria y Motricidad.',c:'Procesamiento secuencial, Procesamiento simultáneo, Rendimiento y No verbal.',d:'Comprensión verbal, Visoespacial, Razonamiento fluido, Memoria de trabajo y Velocidad de procesamiento.'},'d','La d es correcta y enumera los cinco índices primarios. La a reúne índices secundarios; la b corresponde a otra organización de escalas; la c describe la estructura de la K-ABC original.',W],
'SmCm24PIR2025 (1)_143':['Tests de inteligencia','¿Qué prueba fue creada específicamente para evaluar inteligencia analítica, creativa y práctica?',{a:'STAT.',b:'K-ABC.',c:'LPAD.',d:'H-NTLA.'},'a','La a es correcta: STAT deriva de la teoría triárquica de Sternberg. K-ABC evalúa procesamiento cognitivo y rendimiento; LPAD, modificabilidad o potencial de aprendizaje; H-NTLA, aptitud para el aprendizaje en población con discapacidad auditiva.', 'Sternberg, R. J. (1993). Sternberg Triarchic Abilities Test. Yale University.']
};
function upd(q,p){Object.assign(q,{t:[p[0]],e:p[1],o:p[2],c:p[3],x:p[4],r:p[5],v:'VALIDADA_ORIGINAL'});}
for(const [id,p] of Object.entries(U)){const q=ev.find(x=>x.id===id);if(!q)throw Error('missing '+id);upd(q,p)}
function move(id,to,s,t,e,o,c,x,r){const i=ev.findIndex(q=>q.id===id);if(i<0)throw Error(id);const q=ev.splice(i,1)[0];Object.assign(q,{s,t:[t],e,o,c,x,r,v:'VALIDADA_ORIGINAL'});to.push(q)}
move('Simu 8 comentado _002',child,'Clínica Infantojuvenil','Introducción a la psicopatología infantil','¿Cuál NO pertenece a las escalas de banda ancha internalizante del CBCL?',{a:'Problemas de pensamiento.',b:'Ansiedad/depresión.',c:'Retraimiento/depresión.',d:'Quejas somáticas.'},'a','La a es correcta: Problemas de pensamiento no integra la banda ancha internalizante. Ansiedad/depresión, Retraimiento/depresión y Quejas somáticas sí la componen.','Achenbach, T. M. y Rescorla, L. A. (2001). Manual for the ASEBA School-Age Forms & Profiles. University of Vermont.');
move('SmCm11PIR2025_133',soc,'Psicología Social','Procesos de interacción social','¿Qué autor utilizó el paradigma azul-verde en los estudios clásicos sobre influencia minoritaria?',{a:'Asch.',b:'Sherif.',c:'Janis.',d:'Moscovici.'},'d','La d es correcta: Moscovici estudió la influencia de una minoría consistente sobre juicios de color. Asch investigó conformidad mayoritaria; Sherif, formación de normas; Janis, pensamiento grupal.','Moscovici, S., Lage, E. y Naffrechoux, M. (1969). Influence of a consistent minority on the responses of a majority in a color perception task. Sociometry, 32, 365–380. https://doi.org/10.2307/2786541.');
for(const [n,a] of [['evaluacion_psicologica',ev],['clinica_infantojuvenil',child],['psicologia_social',soc]])fs.writeFileSync(P+n+'.json',JSON.stringify(a));
const m=JSON.parse(fs.readFileSync(P+'manifest.json'));for(const v of Object.values(m.subjects))v.count=JSON.parse(fs.readFileSync(P+v.slug+'.json')).length;m.total=Object.values(m.subjects).reduce((n,v)=>n+v.count,0);fs.writeFileSync(P+'manifest.json',JSON.stringify(m,null,2)+'\n');console.log({updated:Object.keys(U).length,moved:2,total:m.total});
