const fs=require('fs'),P='public/banco/',cp=P+'clinica_adultos.json',pp=P+'psicopatologia.json',a=JSON.parse(fs.readFileSync(cp)),psy=JSON.parse(fs.readFileSync(pp));
const D='American Psychiatric Association (2022). DSM-5-TR. Capítulo «Trastornos disociativos». Editorial Médica Panamericana.';
const B='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. II (4.ª ed.). McGraw Hill, cap. 8, pp. 295–322.';
const H='Van der Hart, O., Nijenhuis, E. R. S. y Steele, K. (2006). The Haunted Self. Norton; '+B;
const U={
'DICIEMBRE-DOS-24_COMENTADO_020':{e:'Sobre el trastorno de despersonalización/desrealización, señale la afirmación correcta:',o:{a:'La edad media de inicio ronda los 16 años y es infrecuente que aparezca por primera vez después de los 40.',b:'Suele comenzar por primera vez después de los 40 años.',c:'La pérdida del juicio de realidad es necesaria para diagnosticarlo.',d:'El DSM-5-TR distingue una forma total y otra parcial.'},c:'a',x:'La a es correcta: el comienzo suele producirse en la adolescencia y es infrecuente después de los 40 años. La b invierte ese patrón; la c es falsa porque el juicio de realidad permanece intacto; y la d confunde este trastorno con la distinción CIE-11 del trastorno de identidad disociativo.',r:D},
'PERSEVER___SIMULACRO_COMENTADO_ENERO-UNO-23_063':{e:'En el modelo jerárquico de Van der Hart, Van der Kolk y Boon, la disociación primaria implica:',o:{a:'Procesamiento fragmentado y no integrado del acontecimiento traumático.',b:'Percibir el acontecimiento sin experimentar plenamente su impacto emocional.',c:'Desarrollar identidades separadas.',d:'Integrar por completo el recuerdo y su impacto emocional.'},c:'a',x:'La a es correcta. La b describe la disociación secundaria; la c, la terciaria; y la d expresa integración, no disociación.',r:H},
'PERSEVER___SIMULACRO_COMENTADO_ENERO-UNO-23_064':{e:'Según Kihlstrom, los trastornos disociativos se entienden principalmente como trastornos de:',o:{a:'La percepción.',b:'La memoria.',c:'La inteligencia.',d:'La motivación.'},c:'b',x:'La b es correcta: Kihlstrom destaca la memoria y el acceso consciente a información autobiográfica. Las opciones a, c y d no constituyen el núcleo explicativo de su modelo.',r:'Kihlstrom, J. F. (2005). Dissociative disorders. Annual Review of Clinical Psychology, 1, 227–253. https://doi.org/10.1146/annurev.clinpsy.1.102803.143925.'},
'PERSEVER___SIMULACRO_COMENTADO_JULIO-UNO-23_056':{e:'Según la CIE-11, ¿qué distingue al trastorno de identidad disociativo parcial del trastorno de identidad disociativo?',o:{a:'En el parcial no existe ningún estado de personalidad diferenciado.',b:'En el parcial los estados no dominantes controlan recurrentemente la conducta durante periodos prolongados.',c:'En el parcial el estado dominante desaparece de manera permanente.',d:'En el parcial uno o más estados no dominantes producen intrusiones, pero no asumen recurrentemente el control ejecutivo; pueden hacerlo solo de forma ocasional y limitada.'},c:'d',x:'La d es correcta y evita la ambigüedad de la versión anulada. La a niega los estados diferenciados; la b describe un control recurrente más propio del TID completo; y la c no forma parte de la definición.',r:'World Health Organization (2024). ICD-11 CDDR, «Partial dissociative identity disorder» (6B65).'},
'PERSEVER___SIMULACRO_COMENTADO_JUNIO-DOS-23_038':{e:'¿Qué teoría propone la separación entre el sistema defensivo frente a la amenaza y el sistema encargado de la vida cotidiana?',o:{a:'Modelo autohipnótico.',b:'Modelo SIBAM.',c:'Teoría de la disociación estructural.',d:'Modelo BASK.'},c:'c',x:'La c es correcta: la teoría estructural diferencia la parte emocional defensiva y la parte aparentemente normal orientada a la vida diaria. El modelo autohipnótico se centra en hipnotizabilidad; SIBAM en cinco componentes de experiencia; y BASK en conducta, afecto, sensación y conocimiento.',r:H},
'PERSEVER___SIMULACRO_COMENTADO_JUNIO-DOS-23_057':{e:'¿Qué combinación forma parte de los criterios del trastorno de identidad disociativo?',o:{a:'Dos o más estados de personalidad y lagunas recurrentes de memoria cotidiana, personal o traumática incompatibles con el olvido ordinario.',b:'Una única laguna autobiográfica sin discontinuidad de identidad.',c:'Despersonalización o desrealización persistentes como únicos síntomas.',d:'Reacciones transitorias de menos de un mes sin alteración de identidad.'},c:'a',x:'La a es correcta: reúne perturbación de identidad y amnesia recurrente. La b corresponde mejor a amnesia disociativa; la c al trastorno de despersonalización/desrealización; y la d a reacciones disociativas agudas especificadas.',r:D},
'PERSEVER___SIMULACRO_COMENTADO_JUNIO-DOS-23_084':{e:'En la clasificación funcional de Tyrer, la amnesia disociativa se incluye en:',o:{a:'Disociación de la personalidad.',b:'Disociación de la función cognitiva.',c:'Disociación de la percepción.',d:'Disociación de movimientos o sensaciones.'},c:'b',x:'La b es correcta. La personalidad incluye identidad múltiple; la percepción, despersonalización y desrealización; y movimientos o sensaciones, conversión. Por ello a, c y d no corresponden a la amnesia.',r:B},
'PERSEVER___SIMULACRO_COMENTADO_JUNIO-DOS-23_085':{e:'Respecto a las modalidades de amnesia disociativa, señale la afirmación correcta:',o:{a:'La localizada impide recordar acontecimientos ocurridos durante un periodo específico.',b:'La selectiva implica olvidar todos los acontecimientos de toda la vida.',c:'La generalizada conserva solo una parte del periodo traumático y es la más frecuente.',d:'La continua afecta exclusivamente sucesos anteriores a un momento y nunca el presente.'},c:'a',x:'La a es correcta. La b confunde selectiva con generalizada; la c describe incorrectamente la selectiva y además la generalizada es rara; y la d invierte la dirección temporal de la continua.',r:D},
'PERSEVER___SIMULACRO_COMENTADO_JUNIO-DOS-23_091':{e:'Según la revisión de Simeon sobre despersonalización, ¿qué grupo de sustancias puede inducir experiencias disociativas?',o:{a:'Antagonistas NMDA como ketamina, cannabinoides, agonistas opioides y alucinógenos.',b:'Solo cafeína y nicotina.',c:'Únicamente benzodiacepinas.',d:'Antibióticos, antihistamínicos y antiinflamatorios como grupo específico.'},c:'a',x:'La a es correcta: esos sistemas se han relacionado experimental o clínicamente con experiencias disociativas. Las opciones b y c restringen indebidamente el fenómeno a un único grupo; la d reúne fármacos que no constituyen la clasificación propuesta.',r:'Simeon, D. (2004). Depersonalisation disorder: a contemporary overview. CNS Drugs, 18, 343–354. https://doi.org/10.2165/00023210-200418060-00002.'},
'PERSEVER___SIMULACRO_COMENTADO_JUNIO-UNO-23_106':{e:'Según la CIE-11, el trastorno de identidad disociativo parcial se caracteriza porque:',o:{a:'No existen intrusiones de estados no dominantes.',b:'Dos o más estados asumen recurrentemente el control ejecutivo.',c:'Los estados no dominantes producen intrusiones, pero solo asumen el control de forma ocasional, limitada y transitoria.',d:'Siempre aparecen cambios de identidad visibles y amnesia extensa.'},c:'c',x:'La c es correcta. La a niega las intrusiones características; la b describe el TID completo; y la d convierte manifestaciones variables en obligatorias.',r:'World Health Organization (2024). ICD-11 CDDR, 6B65.'},
'PERSEVER___SIMULACRO_COMENTADO_JUNIO-UNO-23_109':{e:'En la distinción de Farina y colaboradores, ¿qué fenómeno se incluye en la desintegración?',o:{a:'Amnesia autobiográfica.',b:'Desrealización.',c:'Identidad múltiple.',d:'Conversión motora.'},c:'b',x:'La b es correcta: despersonalización y desrealización se consideran fenómenos de desintegración ante sobrecarga. Las opciones a, c y d se incluyen entre fenómenos disociativos o funcionales diferentes en esa propuesta.',r:'Farina, B. et al. (2019). Development of a theory of traumatization and dissociation. Journal of Trauma & Dissociation; '+B},
'PERSEVER___SIMULACRO_COMENTADO_MAYO-DOS-23_210':{e:'Tras un estresor, una persona presenta enlentecimiento subjetivo del tiempo, anestesia, parálisis y microamnesias que remiten en menos de un mes. ¿Qué diagnóstico DSM-5-TR es más compatible?',o:{a:'Trastorno de síntomas somáticos.',b:'Trastorno adaptativo.',c:'Reacción disociativa aguda a sucesos estresantes.',d:'Trastorno de estrés agudo sin comprobar exposición traumática.'},c:'c',x:'La c es correcta y es un ejemplo de otro trastorno disociativo especificado. La a exige preocupación o conducta somática persistente; la b no explica el conjunto disociativo; y la d requiere exposición a trauma del criterio A y su conjunto diagnóstico, no demostrado en el caso.',r:D},
'PERSEVER___SIMULACRO_COMENTADO_MAYO-UNO-23_101':{e:'Según la clasificación de Kihlstrom y colaboradores, la ceguera psicógena se incluye en:',o:{a:'Parálisis disociativa.',b:'Amnesia disociativa.',c:'Anestesia disociativa.',d:'Trastornos de memoria exclusivamente.'},c:'c',x:'La c es correcta: la anestesia disociativa incluye alteraciones funcionales de sensación o percepción como ceguera, sordera y analgesia psicógenas. La a afecta función motora; la b y la d se refieren a memoria.',r:'Kihlstrom, J. F., Glisky, M. L. y Angiulo, M. J. (1994). Dissociative tendencies and dissociative disorders. Journal of Abnormal Psychology; '+B},
'PERSEVER___SIMULACRO_COMENTADO_MAYO-UNO-23_102':{e:'¿Cuál NO constituye una función afectada en la clasificación de la disociación de Tyrer?',o:{a:'Conductas complejas.',b:'Movimientos o sensaciones.',c:'Identidad como categoría independiente.',d:'Función cognitiva.'},c:'c',x:'La c es correcta: Tyrer habla de disociación de la personalidad, no de una categoría denominada «disociación de identidad». Conductas complejas, movimientos o sensaciones y función cognitiva sí aparecen en su clasificación.',r:B},
'PERSEVER___SIMULACRO_COMENTADO_MAYO-UNO-23_201':{e:'¿Qué modelo afirma que el procesamiento integrado requiere la coordinación sincrónica de cuatro ejes?',o:{a:'Disociación estructural.',b:'Modelo autohipnótico.',c:'Modelo BASK.',d:'Modelo SIBAM.'},c:'c',x:'La c es correcta: BASK coordina conducta, afecto, sensación y conocimiento. La disociación estructural separa sistemas defensivo y cotidiano; el modelo autohipnótico se centra en hipnotizabilidad; y SIBAM utiliza cinco componentes.',r:B},
'PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-DOS-23_058':{e:'Según Schalinski y colaboradores, ¿qué edad se asoció especialmente con negligencia física o emocional y síntomas disociativos posteriores?',o:{a:'4–5 años.',b:'6–7 años.',c:'8–9 años.',d:'12–13 años.'},c:'a',x:'La a es correcta: se identificó una ventana de 4–5 años asociada con síntomas disociativos adultos. La franja 8–9 se relacionó más con síntomas depresivos; las otras edades no fueron el hallazgo específico preguntado.',r:'Schalinski, I. et al. (2016). Type and timing of adverse childhood experiences differentially affect severity of PTSD, dissociative and depressive symptoms. BMC Psychiatry, 16, 295. https://doi.org/10.1186/s12888-016-1004-5.'},
'PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-DOS-23_059':{e:'¿Qué autores propusieron un modelo jerárquico de disociación patológica en tres niveles?',o:{a:'Van der Hart, Van der Kolk y Boon.',b:'Kihlstrom.',c:'Hilgard.',d:'Janet.'},c:'a',x:'La a es correcta. Kihlstrom desarrolló una explicación basada en memoria; Hilgard la teoría neodisociativa; y Janet destacó fallos de síntesis psicológica, pero no son los autores del modelo jerárquico preguntado.',r:H},
'PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-UNO-23_142':{e:'En el modelo jerárquico de Van der Hart, ¿qué caracteriza el segundo nivel o disociación secundaria?',o:{a:'Procesamiento fragmentado del trauma.',b:'Desarrollo de identidades separadas.',c:'Percepción del acontecimiento sin experimentar completamente su impacto emocional.',d:'Integración completa de la experiencia.'},c:'c',x:'La c es correcta. La a describe disociación primaria; la b, terciaria; y la d es lo opuesto a la disociación.',r:H},
'PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-UNO-23_166':{e:'La reducción aguda o pérdida de conciencia del entorno, con insensibilidad a estímulos, conductas estereotipadas mínimas o parálisis transitoria, corresponde a:',o:{a:'Despersonalización/desrealización.',b:'Amnesia disociativa.',c:'Trastorno neurocognitivo leve.',d:'Trance disociativo.'},c:'d',x:'La d es correcta: el trance implica restricción marcada de conciencia y respuesta al entorno. La a conserva conciencia del entorno aunque se viva irreal; la b se define por amnesia; y la c no produce este estado episódico.',r:D}
};
for(const [id,z] of Object.entries(U)){const q=a.find(x=>x.id===id);if(!q)throw Error(id);Object.assign(q,z,{v:'VALIDADA_ORIGINAL'});}
function move(id,t,e,o,c,x,r){const i=a.findIndex(q=>q.id===id);if(i<0)throw Error(id);const q=a.splice(i,1)[0];Object.assign(q,{s:'Psicopatología',t:[t],e,o,c,x,r,v:'VALIDADA_ORIGINAL'});psy.push(q)}
move('PERSEV_AGO25_U1_019','Psicopatología de la sensopercepción','Respecto a la sinestesia, señale la afirmación correcta:',{a:'La combinación música-olor es su forma más común.',b:'Es característica principalmente de los trastornos disociativos.',c:'Su prevalencia poblacional se conoce con exactitud absoluta.',d:'En los primeros meses de vida existe mayor conectividad multisensorial, que después se especializa.'},'d','La d es correcta: el desarrollo temprano presenta mayor interconexión sensorial y posterior especialización. La a sustituye combinaciones frecuentes como grafema-color o música-color; la b la asocia erróneamente de forma principal a disociación; y la c presenta como exacta una estimación variable.',B);
move('PERSEVER___SIMULACRO_COMENTADO_JUNIO-DOS-23_069','Psicopatología de la conciencia','Sentirse fuera de uno mismo, observando la propia conducta como si perteneciera a otra persona, corresponde a:',{a:'Escisión de la unidad del yo.',b:'Desorientación temporal.',c:'Obnubilación.',d:'Pérdida de atribución personal.'},'a','La a es correcta: describe una ruptura de la vivencia unitaria del yo. La b afecta orientación; la c reduce el nivel de conciencia; y la d implica no reconocer pensamientos o actos como propios, sin la experiencia extracorporal descrita.',B);
fs.writeFileSync(cp,JSON.stringify(a));fs.writeFileSync(pp,JSON.stringify(psy));const m=JSON.parse(fs.readFileSync(P+'manifest.json'));for(const v of Object.values(m.subjects))v.count=JSON.parse(fs.readFileSync(P+v.slug+'.json')).length;m.total=Object.values(m.subjects).reduce((n,v)=>n+v.count,0);fs.writeFileSync(P+'manifest.json',JSON.stringify(m,null,2)+'\n');console.log({updated:Object.keys(U).length,moved:2,total:m.total});
