const fs=require('fs'),path=require('path'),file=path.join(__dirname,'..','public','banco','clinica_adultos.json'),bank=JSON.parse(fs.readFileSync(file,'utf8'));
const APA='American Psychiatric Association (2022). DSM-5-TR, capítulo «Feeding and Eating Disorders». American Psychiatric Association Publishing.';
const BEL='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. I (4.ª ed.), cap. 13, pp. 485-514. McGraw Hill.';
const U={};function g(id,c,e,o,x,r=`${APA} ${BEL}`){U[id]={c,e,o,x,r,v:'VALIDADA_ORIGINAL'};}
g('14Simulacro2018Comentarios_113','b','Una persona adulta con anorexia nerviosa presenta un IMC de 16,5 kg/m². ¿Qué nivel mínimo de gravedad corresponde?',{a:'Leve.',b:'Moderado.',c:'Grave.',d:'Extremo.'},'La b es correcta: en adultos, un IMC entre 16 y 16,99 kg/m² corresponde a gravedad moderada. Leve es igual o superior a 17; grave, entre 15 y 15,99; y extremo, inferior a 15.');
g('1Simulacro02018Comentarios_029','c','¿Qué trastorno se caracteriza por una alteración de la alimentación que provoca dificultad persistente para cubrir las necesidades nutricionales o energéticas?',{a:'Trastorno de rumiación.',b:'Pica.',c:'Trastorno de evitación/restricción de la ingesta de alimentos.',d:'Bulimia nerviosa.'},'La c es correcta: el TERIA exige fracaso persistente para satisfacer necesidades nutricionales o energéticas con consecuencias clínicas. Pica implica ingerir sustancias no nutritivas; rumiación, regurgitación; y bulimia, atracones con compensación.');
g('ABRIL-UNO-24_COMENTADO_144','b','Respecto a los factores de vulnerabilidad asociados con anorexia nerviosa, señale la afirmación correcta:',{a:'La evitación del daño es necesariamente menor que en bulimia.',b:'Se han descrito perfeccionismo, rigidez y rasgos obsesivo-compulsivos.',c:'La intolerancia emocional carece de relevancia.',d:'Un modelo familiar único explica causalmente todos los casos.'},'La b es correcta. La anorexia se asocia con perfeccionismo, rigidez y rasgos obsesivo-compulsivos. La evitación del daño y la intolerancia emocional pueden ser relevantes, y la etiología es multifactorial, no atribuible a un único patrón familiar.');
g('ABRIL-UNO-24_COMENTADO_145','a','Una persona con trastorno por atracón presenta entre 8 y 13 episodios semanales. ¿Qué gravedad mínima se especifica?',{a:'Grave.',b:'Moderada.',c:'Leve.',d:'Extrema.'},'La a es correcta: 8-13 episodios semanales corresponde a gravedad grave; leve son 1-3, moderada 4-7 y extrema 14 o más.');
g('ABRIL-UNO-24_COMENTADO_146','b','¿Qué trastorno puede diagnosticarse junto con otro trastorno de la conducta alimentaria cuando la conducta adicional justifica atención clínica independiente?',{a:'Trastorno de rumiación.',b:'Pica.',c:'TERIA.',d:'Bulimia nerviosa durante episodios exclusivos de anorexia con atracones/purgas.'},'La b es correcta: la pica puede diagnosticarse adicionalmente cuando su conducta es suficientemente grave para requerir atención propia. Los criterios de rumiación y TERIA contienen exclusiones respecto de otros trastornos alimentarios, y no se diagnostica bulimia si ocurre exclusivamente durante anorexia.');
g('AGOSTO2_063','d','¿Qué antecedente se asocia con mayor riesgo posterior de bulimia nerviosa?',{a:'Ausencia completa de preocupaciones corporales.',b:'Bajo peso mantenido desde la primera infancia.',c:'Falta de exposición a ideales de delgadez.',d:'Obesidad infantil y experiencias de estigmatización por el peso.'},'La d es correcta: la obesidad infantil y la preocupación o estigmatización por peso aumentan el riesgo. Las demás opciones niegan o no representan factores característicos.');
g('AGOSTO2_093','d','En la «docena sucia» de Cash y Grant, ¿cómo se denomina generalizar un estado de ánimo negativo, originado por sucesos ajenos a la apariencia, a la experiencia del propio cuerpo?',{a:'Predecir la desdicha.',b:'El ideal irreal.',c:'Expansión de la fealdad.',d:'El espejo malhumorado.'},'La d es correcta: el espejo malhumorado proyecta un estado emocional negativo sobre la valoración corporal. Predecir la desdicha anticipa consecuencias; el ideal irreal compara con ideales; y expansión de la fealdad generaliza desde una parte corporal rechazada.',BEL);
g('DICIEMBRE-DOS-24_COMENTADO_017','c','¿Qué elemento NO es un componente nuclear de la teoría transdiagnóstica de los trastornos alimentarios?',{a:'Baja autoestima nuclear.',b:'Intolerancia a los estados emocionales.',c:'Inflexibilidad cognitiva como componente transdiagnóstico nuclear.',d:'Dificultades interpersonales.'},'La c es la respuesta: la inflexibilidad cognitiva se ha propuesto como rasgo neurocognitivo o endofenotípico, no como uno de los mecanismos nucleares de mantenimiento del modelo transdiagnóstico. Los otros tres sí se incluyen.',BEL);
g('DICIEMBRE-DOS-24_COMENTADO_019','d','Respecto al curso del trastorno por atracón, señale la afirmación correcta:',{a:'Su inicio medio se sitúa necesariamente antes de los 15 años.',b:'Cada episodio del trastorno dura por definición exactamente 6,5 años.',c:'Siempre está precedido por anorexia nerviosa.',d:'Suele comenzar más tarde que anorexia y bulimia, con frecuencia en la adultez joven o posterior.'},'La d es correcta: el trastorno por atracón suele mostrar un inicio más tardío. La edad no es fija, la duración no es un criterio exacto y puede existir historia de otros trastornos, pero no es obligatoria.');
g('DICIEMBRE-DOS-24_COMENTADO_066','b','Respecto a la pica, señale la afirmación correcta:',{a:'Su principal comorbilidad es necesariamente TDAH.',b:'Puede diagnosticarse junto con otro trastorno alimentario si requiere atención clínica independiente.',c:'En discapacidad intelectual disminuye cuanto mayor es la gravedad.',d:'Las sustancias ingeridas no varían con edad ni disponibilidad.'},'La b es correcta. La pica puede coexistir con otros trastornos alimentarios si es clínicamente independiente; se asocia especialmente a discapacidad intelectual y autismo, puede aumentar con la gravedad intelectual y las sustancias varían según edad y contexto.');
g('DICIEMBRE-UNO-24_COMENTADO_098','a','¿Qué trastorno alimentario presenta, en estudios de curso natural y tratamiento, tasas de remisión relativamente mayores que anorexia y bulimia?',{a:'Trastorno por atracón.',b:'Bulimia nerviosa.',c:'Anorexia nerviosa restrictiva.',d:'Anorexia nerviosa con atracones/purgas.'},'La a es correcta: aunque el trastorno por atracón puede ser persistente y grave, el DSM-5-TR señala tasas de remisión relativamente mayores que en anorexia o bulimia. El enunciado antiguo decía por error «menores».');
g('DICIEMBRE-UNO-24_COMENTADO_099','b','Respecto a los marcadores y hallazgos asociados con bulimia nerviosa, señale la afirmación correcta:',{a:'La erosión del esmalte por vómitos recurrentes es siempre transitoria.',b:'No existe una prueba de laboratorio específica que por sí sola establezca el diagnóstico.',c:'La exploración física revela necesariamente alteraciones graves.',d:'El ejercicio intenso se prescribe siempre ante baja densidad mineral ósea.'},'La b es correcta y corrige la clave antigua. Pueden existir alteraciones electrolíticas y signos de purga, pero ninguna prueba es diagnóstica por sí sola. La erosión puede ser permanente, la exploración puede ser normal y el ejercicio intenso puede aumentar el riesgo de fractura.');
g('DICIEMBRE-UNO-24_COMENTADO_145','a','¿Cuál NO es una característica asociada habitualmente con los episodios de atracón?',{a:'Comer gran cantidad únicamente porque existe hambre física intensa.',b:'Comer mucho más rápido de lo normal.',c:'Comer a solas por vergüenza.',d:'Comer hasta sentirse desagradablemente lleno.'},'La a es la respuesta: el criterio recoge comer grandes cantidades cuando no existe hambre física. Rapidez, plenitud desagradable y comer a solas por vergüenza sí son características asociadas; se requieren al menos tres de cinco.');
g('JULIO1_083','c','Respecto a la bulimia nerviosa, señale la afirmación correcta:',{a:'Todas las personas emplean simultáneamente varios métodos compensatorios.',b:'Los laxantes son el método compensatorio más frecuente.',c:'La autoevaluación está indebidamente influida por el peso y la constitución corporal.',d:'El ejercicio excesivo nunca cuenta como conducta compensatoria.'},'La c es correcta y constituye un criterio diagnóstico. El vómito autoinducido es el método más frecuente; no todas las personas usan varios métodos; y el ejercicio excesivo sí puede ser una conducta compensatoria inapropiada.');
g('JULIO1_084','b','¿Qué característica se asocia más con el subtipo restrictivo de anorexia nerviosa que con el subtipo con atracones/purgas?',{a:'Conductas adictivas.',b:'Perfeccionismo, rigidez y sentimientos de ineficacia.',c:'Mayor impulsividad y labilidad emocional.',d:'Antecedentes personales frecuentes de sobrepeso.'},'La b es correcta. Perfeccionismo, rigidez, hiperresponsabilidad e ineficacia se describen más en el subtipo restrictivo; impulsividad, labilidad, conductas adictivas y antecedentes de sobrepeso se asocian más al subtipo con atracones/purgas.',BEL);
g('JULIO1_085','d','Respecto al desarrollo del TERIA basado en las características sensoriales de los alimentos, señale la afirmación correcta:',{a:'Comienza necesariamente durante la lactancia.',b:'Solo aparece por primera vez después de los 40 años.',c:'Conduce inevitablemente a anorexia o bulimia en la adultez.',d:'Suele comenzar en la primera década y puede seguir un curso estable y duradero.'},'La d es correcta. La evitación sensorial suele aparecer en la primera década y puede persistir; no se limita a lactancia o adultez tardía ni se ha demostrado una evolución inevitable hacia anorexia o bulimia.');
g('JULIO2_032','c','Una persona adulta con anorexia nerviosa presenta un IMC de 15,5 kg/m². ¿Qué especificador mínimo de gravedad corresponde?',{a:'Leve.',b:'Moderado.',c:'Grave.',d:'Extremo.'},'La c es correcta: en adultos, un IMC de 15-15,99 corresponde a gravedad grave. La pregunta original se refería a una menor de 15 años, en quien debe emplearse el percentil de IMC; se ha corregido para que el dato permita responder.');
g('JULIO2_048','c','Respecto a la bulimia nerviosa, señale la afirmación INCORRECTA:',{a:'Atracones y compensaciones aparecen al menos una vez por semana durante tres meses.',b:'La autoevaluación está indebidamente influida por el peso y la constitución corporal.',c:'La gravedad moderada corresponde a 8-13 atracones semanales.',d:'Muchas personas se encuentran en normopeso o sobrepeso.'},'La c es incorrecta y es la respuesta: en bulimia la gravedad se basa en conductas compensatorias inapropiadas, y 8-13 corresponde a grave, no moderada. Las opciones a, b y d son correctas.');
for(const id of ['AGOSTO2_203','JULIO1_098']){const q=bank.find(x=>x.id===id);if(!q)throw Error(`Missing ${id}`);q.t=['Trastornos adictivos y relacionados con sustancias'];}
const gaming=bank.find(q=>q.id==='AGOSTO2_203');Object.assign(gaming,{e:'¿Cuál NO es una denominación empleada para referirse al trastorno de juego por Internet?',o:{a:'Trastorno por uso de Internet.',b:'Adicción a los juegos.',c:'Trastorno por juego de apuestas.',d:'Adicción a Internet.'},c:'c',x:'La c es la respuesta: el juego de apuestas implica arriesgar dinero o bienes y es distinto del juego digital. Las otras expresiones se han usado históricamente, aunque no son completamente equivalentes.',r:'American Psychiatric Association (2022). DSM-5-TR, sección III, «Internet Gaming Disorder». American Psychiatric Association Publishing.',v:'VALIDADA_ORIGINAL'});
const tolerance=bank.find(q=>q.id==='JULIO1_098');Object.assign(tolerance,{e:'En el modelo evolutivo del alcoholismo de Jellinek, ¿en qué fase puede aparecer tolerancia reducida o invertida?',o:{a:'Fase prealcohólica.',b:'Fase prodrómica.',c:'Fase de consumo social estable.',d:'Fase crucial.'},c:'d',x:'La d es correcta: en la fase crucial puede aparecer pérdida de control y tolerancia reducida, alcanzándose intoxicación con cantidades menores. Es un modelo histórico y no una clasificación diagnóstica actual.',r:'Jellinek, E. M. (1952). Phases of alcohol addiction. Quarterly Journal of Studies on Alcohol, 13, 673-684.',v:'VALIDADA_ORIGINAL'});
let n=0;for(const q of bank)if(U[q.id]){Object.assign(q,U[q.id]);n++;}if(n!==18)throw Error(`Expected 18 eating updates, got ${n}`);fs.writeFileSync(file,JSON.stringify(bank));console.log('Audited 20; rehomed 2.');
