const fs=require('fs'),path=require('path'),file=path.join(__dirname,'..','public','banco','clinica_adultos.json'),b=JSON.parse(fs.readFileSync(file,'utf8'));
const ref='American Psychiatric Association (2022). DSM-5-TR, capítulo «Personality Disorders» y modelo alternativo de la sección III; Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología (4.ª ed.), capítulo de trastornos de la personalidad.';
const rows={
'PERSEVER___SIMULACRO_COMENTADO_JULIO-DOS-23_040':['d','La d es correcta: el modelo alternativo conserva seis tipos, entre ellos evitativo, límite y obsesivo-compulsivo, pero no esquizoide.'],
'PERSEVER___SIMULACRO_COMENTADO_JULIO-DOS-23_062':['c','La c es correcta: el modelo de comunicación social sitúa la disfunción social y las dificultades de mentalización entre los procesos que mantienen el TLP. La confianza epistémica es central en su desarrollo temprano.'],
'PERSEVER___SIMULACRO_COMENTADO_JULIO-DOS-23_063':['a','La a es correcta: la personalidad evitativa es frecuente en muestras clínicas con otros trastornos. Reticencia a desechar objetos corresponde al patrón obsesivo-compulsivo.'],
'PERSEVER___SIMULACRO_COMENTADO_JULIO-UNO-23_049':['a','La a es correcta: la hipótesis de «demencia semántica» de Cleckley se formuló para explicar la psicopatía o personalidad antisocial.'],
'PERSEVER___SIMULACRO_COMENTADO_JULIO-UNO-23_055':['d','La d es la excepción. La esquizotipia incluye experiencias inusuales, desorganización cognitiva, anhedonia introvertida e inconformismo impulsivo.'],
'PERSEVER___SIMULACRO_COMENTADO_JUNIO-DOS-23_078':['b','La b es correcta: el TLP suele mostrar inestabilidad crónica en la adultez con crisis de descontrol y uso elevado de recursos. El antisocial puede atenuarse especialmente después de la cuarta década, no la segunda.'],
'PERSEVER___SIMULACRO_COMENTADO_JUNIO-UNO-23_100':['a','La a es correcta: anhedonia es una faceta del dominio de desapego.'],
'PERSEVER___SIMULACRO_COMENTADO_JUNIO-UNO-23_101':['c','La c es correcta: las ideas paranoides pueden aparecer en personalidad paranoide, esquizotípica y, transitoriamente bajo estrés, en TLP; no forman parte del patrón esquizoide.'],
'PERSEVER___SIMULACRO_COMENTADO_MAYO-DOS-23_055':['b','La b es la afirmación incorrecta según la fuente: aunque suele asumirse mayor riesgo en juventud, el suicidio consumado puede aparecer más tarde. Las demás reflejan las estimaciones y comorbilidades citadas en el manual.'],
'PERSEVER___SIMULACRO_COMENTADO_MAYO-DOS-23_056':['d','La d es correcta: el modelo alternativo no conserva el tipo esquizoide; sí incluye límite, obsesivo-compulsivo y evitativo.'],
'PERSEVER___SIMULACRO_COMENTADO_MAYO-UNO-23_112':['d','La d es correcta: empatía e intimidad integran el funcionamiento interpersonal; identidad y autodirección integran el funcionamiento del self.'],
'PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-DOS-23_037':['b','La b es correcta según el seguimiento citado: trastornos del estado de ánimo, ansiedad generalizada y TOC muestran mayor persistencia; otras comorbilidades tienden a remitir más.'],
'PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-DOS-23_038':['d','La d es correcta: un entorno temprano desadaptativo constituye un factor de riesgo relevante; las demás alternativas invierten o restringen indebidamente los hallazgos longitudinales.'],
'PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-DOS-23_065':['a','La a es correcta: los patrones límite y antisocial son los que más tienden a atenuarse o remitir con la edad.'],
'PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-DOS-23_071':['c','La c es correcta: se han descrito déficits prefrontales capaces de contribuir a baja activación ante estrés, falta de atención y problemas decisionales. La baja conductancia de la opción d se atribuye en la fuente al trastorno de conducta.'],
'PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-UNO-23_136':['c','La c es correcta: los estudios de curso citados asocian la peor calidad de vida con personalidad límite, narcisista y obsesivo-compulsiva.'],
'PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-DOS-23_032':['d','La d es correcta: psicoticismo y desapego son los dominios prominentes del perfil esquizotípico en el modelo alternativo.'],
'PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-DOS-23_053':['a','La a es correcta según la comparación utilizada. DSM permite especificar un trastorno de personalidad mediante rasgos; CIE-11 usa distinta gravedad, exige persistencia aproximada de dos años y ofrece calificadores de rasgos propios.'],
'PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-DOS-23_076':['c','La c es la opción que NO reproduce el criterio: DSM excluye que el patrón aparezca exclusivamente durante esquizofrenia o trastorno bipolar; no menciona aquí depresión ni afección médica.'],
'PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-UNO-23_052':['a','La a es correcta: Turkat propuso esta teoría por estadios para el desarrollo de la personalidad paranoide.']};
const clean=s=>String(s??'').replace(/[�]/g,'').replace(/\b([A-Za-zÁÉÍÓÚáéíóúñÑ]{2,})-\s+([a-záéíóúñ]{2,})\b/g,'$1$2').replace(/\s+/g,' ').trim();
for(const[id,[c,x]]of Object.entries(rows)){const q=b.find(z=>z.id===id);if(!q)throw Error(id);q.c=c;q.e=clean(q.e).replace(/^(?:\d+\s+){1,6}(?=[¿¡A-ZÁÉÍÓÚ])/,'').replace(/verdad epistémica/gi,'confianza epistémica');for(const k of'abcd'){q.o[k]=clean(q.o[k]).replace(/verdad epistémica/gi,'confianza epistémica');const p=q.o[k].search(/\s+(?:R[1-4]\s*(?:CORRECTA|INCORRECTA)|El Modelo de|La hipótesis de|El término esquizotipia|En el modelo alternativo|Dentro de la etiología)/i);if(p>10)q.o[k]=q.o[k].slice(0,p).trim()}Object.assign(q,{x,r:ref,v:'VALIDADA_ORIGINAL'})}
fs.writeFileSync(file,JSON.stringify(b));console.log({audited:Object.keys(rows).length});
