import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const bank=path.join(root,'public','banco');
const manifest=JSON.parse(fs.readFileSync(path.join(bank,'manifest.json'),'utf8'));
const datasets=new Map(Object.entries(manifest.subjects).map(([s,m])=>[s,JSON.parse(fs.readFileSync(path.join(bank,m.slug+'.json'),'utf8'))]));
const ta=datasets.get('Tratamientos Adultos');
const topic='Tratamiento de la psicosis y esquizofrenia';
const F='Fonseca-Pedrero, E. (coord.) (2019). Tratamientos psicológicos para la psicosis. Pirámide.';
const A='Fonseca-Pedrero, E. (coord.) (2021). Manual de tratamientos psicológicos: Adultos. Pirámide.';
const clean=s=>String(s||'').replace(/[]/g,'').replace(/\u00ad/g,'').replace(/([A-Za-zÁÉÍÓÚáéíóúñÑ])[-‐]\s+([a-záéíóúñ])/g,'$1$2').replace(/\s+/g,' ').trim().replace(/^\d+(?:\s+\d+)*\s+(?=[¿A-ZÁÉÍÓÚ])/,'');
const full=(correct, reasons)=>`La opción ${correct} es correcta: ${reasons}`;
const updates={
'3Simulacro2018Comentarios_172':{e:'¿Cuál de los siguientes módulos NO se incorporó a la reformulación ampliada de la Terapia Psicológica Integrada (IPT) para la esquizofrenia?',o:{a:'Entrenamiento en manejo de emociones.',b:'Entrenamiento en habilidades de ocio, vivienda y trabajo.',c:'Tratamiento orientado al afrontamiento.',d:'Entrenamiento específico en hábitos de vida saludable.'},c:'d',x:full('d','el entrenamiento específico en hábitos de vida saludable no figura entre los módulos añadidos a la reformulación ampliada de la IPT. La a es falsa porque el manejo de emociones sí se incorporó. La b es falsa porque las habilidades de ocio, vivienda y trabajo forman parte de la ampliación funcional. La c es falsa porque el tratamiento orientado al afrontamiento también fue incorporado.'),r:F},
'4Simulacro02018Comentarios_174':{e:'Según las recomendaciones de Liberman para la esquizofrenia, ¿qué duración aproximada tiene la fase de estabilización, cuyo objetivo incluye reducir el estrés psicosocial?',o:{a:'Desde el inicio del episodio agudo hasta aproximadamente los 6–12 meses siguientes.',b:'Desde el inicio del episodio agudo hasta aproximadamente los 12–18 meses siguientes.',c:'Desde el inicio del episodio agudo hasta aproximadamente los 3–6 meses siguientes.',d:'Tiene necesariamente una duración indefinida.'},c:'a',x:full('a','la fase de estabilización se extiende aproximadamente durante los 6–12 meses posteriores al inicio del episodio agudo y busca consolidar la remisión y reducir el estrés y el riesgo de recaída. La b prolonga el intervalo más allá del marco descrito. La c lo acorta. La d confunde estabilización con el seguimiento o mantenimiento de duración individualizada.'),r:F},
'4Simulacro02018Comentarios_188':{e:'Dentro de la Terapia Psicológica Integrada (IPT) para la esquizofrenia, ¿qué módulo entrena directamente la ejecución de conductas interpersonales mediante práctica y retroalimentación?',o:{a:'Diferenciación cognitiva.',b:'Percepción social.',c:'Comunicación verbal.',d:'Entrenamiento en habilidades sociales.'},c:'d',x:full('d','el módulo de habilidades sociales utiliza modelado, ensayo conductual y retroalimentación para practicar respuestas interpersonales. La a trabaja procesos cognitivos básicos. La b se centra en analizar claves y situaciones sociales. La c entrena el intercambio verbal, pero no designa el módulo de práctica conductual interpersonal preguntado.'),r:'Roder, V., Brenner, H. D., Kienzle, N. y Fuentes, I. (2007). Terapia psicológica integrada para la esquizofrenia. Alborán; '+F},
'4Simulacro02018Comentarios_190':{e:'En el tratamiento de la esquizofrenia, ¿qué caracteriza a la intervención cognitivo-conductual desarrollada por Tarrier y colaboradores?',o:{a:'Es exclusivamente una intervención familiar psicoeducativa.',b:'Consiste únicamente en entrenamiento en habilidades sociales.',c:'Es una intervención cognitivo-conductual dirigida a reducir el malestar y la interferencia asociados a delirios y alucinaciones.',d:'Es una modalidad de tratamiento asertivo comunitario.'},c:'c',x:full('c','Tarrier desarrolló una intervención cognitivo-conductual centrada en estrategias de afrontamiento y en el trabajo con síntomas psicóticos persistentes, como delirios y alucinaciones. La a corresponde a programas familiares. La b reduce indebidamente el tratamiento a habilidades sociales. La d describe un modelo de organización comunitaria de servicios.'),r:'Tarrier, N. et al. (1993). A trial of two cognitive-behavioural methods of treating drug-resistant residual psychotic symptoms in schizophrenic patients. British Journal of Psychiatry, 162, 524–532. https://doi.org/10.1192/bjp.162.4.524; '+F},
'ABRIL-UNO-24_COMENTADO_096':{e:'¿Qué cuatro habilidades incluye el modelo integrador de metacognición aplicado a la psicosis?',o:{a:'Autorreflexividad, comprensión de la mente ajena, teoría de la mente y estilo atribucional.',b:'Procesamiento emocional, percepción social, teoría de la mente y estilo atribucional.',c:'Autorreflexividad, comprensión de la mente ajena, descentramiento y dominio.',d:'Percepción emocional, descentramiento, percepción social y estilo atribucional.'},c:'c',x:full('c','el modelo distingue autorreflexividad, comprensión de la mente del otro, descentramiento y dominio, entendido este último como utilización integrada de la información metacognitiva para afrontar problemas. La a sustituye descentramiento y dominio por constructos que no forman la cuaterna. La b enumera dominios clásicos de cognición social. La d mezcla componentes de cognición social con descentramiento.'),r:'Lysaker, P. H. y Dimaggio, G. (2014). Metacognitive capacities for reflection in schizophrenia. Journal of Contemporary Psychotherapy, 44, 73–83. https://doi.org/10.1007/s10879-013-9249-6; '+F},
'JUNIO1_131':{e:'En la arquitectura piramidal del fenotipo psicótico de Yung, ¿a qué nivel corresponden las experiencias psicotiformes asociadas a malestar, búsqueda de ayuda y deterioro funcional o comorbilidad?',o:{a:'Nivel 1.',b:'Nivel 2.',c:'Nivel 3.',d:'Nivel 4.'},c:'c',x:full('c','el nivel 3 reúne experiencias psicotiformes clínicamente relevantes por su asociación con malestar, búsqueda de ayuda, deterioro o comorbilidad. La a recoge experiencias incidentales sin malestar. La b representa un nivel intermedio de experiencias más persistentes, pero sin el conjunto clínico descrito. La d corresponde al extremo de mayor gravedad, con trastorno psicótico establecido.'),r:'Yung, A. R. et al. (2007). The psychosis threshold in Ultra High Risk research. Schizophrenia Bulletin, 33(6), 1436–1440. https://doi.org/10.1093/schbul/sbm074; '+F},
'PERSEV_AGO25_U1_179':{e:'Respecto al marco de recuperación personal CHIME en psicosis, señale la afirmación correcta:',o:{a:'Describe ocho niveles secuenciales de asimilación de experiencias problemáticas.',b:'La C corresponde a conciencia social.',c:'La H corresponde a empoderamiento y responsabilidad.',d:'La M corresponde a meaning, es decir, significado vital.'},c:'d',x:full('d','la M de CHIME corresponde a Meaning in life, construcción de significado vital. La a describe otro modelo procesual y CHIME no impone ocho etapas. La b es falsa porque C corresponde a Connectedness o conexión. La c es falsa porque H corresponde a Hope and optimism; el empoderamiento se representa con la E.'),r:'Leamy, M., Bird, V., Le Boutillier, C., Williams, J. y Slade, M. (2011). Conceptual framework for personal recovery in mental health. British Journal of Psychiatry, 199(6), 445–452. https://doi.org/10.1192/bjp.bp.110.083733.'},
'PERSEV_JUL25_D2_106':{e:'Señale la afirmación correcta sobre la Terapia de Remediación Cognitiva (CRT) y la Terapia de Potenciación Cognitiva (CET) para la psicosis:',o:{a:'En primeros episodios, la CET se ha asociado con preservación del volumen de sustancia gris en diversas estructuras cerebrales.',b:'La CRT se limita a atención, memoria y solución de problemas y excluye las funciones ejecutivas.',c:'La CET trabaja exclusivamente funciones ejecutivas, atención y memoria.',d:'La CET consta de 40 sesiones individuales de una hora, tres veces por semana.'},c:'a',x:full('a','estudios de CET en primeros episodios han informado efectos compatibles con una mayor preservación de sustancia gris. La b es falsa porque la CRT también aborda funciones ejecutivas y no se define por esa exclusión. La c es falsa porque CET integra entrenamiento neurocognitivo y cognición social. La d es falsa porque ese formato no corresponde al programa CET, que es más prolongado e integra sesiones grupales y entrenamiento asistido por ordenador.'),r:'Eack, S. M. et al. (2010). Neuroprotective effects of cognitive enhancement therapy against gray matter loss in early schizophrenia. Archives of General Psychiatry, 67(7), 674–682. https://doi.org/10.1001/archgenpsychiatry.2010.63; '+F},
'PERSEVER___SIMULACRO_COMENTADO_ABRIL-DOS-23_061':{e:'Respecto al Tratamiento Asertivo Comunitario (TAC), señale la afirmación INCORRECTA:',o:{a:'Suele mostrar mayor utilidad en áreas con elevada densidad poblacional y morbilidad psiquiátrica.',b:'El equipo mantiene contactos frecuentes con la persona atendida, ajustados a sus necesidades.',c:'Las principales guías recomiendan el TAC para personas con esquizofrenia con escasa vinculación a los servicios.',d:'El TAC flexible amplía el modelo mediante una gestión de casos adaptable a un perfil más amplio.'},c:'b',x:full('b','tal como estaba formulada, fijar como requisito universal un mínimo de un contacto semanal no define de manera exacta la intensidad flexible del TAC; la frecuencia se individualiza y puede ser mayor. La a describe contextos donde el modelo presenta especial utilidad. La c recoge una indicación compartida por guías clínicas para personas con mala vinculación. La d describe correctamente el desarrollo de equipos TAC flexibles.'),r:A+' Véase Tratamiento Asertivo Comunitario, p. 257.'},
'PERSEVER___SIMULACRO_COMENTADO_ABRIL-DOS-23_079':{e:'En los estados mentales de alto riesgo de psicosis, ¿en qué grupo tiende a ser más breve la duración de los síntomas psicóticos atenuados no tratados?',o:{a:'Síntomas positivos atenuados (APS).',b:'Episodios psicóticos breves, limitados e intermitentes (BLIPS).',c:'Riesgo genético o personalidad esquizotípica con deterioro funcional (GRD).',d:'Síntomas básicos.'},c:'b',x:full('b','los BLIPS se definen por episodios psicóticos francos pero breves y autorremitidos, por lo que la duración no tratada tiende a ser menor. La a implica síntomas subumbrales más persistentes. La c se define por riesgo genético o esquizotipia junto con deterioro funcional, no por episodios breves. La d recoge alteraciones subjetivas básicas y no el patrón temporal descrito.'),r:F},
'PERSEVER___SIMULACRO_COMENTADO_ABRIL-DOS-23_080':{e:'En relación con los niveles de prevención primaria de la psicosis, señale la afirmación correcta:',o:{a:'La prevención universal se dirige únicamente a grupos con riesgo elevado que aún no presentan síntomas.',b:'La prevención selectiva se dirige a personas que ya muestran signos o síntomas subclínicos.',c:'La prevención indicada se dirige indiscriminadamente a toda la población.',d:'En los estados mentales de alto riesgo, la prevención indicada forma parte de la intervención temprana, a diferencia de la universal y la selectiva.'},c:'d',x:full('d','la intervención sobre estados mentales de alto riesgo corresponde a prevención indicada y se integra en los programas de intervención temprana. La a confunde prevención universal con selectiva: la universal se dirige a la población general. La b confunde selectiva con indicada: la selectiva se dirige a grupos con mayor riesgo sin signos clínicos necesarios. La c es falsa porque la indicada se dirige a personas con manifestaciones subclínicas o marcadores individuales de alto riesgo.'),r:F},
'PERSEVER___SIMULACRO_COMENTADO_ABRIL-DOS-23_201':{e:'En relación con los niveles de prevención primaria de la psicosis, señale la afirmación correcta:',o:{a:'La prevención universal se dirige únicamente a grupos con riesgo elevado que aún no presentan síntomas.',b:'La prevención selectiva se dirige a personas que ya muestran signos o síntomas subclínicos.',c:'La prevención indicada se dirige indiscriminadamente a toda la población.',d:'En los estados mentales de alto riesgo, la prevención indicada forma parte de la intervención temprana, a diferencia de la universal y la selectiva.'},c:'d',x:full('d','la intervención sobre estados mentales de alto riesgo corresponde a prevención indicada y se integra en los programas de intervención temprana. La a confunde universal con selectiva. La b confunde selectiva con indicada. La c atribuye a la prevención indicada el objetivo poblacional propio de la universal.'),r:F},
'PERSEVER___SIMULACRO_COMENTADO_AGOSTO-UNO-23_175':{e:'¿Cuál de los siguientes NO es un elemento fundamental del Tratamiento Asertivo Comunitario (TAC)?',o:{a:'Prestación continuada de servicios, con disponibilidad 24 horas al día y siete días a la semana.',b:'Baja proporción de personas atendidas por profesional, aproximadamente 1:10.',c:'Realización de las intervenciones principalmente en el contexto hospitalario.',d:'Mantenimiento de la atención durante periodos amplios y, si es necesario, sin un límite prefijado.'},c:'c',x:full('c','el TAC presta la intervención principalmente en el entorno natural y comunitario de la persona, no en el hospital. La a sí es un elemento característico por la disponibilidad continuada. La b también es característica porque una ratio baja permite atención intensiva. La d también forma parte del modelo, que mantiene continuidad durante periodos prolongados cuando es necesario.'),r:A+' Véase Tratamiento Asertivo Comunitario, p. 257.'},
'PERSEVER___SIMULACRO_COMENTADO_AGOSTO-UNO-23_176':{e:'En la Terapia Neurocognitiva Integrada (INT) para la psicosis, ¿qué área pertenece a la cognición social?',o:{a:'Velocidad de procesamiento.',b:'Razonamiento y resolución de problemas.',c:'Regulación emocional.',d:'Memoria de trabajo.'},c:'c',x:full('c','la regulación emocional se incluye entre las áreas de cognición social trabajadas por la INT. La a es un dominio neurocognitivo. La b también pertenece a la neurocognición. La d es asimismo una función neurocognitiva; ninguna de estas tres constituye el dominio sociocognitivo solicitado.'),r:A+' Véase INT, pp. 279–283.'},
'PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-UNO-23_081':{e:'Según el modelo de estadificación de la psicosis de Wood y colaboradores, ¿en cuál de los siguientes estadios se aplica prevención indicada?',o:{a:'Malestar inespecífico.',b:'Primer episodio psicótico.',c:'Recurrencia y persistencia.',d:'Resistencia al tratamiento.'},c:'a',x:full('a','el malestar inespecífico, junto con los estados mentales de alto riesgo, se sitúa en la fase de prevención indicada. La b corresponde a intervención temprana y prevención secundaria. La c corresponde a prevención terciaria y rehabilitación. La d exige estrategias para enfermedad persistente o resistente, no prevención indicada.'),r:F+' Véase el modelo de estadificación, p. 65.'},
'PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-UNO-23_193':{e:'¿Cuál de los siguientes NO es un criterio de inclusión habitual de la Terapia de Potenciación Cognitiva (CET) para la psicosis?',o:{a:'Encontrarse en fase aguda.',b:'Presentar un cociente intelectual superior a 80.',c:'No presentar dependencia comórbida de sustancias.',d:'Recibir tratamiento en régimen ambulatorio.'},c:'a',x:full('a','la CET se aplica a personas clínicamente estabilizadas y en fase de recuperación, no durante la fase aguda. La b sí figura entre los criterios de inclusión descritos. La c también, pues la dependencia de sustancias comórbida suele excluirse. La d es compatible con el formato ambulatorio del programa.'),r:F+' Véase CET, p. 330.'},
'PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-UNO-23_199':{e:'Señale la afirmación correcta sobre los siete principios del Diálogo Abierto para la psicosis:',o:{a:'La respuesta inmediata procura celebrar la primera reunión antes de que transcurran 24 horas desde el primer contacto.',b:'Las personas de la red social que se incorporan deben permanecer obligatoriamente durante todo el tratamiento.',c:'Asumir la responsabilidad implica organizar el equipo y derivar sistemáticamente el caso a otros servicios.',d:'La tolerancia a la incertidumbre exige tomar decisiones diagnósticas y terapéuticas de inmediato.'},c:'a',x:full('a','la respuesta inmediata implica disponibilidad y organización de la primera reunión dentro de las primeras 24 horas. La b es falsa porque la composición de la red permanece abierta y flexible. La c es falsa porque el equipo asume la responsabilidad y evita derivaciones fragmentadoras innecesarias. La d es falsa porque tolerar la incertidumbre supone aplazar decisiones prematuras mientras se construye el diálogo.'),r:'Seikkula, J. y Olson, M. E. (2003). The Open Dialogue Approach to Acute Psychosis. Family Process, 42(3), 403–418. https://doi.org/10.1111/j.1545-5300.2003.00403.x; '+F},
'PERSEVER___SIMULACRO_COMENTADO_ENERO-UNO-23_161':{e:'¿Cuál es una diferencia entre la Terapia de Potenciación Cognitiva (CET) y la Terapia Psicológica Integrada (IPT) para la esquizofrenia?',o:{a:'La CET aborda solo neurocognición y la IPT aborda neurocognición y cognición social.',b:'La IPT aborda solo neurocognición y la CET aborda neurocognición y cognición social.',c:'Ambas abordan neurocognición y cognición social, pero la IPT es menos lineal y escalonada que la CET.',d:'Ambas abordan neurocognición y cognición social, pero la CET es menos lineal y escalonada que la IPT.'},c:'d',x:full('d','ambas intervenciones trabajan neurocognición y cognición social, pero CET presenta una organización menos lineal y escalonada que IPT. La a es falsa porque CET no se limita a neurocognición. La b es falsa porque IPT tampoco se limita a neurocognición. La c invierte la diferencia organizativa descrita.'),r:'Hogarty, G. E. y Flesher, S. (1999). Practice principles of cognitive enhancement therapy for schizophrenia. Schizophrenia Bulletin, 25(4), 693–708. https://doi.org/10.1093/oxfordjournals.schbul.a033414; '+F},
};
for(const [id,u] of Object.entries(updates)){const q=ta.find(x=>x.id===id);if(!q||q.t?.[0]!==topic)throw Error(id);Object.assign(q,u,{v:'VALIDADA_ORIGINAL'});}
const moves={
'PERSEV_AGO25_U1_122':['Tratamientos Adultos','Tratamiento de la depresión y trastornos del ánimo'],
'PERSEV_JUL25_D2_161':['Tratamientos Adultos','Tratamiento de los trastornos somáticos']};
for(const [id,[s,t]] of Object.entries(moves)){const i=ta.findIndex(q=>q.id===id);const q=ta[i];if(!q)throw Error(id);ta.splice(i,1);datasets.get(s).push({...q,s,t:[t],v:'REVISAR'});}
const all=[...datasets.values()].flat();if(all.length!==manifest.total||new Set(all.map(q=>q.id)).size!==all.length)throw Error('integridad');
for(const [s,d] of datasets){manifest.subjects[s].count=d.length;fs.writeFileSync(path.join(bank,manifest.subjects[s].slug+'.json'),JSON.stringify(d)+'\n');}
fs.writeFileSync(path.join(bank,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');
console.log(JSON.stringify({validated:Object.keys(updates).length,rehome:Object.keys(moves).length,remainingFirstBlock:55-Object.keys(updates).length-Object.keys(moves).length,total:all.length},null,2));
