const fs=require('fs'),P='public/banco/';
let adult=JSON.parse(fs.readFileSync(P+'clinica_adultos.json','utf8'));
let childTreat=JSON.parse(fs.readFileSync(P+'tratamientos_infantiles.json','utf8'));
const DSM='American Psychiatric Association (2022). DSM-5-TR. Trastornos relacionados con sustancias y trastornos adictivos.';
const BEL='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. I (4.ª ed.). McGraw Hill, capítulo sobre trastornos adictivos.';
const U={
'3Simulacro2018Comentarios_164':{e:'¿Qué efecto gastrointestinal es característico del consumo de opioides como la heroína?',o:{a:'Diarrea intensa.',b:'Hematemesis inmediata.',c:'Hiperperistaltismo.',d:'Estreñimiento.'},c:'d',x:'La d es correcta: los opioides disminuyen la motilidad gastrointestinal y producen estreñimiento. La a es característica de la abstinencia, no del consumo. La b no es un efecto típico y la c expresa lo contrario del efecto farmacológico.',r:DSM},
'ABRIL-UNO-24_COMENTADO_164':{e:'¿Qué modelo del juego por Internet integra motivación, control ejecutivo y toma de decisiones y propone implicaciones terapéuticas?',o:{a:'Modelo de uso patológico de Internet de Davis.',b:'Modelo de desarrollo y mantenimiento de Brand.',c:'Modelo cognitivo-conductual de Dong y Potenza.',d:'Modelo neurocognitivo tripartito de Wei.'},c:'c',x:'La c es correcta: Dong y Potenza articulan esos tres componentes. Davis diferencia uso patológico generalizado y específico; Brand destaca predisposición, respuestas afectivo-cognitivas y control ejecutivo; y Wei propone sistemas impulsivo, reflexivo e interoceptivo.',r:'Dong, G. y Potenza, M. N. (2014). A cognitive-behavioral model of Internet gaming disorder. Journal of Psychiatric Research, 58, 7–11. https://doi.org/10.1016/j.jpsychires.2014.07.005.'},
'ABRIL-UNO-24_COMENTADO_165':{e:'¿Cómo se denomina el impulso de consumir regularmente una sustancia para obtener placer o evitar malestar?',o:{a:'Potencial adictivo.',b:'Tolerancia.',c:'Dependencia física.',d:'Dependencia psíquica.'},c:'d',x:'La d es correcta: describe deseo y necesidad psicológica de consumo. La a es la capacidad de una sustancia para generar adicción; b implica necesitar dosis mayores; y c se evidencia mediante adaptación fisiológica y abstinencia.',r:BEL},
'DICIEMBRE-DOS-24_COMENTADO_013':{e:'Respecto al cannabis y sus consecuencias, señale la afirmación correcta:',o:{a:'El inicio temprano y el consumo frecuente o de alta potencia se asocian con mayor riesgo de consecuencias adversas.',b:'La abstinencia alcanza siempre su máximo entre 20 y 48 horas.',c:'El consumo habitual elimina las reacciones paranoides y la ansiedad aguda.',d:'Todo consumo triplica necesariamente el riesgo de psicosis.'},c:'a',x:'La a es correcta: edad temprana, frecuencia y potencia se relacionan con mayor riesgo. La b fija un curso propio de otras sustancias y no es universal para cannabis. La c es falsa: la tolerancia no elimina esas reacciones. La d convierte una asociación dependiente de dosis y patrón en un riesgo idéntico para cualquier consumo.',r:DSM+' National Academies of Sciences, Engineering, and Medicine (2017). The Health Effects of Cannabis and Cannabinoids.'},
'DICIEMBRE-DOS-24_COMENTADO_014':{e:'¿Qué factor facilita especialmente el aprendizaje y mantenimiento del consumo de sustancias?',o:{a:'Una menor percepción de riesgo reduce el consumo.',b:'La búsqueda de sensaciones protege frente al consumo.',c:'El rendimiento académico no guarda relación con el consumo.',d:'La inmediatez del efecto facilita la asociación entre conducta y refuerzo.'},c:'d',x:'La d es correcta: cuanto más inmediata es la consecuencia reforzante, más eficaz es el aprendizaje. La a invierte la relación; b es falsa porque búsqueda de sensaciones se asocia con mayor riesgo; y c niega una asociación bien documentada.',r:BEL},
'DICIEMBRE-DOS-24_COMENTADO_016':{e:'Según el DSM-5-TR, ¿qué fenómeno es frecuente en el trastorno por consumo de estimulantes?',o:{a:'El efecto euforizante tarda siempre más de una hora cuando se fuma.',b:'Las claves asociadas a la droga pueden provocar craving condicionado.',c:'La abstinencia se caracteriza principalmente por delirium.',d:'Es más frecuente en mayores de 65 años que en adultos jóvenes.'},c:'b',x:'La b es correcta: personas, lugares u objetos asociados pueden desencadenar deseo intenso. La a es falsa porque fumar o inyectar produce efectos rápidos. La c es falsa: predominan disforia, fatiga, sueño y cambios psicomotores. La d contradice la distribución por edad.',r:DSM},
'DICIEMBRE-UNO-24_COMENTADO_108':{e:'¿Cómo se denomina la euforia inicial breve e intensa producida por algunos inhalantes, seguida de sedación?',o:{a:'Crash.',b:'Rush.',c:'Craving.',d:'Flashback.'},c:'b',x:'La b es correcta: rush designa el efecto euforizante inicial. Crash es el estado disfórico tras estimulantes; craving es deseo intenso; y flashback es recurrencia perceptiva posterior, especialmente asociada a alucinógenos.',r:BEL},
'DICIEMBRE-UNO-24_COMENTADO_109':{e:'¿Cuál NO es un diagnóstico relacionado con el alcohol del DSM-5-TR?',o:{a:'Dependencia del alcohol como categoría separada.',b:'Trastorno por consumo de alcohol.',c:'Intoxicación por alcohol.',d:'Abstinencia de alcohol.'},c:'a',x:'La a es correcta: abuso y dependencia se integraron en trastorno por consumo de alcohol. Las opciones b, c y d sí son diagnósticos actuales.',r:DSM},
'JULIO1_099':{e:'Respecto al trastorno por juego de apuestas, señale la afirmación correcta:',o:{a:'Presenta elevada comorbilidad con trastornos por consumo de sustancias, incluido tabaco y alcohol.',b:'La frecuencia de juego determina por sí sola la gravedad.',c:'El efecto telescópico se observa exclusivamente en hombres.',d:'La comorbilidad afectiva y ansiosa es idéntica en hombres y mujeres.'},c:'a',x:'La a es correcta: la comorbilidad con consumo de sustancias es elevada. La b es falsa porque importan pérdida de control, consecuencias y criterios, no solo frecuencia. La c es falsa: el efecto telescópico se ha descrito especialmente en mujeres. La d ignora diferencias clínicas por sexo.',r:DSM},
'JULIO1_100':{e:'¿Cuál es un signo característico de la abstinencia de opioides?',o:{a:'Miosis con depresión respiratoria.',b:'Estreñimiento y sedación.',c:'Lagrimeo o rinorrea.',d:'Ausencia de síntomas autonómicos.'},c:'c',x:'La c es correcta: lagrimeo/rinorrea forman parte del síndrome, junto con midriasis, piloerección, diarrea y dolores. La a y b describen intoxicación por opioides. La d es falsa porque la abstinencia presenta activación autonómica.',r:DSM},
'JULIO2_022':{e:'Según la caracterización de Belloch, ¿qué modalidad alucinatoria aparece con especial frecuencia en trastornos inducidos por sustancias?',o:{a:'Auditiva.',b:'Visual.',c:'Gustativa.',d:'Olfativa.'},c:'b',x:'La b es correcta según la tabla comparativa del manual. Las modalidades a, c y d pueden aparecer según sustancia y cuadro, pero no son la respuesta general solicitada.',r:'Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. I (4.ª ed.). McGraw Hill, psicopatología de la percepción.'},
'JUNIO-UNO-24_COMENTADO_045':{e:'¿Para cuál de las siguientes sustancias no establece el DSM-5-TR un trastorno por consumo específico?',o:{a:'Inhalantes.',b:'Cafeína.',c:'Estimulantes.',d:'Tabaco.'},c:'b',x:'La b es correcta: existen intoxicación y abstinencia por cafeína, pero no un trastorno por consumo de cafeína formal. Inhalantes, estimulantes y tabaco sí tienen trastornos por consumo.',r:DSM},
'JUNIO-UNO-24_COMENTADO_066':{e:'¿Cuál NO es un criterio nuclear que defina por sí mismo las adicciones comportamentales?',o:{a:'Pérdida de control.',b:'Tolerancia funcional o necesidad de aumentar la conducta.',c:'Malestar al reducir o impedir la conducta.',d:'Daño orgánico farmacotóxico directo.'},c:'d',x:'La d es correcta: al no administrarse una sustancia, no existe toxicidad farmacológica directa como criterio nuclear. La a, b y c describen fenómenos clínicos análogos a pérdida de control, tolerancia y abstinencia.',r:BEL},
'JUNIO-UNO-24_COMENTADO_068':{e:'¿Qué describe mejor un uso no problemático de una sustancia?',o:{a:'Un patrón que produce deterioro clínicamente significativo.',b:'Consumo persistente pese a consecuencias negativas.',c:'Ingesta ocasional sin consecuencias negativas ni pérdida de control.',d:'Consumo moderado con deterioro funcional mantenido.'},c:'c',x:'La c es correcta: describe uso sin daño clínico. La a, b y d incorporan consecuencias o deterioro y se aproximan a consumo problemático o trastorno.',r:BEL},
'JUNIO1_084':{e:'¿Qué caracteriza al modelo de desarrollo y mantenimiento de la adicción a Internet de Brand y colaboradores?',o:{a:'Se limita a distinguir uso generalizado y específico sin procesos ejecutivos.',b:'El control inhibitorio y las funciones ejecutivas modulan el efecto de refuerzos y respuestas afectivo-cognitivas.',c:'Fue el primer modelo exclusivo del juego por Internet con tres componentes de decisión.',d:'Se limita a tres sistemas: impulsivo, reflexivo e interoceptivo.'},c:'b',x:'La b es correcta. La a corresponde al modelo de Davis; c al modelo de Dong y Potenza; y d al modelo tripartito de Wei.',r:'Brand, M. et al. (2014). Internet addiction: coping styles, expectancies, and treatment implications. Frontiers in Psychology, 5, 1256. https://doi.org/10.3389/fpsyg.2014.01256.'},
'MAYO-DOS-24_COMENTADO_143':{e:'Según la EFSA, ¿qué ingesta diaria de cafeína no plantea problemas de seguridad para la mayoría de adultos sanos no embarazados?',o:{a:'Hasta 100 mg.',b:'Hasta 200 mg en todo el día.',c:'Hasta 400 mg repartidos durante el día.',d:'Hasta 1.000 mg.'},c:'c',x:'La c es correcta: hasta 400 mg diarios no plantea problemas de seguridad en adultos sanos no embarazados. La a es inferior al límite; 200 mg es la referencia para una dosis única y para embarazo/lactancia; y 1.000 mg puede causar toxicidad. «No plantea problemas de seguridad» no equivale a una recomendación de consumir esa cantidad.',r:'EFSA NDA Panel (2015). Scientific Opinion on the safety of caffeine. EFSA Journal, 13(5), 4102. https://doi.org/10.2903/j.efsa.2015.4102.'},
'MAYO-UNO-24_COMENTADO_020':{e:'¿Qué caracteriza al patrón gamma de consumo de alcohol de Jellinek?',o:{a:'Consumo episódico sin pérdida de control ni dependencia.',b:'Pérdida de control, progresión, tolerancia adquirida y dependencia física.',c:'Consumo diario con imposibilidad de abstenerse, pero sin pérdida de control sobre la cantidad.',d:'Consumo por motivos psicológicos sin dependencia física.'},c:'b',x:'La b es correcta y define el patrón gamma. La c corresponde al patrón delta; d al alfa; y a se aproxima al épsilon si se formula como consumo periódico, pero omite su carácter episódico característico.',r:'Jellinek, E. M. (1960). The Disease Concept of Alcoholism. Hillhouse Press.'},
'MAYO-UNO-24_COMENTADO_052':{e:'¿Cuál fue el primer modelo centrado exclusivamente en el trastorno de juego por Internet?',o:{a:'Modelo tripartito de Wei.',b:'Modelo de uso patológico de Davis.',c:'Modelo de Brand.',d:'Modelo cognitivo-conductual de Dong y Potenza.'},c:'d',x:'La d es correcta. Davis y Brand abordan usos problemáticos de Internet más amplios. Wei desarrolló posteriormente un modelo neurocognitivo tripartito específico.',r:'Dong, G. y Potenza, M. N. (2014). Journal of Psychiatric Research, 58, 7–11. https://doi.org/10.1016/j.jpsychires.2014.07.005.'},
'MAYO2_201':{e:'¿Qué combinación es característica de la intoxicación por opioides?',o:{a:'Midriasis, diarrea y piloerección.',b:'Hipervigilancia, hipertensión y verborrea.',c:'Miosis, depresión respiratoria y estreñimiento.',d:'Nistagmo, analgesia y agresividad.'},c:'c',x:'La c es correcta: miosis y depresión respiratoria son signos clásicos, y el estreñimiento deriva de la menor motilidad. La a corresponde a abstinencia; b a estimulantes; y d no constituye la tríada opioide.',r:DSM},
'MAYO2_205':{e:'Respecto a las variables implicadas en el juego de apuestas, señale la afirmación correcta:',o:{a:'Las casi ganancias pueden resultar desagradables y, aun así, aumentar la motivación para continuar jugando.',b:'Los estímulos condicionados son iguales en todos los jugadores y no requieren análisis funcional.',c:'Las máquinas se programan para ofrecer el máximo número posible de premios grandes.',d:'La falacia del jugador consiste en creer que la habilidad personal modifica directamente un resultado aleatorio.'},c:'a',x:'La a es correcta: las near misses activan circuitos de recompensa y motivan continuar aunque se valoren negativamente. La b es falsa por la variabilidad individual. La c es falsa: predominan pequeñas ganancias y casi ganancias, no premios grandes. La d define mejor ilusión de control; la falacia del jugador cree que resultados previos alteran la probabilidad futura.',r:'Clark, L. et al. (2009). Gambling near-misses enhance motivation to gamble. Neuron, 61, 481–490. https://doi.org/10.1016/j.neuron.2008.12.031.'},
'NOVIEMBRE-DOS-24_COMENTADO_068':{e:'¿Qué sustancia presenta una asociación clínica bien establecida con ginecomastia mediante alteraciones hormonales y enfermedad hepática?',o:{a:'Cannabis ocasional.',b:'Cocaína.',c:'Alcohol consumido crónicamente.',d:'Cafeína.'},c:'c',x:'La c es correcta: el consumo crónico de alcohol se asocia con hipogonadismo, alteración de la relación estrógeno/andrógeno y enfermedad hepática. La asociación con cannabis es incierta y no permite una respuesta única; cocaína y cafeína no son causas típicas bien establecidas. Se corrige la clave original b.',r:'Kanakis, G. A. et al. (2019). EAA clinical practice guidelines—gynecomastia evaluation and management. Andrology, 7, 778–793. https://doi.org/10.1111/andr.12636.'},
'OCTUBRE-UNO-24_COMENTADO_061':{e:'Respecto a los diagnósticos inducidos por sustancias del DSM-5-TR, señale la afirmación correcta:',o:{a:'Incluye intoxicación por tabaco.',b:'Incluye trastorno por consumo de cafeína.',c:'No establece un síndrome de abstinencia de alucinógenos.',d:'Incluye abstinencia de inhalantes, pero no intoxicación.'},c:'c',x:'La c es correcta. La a es falsa porque no hay intoxicación por tabaco; b porque no hay trastorno formal por consumo de cafeína; y d porque existe intoxicación por inhalantes, pero no un síndrome de abstinencia formal.',r:DSM},
'OCTUBRE-UNO-24_COMENTADO_064':{e:'¿Qué modelo fue el primero centrado exclusivamente en el trastorno de juego por Internet?',o:{a:'Modelo de Brand.',b:'Modelo cognitivo-conductual de Dong y Potenza.',c:'Modelo de Davis.',d:'Modelo tripartito de Wei.'},c:'b',x:'La b es correcta. Brand y Davis abarcan usos de Internet más amplios; Wei es un desarrollo específico posterior.',r:'Dong, G. y Potenza, M. N. (2014). Journal of Psychiatric Research, 58, 7–11. https://doi.org/10.1016/j.jpsychires.2014.07.005.'},
'OCTUBRE-UNO-24_COMENTADO_068':{e:'¿Para qué intoxicaciones contempla el DSM-5-TR el especificador «con alteraciones de la percepción»?',o:{a:'Alcohol y sedantes.',b:'Cafeína y tabaco.',c:'Cannabis, estimulantes y opioides.',d:'Inhalantes exclusivamente.'},c:'c',x:'La c es correcta según los especificadores DSM-5-TR. Alcohol/sedantes, cafeína/tabaco e inhalantes no comparten conjuntamente ese especificador en la forma propuesta.',r:DSM}
};
for(const [id,p] of Object.entries(U)){const q=adult.find(x=>x.id===id);if(!q)throw Error(id);Object.assign(q,p,{v:'VALIDADA_ORIGINAL'});}
const move='MAYO-UNO-24_COMENTADO_119',i=adult.findIndex(q=>q.id===move);if(i<0)throw Error(move);const q=adult.splice(i,1)[0];Object.assign(q,{s:'Tratamientos Infantiles',t:['Otros problemas infantojuveniles'],e:'¿Qué recurso es más apropiado para un adolescente con consumo bajo o moderado, problemas asociados moderados y necesidad de un entorno estructurado, sin separar al menor de su medio habitual?',o:{a:'Tratamiento ambulatorio estándar.',b:'Tratamiento ambulatorio intensivo.',c:'Centro residencial de baja intensidad.',d:'Tratamiento residencial.'},c:'b',x:'La b es correcta: aporta mayor estructura e intensidad manteniendo al menor en su entorno. La a ofrece menos estructura; c y d implican separación residencial, no necesaria en el caso.',r:'Fonseca-Pedrero, E. (coord.). Manual de tratamientos psicológicos infantojuveniles, apartado de intervención en consumo de sustancias.',v:'VALIDADA_ORIGINAL'});childTreat.push(q);
fs.writeFileSync(P+'clinica_adultos.json',JSON.stringify(adult));fs.writeFileSync(P+'tratamientos_infantiles.json',JSON.stringify(childTreat));
const mp=P+'manifest.json',m=JSON.parse(fs.readFileSync(mp));m.subjects['Clínica Adultos'].count=adult.length;m.subjects['Tratamientos Infantiles'].count=childTreat.length;fs.writeFileSync(mp,JSON.stringify(m,null,2)+'\n');
console.log(JSON.stringify({updated:Object.keys(U).length,moved:move,adult:adult.length,childTreat:childTreat.length}));
