const fs=require('fs'),P='public/banco/',a=JSON.parse(fs.readFileSync(P+'clinica_adultos.json'));
const DSM='American Psychiatric Association (2022). DSM-5-TR. “Substance-Related and Addictive Disorders”. https://doi.org/10.1176/appi.books.9780890425787.';
const BEL='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. I (4.ª ed.). McGraw Hill, capítulo “Trastornos adictivos y relacionados con sustancias”.';
const U={
'PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-DOS-23_033':{e:'¿Para cuál de estas sustancias no existe un trastorno por consumo reconocido como diagnóstico formal en el DSM-5-TR?',o:{a:'Alcohol.',b:'Cafeína.',c:'Alucinógenos.',d:'Tabaco.'},c:'b',x:'La b es correcta: el trastorno por consumo de cafeína permanece como afección propuesta para estudio, no como diagnóstico formal. Alcohol, alucinógenos y tabaco sí cuentan con trastornos por consumo. No debe confundirse con intoxicación o abstinencia de cafeína, que sí son diagnósticos.',r:DSM},
'PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-DOS-23_037':{e:'¿Qué estructura caracteriza al modelo cognitivo-conductual de juego por Internet de Dong y Potenza?',o:{a:'Tres dominios: motivación, control ejecutivo y toma de decisiones.',b:'Solo vínculos top-down y bottom-up.',c:'Sistemas impulsivo, reflexivo e interoceptivo.',d:'Ausencia de implicaciones terapéuticas.'},c:'a',x:'La a es correcta. La b alude a interacciones destacadas por Brand; la c corresponde al modelo tripartito de Wei; y la d es falsa porque Dong y Potenza sí derivan implicaciones para intervención.',r:'Dong, G. y Potenza, M. N. (2014). A cognitive-behavioral model of Internet gaming disorder. Journal of Psychiatric Research, 58, 7–11. https://doi.org/10.1016/j.jpsychires.2014.07.005.'},
'PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-DOS-23_061':{e:'Nistagmo vertical, hipertensión, analgesia o entumecimiento, ataxia, disartria y rigidez muscular orientan a intoxicación por:',o:{a:'Cannabis.',b:'Alcohol.',c:'Fenciclidina.',d:'Inhalantes.'},c:'c',x:'La c es correcta: el nistagmo vertical, la hipertensión, la analgesia y la rigidez son especialmente orientativos de fenciclidina. Alcohol e inhalantes pueden producir incoordinación, pero no este conjunto discriminativo; cannabis tampoco lo explica.',r:DSM},
'PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-DOS-23_079':{e:'¿Con qué grupo de sustancias se asocia especialmente el trastorno perceptivo persistente, antes denominado “flashbacks”?',o:{a:'Alcohol.',b:'Cannabis exclusivamente.',c:'Opioides.',d:'Alucinógenos.'},c:'d',x:'La d es correcta: el DSM-5-TR reconoce el trastorno perceptivo persistente por alucinógenos, con reexperimentación de fenómenos perceptivos tras cesar el efecto agudo. Alcohol y opioides no definen este cuadro; cannabis no es la categoría diagnóstica específica solicitada.',r:DSM},
'PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-UNO-23_036':{e:'¿Cuál de estas manifestaciones puede aparecer en una intoxicación grave por cafeína?',o:{a:'Miosis con depresión respiratoria.',b:'Lagrimeo, rinorrea y piloerección.',c:'Bradicardia con somnolencia como patrón típico.',d:'Taquicardia o arritmia y agitación psicomotora.'},c:'d',x:'La d es correcta: una intoxicación intensa puede producir activación, taquicardia o arritmia, verborrea y agitación. La a describe opioides; la b, abstinencia de opioides; y la c invierte el patrón estimulante. Se elimina la mención impropia a “delirium tremens”, término reservado habitualmente a abstinencia alcohólica grave.',r:DSM},
'PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-UNO-23_040':{e:'Una persona presenta taquicardia, midriasis, hipertensión y alucinaciones sin conservar el juicio de realidad tras consumir cocaína. ¿Cuál es el diagnóstico más ajustado?',o:{a:'Intoxicación por cannabis con alteraciones perceptivas.',b:'Intoxicación por cocaína sin otra especificación.',c:'Trastorno psicótico inducido por estimulantes, con alucinaciones.',d:'Intoxicación por estimulantes con alteraciones perceptivas.'},c:'c',x:'La c es correcta: cuando las alucinaciones se viven como reales y dominan el cuadro, se valora un trastorno psicótico inducido por estimulantes. El especificador de alteraciones perceptivas exige juicio de realidad conservado, por lo que d no encaja; a atribuye otra sustancia y b no recoge adecuadamente el síndrome psicótico.',r:DSM},
'PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-DOS-23_027':{e:'¿Qué complicación potencialmente mortal se asocia a la intoxicación por MDMA (“éxtasis”), especialmente con actividad intensa y ambientes calurosos?',o:{a:'Hipertermia.',b:'Miosis aislada.',c:'Hipotermia persistente.',d:'Síndrome amnésico puro.'},c:'a',x:'La a es correcta: MDMA puede provocar hipertermia grave, deshidratación, alteraciones electrolíticas y fallo orgánico. La miosis no es el signo característico; la hipotermia invierte la alteración; y un síndrome amnésico puro no define esta intoxicación.',r:'World Health Organization (2016). The health and social effects of nonmedical cannabis use; complemented by DSM-5-TR, stimulant-related disorders.'},
'PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-DOS-23_062':{e:'¿Qué describe el denominado “efecto telescópico” en parte de la literatura sobre juego de apuestas?',o:{a:'Una progresión relativamente más rápida desde el inicio del juego hasta los problemas en mujeres que llegan a tratamiento.',b:'Una progresión inevitablemente más rápida en todos los hombres.',c:'Un inicio necesariamente más temprano en mujeres.',d:'Que la mitad exacta de las mujeres solicita tratamiento.'},c:'a',x:'La a es correcta como descripción histórica del efecto telescópico, aunque no aparece igual en todas las muestras. La b y c lo invierten o lo convierten en una regla universal; la d aporta una proporción no definitoria. La formulación evita presentar diferencias grupales como deterministas.',r:BEL},
'PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-UNO-23_079':{e:'¿En qué abstinencia son frecuentes irritabilidad, nerviosismo, disminución del apetito y dificultades para dormir, incluidos sueños inquietantes?',o:{a:'Cannabis.',b:'Cafeína.',c:'Opioides.',d:'Alucinógenos.'},c:'a',x:'La a es correcta: esos síntomas integran el síndrome de abstinencia de cannabis. La cafeína produce sobre todo cefalea, fatiga y somnolencia; los opioides producen un cuadro autonómico y gastrointestinal; los alucinógenos no tienen abstinencia formal DSM-5-TR.',r:DSM},
'PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-UNO-23_093':{e:'¿Qué característica genética puede reducir el riesgo de trastorno por consumo de alcohol al producir una reacción aversiva inmediata?',o:{a:'Metabolización ultrarrápida del acetaldehído.',b:'Ausencia de respuesta fisiológica al alcohol.',c:'Mayor tolerancia innata sin síntomas.',d:'Enrojecimiento agudo por acumulación de acetaldehído.'},c:'d',x:'La d es correcta: variantes que reducen la actividad de ALDH2 favorecen acumulación de acetaldehído, rubor y malestar, lo que suele proteger frente al consumo intenso. La a reduciría acetaldehído; b elimina la reacción protectora; y c describe mayor tolerancia, no el fenotipo de bajo riesgo citado.',r:DSM},
'PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-UNO-23_109':{e:'Según el modelo neurocognitivo tripartito de Wei, ¿qué patrón caracteriza el trastorno de juego por Internet?',o:{a:'Sistema impulsivo hiperactivo, sistema reflexivo hipoactivo y modulación interoceptiva disfuncional.',b:'Solo cogniciones distales y proximales, sin sistemas neurales.',c:'Control ejecutivo hiperactivo que inhibe toda señal de recompensa.',d:'Tres dominios denominados motivación, ejecución y decisión, sin ínsula.'},c:'a',x:'La a es correcta. La b corresponde de forma simplificada a Davis; la c invierte el déficit de control; y la d aproxima el modelo de Dong y Potenza, no el tripartito de Wei.',r:'Wei, L. et al. (2017). A tripartite neurocognitive model of Internet gaming disorder. Frontiers in Psychiatry, 8, 285. https://doi.org/10.3389/fpsyt.2017.00285.'},
'SEPTIEMBRE-DOS-24_COMENTADO_115':{e:'¿A qué clase farmacológica pertenece principalmente el THC del cannabis?',o:{a:'Opioide.',b:'Estimulante anfetamínico.',c:'Sedante-hipnótico benzodiacepínico.',d:'Cannabinoide psicoactivo con acción sobre receptores CB1.'},c:'d',x:'La d es correcta: el THC es un cannabinoide psicoactivo que actúa principalmente sobre receptores CB1. No es opioide, anfetamina ni benzodiacepina. Se sustituye una pregunta epidemiológica cambiante sobre la droga ilegal más consumida.',r:DSM},
'SEPTIEMBRE-DOS-24_COMENTADO_116':{e:'En el trastorno por juego de apuestas, volver a jugar para recuperar pérdidas anteriores se denomina:',o:{a:'Gran premio inicial (“big win”).',b:'Caza de pérdidas (“chasing”).',c:'Casi ganancia (“near miss”).',d:'Craving.'},c:'b',x:'La b es correcta: chasing es regresar para “desquitarse” o recuperar dinero perdido y constituye criterio diagnóstico. Big win es una gran ganancia temprana; near miss es un resultado cercano a ganar; craving es deseo intenso, no la conducta específica de perseguir pérdidas.',r:DSM},
'SEPTIEMBRE-UNO-24_COMENTADO_165':{e:'Según la EFSA, ¿qué cantidad de cafeína en una dosis única no plantea, en general, problemas de seguridad para adultos sanos?',o:{a:'Hasta 50 mg.',b:'Hasta 200 mg.',c:'Hasta 600 mg.',d:'Hasta 1.000 mg.'},c:'b',x:'La b es correcta: hasta 200 mg en una toma no plantea problemas de seguridad para la mayoría de adultos sanos. La a es inferior pero no representa el límite evaluado; 600 y 1.000 mg aumentan la probabilidad de efectos adversos. Se reemplaza una lista causal inespecífica.',r:'EFSA NDA Panel (2015). Scientific Opinion on the safety of caffeine. EFSA Journal, 13(5), 4102. https://doi.org/10.2903/j.efsa.2015.4102.'},
'SEPTIEMBRE-UNO-24_COMENTADO_169':{e:'La tolerancia producida por cambios en absorción, distribución, metabolismo o eliminación se denomina:',o:{a:'Farmacocinética o metabólica.',b:'Farmacodinámica.',c:'Conductual.',d:'Inversa.'},c:'a',x:'La a es correcta: modifica la cantidad o duración de sustancia disponible en el organismo. La farmacodinámica implica adaptación de receptores o sistemas diana; la conductual depende de aprendizaje; y la inversa o sensibilización aumenta la respuesta.',r:BEL},
'Simu 13 comentado_065':{e:'En una clasificación funcional clásica por su efecto predominante sobre el sistema nervioso central, los derivados del cannabis suelen incluirse entre:',o:{a:'Depresores puros.',b:'Estimulantes puros.',c:'Perturbadores o psicodislépticos.',d:'Opioides.'},c:'c',x:'La c es correcta en la clasificación tradicional porque pueden alterar percepción, cognición y experiencia subjetiva. No son depresores o estimulantes puros, aunque produzcan efectos mixtos, y no pertenecen a los opioides.',r:BEL},
'Simu 13 comentado_066':{e:'¿Qué describe la dependencia cruzada?',o:{a:'La capacidad general de cualquier sustancia para causar adicción.',b:'La necesidad de aumentar dosis de la misma sustancia.',c:'La adaptación neuronal tras exposición repetida.',d:'La capacidad de una sustancia para suprimir la abstinencia producida por otra de acción semejante.'},c:'d',x:'La d es correcta; un ejemplo es la metadona suprimiendo abstinencia de heroína. La a define potencial adictivo; la b corresponde a tolerancia; y la c describe neuroadaptación sin exigir sustitución entre sustancias.',r:BEL},
'Simu 14 comentado _065':{e:'¿Qué correspondencia entre sustancia y efecto predominante sobre el sistema nervioso central es correcta?',o:{a:'Opiáceos—perturbadores.',b:'Cocaína—depresora.',c:'Xantinas—estimulantes.',d:'LSD—estimulante.'},c:'c',x:'La c es correcta: cafeína y otras xantinas son estimulantes. Los opiáceos son depresores; la cocaína es estimulante; y LSD se clasifica como alucinógeno o perturbador.',r:BEL},
'Simu 15 comentado_049':{e:'¿Cuál NO es un diagnóstico relacionado con el alcohol reconocido en el DSM-5-TR?',o:{a:'Dependencia del alcohol como categoría separada.',b:'Trastorno por consumo de alcohol.',c:'Intoxicación por alcohol.',d:'Disfunción sexual inducida por alcohol.'},c:'a',x:'La a es correcta: abuso y dependencia se integraron en el trastorno por consumo de alcohol. Las opciones b y c son diagnósticos del capítulo de sustancias; la d puede diagnosticarse como trastorno inducido por sustancias/medicamentos cuando cumple sus criterios.',r:DSM},
'Simu 15 comentado_067':{e:'¿Qué número de criterios corresponde a gravedad leve de un trastorno por consumo de sustancias en DSM-5-TR?',o:{a:'Cero o uno.',b:'Dos o tres.',c:'Cuatro o cinco.',d:'Seis o más.'},c:'b',x:'La b es correcta. Cero o uno no alcanza el diagnóstico; cuatro o cinco indican gravedad moderada; seis o más, grave.',r:DSM},
'Simu 15 comentado_084':{e:'¿A qué clase pertenece la cocaína?',o:{a:'Depresores del sistema nervioso central.',b:'Alucinógenos clásicos.',c:'Estimulantes.',d:'Opioides.'},c:'c',x:'La c es correcta: la cocaína bloquea la recaptación de monoaminas y se clasifica como estimulante. No es un depresor, un alucinógeno clásico ni un opioide. Se elimina la comparación imprecisa entre dependencia psicológica y física.',r:DSM},
'Simu 32 comentado hardcore 2_059':{e:'¿Qué afirmación sobre la cafeína es correcta según el DSM-5-TR?',o:{a:'El trastorno por consumo de cafeína es un diagnóstico formal del capítulo principal.',b:'La intoxicación y la abstinencia de cafeína sí cuentan con criterios diagnósticos.',c:'El consumo habitual impide desarrollar abstinencia.',d:'No puede producir deterioro clínicamente significativo.'},c:'b',x:'La b es correcta. El trastorno por consumo de cafeína figura como condición para estudio, no diagnóstico formal; el consumo habitual puede generar abstinencia; y tanto intoxicación como retirada pueden causar malestar o deterioro.',r:DSM},
'Simu 6 comentado__066':{e:'¿Qué signo puede aparecer durante la intoxicación por alcohol?',o:{a:'Marcha inestable.',b:'Lagrimeo y rinorrea.',c:'Temblor de manos por retirada.',d:'Insomnio como único signo.'},c:'a',x:'La a es correcta: la incoordinación y la marcha inestable figuran entre los signos de intoxicación. Lagrimeo y rinorrea orientan a abstinencia opioide; el temblor de manos a abstinencia alcohólica; y el insomnio aislado no define intoxicación.',r:DSM},
'Simu 7 comentado _086':{e:'¿Qué hallazgo físico es compatible con una intoxicación reciente por cannabis?',o:{a:'Miosis puntiforme y depresión respiratoria.',b:'Nistagmo vertical.',c:'Inyección conjuntival y aumento del apetito.',d:'Rigidez muscular con analgesia.'},c:'c',x:'La c es correcta: inyección conjuntival y aumento del apetito son signos posibles. La a corresponde a opioides; b y d orientan especialmente a fenciclidina. Se retira el porcentaje histórico de dependencia.',r:DSM},
'Simu 7 comentado _105':{e:'¿Cómo cambia habitualmente la función reforzante de una sustancia al desarrollarse dependencia?',o:{a:'Pasa necesariamente de negativa a positiva.',b:'Deja de reforzar cualquier conducta.',c:'Al refuerzo positivo inicial puede añadirse refuerzo negativo por alivio de abstinencia o malestar.',d:'Solo opera mediante castigo positivo.'},c:'c',x:'La c es correcta: al principio puede predominar la búsqueda de efectos agradables y, con dependencia, el consumo también se mantiene por aliviar malestar. La a invierte la secuencia; la b niega el mantenimiento; y la d confunde reforzamiento con castigo. Se elimina una atribución autoral dudosa.',r:BEL},
'SM_ABRIL_1_SOL_1_054':{e:'¿Cuál de estos signos forma parte de la intoxicación por alcohol y no del síndrome de abstinencia?',o:{a:'Insomnio.',b:'Ansiedad.',c:'Hiperactividad autonómica.',d:'Alteración de atención o memoria durante la intoxicación.'},c:'d',x:'La d es correcta: la intoxicación puede producir deterioro de atención o memoria junto con habla pastosa, incoordinación o marcha inestable. Insomnio, ansiedad e hiperactividad autonómica son característicos de abstinencia alcohólica.',r:DSM}
};
const ids=require('../tmp/addictions_next26_ids.json');if(ids.length!==26)throw Error('lote');for(const id of ids){const q=a.find(z=>z.id===id),p=U[id];if(!q||!p)throw Error(id);Object.assign(q,p,{v:'VALIDADA_ORIGINAL'});}fs.writeFileSync(P+'clinica_adultos.json',JSON.stringify(a));console.log(JSON.stringify({updated:ids.length}));
