const fs=require('fs'),P='public/banco/',cp=P+'clinica_adultos.json',pp=P+'psicopatologia.json',a=JSON.parse(fs.readFileSync(cp)),psy=JSON.parse(fs.readFileSync(pp));
const D='American Psychiatric Association (2022). DSM-5-TR. Capítulo «Trastornos disociativos». Editorial Médica Panamericana.';
const B='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. II (4.ª ed.). McGraw Hill, cap. 8, pp. 295–322.';
const H='Van der Hart, O., Nijenhuis, E. R. S. y Steele, K. (2006). The Haunted Self. Norton; '+B;
const X={
'ABRIL-UNO-24_COMENTADO_160':['c','La c es correcta: Tyrer relaciona la conversión con disociación de movimientos o sensaciones. La a es falsa porque la identidad disociativa afecta a la personalidad; la b atribuye la amnesia a percepción en vez de cognición; y la d sitúa erróneamente fuga y trance en una categoría residual.',B],
'JULIO1_104':['b','La b es correcta: esa descripción corresponde a reacciones disociativas agudas ante sucesos estresantes, ejemplo de otro trastorno disociativo especificado. La a se refiere a cuadros crónicos; la c exige criterios de TEPT; y la d no reúne la definición del trance CIE-11.',D],
'JUNIO-UNO-24_COMENTADO_049':['d','La d es correcta: la amnesia selectiva impide recordar parte de un acontecimiento durante un periodo delimitado. La localizada afecta todo un periodo; la continua, lo ocurrido desde un punto hasta el presente; y la sistematizada, una categoría específica de información.',B],
'JUNIO-UNO-24_COMENTADO_077':['d','La d es la incorrecta: en el TID la amnesia no se limita a traumas y puede afectar acontecimientos cotidianos. La a describe lagunas remotas; la b, lapsos recientes; y la c, evidencias de acciones que la persona no recuerda, las tres formas recogidas por el DSM-5-TR.',D],
'MAYO-DOS-24_COMENTADO_157':['c','La c es correcta: también se han descrito procedimientos médicos infantiles, guerra, explotación infantil y terrorismo como antecedentes traumáticos. La a sustituye abuso sexual por psicológico; la b reduce indebidamente una frecuencia muy elevada al 20 %; y la d invierte factores asociados a peor pronóstico.',D],
'MAYO-UNO-24_COMENTADO_038':['d','La d es correcta: en el TID parcial el estado no dominante no asume recurrentemente el control, aunque puede hacerlo de forma ocasional y limitada. La a describe de modo incompleto la intrusión; la b niega su asociación frecuente con trauma; y la c afirma amnesia habitual cuando puede estar ausente.', 'World Health Organization (2024). ICD-11 CDDR, «Partial dissociative identity disorder» (6B65).'],
'MAYO-UNO-24_COMENTADO_044':['b','La b es correcta: la rumiación o preocupación obsesiva es una característica afectivo-cognitiva frecuente. La a alude a comorbilidad postraumática; la c es una manifestación conductual; y la d —macropsia— es una distorsión perceptiva, no afectiva. Se corrige la clave anterior d.',B],
'PERSEV_JUL25_D2_039':['d','La d es correcta: Tyrer relaciona despersonalización y desrealización con disociación de la percepción. La a confunde personalidad con amnesia; la b atribuye la identidad disociativa a conductas complejas; y la c intercambia función cognitiva con fuga y trance.',B],
'PERSEVER___SIMULACRO_COMENTADO_ABRIL-DOS-23_139':['c','La c es correcta: la teoría neodisociativa de Hilgard postula estructuras cognitivas jerarquizadas de control. La a es un modelo traumático multifactorial; la b, Kihlstrom, se apoya en memoria y redes asociativas; y la d clasifica niveles de fragmentación traumática. Se corrige la clave anterior b.', 'Hilgard, E. R. (1977). Divided Consciousness. Wiley; '+B],
'PERSEVER___SIMULACRO_COMENTADO_ABRIL-DOS-23_176':['a','La a es correcta: la aparición de síntomas postraumáticos puede incrementar formas circunscritas de amnesia. La b es falsa porque la generalizada suele comenzar bruscamente; la c es falsa porque lo olvidado puede abarcar desde minutos hasta décadas; y la d describe mejor dificultades crónicas del TID.',D],
'PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-DOS-23_063':['d','La d es correcta: Farina y colaboradores sitúan despersonalización y desrealización entre fenómenos de desintegración. Alexitimia, identidad múltiple y amnesia se vinculan en su propuesta con otros procesos disociativos, por lo que a, b y c no responden.', 'Farina, B. et al. (2019). Development of a theory of traumatization and dissociation. Journal of Trauma & Dissociation; '+B],
'PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-UNO-23_058':['b','La b es correcta: las intrusiones repentinas en conciencia o conducta son fenómenos disociativos positivos por adición de experiencia. La a mezcla fragmentación y desconexión; la c describe síntomas negativos por pérdida de acceso o control; y la d enumera dominios del TEPT.',D],
'PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-UNO-23_059':['a','La a es correcta: el TID parcial se asocia con frecuencia a una historia traumática. La b describe erróneamente el TID total; la c atribuye una duración amnésica obligatoria; y la d afirma que la amnesia es habitual, cuando puede no aparecer.', 'World Health Organization (2024). ICD-11 CDDR, 6B65.'],
'PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-UNO-23_074':['b','La b es correcta: la disociación secundaria implica percibir el acontecimiento sin experimentar plenamente su impacto emocional. La primaria es fragmentación del procesamiento; la terciaria implica identidades separadas; y no existe un cuarto nivel en este modelo.',H],
'PERSEVER___SIMULACRO_COMENTADO_ENERO-UNO-23_072':['c','La c es correcta: una autoimagen negativa, culpa y baja autoestima pueden mantener síntomas disociativos. La a invierte el riesgo asociado a menor edad; la b no es un factor protector ni está formulada como variable nuclear; y la d no forma parte del modelo.',B],
'PERSEVER___SIMULACRO_COMENTADO_JULIO-DOS-23_026':['a','La a es correcta: la teoría estructural separa el sistema defensivo frente a amenaza —parte emocional— del sistema de vida cotidiana —parte aparentemente normal—. La b es una división genérica; la c enumera BASK; y la d no corresponde al modelo.',H],
'PERSEVER___SIMULACRO_COMENTADO_JULIO-UNO-23_048':['c','La c es correcta: la disociación terciaria supone el desarrollo de identidades separadas. La primaria consiste en fragmentación del trauma; la secundaria, en separación del impacto emocional; y no existe disociación cuaternaria en este modelo.',H],
'PERSEVER___SIMULACRO_COMENTADO_JULIO-UNO-23_066':['c','La c es correcta: Kihlstrom propone una desconexión entre memorias autobiográficas y representación mental del yo. La a contradice su énfasis en memoria; la b sustituye red asociativa por jerarquía; y la d es falsa porque la memoria semántica suele preservarse.', 'Kihlstrom, J. F. (2005). Dissociative disorders. Annual Review of Clinical Psychology, 1, 227–253. https://doi.org/10.1146/annurev.clinpsy.1.102803.143925.']};
const clean=s=>String(s||'').replace(/[�]/g,'').replace(/^\s*(?:\d+\s+){1,6}/,'').replace(/([A-Za-zÁÉÍÓÚáéíóúñ])-\s+([A-Za-zÁÉÍÓÚáéíóúñ])/g,'$1$2').replace(/\s+/g,' ').trim();
const cut=s=>clean(s).split(/\s+(?=(?:La opci[oó]n|Las alteraciones|Reed \(|Tyrer \(|Van der Hart|Actualmente,|En el libro|Seg[uú]n la CIE|Belloch|Este año|Farina et al\.|Se enfatiza|En la [uú]ltima convocatoria))/i)[0];
for(const [id,[c,x,r]] of Object.entries(X)){const q=a.find(z=>z.id===id);if(!q)throw Error(id);q.e=clean(q.e).replace(/^(?:Marque|Señale|Indique)\s+/i,m=>m);q.o=Object.fromEntries(Object.entries(q.o).map(([k,v])=>[k,cut(v)]));Object.assign(q,{c,x,r,v:'VALIDADA_ORIGINAL'});}
function move(id,e,o,c,x,r){const i=a.findIndex(q=>q.id===id);if(i<0)throw Error(id);const q=a.splice(i,1)[0];Object.assign(q,{s:'Psicopatología',t:['Psicopatología de la conciencia'],e,o,c,x,r,v:'VALIDADA_ORIGINAL'});psy.push(q)}
move('JULIO1_076','En la clasificación de Reed de las alteraciones de la conciencia del yo, la escisión de la unidad del yo corresponde a:',{a:'Confusión de los límites del yo.',b:'Pérdida de atribución personal.',c:'Deterioro de la unidad del yo.',d:'Pérdida de la experiencia de realidad.'},'c','La c es correcta: la escisión describe una fractura de la vivencia unitaria del yo. La a afecta la diferenciación yo-entorno; la b, el reconocimiento de pensamientos o actos como propios; y la d incluye despersonalización y desrealización.','Reed, G. (1988). The Psychology of Anomalous Experience. Prometheus; '+B);
move('PERSEV_JUL25_D2_043','Una persona afirma que está «flotando y existiendo dentro de todas las cosas». Según Reed, esta experiencia corresponde a:',{a:'Confusión de los límites del yo.',b:'Pérdida de atribución personal.',c:'Deterioro de la unidad del yo.',d:'Pérdida de la experiencia de realidad.'},'a','La a es correcta: la persona deja de vivirse claramente diferenciada del entorno. La b afecta la autoría de actos o pensamientos; la c implica escisión interna del yo; y la d supone extrañeza o irrealidad manteniendo diferenciación.','Reed, G. (1988). The Psychology of Anomalous Experience. Prometheus; '+B);
fs.writeFileSync(cp,JSON.stringify(a));fs.writeFileSync(pp,JSON.stringify(psy));const m=JSON.parse(fs.readFileSync(P+'manifest.json'));for(const v of Object.values(m.subjects))v.count=JSON.parse(fs.readFileSync(P+v.slug+'.json')).length;m.total=Object.values(m.subjects).reduce((n,v)=>n+v.count,0);fs.writeFileSync(P+'manifest.json',JSON.stringify(m,null,2)+'\n');console.log({updated:Object.keys(X).length,moved:2,total:m.total});
