const fs=require('fs');
const ap='public/banco/tratamientos_adultos.json',cp='public/banco/tratamientos_infantiles.json';
const a=JSON.parse(fs.readFileSync(ap,'utf8')),child=JSON.parse(fs.readFileSync(cp,'utf8')),m=new Map(a.map(q=>[q.id,q]));
const F='Fonseca Pedrero, E. (coord.) (2021). Manual de tratamientos psicológicos: Adultos. Pirámide.';
const FI='Fonseca Pedrero, E. (coord.) (2021). Manual de tratamientos psicológicos: Infancia y adolescencia. Pirámide.';
const B='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. II (4.ª ed.). McGraw Hill.';
function set(id,z){const q=m.get(id);if(!q)throw Error(id);Object.assign(q,z,{v:'VALIDADA_ORIGINAL'});}
function move(id,target,topic){const i=a.findIndex(q=>q.id===id);if(i<0)throw Error('move '+id);const[q]=a.splice(i,1);q.t=[topic];q.v='REVISAR';if(!target.some(x=>x.id===id))target.push(q);}
for(const [id,topic] of [
 ['SIM_PERS_AGO25_117','Técnicas psicológicas generales'],
 ['Simu 11 comentado_195','Tratamiento de los trastornos de personalidad'],
 ['Simu 12 comentado_077','Tratamiento de los trastornos de ansiedad'],
 ['Simu 14 comentado _099','Tratamiento de los trastornos alimentarios'],
 ['Simu 15 comentado_176','Tratamiento del TOC y relacionados'],
 ['Simu 15 comentado_204','Técnicas psicológicas generales'],
 ['Simu 16 comentado_001','Técnicas psicológicas generales'],
 ['Simu 16 comentado_138','Tratamiento de las adicciones'],
 ['Simu 16 comentado_203','Tratamientos transdiagnósticos'],
 ['Simu 6 comentado__137','Técnicas psicológicas generales']
])move(id,a,topic);
for(const [id,topic] of [['Simu 6 comentado__140','Introducción a los tratamientos infantojuveniles'],['Simu 6 comentado__166','Trauma y malos tratos infantojuveniles']])move(id,child,topic);

set('SIM_ABR2_126',{e:'¿Cuál es una meta central del CBASP para la depresión crónica?',o:{a:'Ayudar a reconocer las consecuencias interpersonales de la propia conducta y resolver problemas de relación.',b:'Eliminar cualquier emoción negativa.',c:'Interpretar exclusivamente contenidos inconscientes.',d:'Sustituir la psicoterapia por medicación.'},c:'a',x:'El CBASP utiliza especialmente el análisis situacional para que la persona perciba la relación entre su conducta y sus consecuencias interpersonales y aprenda respuestas más eficaces.',r:'McCullough, J. P. (2000). Treatment for Chronic Depression: Cognitive Behavioral Analysis System of Psychotherapy. Guilford Press.'});
set('SIM_ABR2_134',{e:'¿Cuáles son los cuatro focos clásicos de la terapia interpersonal para la depresión?',o:{a:'Duelo, disputas de rol, transiciones de rol y déficits interpersonales.',b:'Exposición, prevención de respuesta, relajación y reestructuración.',c:'Trabajo, familia, pareja y ocio.',d:'Transferencia, contratransferencia, sueños y resistencia.'},c:'a',x:'La TIP organiza el tratamiento alrededor de cuatro áreas: duelo, disputas, transiciones y déficits interpersonales, priorizando la más vinculada al episodio actual.',r:F});
set('SIM_ABR25_128',{e:'¿Qué elemento ocupa un lugar central en el modelo cognitivo de la depresión de Beck?',o:{a:'La tríada cognitiva negativa sobre uno mismo, el mundo y el futuro.',b:'Un déficit dopaminérgico como explicación psicológica suficiente.',c:'La existencia obligatoria de trauma infantil.',d:'La indefensión aprendida de Seligman como componente propio del modelo.'},c:'a',x:'La tríada cognitiva reúne las valoraciones negativas del yo, el mundo o experiencias y el futuro. La indefensión aprendida pertenece a otro modelo explicativo.',r:'Beck, A. T. et al. (1979). Cognitive Therapy of Depression. Guilford Press.'});
for(const id of ['SIM_ABR25_142','SIM_ABR25_206'])set(id,{e:'¿Para qué cuadro fue desarrollado específicamente el CBASP de McCullough?',o:{a:'Depresión crónica o persistente.',b:'Trastorno límite de la personalidad.',c:'Esquizofrenia.',d:'TDAH.'},c:'a',x:'El CBASP es una psicoterapia concebida específicamente para formas crónicas de depresión, con especial atención al aprendizaje interpersonal.',r:'McCullough, J. P. (2003). Treatment for chronic depression using CBASP. Journal of Clinical Psychology, 59, 833-846.'});
set('SIM_ABR25_150',{e:'¿Qué áreas problemáticas aborda la terapia interpersonal de Klerman y Weissman para la depresión?',o:{a:'Duelo, disputas de rol, transiciones de rol y déficits interpersonales.',b:'Interpretación del inconsciente y de los sueños.',c:'Modificación directa de rasgos básicos de personalidad.',d:'Exposición a sensaciones corporales y prevención de respuesta.'},c:'a',x:'La TIP selecciona uno o, excepcionalmente, más focos entre duelo, disputas, transiciones y déficits interpersonales.',r:F});
set('SIM_ABR25_207',{e:'¿Cuál de los siguientes contenidos NO constituye un foco específico de la terapia interpersonal para la depresión?',o:{a:'Déficits interpersonales.',b:'Duelo.',c:'Reestructuración de la organización básica de la personalidad.',d:'Transiciones de rol.'},c:'c',x:'La TIP es focal y no pretende reorganizar la estructura básica de personalidad. Duelo, transiciones y déficits son tres de sus cuatro áreas clásicas.',r:F});
set('SIM_PERS_AGO25_002',{e:'En las primeras fases de la terapia cognitiva de Beck para la depresión, ¿qué objetivo tienen principalmente las técnicas conductuales?',o:{a:'Modificar de inmediato los esquemas nucleares más profundos.',b:'Aumentar la actividad y contrarrestar pasividad, evitación y aislamiento.',c:'Limitarse a debatir distorsiones cognitivas abstractas.',d:'Realizar exclusivamente un inventario interpersonal.'},c:'b',x:'Al inicio, la programación de actividades, las tareas graduadas y otras estrategias conductuales ayudan a recuperar funcionamiento y experiencias de dominio o agrado, facilitando después el trabajo cognitivo.',r:'Beck, A. T. et al. (1979). Cognitive Therapy of Depression. Guilford Press.'});
set('SIM_PERS_AGO25_017',{e:'¿Cuál NO es una de las cuatro áreas problemáticas clásicas de la terapia interpersonal para la depresión?',o:{a:'Duelo.',b:'Disputas interpersonales de rol.',c:'Transiciones de rol.',d:'Déficit general de asertividad considerado como área independiente.'},c:'d',x:'El cuarto foco es déficits interpersonales, concepto más amplio que un déficit general de asertividad. Los otros tres sí son áreas propias de la TIP.',r:F});
set('SIM_PERS_AGO25_051',{e:'En activación conductual para la depresión, ¿por qué se mantienen con frecuencia la evitación y la inactividad?',o:{a:'Porque reciben siempre refuerzo positivo social.',b:'Porque producen alivio inmediato de malestar mediante refuerzo negativo.',c:'Porque constituyen necesariamente un castigo positivo.',d:'Exclusivamente por una creencia consciente de indefensión.'},c:'b',x:'Evitar puede reducir malestar a corto plazo y quedar reforzado negativamente, pero a largo plazo restringe el contacto con consecuencias valiosas y mantiene la depresión.',r:'Martell, C. R., Dimidjian, S. y Herman-Dunn, R. (2010). Behavioral Activation for Depression. Guilford Press.'});
set('SIM_PERS_AGO25_077',{e:'¿Para qué trastorno se desarrolló específicamente el Sistema de Psicoterapia de Análisis Cognitivo-Conductual de McCullough?',o:{a:'Depresión crónica, incluida la antigua distimia.',b:'Trastorno bipolar I.',c:'Depresión psicótica aguda como monoterapia.',d:'Trastorno disfórico premenstrual.'},c:'a',x:'El CBASP se diseñó específicamente para la depresión crónica. No es una intervención específica para bipolaridad, psicosis afectiva ni trastorno disfórico premenstrual.',r:'McCullough, J. P. (2003). Journal of Clinical Psychology, 59, 833-846.'});
set('SIM_PERS_AGO25_122',{e:'¿Qué ejemplo representa mejor la abstracción selectiva o filtro mental en la depresión?',o:{a:'«Si no obtengo la máxima nota, soy un fracaso total».',b:'«Mi jefe no me saludó; sé que piensa que soy incompetente».',c:'«Cometí un error; toda la presentación fue desastrosa», ignorando los numerosos aspectos positivos.',d:'«Me siento inútil, por tanto soy inútil».'},c:'c',x:'La abstracción selectiva consiste en atender a un detalle negativo aislado y valorar toda la experiencia a partir de él. La a refleja pensamiento dicotómico, la b lectura de mente y la d razonamiento emocional.',r:'Beck, A. T. et al. (1979). Cognitive Therapy of Depression. Guilford Press.'});
set('Simu 11 comentado_171',{e:'Según NICE, ¿cuál figura entre las opciones iniciales para un nuevo episodio de depresión más grave en adultos?',o:{a:'Farmacoterapia como única alternativa válida.',b:'Apoyo inespecífico sin intervención estructurada.',c:'Psicoterapia psicodinámica prolongada obligatoria.',d:'Combinación de TCC individual y un antidepresivo, decidida junto con el paciente.'},c:'d',x:'NICE incluye la combinación de TCC individual y antidepresivo entre las opciones iniciales para depresión más grave. No existe un tratamiento universal: deben considerarse necesidades, preferencias, riesgos y tratamientos previos.',r:'National Institute for Health and Care Excellence (2022). Depression in adults: treatment and management (NG222).'});
set('Simu 12 comentado_172',{e:'¿Cuál de las siguientes intervenciones NO fue diseñada para el tratamiento del trastorno bipolar?',o:{a:'Terapia interpersonal y de ritmos sociales.',b:'Psicoeducación para el trastorno bipolar.',c:'Terapia integradora de Newman.',d:'Terapia centrada en la familia de Miklowitz.'},c:'c',x:'La terapia integradora de Newman se diseñó para el trastorno de ansiedad generalizada. IPSRT, psicoeducación y terapia familiar son intervenciones reconocidas para bipolaridad.',r:F});
set('Simu 12 comentado_173',{e:'¿Qué psicoterapia para la depresión se desarrolló inicialmente en investigación psiquiátrica vinculada al tratamiento de mantenimiento con medicación?',o:{a:'Terapia cognitiva de Beck.',b:'Activación conductual.',c:'Terapia interpersonal de Klerman y Weissman.',d:'Terapia de solución de problemas.'},c:'c',x:'La TIP surgió en estudios sobre tratamiento agudo y de mantenimiento de la depresión que comparaban medicación y psicoterapia, antes de consolidarse como tratamiento independiente y adaptable.',r:'Weissman, M. M., Markowitz, J. C. y Klerman, G. L. (2018). The Guide to Interpersonal Psychotherapy. Oxford University Press.'});
set('Simu 13 comentado_122',{e:'Además de la terapia interpersonal de Klerman, ¿en qué planteamiento se fundamenta la terapia interpersonal y de ritmos sociales?',o:{a:'Teoría de la regulación emocional de Gross.',b:'Teoría del apego como explicación exclusiva.',c:'Terapia dialéctica conductual.',d:'Hipótesis de los zeitgebers sociales: las alteraciones de rutinas pueden desregular ritmos biológicos y precipitar episodios.'},c:'d',x:'La IPSRT integra TIP con la hipótesis de los zeitgebers sociales, según la cual acontecimientos que alteran rutinas y ritmos sociales pueden desestabilizar los ritmos circadianos en personas vulnerables.',r:'Frank, E., Swartz, H. A. y Kupfer, D. J. (2000). Interpersonal and social rhythm therapy: managing the chaos of bipolar disorder. Biological Psychiatry, 48, 593-604.'});
set('Simu 13 comentado_123',{e:'¿En cuál de las siguientes situaciones resulta especialmente útil el litio?',o:{a:'Manía disfórica o mixta como predictor específico de respuesta óptima.',b:'Trastorno bipolar con riesgo o antecedentes de conducta suicida.',c:'Embarazo, por carecer de riesgos fetales.',d:'Como tratamiento único de la depresión psicótica.'},c:'b',x:'El litio posee evidencia relevante en prevención del suicidio y es un tratamiento fundamental de mantenimiento bipolar. Las características mixtas predicen peor respuesta relativa; en embarazo exige una valoración cuidadosa de riesgos y beneficios.',r:'National Institute for Health and Care Excellence (2023). Bipolar disorder: assessment and management (CG185); '+B});
set('Simu 14 comentado _096',{e:'En el trastorno bipolar I, ¿en qué situación NO se recomienda utilizar un antidepresivo en monoterapia?',o:{a:'Nunca, porque los antidepresivos están prohibidos en toda circunstancia.',b:'En la prevención de recaídas depresivas sin acompañarlo de un estabilizador o antipsicótico adecuado.',c:'Cuando se combina prudentemente con un tratamiento antimaníaco indicado.',d:'Cuando se revisan antecedentes de viraje y ciclación antes de prescribirlo.'},c:'b',x:'En bipolar I se evita la monoterapia antidepresiva por el riesgo de viraje o desestabilización. Si se emplea, debe seleccionarse cuidadosamente y acompañarse de tratamiento antimaníaco; no está universalmente prohibido en cualquier combinación.',r:'Yatham, L. N. et al. (2018). CANMAT and ISBD 2018 guidelines. Bipolar Disorders, 20, 97-170.'});
set('Simu 15 comentado_163',{e:'¿Cuál NO es una meta de la terapia interpersonal y de ritmos sociales para el trastorno bipolar?',o:{a:'Eliminar sistemáticamente la medicación una vez estabilizado el estado de ánimo.',b:'Reducir la intensidad de estresores interpersonales.',c:'Aprender rutinas que ayuden a prevenir nuevos episodios.',d:'Mantener ciclos diarios y de sueño-vigilia regulares.'},c:'a',x:'La IPSRT se plantea habitualmente como complemento de la farmacoterapia, no como procedimiento para retirarla de forma sistemática. Las demás opciones describen sus metas.',r:'Frank, E. (2005). Treating Bipolar Disorder. Guilford Press.'});
set('Simu 15 comentado_178',{e:'¿Cuál de las siguientes psicoterapias cuenta con eficacia establecida para los trastornos depresivos?',o:{a:'Terapia psicodinámica no estructurada como única intervención respaldada.',b:'Terapia sistémica genérica para cualquier presentación.',c:'Terapia interpersonal.',d:'Una supuesta «terapia del sueño» indiferenciada.'},c:'c',x:'La terapia interpersonal es un tratamiento estructurado y respaldado para la depresión. La clave original «terapia sistémica» era incorrecta y las restantes alternativas no describen una intervención específica con el mismo respaldo general.',r:'National Institute for Health and Care Excellence (2022). Depression in adults: treatment and management (NG222); '+F});

fs.writeFileSync(ap,JSON.stringify(a));fs.writeFileSync(cp,JSON.stringify(child));
console.log('Bloque 4: 20 auditadas y 12 reubicadas.');
