const fs=require('fs'),path=require('path'),file=path.join(__dirname,'..','public','banco','clinica_adultos.json'),b=JSON.parse(fs.readFileSync(file,'utf8'));
const ref='American Psychiatric Association (2022). DSM-5-TR, capítulo «Personality Disorders» y modelo alternativo de la sección III; Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología (4.ª ed.), capítulo de trastornos de la personalidad.';
const rows={
'PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-UNO-23_061':['b','La b es correcta: la CIE ha situado la esquizotipia entre los trastornos del espectro de la esquizofrenia, no como trastorno de personalidad. La gravedad mínima del trastorno es leve y al DSM le falta en d el dominio psicoticismo.'],
'PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-UNO-23_066':['c','La c reúne correctamente alta reactividad e intensidad, afecto negativo, labilidad y retorno lento a la línea basal.'],
'PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-DOS-23_054':['c','La c es correcta: Pincus y Wilson describieron variantes sumisa, explotadora y amorosa de la dependencia.'],
'PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-DOS-23_074':['a','La a es correcta según el modelo transdiagnóstico citado: la baja tolerancia al malestar se relaciona con el inicio o mantenimiento del TLP.'],
'PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-UNO-23_076':['b','La b es correcta: en el perfil alternativo narcisista, la búsqueda de atención y admiración regula una autoestima vulnerable.'],
'PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-UNO-23_092':['d','La d es correcta: la confusión sobre identidad sexual se integra en las alteraciones de identidad.'],
'SEPTIEMBRE-DOS-24_COMENTADO_091':['c','La c es correcta: el tipo esquizoide no se conserva entre los seis diagnósticos específicos del modelo alternativo.'],
'SEPTIEMBRE-UNO-24_COMENTADO_180':['b','La b es la incorrecta: los problemas internalizantes y externalizantes tempranos suelen preceder y predecir síntomas límite posteriores, no al revés.'],
'SEPTIEMBRE-UNO-24_COMENTADO_181':['c','La c es correcta: el trastorno paranoide no se conserva como tipo específico en el modelo alternativo.'],
'Simu 11 comentado_039':['a','La a es correcta: el clúster B agrupa personalidad antisocial, límite, histriónica y narcisista.'],
'Simu 13 comentado_071':['d','La d es correcta: el patrón esquizoide se caracteriza por desapego de las relaciones íntimas y expresión emocional restringida.'],
'Simu 13 comentado_072':['d','La d es la excepción: la desconfianza generalizada define principalmente personalidad paranoide; el patrón esquizotípico combina déficits interpersonales, distorsiones y excentricidad.'],
'Simu 13 comentado_074':['b','La b es correcta: el criterio A evalúa funcionamiento del self —identidad y autodirección— e interpersonal —empatía e intimidad—.'],
'Simu 15 comentado_045':['c','La c es la excepción: desprecio y vulneración de derechos corresponde al patrón antisocial del clúster B.'],
'Simu 15 comentado_050':['c','La c es correcta: Linehan explica el TLP mediante la interacción entre vulnerabilidad biológica y ambiente invalidante.'],
'Simu 15 comentado_054':['a','La a es correcta: los trastornos se caracterizan por deterioro moderado o mayor del funcionamiento de la personalidad y uno o más rasgos patológicos.'],
'Simu 16 comentado_006':['c','La c es la excepción: el criterio recoge vacío crónico, no euforia crónica. Las demás alternativas son criterios diagnósticos del TLP.'],
'Simu 16 comentado_095':['b','La b es correcta: el diagnóstico de personalidad antisocial exige al menos 18 años y evidencia de trastorno de conducta antes de los 15.'],
'Simu 16 comentado_101':['a','La a es correcta: el perfil obsesivo-compulsivo exige tres o más de perfeccionismo rígido, perseveración, evitación de la intimidad y afectividad restringida.']};
const clean=s=>String(s??'').replace(/[�]/g,'').replace(/\b([A-Za-zÁÉÍÓÚáéíóúñÑ]{2,})-\s+([a-záéíóúñ]{2,})\b/g,'$1$2').replace(/\s+/g,' ').trim();
for(const[id,[c,x]]of Object.entries(rows)){const q=b.find(z=>z.id===id);if(!q)throw Error(id);q.c=c;q.e=clean(q.e).replace(/^(?:\d+\s+){1,6}(?=[¿¡A-ZÁÉÍÓÚ])/,'');for(const k of'abcd')q.o[k]=clean(q.o[k]);Object.assign(q,{x,r:ref,v:'VALIDADA_ORIGINAL'})}
const corrupt=b.find(q=>q.id==='Simu 15 comentado_054');Object.assign(corrupt,{e:'Según el modelo alternativo de la sección III del DSM-5-TR, ¿qué caracteriza a un trastorno de la personalidad?',o:{a:'Deterioro del funcionamiento de la personalidad y presencia de rasgos patológicos.',b:'Únicamente la pertenencia a uno de los tres clústeres tradicionales.',c:'La presencia obligatoria de psicosis y deterioro cognitivo.',d:'Un episodio limitado a situaciones de estrés agudo.'},c:'a'});
const moved=b.find(q=>q.id==='PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-UNO-23_067');Object.assign(moved,{t:['Trastornos disociativos'],e:'Según el manual de referencia, ¿en qué trastorno disociativo puede aparecer un patrón repetido de relaciones que implican abuso físico o sexual?',o:{a:'Amnesia disociativa.',b:'Trastorno de identidad disociativo.',c:'Trastorno de despersonalización/desrealización.',d:'Trastorno de adaptación.'},c:'b',x:'La b es correcta: en el trastorno de identidad disociativo son frecuentes historias traumáticas graves y patrones relacionales en los que puede repetirse la victimización. Las restantes opciones no se caracterizan específicamente por este patrón.',r:'Caballo, V. E., Salazar, I. C. y Carrobles, J. A. Manual de psicopatología y trastornos psicológicos, capítulo de trastornos disociativos.',v:'VALIDADA_ORIGINAL'});
fs.writeFileSync(file,JSON.stringify(b));console.log({audited:20,personality:19,movedToDissociative:1,reconstructed:'Simu 15 comentado_054'});
