const fs=require('fs'),P='public/banco/';
let adult=JSON.parse(fs.readFileSync(P+'clinica_adultos.json','utf8'));
let treat=JSON.parse(fs.readFileSync(P+'tratamientos_adultos.json','utf8'));
const dsm='American Psychiatric Association (2022). DSM-5-TR. Trastornos relacionados con traumas y factores de estrés.';
const cie='World Health Organization (2024). ICD-11 CDDR. Disorders specifically associated with stress.';
const bel='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. II (4.ª ed.). McGraw Hill, capítulo sobre trauma y factores de estrés.';
const U={
'PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-UNO-23_043':{e:'¿Dónde se clasifica el trastorno de duelo prolongado en el DSM-5-TR?',o:{a:'Entre los trastornos depresivos especificados.',b:'Entre los trastornos relacionados con traumas y factores de estrés.',c:'Entre los trastornos de ansiedad especificados.',d:'Entre los trastornos disociativos especificados.'},c:'b',x:'La b es correcta: el DSM-5-TR incorporó el trastorno de duelo prolongado como diagnóstico dentro de los trastornos relacionados con traumas y factores de estrés. La a, c y d lo sitúan en capítulos distintos. Se actualiza la antigua formulación del DSM-5, donde el duelo complejo persistente aparecía como afección propuesta para estudio posterior.',r:dsm},
'PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-UNO-23_088':{e:'¿Cuál de las siguientes variables se considera un factor postraumático de mantenimiento?',o:{a:'La intencionalidad del suceso.',b:'El estrés acumulativo previo.',c:'La necesidad persistente de buscar culpables.',d:'Una personalidad vulnerable.'},c:'c',x:'La c es correcta: buscar culpables de forma persistente puede mantener rumiación y anclaje en el trauma. La a es una característica precipitante del suceso. La b y la d son factores predisponentes previos a la exposición.',r:bel},
'PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-UNO-23_093':{e:'¿Cuál de los siguientes pertenece al grupo de alteraciones negativas de las cogniciones y del estado de ánimo del TEPT?',o:{a:'Pesadillas relacionadas con el trauma.',b:'Conductas de evitación externa.',c:'Creencias negativas persistentes sobre uno mismo, los demás o el mundo.',d:'Respuesta de sobresalto exagerada.'},c:'c',x:'La c es correcta y corresponde al criterio D. La a es un síntoma de intrusión; la b pertenece a evitación; y la d a alteraciones de activación y reactividad. Se elimina la clasificación ambigua entre síntomas «positivos» y «negativos».',r:dsm},
'PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-DOS-23_208':{e:'Señale la afirmación FALSA respecto al criterio de trauma y las manifestaciones del TEPT:',o:{a:'Toda enfermedad médica potencialmente mortal constituye por sí sola un acontecimiento traumático del criterio A.',b:'En menores, la violencia sexual puede incluir experiencias inapropiadas para el desarrollo sin lesión física.',c:'Durante un flashback la persona puede comportarse como si el suceso estuviera ocurriendo de nuevo.',d:'Pueden aparecer síntomas disociativos y experiencias perceptivas inusuales.'},c:'a',x:'La a es falsa: una enfermedad grave no cumple automáticamente el criterio A; sí pueden hacerlo acontecimientos médicos súbitos y catastróficos. La b es correcta porque la violencia sexual no exige lesión física. La c describe reacciones disociativas de intrusión. La d recoge manifestaciones asociadas posibles, sin convertirlas necesariamente en un trastorno psicótico.',r:dsm},
'PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-UNO-23_082':{e:'¿Cuál es un factor de mantenimiento postraumático?',o:{a:'El estrés acumulativo.',b:'La intencionalidad del suceso.',c:'La gravedad del acontecimiento.',d:'La necesidad persistente de buscar culpables.'},c:'d',x:'La d es correcta porque perpetúa rumiación y dificulta la elaboración. La a es predisponente. La b y la c son características precipitantes del propio acontecimiento.',r:bel},
'PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-UNO-23_097':{t:['Trastornos disociativos'],e:'¿Qué grupo de trastornos ha sido denominado en la literatura «epidemia oculta» por su frecuente infradetección?',o:{a:'Trastornos de ansiedad.',b:'Trastornos disociativos.',c:'Trastornos depresivos.',d:'Trastorno del espectro autista.'},c:'b',x:'La b es correcta: la expresión «epidemia oculta» se ha aplicado a los trastornos disociativos por su infrarreconocimiento y su relación frecuente con trauma temprano. La a y la c son muy prevalentes, pero no corresponden a esa denominación específica. La d es un trastorno del neurodesarrollo y tampoco corresponde. Se reubica en trastornos disociativos.',r:'Spiegel, D. et al. (2011). Dissociative disorders in DSM-5. Depression and Anxiety, 28, 824–852. https://doi.org/10.1002/da.20874; '+bel},
'PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-UNO-23_099':{e:'¿Cuándo puede diagnosticarse trastorno de adaptación después de un acontecimiento traumático?',o:{a:'Solo cuando se cumplen todos los criterios de TEPT.',b:'Únicamente durante las primeras 48 horas.',c:'Nunca después de un acontecimiento que cumpla el criterio A de trauma.',d:'Cuando la respuesta clínicamente significativa no alcanza los criterios de trastorno de estrés agudo o TEPT.'},c:'d',x:'La d es correcta: un trauma no obliga a diagnosticar TEPT o estrés agudo si no se alcanza su umbral; puede diagnosticarse adaptación cuando se cumplen sus propios criterios. La a es falsa porque entonces correspondería TEPT. La b inventa un límite temporal. La c es falsa porque la gravedad del estresor no excluye por sí misma el diagnóstico.',r:dsm},
'Simu 12 comentado_075':{e:'¿Cuál de las siguientes NO es una de las cuatro dimensiones del modelo 4-D de Frewen y Lanius?',o:{a:'Memoria implícita.',b:'Pensamiento.',c:'Cuerpo.',d:'Emoción.'},c:'a',x:'La a es correcta: las cuatro dimensiones son tiempo-memoria, pensamiento, cuerpo y emoción. La memoria implícita puede ser relevante para el trauma, pero no constituye una dimensión independiente del modelo. Las opciones b, c y d sí forman parte de él.',r:'Frewen, P. A. y Lanius, R. A. (2014). Trauma-related altered states of consciousness: Exploring the 4-D model. Journal of Trauma & Dissociation, 15, 436–456. https://doi.org/10.1080/15299732.2013.873377.'},
'Simu 13 comentado_049':{e:'Según Echeburúa y colaboradores, ¿cuál es una variable predisponente previa al trauma?',o:{a:'El anclaje en el pasado.',b:'El estrés acumulativo.',c:'La necesidad persistente de buscar culpables.',d:'La negación emocional posterior del suceso.'},c:'b',x:'La b es correcta: el estrés acumulativo incrementa vulnerabilidad antes del acontecimiento. La a, c y d son mecanismos postraumáticos de mantenimiento. Se corrige la clave original a.',r:bel},
'Simu 14 comentado _046':{e:'¿Qué actualización introdujo el DSM-5-TR en los trastornos relacionados con trauma y factores de estrés?',o:{a:'Eliminó el trastorno de duelo prolongado.',b:'Eliminó los criterios de TEPT para menores de seis años.',c:'Añadió como ejemplo especificado la respuesta persistente al trauma con síntomas semejantes al TEPT.',d:'Mantuvo el duelo prolongado únicamente en la sección de afecciones para estudio.'},c:'c',x:'La c es correcta: el DSM-5-TR añadió esa presentación subumbral persistente entre otros trastornos especificados. La a y d son falsas porque el duelo prolongado se convirtió en diagnóstico formal. La b es falsa porque se mantienen criterios específicos para menores de seis años.',r:dsm},
'Simu 15 comentado_064':{e:'Respecto a los sucesos traumáticos y el daño psicológico, señale la afirmación INCORRECTA:',o:{a:'La amenaza vital, la lesión grave, la intencionalidad y la pérdida violenta pueden aumentar el impacto.',b:'La vulnerabilidad previa y una red de apoyo débil pueden favorecer indefensión.',c:'El trauma psicológico queda definido exclusivamente por las características objetivas del acontecimiento.',d:'Las reacciones varían según factores personales, sociales y temporales.'},c:'c',x:'La c es incorrecta: el impacto no depende exclusivamente del hecho, sino también de vulnerabilidad, significado, apoyo y afrontamiento. La a describe características de mayor impacto. La b recoge factores de vulnerabilidad. La d es correcta porque existe gran variabilidad interindividual y evolutiva.',r:bel},
'Simu 16 comentado_110':{e:'¿Para qué trastorno propusieron Botella, Baños y Guillén un modelo centrado en magnificar el estresor y minusvalorar los recursos de afrontamiento?',o:{a:'Trastorno bipolar.',b:'Trastorno de ansiedad generalizada.',c:'Trastorno depresivo mayor.',d:'Trastorno de adaptación.'},c:'d',x:'La d es correcta: el modelo explica el trastorno de adaptación mediante una valoración desproporcionada del estresor y baja autoeficacia percibida. La a se define por episodios afectivos; b por preocupación generalizada; y c por un episodio depresivo, no por el modelo específico citado.',r:'Botella, C., Baños, R. M. y Guillén, V. (2008). Creciendo en la adversidad: una propuesta de tratamiento para los trastornos adaptativos.'},
'Simu 32 comentado hardcore 2_072':{e:'¿Cuál pertenece a las alteraciones negativas de cognición y estado de ánimo del TEPT?',o:{a:'Pesadillas recurrentes relacionadas con el trauma.',b:'Sentimientos persistentes de desapego respecto a los demás.',c:'Evitación de lugares o personas asociados al trauma.',d:'Respuesta de sobresalto exagerada.'},c:'b',x:'La b es correcta y corresponde al criterio D. La a es intrusión; la c es evitación; y la d es activación/reactividad.',r:dsm},
'Simu 7 comentado _069':{e:'Señale la afirmación INCORRECTA sobre el trastorno de duelo prolongado en la CIE-11:',o:{a:'Incluye añoranza persistente o preocupación por la persona fallecida, acompañada de intenso dolor emocional.',b:'La respuesta debe persistir al menos un mes.',c:'Produce deterioro significativo en áreas importantes.',d:'Aparece como diagnóstico en la CIE-11.'},c:'b',x:'La b es incorrecta: la CIE-11 exige una duración atípicamente prolongada, como mínimo seis meses tras la pérdida. La a describe su núcleo clínico; la c recoge el deterioro requerido; y la d es correcta porque la CIE-11 lo incluye como entidad diagnóstica.',r:cie+' Prolonged grief disorder (6B42).'},
'Simu 7 comentado _077':{e:'¿Cuál es un síntoma de intrusión del TEPT?',o:{a:'Evitar recuerdos del trauma.',b:'Alteración persistente del sueño.',c:'Irritabilidad y arrebatos de furia.',d:'Reacciones disociativas o flashbacks.'},c:'d',x:'La d es correcta: los flashbacks forman parte de intrusión. La a pertenece a evitación. La b y la c pertenecen a activación y reactividad.',r:dsm},
'Simu 8 comentado _037':{e:'¿Cuál NO es un factor predisponente pretraumático?',o:{a:'Exposición previa a traumas.',b:'Gravedad del suceso traumático.',c:'Personalidad vulnerable.',d:'Estrés acumulativo.'},c:'b',x:'La b es correcta: la gravedad es un factor precipitante del acontecimiento. La a, c y d existen antes del trauma y aumentan vulnerabilidad.',r:bel},
'Simu 8 comentado _057':{e:'¿Qué son los recuerdos intrusivos en el TEPT?',o:{a:'Recuerdos angustiosos recurrentes, involuntarios e intrusivos del acontecimiento.',b:'Pensamientos buscados voluntariamente para analizar el trauma.',c:'Reacciones en las que siempre se pierde completamente la conciencia del presente.',d:'Incapacidad para recordar aspectos importantes del suceso.'},c:'a',x:'La a es correcta y reproduce el criterio de intrusión. La b es falsa porque no son voluntarios. La c describe el extremo de una reacción disociativa, no todo recuerdo intrusivo. La d corresponde a amnesia disociativa dentro de alteraciones cognitivas.',r:dsm},
'Simu 8 comentado _060':{e:'¿Cuál NO pertenece a los grupos característicos de respuesta postraumática descritos por el manual?',o:{a:'Reexperimentación.',b:'Alteraciones cognitivas.',c:'Evitación.',d:'Sensación de indefensión.'},c:'d',x:'La d es correcta: la indefensión puede acompañar al cuadro, pero no es uno de los grupos sintomáticos principales. La a, b y c sí forman parte de la caracterización clínica. En DSM-5-TR los grupos se denominan intrusión, evitación, alteraciones negativas cognitivas/afectivas y activación/reactividad.',r:bel+' '+dsm},
'Simu 8 comentado _068':{e:'¿En qué grupo se incluyen las reacciones disociativas o flashbacks del TEPT?',o:{a:'Evitación.',b:'Intrusión.',c:'Alteraciones negativas de cognición y estado de ánimo.',d:'Activación y reactividad.'},c:'b',x:'La b es correcta: los flashbacks son síntomas de intrusión. La a agrupa esfuerzos de evitación; la c, amnesia, creencias y afecto negativos; y la d, hiperactivación, sueño, irritabilidad y sobresalto.',r:dsm},
'Simu 8 comentado _069':{e:'¿Qué modelo explica los síntomas depresivos postraumáticos por exposición a situaciones percibidas como incontrolables?',o:{a:'Condicionamiento clásico.',b:'Condicionamiento operante.',c:'Teoría de la indefensión aprendida.',d:'Teoría del procesamiento emocional.'},c:'c',x:'La c es correcta: la incontrolabilidad percibida genera pasividad, desesperanza y síntomas depresivos. La a explica asociaciones de miedo; la b, mantenimiento de evitación por refuerzo; y la d, estructuras de miedo y procesamiento insuficiente.',r:'Seligman, M. E. P. (1975). Helplessness. Freeman; '+bel},
'simu 9 comentado_099':{e:'¿Cuál NO es una manifestación característica de los momentos iniciales tras un trauma?',o:{a:'Malestar emocional generalizado.',b:'Aislamiento.',c:'Pérdida de apetito.',d:'Transformación persistente de la personalidad.'},c:'d',x:'La d es correcta: una transformación persistente implica evolución prolongada, no una reacción inicial. La a, b y c pueden aparecer tempranamente como respuestas agudas.',r:bel},
'SM_ABRIL_1_SOL_1_060':{e:'Señale la afirmación correcta sobre el TEPT:',o:{a:'En niños pequeños son frecuentes patrones comórbidos distintos de los adultos, como ansiedad de separación y conducta negativista.',b:'El trastorno de estrés agudo dura entre tres horas y un mes.',c:'La exposición mediante televisión siempre cumple el criterio de trauma.',d:'La expresión retardada se aplica cuando solo una parte de los criterios aparece después de seis meses.'},c:'a',x:'La a es correcta: la comorbilidad infantil difiere de la adulta. La b es falsa porque la duración mínima es tres días, no tres horas. La c es falsa salvo exposición electrónica relacionada con el trabajo. La d es falsa: se exige que el conjunto completo de criterios no se cumpla hasta al menos seis meses, aunque algunos síntomas comiencen antes.',r:dsm},
'SM_DICIEMBRE_1_SOL_1_014':{e:'Comparado con el trastorno depresivo mayor, ¿qué característica se observa con mayor frecuencia en el trastorno de adaptación?',o:{a:'La ideación suicida aparece solo con mayor carga sintomática.',b:'El intervalo entre amenaza e intento suicida es más largo.',c:'La conducta suicida aparece necesariamente más tarde.',d:'La resolución sintomática y el retorno laboral suelen ser más rápidos.'},c:'d',x:'La d es correcta: el trastorno de adaptación suele tener evolución más breve y recuperación funcional más temprana. La a es falsa porque la ideación puede aparecer con menor carga sintomática. La b y c son falsas: la transición a conducta suicida puede ser más rápida y no necesariamente tardía.',r:bel}
};
for(const [id,p] of Object.entries(U)){const q=adult.find(x=>x.id===id);if(!q)throw Error(id);Object.assign(q,p,{v:'VALIDADA_ORIGINAL'});}
function move(id,topic,patch){const i=adult.findIndex(q=>q.id===id);if(i<0)throw Error(id);const q=adult.splice(i,1)[0];Object.assign(q,{s:'Tratamientos Adultos',t:[topic],...patch,v:'VALIDADA_ORIGINAL'});treat.push(q)}
move('Simu 31 comentado Hardcore 1_100','Tratamiento del trauma y TEPT',{e:'¿En qué ámbito se utiliza la metáfora de la «digestión psicológica» para explicar la elaboración emocional de experiencias difíciles?',o:{a:'Tratamiento de la anorexia nerviosa.',b:'Tratamiento de la bulimia nerviosa.',c:'Tratamiento farmacológico de la depresión.',d:'Intervención psicológica tras experiencias traumáticas.'},c:'d',x:'La d es correcta: la metáfora compara la elaboración del trauma con un proceso de asimilación, integración y transformación de la experiencia. La a y b usan intervenciones específicas para TCA, pero no corresponden a esta metáfora. La c se refiere a farmacoterapia y tampoco describe procesamiento psicológico.',r:'Echeburúa, E. y Corral, P. de (2007). Intervención en crisis en víctimas de sucesos traumáticos. Psicología Conductual, 15, 373–387.'});
move('Simulacro06.2018Comentarios_221','Psicología de la salud — estrés laboral y burnout',{e:'¿Qué autores iniciaron la investigación sistemática sobre la relación entre acontecimientos vitales estresantes y salud mediante una escala de reajuste social?',o:{a:'Matarazzo.',b:'Zola.',c:'Lazarus.',d:'Holmes y Rahe.'},c:'d',x:'La d es correcta: Holmes y Rahe desarrollaron la Social Readjustment Rating Scale para estudiar acontecimientos vitales y enfermedad. Matarazzo impulsó la psicología de la salud; Zola estudió sociología médica; y Lazarus desarrolló el modelo transaccional de estrés y afrontamiento, pero no fue coautor de esa escala.',r:'Holmes, T. H. y Rahe, R. H. (1967). The Social Readjustment Rating Scale. Journal of Psychosomatic Research, 11, 213–218. https://doi.org/10.1016/0022-3999(67)90010-4.'});
fs.writeFileSync(P+'clinica_adultos.json',JSON.stringify(adult));fs.writeFileSync(P+'tratamientos_adultos.json',JSON.stringify(treat));
const mp=P+'manifest.json',m=JSON.parse(fs.readFileSync(mp));m.subjects['Clínica Adultos'].count=adult.length;m.subjects['Tratamientos Adultos'].count=treat.length;fs.writeFileSync(mp,JSON.stringify(m,null,2)+'\n');
console.log(JSON.stringify({updated:Object.keys(U).length,moved:2,adult:adult.length,treat:treat.length}));
