const fs=require('fs'),P='public/banco/',a=JSON.parse(fs.readFileSync(P+'evaluacion_psicologica.json'));
const BAT='Arribas, D., Santamaría, P., Sánchez-Sánchez, F. y Fernández-Pinto, I. (2025). BAT-7, Batería de Aptitudes de TEA: manual. Hogrefe TEA Ediciones, ficha técnica y pp. 16–17. https://web.teaediciones.com/Ejemplos/BAT-7_Extracto_Manual.pdf.';
const PMA='Thurstone, L. L. y Thurstone, T. G.; adaptación española revisada por Hogrefe TEA Ediciones (2019). PMA-R, Aptitudes Mentales Primarias-Revisado: manual, pp. 15–16. https://web.teaediciones.com/Ejemplos/PMA-R-Manual-EXTRACTO.pdf.';
const U={
'PERSEVER___SIMULACRO_COMENTADO_AGOSTO-UNO-23_136':{e:'¿Qué índices de inteligencia puede proporcionar la aplicación correspondiente del BAT-7?',o:{a:'Comprensión verbal, razonamiento perceptivo, memoria de trabajo y velocidad de procesamiento.',b:'Únicamente un cociente intelectual total.',c:'Procesamiento secuencial y procesamiento simultáneo.',d:'Capacidad general (g), inteligencia fluida (Gf) e inteligencia cristalizada (Gc).'},c:'d',x:'La d es correcta: el BAT-7 permite estimar g, Gf y Gc. La a reproduce la estructura clásica de escalas Wechsler; la b omite dos índices diferenciados; y la c corresponde a la organización de la K-ABC, no al BAT-7.',r:BAT},
'PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-DOS-23_111':{e:'¿Cuántos tests diferentes contiene la aplicación completa del BAT-7?',o:{a:'Cinco.',b:'Seis.',c:'Siete.',d:'Ocho.'},c:'c',x:'La c es correcta: contiene siete tests —verbal, espacial, atención, razonamiento, numérico, mecánico y ortografía—. Las opciones a y b reducen indebidamente su composición. La d confunde los siete tests con las ocho puntuaciones aptitudinales, porque Atención genera también Concentración.',r:BAT},
'PERSEVER___SIMULACRO_COMENTADO_ENERO-UNO-23_130':{e:'¿Qué conjunto recoge las cinco aptitudes evaluadas por el PMA-R?',o:{a:'Comprensión verbal, espacial, razonamiento, numérica y fluidez verbal.',b:'Memoria de trabajo, velocidad, atención, ortografía y aptitud mecánica.',c:'Inteligencia fluida, cristalizada, memoria, atención y creatividad.',d:'Comprensión verbal, percepción táctil, coordinación motora, cálculo y personalidad.'},c:'a',x:'La a es correcta: el PMA-R evalúa los factores V, E, R, N y F. La b mezcla dimensiones del BAT-7 y de Wechsler; la c combina índices y constructos que no forman las cinco pruebas del PMA-R; y la d incorpora percepción táctil, motricidad y personalidad, ajenas a esta batería.',r:PMA},
'PERSEVER___SIMULACRO_COMENTADO_MAYO-DOS-23_185':{e:'En el marco CHC utilizado para interpretar el BAT-7, ¿en qué estrato se sitúan sus puntuaciones de aptitud específicas?',o:{a:'Estrato 0.',b:'Estrato II.',c:'Estrato I.',d:'Estrato IV.'},c:'c',x:'La c es correcta: las puntuaciones específicas representan aptitudes estrechas del estrato I. El estrato II corresponde a capacidades amplias como Gf y Gc; el estrato III se reserva al factor general g; los estratos 0 y IV no forman parte de la jerarquía CHC estándar aplicada aquí.',r:BAT},
'PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-UNO-23_027':{e:'Señale la afirmación INCORRECTA sobre el BAT-7:',o:{a:'Dispone de tres niveles de dificultad: E, M y S.',b:'Permite estimar g, Gf y Gc.',c:'Requiere cualificación profesional de nivel B.',d:'Entre sus puntuaciones aptitudinales figura Memoria como escala independiente.'},c:'d',x:'La d es la incorrecta: las ocho puntuaciones son Verbal, Espacial, Atención, Concentración, Razonamiento, Numérica, Mecánica y Ortografía; no incluye Memoria como escala independiente. Las opciones a, b y c coinciden con la ficha técnica oficial: tres niveles, tres índices y cualificación B. Se corrige la clave original a.',r:BAT},
'SEPTIEMBRE-UNO-24_COMENTADO_105':{e:'¿Cuántas puntuaciones de aptitud específicas ofrece el BAT-7 en su aplicación completa?',o:{a:'Cinco.',b:'Seis.',c:'Ocho.',d:'Diez.'},c:'c',x:'La c es correcta: ofrece ocho puntuaciones aptitudinales. Aunque contiene siete tests, el test de Atención genera dos puntuaciones —Atención y Concentración—. Las opciones a y b infravaloran el perfil y la d añade dos puntuaciones inexistentes.',r:BAT},
'Simu 16 comentado_074':{e:'Se desea evaluar en una persona de 14 años la inteligencia fluida y la cristalizada mediante una batería colectiva de aptitudes. ¿Qué prueba es adecuada?',o:{a:'BAT-7.',b:'BAS-II.',c:'Bayley-III.',d:'MATRICES.'},c:'a',x:'La a es correcta: el nivel correspondiente del BAT-7 puede aplicarse a los 14 años y proporciona Gf y Gc. BAS-II es una escala individual de inteligencia infantil, no la batería colectiva solicitada; Bayley-III se dirige al desarrollo temprano; y MATRICES estima principalmente inteligencia general no verbal, no ambos índices diferenciados.',r:BAT},
'SM_AGOSTO_1_SOL_1_037':{e:'¿Qué instrumento evalúa razonamiento espacial, numérico, abstracto y verbal, además de memoria diferida?',o:{a:'EFAI.',b:'Otis Sencillo.',c:'CAMBIOS.',d:'RP-30.'},c:'a',x:'La a es correcta: EFAI proporciona un perfil factorial de esas cuatro áreas de razonamiento y una medida de memoria. Otis Sencillo ofrece una estimación general más breve; CAMBIOS evalúa flexibilidad y atención ante condiciones cambiantes; y RP-30 se centra en rapidez y flexibilidad de razonamiento lógico.',r:'Santamaría, P. et al. (2005). EFAI, Evaluación Factorial de las Aptitudes Intelectuales. TEA Ediciones, manual y ficha técnica; Moreno Rosset, C. (2005). Evaluación psicológica (2.ª ed.), pp. 612–613.'},
'SM_DICIEMBRE_2_SOL_1_115':{e:'Según la interpretación jerárquica CHC del BAT-7, sus aptitudes específicas se sitúan en:',o:{a:'El estrato I, como capacidades estrechas.',b:'El estrato II, como capacidades amplias.',c:'El estrato III, equivalente a g.',d:'Un estrato IV situado por encima de g.'},c:'a',x:'La a es correcta: las aptitudes específicas se interpretan como capacidades estrechas de primer estrato. El estrato II agrupa capacidades amplias —por ejemplo Gf y Gc— y el III corresponde a capacidad general; el IV no pertenece a la jerarquía estándar. La redacción explicita qué significa cada alternativa.',r:BAT},
'SM_JULIO_1_SOL_1_147':{e:'¿Cuál de las siguientes NO es una batería de aptitudes múltiples?',o:{a:'Test de Vocabulario en Imágenes Peabody (PPVT).',b:'Evaluación Factorial de Aptitudes Intelectuales (EFAI).',c:'Test de Aptitudes Diferenciales (DAT-5).',d:'Batería de Aptitudes para el Aprendizaje Escolar (BAPAE).'},c:'a',x:'La a es correcta: Peabody es una prueba específica de vocabulario receptivo, no una batería con múltiples subtests aptitudinales. EFAI y DAT-5 ofrecen perfiles de varias aptitudes; BAPAE reúne pruebas orientadas a aptitudes relevantes para el aprendizaje escolar. Se sustituye el inexistente “PAT” por la denominación real PPVT.',r:'Fernández-Ballesteros, R. (2013). Evaluación psicológica: conceptos, métodos y estudio de casos. Pirámide, p. 321; Dunn, L. M. y Dunn, D. M. (2007). Peabody Picture Vocabulary Test (4th ed.). Pearson.'}
};
const ids=a.filter(q=>q.t?.includes('Tests de aptitudes')).map(q=>q.id);if(ids.length!==10)throw Error('recuento');for(const id of ids){const q=a.find(z=>z.id===id),p=U[id];if(!p)throw Error(id);Object.assign(q,p,{v:'VALIDADA_ORIGINAL'});}fs.writeFileSync(P+'evaluacion_psicologica.json',JSON.stringify(a));console.log(JSON.stringify({updated:ids.length}));
