const fs=require('fs'),path=require('path'),file=path.join(__dirname,'..','public','banco','clinica_adultos.json');
const b=JSON.parse(fs.readFileSync(file,'utf8')),ref='American Psychiatric Association (2022). DSM-5-TR, capítulo «Personality Disorders» y modelo alternativo de la sección III; Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología (4.ª ed.), capítulo de trastornos de la personalidad.';
const rows={
'MAYO-UNO-24_COMENTADO_049':['d','Paranoide, esquizoide, histriónico y dependiente son los cuatro tipos no conservados como diagnósticos específicos en el modelo alternativo por disponer de menor apoyo para su utilidad y validez.'],
'MAYO2_046':['c','La c es correcta: los fenómenos disociativos y psicóticos transitorios de mayor gravedad se agrupan en las alteraciones de la identidad.'],
'OCTUBRE-UNO-24_COMENTADO_041':['b','La b es correcta: la suspicacia es una faceta del dominio de desapego.'],
'OCTUBRE-UNO-24_COMENTADO_046':['b','La b recoge los componentes de desregulación emocional: sensibilidad, afecto negativo intenso, escasez de estrategias eficaces y uso de estrategias inadecuadas.'],
'OCTUBRE-UNO-24_COMENTADO_055':['b','La b es correcta: comprender y tolerar perspectivas distintas forma parte de la empatía; cercanía pertenece a intimidad y autorreflexión a identidad.'],
'PERSEV_AGO25_U1_203':['a','La a es correcta según el manual: los trastornos afectivos muestran una comorbilidad vital muy elevada con TLP. En TCA destaca especialmente bulimia, y la comorbilidad por sustancias tiende a disminuir con el tiempo.'],
'PERSEV_AGO25_U1_210':['b','La b es correcta: DSM-5-TR recoge estimaciones poblacionales aproximadas del 2,1 % al 7,9 % para personalidad obsesivo-compulsiva.'],
'PERSEV_JUL25_D2_050':['b','La b es correcta: el modelo de cascadas emocionales propone que la rumiación amplifica el afecto negativo y favorece conductas desadaptativas.'],
'PERSEV_JUL25_D2_204':['b','La b es correcta dentro de la clasificación usada por el manual: son experiencias alucinatorias transitorias ligadas a estrés, como las observadas en TLP.'],
'PERSEVER___SIMULACRO_COMENTADO_ABRIL-DOS-23_126':['d','La d es la incorrecta: el deterioro y el riesgo suicida son mayores en adultos jóvenes que en personas mayores. La reducción sintomática, la mejoría funcional moderada y el descenso de comorbilidad a largo plazo están descritos.'],
'PERSEVER___SIMULACRO_COMENTADO_ABRIL-DOS-23_137':['b','La b es correcta: la teoría por estadios de Turkat explica el desarrollo del patrón paranoide. Se corrige la clave antigua, que señalaba TLP.'],
'PERSEVER___SIMULACRO_COMENTADO_ABRIL-UNO-23_077':['b','La b es la excepción: el vacío crónico se asocia especialmente con TLP; baja autoestima, preocupación y escaso sentido del humor aparecen en la descripción de personalidad depresiva.'],
'PERSEVER___SIMULACRO_COMENTADO_AGOSTO-UNO-23_058':['b','La b es correcta: Magnavita organiza la sistemática en matrices intrapsíquicas, diádicas, triádicas, familiares y socioculturales.'],
'PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-DOS-23_052':['d','La d es correcta: el trastorno esquizotípico se caracteriza principalmente por psicoticismo y desapego en el modelo alternativo.'],
'PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-DOS-23_199':['b','La b es correcta: la revisión de Crowell y colaboradores dio mayor peso a la impulsividad temprana como vulnerabilidad biológica adicional.'],
'PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-UNO-23_061':['b','La b es correcta: anhedonia es una faceta de desapego; impulsividad pertenece a desinhibición, inseguridad de separación a afectividad negativa y búsqueda de atención a antagonismo.'],
'PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-UNO-23_080':['d','La d es correcta: los síntomas psicóticos y disociativos transitorios se sitúan en alteraciones de la identidad.'],
'PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-UNO-23_084':['a','La a es correcta en la ampliación de Crowell del modelo biosocial: la impulsividad temprana puede constituir una vulnerabilidad biológica. El modelo también describe alta sensibilidad, respuestas intensas y retorno lento a la línea basal.'],
'PERSEVER___SIMULACRO_COMENTADO_ENERO-UNO-23_058':['a','La a es correcta: empatía e intimidad constituyen el funcionamiento interpersonal; identidad y autodirección constituyen el funcionamiento del self.'],
'PERSEVER___SIMULACRO_COMENTADO_ENERO-UNO-23_142':['c','La c es correcta: la sección III del DSM-5 presenta un modelo híbrido categorial-dimensional. La CIE-11 es dimensional y DSM-5 abandonó el sistema multiaxial.' ]};
const clean=s=>String(s??'').replace(/[�]/g,'').replace(/\b([A-Za-zÁÉÍÓÚáéíóúñÑ]{2,})-\s+([a-záéíóúñ]{2,})\b/g,'$1$2').replace(/\s+/g,' ').trim();
for(const [id,[c,x]] of Object.entries(rows)){const q=b.find(z=>z.id===id);if(!q)throw Error(id);q.c=c;q.e=clean(q.e).replace(/^(?:\d+\s+){1,6}(?=[¿¡A-ZÁÉÍÓÚ])/,'').replace('Alternaciones de la identidad','Alteraciones de la identidad');for(const k of ['a','b','c','d']){q.o[k]=clean(q.o[k]);const p=q.o[k].search(/\s+(?:R[1-4]\s*(?:CORRECTA|INCORRECTA)|La respuesta correcta|Dimensiones transdiagnósticas|MODELOS TEÓRICOS|En las características transdiagnósticas|Sé que algunas|La teoría de estadios|La opción de)/i);if(p>10)q.o[k]=q.o[k].slice(0,p).trim()}Object.assign(q,{x,r:ref,v:'VALIDADA_ORIGINAL'})}
fs.writeFileSync(file,JSON.stringify(b));console.log({audited:Object.keys(rows).length,keyCorrections:['ABRIL-DOS-23_126 b→d','ABRIL-DOS-23_137 a→b']});
