const fs=require('fs'),P='public/banco/',F=P+'clinica_adultos.json';
const a=JSON.parse(fs.readFileSync(F,'utf8'));
const D='American Psychiatric Association (2022). DSM-5-TR. Capítulo «Trastornos disociativos». Editorial Médica Panamericana.';
const B='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. II (4.ª ed.). McGraw Hill, capítulo sobre trastornos disociativos.';
const C='Caballo, V. E., Salazar, I. C. y Carrobles, J. A. (dirs.) (2014). Manual de psicopatología y trastornos psicológicos. Pirámide, p. 482.';
const U={
'JUNIO1_120':{e:'¿Qué trastorno disociativo puede presentar disfunciones sexuales como característica fisiológica asociada?',o:{a:'Amnesia disociativa.',b:'Trastorno de identidad disociativo.',c:'Trastorno de despersonalización/desrealización.',d:'Trance disociativo.'},c:'a',x:'La a es correcta según la tabla clínica de la fuente: las disfunciones sexuales figuran entre las alteraciones fisiológicas asociadas a la amnesia disociativa. La b se asocia, entre otros rasgos, con elevada hipnotizabilidad; la c puede incluir distorsiones perceptivas como macropsia o micropsia; y la d se define por reducción de la conciencia y respuesta al entorno, no por este rasgo.',r:C},
'PERSEVER___SIMULACRO_COMENTADO_ABRIL-DOS-23_164':{e:'Según Caballo y colaboradores, ¿qué alteración fisiológica se asocia a la amnesia disociativa?',o:{a:'Disfunción sexual.',b:'Elevada hipnotizabilidad.',c:'Comportamiento mecánico.',d:'Macropsia o micropsia.'},c:'a',x:'La a es correcta: la fuente vincula las disfunciones sexuales con la amnesia disociativa. La b se describe en el trastorno de identidad disociativo; la c es una alteración conductual, no fisiológica; y la d se relaciona con despersonalización/desrealización.',r:C},
'PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-UNO-23_069':{e:'¿Cuál es una característica fisiológica asociada a la amnesia disociativa?',o:{a:'Disfunción sexual.',b:'Regresión cronológica.',c:'Macropsia o micropsia.',d:'Autolesiones e intentos de suicidio.'},c:'a',x:'La a es correcta según la clasificación clínica empleada por la fuente. La b y la d se describen entre manifestaciones del trastorno de identidad disociativo y no como alteraciones fisiológicas de la amnesia; la c se asocia al trastorno de despersonalización/desrealización.',r:C},
'PERSEVER___SIMULACRO_COMENTADO_MAYO-DOS-23_044':{e:'Respecto al trastorno de identidad disociativo, señale la afirmación correcta:',o:{a:'Se han implicado la corteza orbitofrontal, el hipocampo, la circunvolución parahipocampal y la amígdala.',b:'La conversión constituye necesariamente un síntoma cognitivo nuclear.',c:'En la infancia los cambios de identidad se presentan siempre igual que en adultos.',d:'La negligencia a los 8–9 años se asocia específicamente a disociación y a los 4–5 años a depresión.'},c:'a',x:'La a es correcta: esas regiones forman parte de los circuitos estudiados en la fisiopatología disociativa. La b clasifica erróneamente la conversión como síntoma cognitivo nuclear; la c ignora que en menores la presentación puede ser menos elaborada y confundirse con fenómenos evolutivos; y la d invierte las ventanas descritas: 4–5 años se vinculó más con disociación y 8–9 con depresión.',r:B+'; Schalinski, I. et al. (2016). BMC Psychiatry, 16, 295. https://doi.org/10.1186/s12888-016-1004-5.'},
'PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-UNO-23_170':{e:'Según Kihlstrom, ¿qué mecanismo explica las alteraciones de memoria de los trastornos disociativos?',o:{a:'Un déficit general e irreversible de atención.',b:'La separación completa del sí mismo respecto de la red de memoria.',c:'La pérdida de conexión entre recuerdos autobiográficos y la representación mental del sí mismo.',d:'Un deterioro limitado a memoria implícita y semántica.'},c:'c',x:'La c es correcta: el modelo relaciona la amnesia disociativa con una desconexión funcional entre la información autobiográfica y el sí mismo. La a reduce indebidamente el fenómeno a atención; la b excluye el sí mismo de la red cuando actúa como estructura organizadora; y la d es falsa porque el problema afecta principalmente al acceso explícito a información autobiográfica.',r:'Kihlstrom, J. F. (2005). Dissociative disorders. Annual Review of Clinical Psychology, 1, 227–253. https://doi.org/10.1146/annurev.clinpsy.1.102803.143925.'},
'PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-UNO-23_179':{e:'En la clasificación funcional de Tyrer, la amnesia disociativa se incluye en:',o:{a:'Disociación de la función cognitiva.',b:'Disociación de la percepción.',c:'Disociación de conductas complejas.',d:'Disociación de movimientos o sensaciones.'},c:'a',x:'La a es correcta porque la amnesia afecta al acceso cognitivo a información autobiográfica. La b comprende fenómenos perceptivos como despersonalización/desrealización; la c se refiere a conductas complejas disociadas; y la d agrupa alteraciones funcionales motoras o sensitivas.',r:B},
'PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-DOS-23_034':{e:'¿Qué modelo explicativo de la disociación atribuye un papel central al trauma y al conflicto entre el mundo interno y la realidad externa?',o:{a:'Modelo BASK.',b:'Modelo autohipnótico.',c:'Modelo de estructuras paralelas diferentes.',d:'Modelo del factor traumático.'},c:'d',x:'La d es correcta: el modelo traumático entiende la disociación como respuesta defensiva ante experiencias abrumadoras y el conflicto entre realidad interna y externa. BASK describe cuatro componentes de procesamiento; el autohipnótico destaca la hipnotizabilidad; y el modelo de estructuras paralelas plantea sistemas mentales segregados, pero no es la formulación solicitada.',r:B},
'PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-DOS-23_036':{e:'¿Cuál de las siguientes se describe como alteración fisiológica asociada a la amnesia disociativa?',o:{a:'Regresión cronológica.',b:'Macropsia.',c:'Analgesia.',d:'Conversión.'},c:'c',x:'La c es correcta: la analgesia representa una disminución disociativa de la sensibilidad dolorosa. La a es un fenómeno conductual o de identidad; la b es una distorsión perceptiva vinculada a despersonalización/desrealización; y la d designa síntomas neurológicos funcionales, no la alteración fisiológica concreta solicitada.',r:C},
'PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-DOS-23_203':{e:'¿Para qué grupo de problemas se formuló el modelo etiológico multifactorial de Vanderlinden y Vandereycken?',o:{a:'Trastorno obsesivo-compulsivo.',b:'Síntomas y trastornos disociativos relacionados con experiencias traumáticas.',c:'Disfunciones sexuales.',d:'Trastornos de la conducta alimentaria exclusivamente.'},c:'b',x:'La b es correcta: el modelo explica cómo factores del trauma, la vulnerabilidad y el contexto favorecen síntomas disociativos. La a y la c no son su objeto; la d resulta tentadora por la trayectoria de los autores, pero el modelo preguntado no se limita a los trastornos alimentarios.',r:'Vanderlinden, J. y Vandereycken, W. (1997). Trauma, Dissociation, and Impulse Dyscontrol in Eating Disorders. Brunner/Mazel; '+B},
'PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-UNO-23_057':{e:'¿Cuál es una característica fisiológica asociada al trastorno de identidad disociativo?',o:{a:'Incapacidad para recordar información personal importante.',b:'Síntomas de estrés postraumático.',c:'Elevada capacidad o susceptibilidad hipnótica.',d:'Autolesiones e intentos de suicidio.'},c:'c',x:'La c es correcta según la clasificación de la fuente. La a es un síntoma cognitivo de amnesia; la b es una manifestación clínica comórbida, no una característica fisiológica; y la d pertenece al ámbito conductual y de riesgo.',r:C},
'PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-UNO-23_091':{e:'En la amnesia disociativa, recordar solo una parte de los acontecimientos ocurridos durante un periodo delimitado corresponde a la modalidad:',o:{a:'Generalizada.',b:'Selectiva.',c:'Localizada.',d:'Continua.'},c:'b',x:'La b es correcta: en la amnesia selectiva se recuerdan algunos acontecimientos del periodo, pero no todos. La localizada supone no recordar ninguno durante un periodo; la generalizada abarca la propia historia vital y es rara; y la continua afecta sucesos nuevos desde un momento determinado hasta el presente.',r:D},
'PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-DOS-23_024':{e:'Sobre las consecuencias neurobiológicas del trauma y la disociación, señale la afirmación correcta:',o:{a:'El trauma del desarrollo afecta específicamente al córtex parietotemporal como principal regulador ejecutivo de la amígdala.',b:'El cortisol del estrés crónico daña selectivamente el hipotálamo, principal estructura de memoria declarativa.',c:'El subtipo disociativo del TEPT se ha asociado a hiperactivación de regiones reguladoras prefrontales y menor activación de amígdala e ínsula.',d:'El trauma temprano forma memoria declarativa de miedo, pero impide siempre la memoria emocional y sensorial.'},c:'c',x:'La c es correcta y refleja el patrón de sobremodulación emocional propuesto para el subtipo disociativo. La a confunde córtex parietotemporal con prefrontal medial; la b confunde hipotálamo con hipocampo; y la d usa un absoluto falso, pues pueden predominar memorias emocionales y sensoriales fragmentadas.',r:'Lanius, R. A. et al. (2012). Emotion modulation in PTSD: Clinical and neurobiological evidence for a dissociative subtype. American Journal of Psychiatry, 167, 640–647; '+B},
'PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-DOS-23_030':{e:'Dos semanas después de un accidente, una persona presenta enlentecimiento subjetivo del tiempo, despersonalización, desrealización, analgesia y una laguna breve, pero no reúne el número de síntomas exigido para trastorno de estrés agudo. ¿Cuál es el diagnóstico DSM-5-TR más compatible?',o:{a:'Trastorno de estrés agudo.',b:'TEPT con especificador de corta duración.',c:'Reacción disociativa aguda a sucesos estresantes.',d:'Trance disociativo.'},c:'c',x:'La c es correcta: esta categoría de otro trastorno disociativo especificado permite describir un cuadro agudo predominantemente disociativo de menos de un mes. La a exige nueve o más síntomas del conjunto diagnóstico; la b no es un especificador vigente y el TEPT exige más de un mes; la d requiere reducción marcada de conciencia y respuesta al entorno, no descrita.',r:D},
'PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-UNO-23_111':{e:'¿Qué dato hace MENOS probable un trastorno disociativo crónico como explicación principal?',o:{a:'Múltiples diagnósticos previos y perfiles sintomáticos cambiantes.',b:'Escasa respuesta a tratamientos estándar de diagnósticos previos.',c:'Autolesiones y síntomas compatibles con trauma o disociación.',d:'Inicio reciente en la edad adulta tras una trayectoria estable de buen funcionamiento, sin trauma ni síntomas disociativos previos.'},c:'d',x:'La d es correcta: un comienzo adulto reciente, sin antecedentes ni precipitante compatible, obliga a priorizar otras explicaciones médicas, por sustancias o psiquiátricas. Las opciones a, b y c son señales que pueden justificar explorar disociación, aunque ninguna establece por sí sola el diagnóstico.',r:B},
'SEPTIEMBRE-DOS-24_COMENTADO_112':{e:'La reducción aguda o pérdida completa de conciencia del entorno, manifestada como apatía o insensibilidad intensa a los estímulos, define principalmente:',o:{a:'Amnesia disociativa.',b:'Trastorno de despersonalización/desrealización.',c:'Trance disociativo.',d:'Trastorno de identidad disociativo.'},c:'c',x:'La c es correcta: el trance disociativo implica una marcada restricción de conciencia y respuesta al entorno y puede acompañarse de conductas estereotipadas o parálisis. La a se define por amnesia autobiográfica; la b por irrealidad con juicio de realidad intacto; y la d por discontinuidad de identidad y lagunas recurrentes.',r:D},
'SEPTIEMBRE-DOS-24_COMENTADO_126':{e:'En el modelo multifactorial de Vanderlinden y Vandereycken, ¿qué variable NO favorece la aparición de síntomas disociativos tras experiencias traumáticas?',o:{a:'Menor edad de la víctima.',b:'Menor gravedad del abuso.',c:'Desorganización familiar.',d:'Autoimagen negativa.'},c:'b',x:'La b es correcta porque el riesgo se relaciona con mayor, no menor, gravedad del abuso. La menor edad aumenta vulnerabilidad; la desorganización familiar dificulta protección e integración; y una autoimagen negativa actúa como factor de vulnerabilidad o mantenimiento.',r:'Vanderlinden, J. y Vandereycken, W. (1997). Trauma, Dissociation, and Impulse Dyscontrol in Eating Disorders. Brunner/Mazel; '+B},
'SIM_PERS_AGO25_099':{e:'Sentirse como un observador externo de los propios pensamientos, sensaciones, cuerpo o acciones se denomina:',o:{a:'Desrealización.',b:'Alucinación cenestésica.',c:'Despersonalización.',d:'Fuga disociativa.'},c:'c',x:'La c es correcta: la despersonalización consiste en irrealidad o distanciamiento respecto del propio yo. La desrealización afecta al entorno; la alucinación cenestésica es una percepción corporal sin estímulo; y la fuga implica viaje o deambulación asociada a amnesia autobiográfica.',r:D},
'Simu 13 comentado_053':{e:'¿Qué trastorno se define por una reducción aguda o pérdida completa de conciencia del entorno, con insensibilidad a estímulos y posibles conductas estereotipadas mínimas o parálisis transitoria?',o:{a:'Síndromes crónicos y recurrentes de síntomas disociativos mixtos.',b:'Alteración de identidad por persuasión coercitiva prolongada.',c:'Reacción disociativa aguda a sucesos estresantes.',d:'Trance disociativo.'},c:'d',x:'La d es correcta: reproduce el núcleo definitorio del trance disociativo. La a exige un patrón crónico y mixto; la b se vincula a control coercitivo de identidad; y la c describe un cuadro agudo tras estrés, pero no queda definida específicamente por la restricción de conciencia del entorno aquí descrita.',r:D},
'Simu 14 comentado _001':{e:'¿Qué categoría del DSM-5-TR se aproxima más al trastorno de identidad disociativo parcial de la CIE-11?',o:{a:'Alteración de identidad por persuasión coercitiva prolongada.',b:'Reacción disociativa aguda a sucesos estresantes.',c:'Síndromes crónicos y recurrentes de síntomas disociativos mixtos.',d:'Trance disociativo.'},c:'c',x:'La c es la mejor respuesta entre las opciones: recoge presentaciones crónicas mixtas que no cumplen plenamente el TID del DSM. La a exige coerción prolongada; la b es aguda y breve; y la d se caracteriza por restricción de conciencia. La equivalencia no es literal porque DSM-5-TR y CIE-11 organizan estas categorías de forma distinta.',r:D+'; World Health Organization (2024). ICD-11 CDDR, 6B65.'},
'Simu 14 comentado _049':{e:'Respecto al trastorno de despersonalización/desrealización, señale la afirmación correcta:',o:{a:'Durante las experiencias, el juicio de realidad permanece intacto.',b:'La búsqueda de sensaciones es su factor temperamental característico.',c:'Se diagnostica con una frecuencia claramente mayor en mujeres.',d:'Presenta necesariamente un curso episódico y baja comorbilidad con ansiedad o depresión.'},c:'a',x:'La a es correcta y constituye un criterio diferencial esencial: la persona reconoce que la experiencia de irrealidad no es real. La b es falsa porque se han descrito evitación del daño y otros factores, no búsqueda de sensaciones como rasgo definitorio; la c es falsa porque la proporción por sexo es aproximadamente igual; y la d es falsa porque el curso puede ser persistente y la comorbilidad ansioso-depresiva es frecuente.',r:D}
};
for(const [id,z] of Object.entries(U)){const q=a.find(x=>x.id===id);if(!q)throw Error('Falta '+id);Object.assign(q,z,{v:'VALIDADA_ORIGINAL'});}
fs.writeFileSync(F,JSON.stringify(a));
const m=JSON.parse(fs.readFileSync(P+'manifest.json','utf8'));for(const v of Object.values(m.subjects))v.count=JSON.parse(fs.readFileSync(P+v.slug+'.json','utf8')).length;m.total=Object.values(m.subjects).reduce((n,v)=>n+v.count,0);fs.writeFileSync(P+'manifest.json',JSON.stringify(m,null,2)+'\n');
console.log({actualizadas:Object.keys(U).length,total:m.total});
