const fs=require('fs'),P='public/banco/';
const ev=JSON.parse(fs.readFileSync(P+'evaluacion_psicologica.json')),child=JSON.parse(fs.readFileSync(P+'clinica_infantojuvenil.json')),pers=JSON.parse(fs.readFileSync(P+'psicologia_de_la_personalidad_y_diferencial.json')),evo=JSON.parse(fs.readFileSync(P+'psicologia_evolutiva.json')),soc=JSON.parse(fs.readFileSync(P+'psicologia_social.json'));
const REF='Moreno Rosset, C. y Ramírez Uclés, I. (2019). Evaluación psicológica: proceso, técnicas y aplicaciones en áreas y contextos. Sanz y Torres; Fernández-Ballesteros, R. (2013). Evaluación psicológica. Pirámide.';
const W='Wechsler, D. (2012). WAIS-IV: Escala de inteligencia de Wechsler para adultos-IV. Manual técnico y de interpretación. Pearson.';
const U={
'JULIO2_070':['La entrevista','¿Qué describe la sincronía durante una entrevista psicológica?',{a:'La capacidad de diagnosticar sin formular preguntas.',b:'La armonía y coordinación entre las conductas no verbales del entrevistador y del entrevistado.',c:'La identificación completa del entrevistador con el mundo interno del paciente.',d:'La distancia física mantenida entre ambos.'},'b','La b es correcta: sincronía alude a coordinación y sintonía conductual. La a no define una habilidad comunicativa; la c confunde sincronía con una formulación extrema de empatía; y la d corresponde a proxemia.',REF],
'JULIO2_082':['Evaluación neuropsicológica','¿Qué subprueba de Wechsler permite obtener una medida de atención y memoria de trabajo en una evaluación neuropsicológica?',{a:'Dígitos.',b:'Vocabulario.',c:'Cubos.',d:'Claves.'},'a','La a es correcta: Dígitos exige atención, retención y manipulación inmediata. Vocabulario evalúa conocimiento léxico; Cubos, razonamiento y organización visoespacial; y Claves, velocidad de procesamiento.',W],
'MAYO-UNO-24_COMENTADO_150':['Técnicas proyectivas','¿Cuál es la finalidad del interrogatorio o encuesta posterior a la asociación libre en el Rorschach?',{a:'Administrar nuevas láminas elegidas individualmente.',b:'Calcular directamente el cociente intelectual.',c:'Sustituir todas las respuestas espontáneas.',d:'Aclarar dónde y qué características de la mancha determinaron cada respuesta.'},'d','La d es correcta: la encuesta aclara localización y determinantes para poder codificar. La a altera el material estandarizado; la b no es finalidad del Rorschach; y la c eliminaría información esencial de la fase de respuesta.', 'Exner, J. E. (2003). The Rorschach: A Comprehensive System, vol. 1 (4th ed.). Wiley.'],
'MAYO-UNO-24_COMENTADO_166':['Tests de inteligencia','¿Qué subprueba suplementaria del WAIS-IV solo dispone de baremos para el intervalo de 16 a 69 años?',{a:'Cubos.',b:'Letras y números.',c:'Matrices.',d:'Dígitos.'},'b','La b es correcta: Letras y números es suplementaria y se limita a 16–69 años. Cubos, Matrices y Dígitos son pruebas principales con un intervalo adulto más amplio.',W],
'PERSEV_AGO25_U1_056':['Evaluación infantil','¿Cuál NO es una de las cinco áreas principales del Currículo Carolina?',{a:'Personalidad psicopatológica.',b:'Cognición.',c:'Comunicación.',d:'Motricidad gruesa.'},'a','La a es correcta: el Currículo Carolina aborda cognición, comunicación, adaptación social, motricidad fina y motricidad gruesa, no personalidad psicopatológica. Las opciones b, c y d sí son áreas del programa.', 'Johnson-Martin, N. M. et al. (1991). Currículo Carolina para niños con necesidades especiales. TEA Ediciones.'],
'PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-UNO-23_108':['La entrevista','¿Cuál de los siguientes es una cualidad comunicativa del entrevistador, pero no un compromiso contractual o ético de la alianza?',{a:'Honestidad.',b:'Confidencialidad.',c:'Sensibilidad.',d:'Acuerdo sobre honorarios.'},'c','La c es correcta: sensibilidad es una competencia relacional. Honestidad, confidencialidad y acuerdo sobre honorarios forman parte de los compromisos y condiciones explícitas del encuadre.',REF],
'PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-UNO-23_041':['Tests de inteligencia','¿Cuál afirmación sobre las BAS-II es INCORRECTA?',{a:'Incluyen escalas diferenciadas según la edad.',b:'Proporcionan un cociente intelectual hasta los 49 años.',c:'Evalúan individualmente desde la primera infancia hasta la adolescencia.',d:'Cubos y Copia contribuyen a la aptitud espacial en la batería infantil.'},'b','La b es incorrecta: BAS-II es una prueba infantil y adolescente, no una escala que ofrezca CI hasta los 49 años. Las restantes describen su organización por edades y componentes espaciales.', 'Elliott, C. D., Smith, P. y McCulloch, K. (2011). BAS-II, Escalas de Aptitudes Intelectuales. TEA Ediciones, manual.'],
'PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-DOS-23_203':['La entrevista','¿Qué tres aspectos del comportamiento no verbal del psicólogo deben vigilarse especialmente?',{a:'Congruencia, autenticidad y diagnóstico.',b:'Congruencia, sincronía y sensibilidad.',c:'Sinceridad, persuasión y confrontación.',d:'Proximidad, interpretación y directividad.'},'b','La b es correcta: congruencia, sincronía y sensibilidad favorecen una comunicación coherente y ajustada. Las otras opciones mezclan técnicas o tareas clínicas con dimensiones no verbales.',REF],
'PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-DOS-23_205':['Tests de inteligencia','¿Qué dos pruebas forman el índice espacial de las BAS-II en la batería infantil?',{a:'Semejanzas gráficas y Copia.',b:'Matrices y Semejanzas gráficas.',c:'Cubos y Razonamiento numérico.',d:'Cubos y Copia.'},'d','La d es correcta: Cubos y Copia integran la aptitud espacial. Semejanzas gráficas y Matrices se vinculan al razonamiento no verbal; Razonamiento numérico no es una prueba espacial.', 'Elliott, C. D. et al. (2011). BAS-II. TEA Ediciones, manual técnico.'],
'3Simulacro2018Comentarios_006':['Técnicas subjetivas','Las técnicas en las que una persona describe o clasifica cómo se percibe a sí misma, a otras personas u objetos se denominan:',{a:'Observacionales.',b:'Subjetivas.',c:'Objetivas.',d:'Proyectivas.'},'b','La b es correcta: las técnicas subjetivas recogen construcciones y clasificaciones personales. Las observacionales registran conducta; las objetivas usan tareas o aparatos estructurados; y las proyectivas emplean estímulos ambiguos con interpretación inferencial.',REF],
'JULIO2_083':['Técnicas subjetivas','Respecto al pensamiento en voz alta, señale la afirmación correcta:',{a:'Es siempre una entrevista completamente estructurada.',b:'Solo existe la variante de monólogo continuo.',c:'El examinador debe interpretar sin registrar las verbalizaciones.',d:'Las verbalizaciones se registran mientras el sujeto responde a tareas o estímulos concretos.'},'d','La d es correcta: se registra el flujo verbal concurrente con una tarea. La a lo clasifica erróneamente como entrevista; la b ignora otras modalidades; y la c elimina el registro, que es precisamente la fuente de datos.',REF],
'MAYO-UNO-24_COMENTADO_175':['Técnicas objetivas','¿Qué prueba evalúa distintas habilidades de percepción visual sin requerir una respuesta motora compleja?',{a:'Test de Punteado.',b:'Tiempo de anticipación.',c:'TVPS-R.',d:'Tablero de Purdue.'},'c','La c es correcta: TVPS-R evalúa discriminación, memoria visual, relaciones espaciales, constancia, memoria secuencial, figura-fondo y cierre. Punteado y Purdue valoran destreza motora; Tiempo de anticipación evalúa una respuesta temporal perceptivo-motora.', 'Gardner, M. F. (1996). Test of Visual-Perceptual Skills (Non-Motor)—Revised. Psychological and Educational Publications.'],
'SmCm09PIR2025_137':['Tests de inteligencia','En WAIS-III y WAIS-IV, la subprueba Aritmética contribuye principalmente al índice de:',{a:'Memoria de trabajo.',b:'Comprensión verbal.',c:'Velocidad de procesamiento.',d:'Razonamiento perceptivo.'},'a','La a es correcta: Aritmética requiere atención, retención y manipulación mental. No forma parte de Comprensión verbal, Velocidad de procesamiento ni Razonamiento perceptivo.',W],
'SmCm12PIR2024 2_161':['Técnicas subjetivas','¿Cómo se denominan las técnicas que permiten que el sujeto clasifique o describa a sí mismo, a otras personas u objetos?',{a:'Objetivas.',b:'Autoinformes exclusivamente.',c:'Subjetivas.',d:'Proyectivas.'},'c','La c es correcta por centrarse en la organización subjetiva de constructos. Las objetivas se basan en tareas estructuradas; autoinforme es una categoría más amplia y no equivale a esta definición; y las proyectivas infieren dinámica a partir de estímulos ambiguos.',REF],
'SmCm24PIR2025 (1)_042':['Fundamentos de la evaluación psicológica','¿Qué enfoque de evaluación enfatiza las variables ambientales y funcionales y dirige la evaluación al cambio de conducta?',{a:'Del atributo.',b:'Psicodinámico.',c:'Conductual.',d:'Constructivista.'},'c','La c es correcta: el enfoque conductual analiza relaciones funcionales entre conducta y ambiente para intervenir. El atributo prioriza rasgos; el psicodinámico, conflictos y procesos intrapsíquicos; y el constructivista, significados personales.',REF],
'SmCm3PIR2024_040':['Tests de inteligencia','¿Cómo se denomina el aumento generacional observado en las puntuaciones medias de inteligencia?',{a:'Efecto Cattell.',b:'Efecto Horn.',c:'Efecto Flynn.',d:'Efecto Stern.'},'c','La c es correcta: el efecto Flynn describe incrementos seculares de puntuaciones de CI. Cattell y Horn se vinculan al modelo fluido-cristalizado; Stern introdujo el cociente mental clásico, pero no da nombre a este efecto.', 'Flynn, J. R. (1987). Massive IQ gains in 14 nations. Psychological Bulletin, 101, 171–191. https://doi.org/10.1037/0033-2909.101.2.171.'],
'14Simulacro2018Comentarios_047':['Tests de inteligencia','¿Qué subprueba de Wechsler evalúa principalmente amplitud atencional y memoria de trabajo verbal inmediata?',{a:'Semejanzas.',b:'Dígitos.',c:'Vocabulario.',d:'Cubos.'},'b','La b es correcta: Dígitos exige repetir y manipular secuencias auditivas. Semejanzas mide razonamiento verbal; Vocabulario, conocimiento léxico; y Cubos, razonamiento visoespacial. Se sustituye la afirmación poco estable sobre cuál es “menos discriminativa”.',W],
'14Simulacro2018Comentarios_048':['Tests de inteligencia','En WAIS-IV, ¿qué afirmación sobre el orden de administración es correcta?',{a:'Se administran primero todas las tareas verbales.',b:'Se sigue el orden estandarizado del manual, que intercala tareas de distintos índices.',c:'Se administran primero todas las tareas manipulativas.',d:'El evaluado elige libremente el orden.'},'b','La b es correcta: la estandarización exige seguir el orden del manual salvo reglas específicas. No se agrupan todas las tareas verbales o manipulativas y el orden no depende de preferencias del evaluado.',W],
'14Simulacro2018Comentarios_049':['Tests de inteligencia','¿Cómo son los estímulos de la escala CPM de Matrices Progresivas de Raven?',{a:'Problemas escritos de cálculo.',b:'Dibujos de objetos cotidianos que deben nombrarse.',c:'Diseños geométricos incompletos en los que debe seleccionarse la pieza que falta.',d:'Series de fichas de dominó exclusivamente.'},'c','La c es correcta: CPM presenta patrones figurativos incompletos. No exige cálculo escrito ni denominación de objetos; las series de dominó pertenecen a pruebas distintas.', 'Raven, J., Raven, J. C. y Court, J. H. (1998). Manual for Raven’s Progressive Matrices and Vocabulary Scales. Oxford Psychologists Press.'],
'1Simulacro02018Comentarios_058':['Tests de inteligencia','Desde un enfoque clásico basado en el procedimiento de construcción, las pruebas de inteligencia se distinguen en:',{a:'Normativas y criteriales.',b:'Racionales y factoriales.',c:'De velocidad y personalidad.',d:'Proyectivas y objetivas.'},'b','La b es correcta: la metodología racional deriva tareas de concepciones clínicas o teóricas y la factorial selecciona estructura mediante análisis factorial. Las demás clasificaciones responden a otros criterios o mezclan categorías.',REF],
'1Simulacro02018Comentarios_061':['Tests de inteligencia','¿Qué limitación puede afectar especialmente a la aplicación colectiva de pruebas de factor g?',{a:'Su corrección es necesariamente manual y lenta.',b:'Algunos participantes pueden no comprender bien las instrucciones sin apoyo individual.',c:'Solo pueden aplicarse de manera individual.',d:'Siempre requieren lenguaje complejo.'},'b','La b es correcta: en grupo es más difícil detectar y resolver incomprensión individual. La a no es necesaria; la c contradice la aplicación colectiva; y la d es falsa porque muchas reducen la carga verbal.',REF],
'3Simulacro2018Comentarios_007':['Tests de inteligencia','¿Qué prueba representa históricamente una construcción principalmente racional o clínica de la inteligencia?',{a:'Escalas Wechsler.',b:'Matrices de Raven.',c:'Test de factor g de Cattell.',d:'PMA de Thurstone.'},'a','La a es correcta: Wechsler seleccionó subpruebas con criterio clínico y racional. Raven, Cattell y PMA se vinculan más estrechamente con enfoques factoriales.',REF],
'3Simulacro2018Comentarios_010':['Tests de inteligencia','En la teoría triárquica de Sternberg, la inteligencia práctica se vincula principalmente con la subteoría:',{a:'Contextual.',b:'Componencial.',c:'Experiencial.',d:'Psicométrica.'},'a','La a es correcta: la subteoría contextual aborda adaptación, selección y modificación del ambiente. La componencial se refiere a mecanismos de procesamiento; la experiencial, a novedad y automatización; “psicométrica” no es una subteoría triárquica.', 'Sternberg, R. J. (1985). Beyond IQ: A Triarchic Theory of Human Intelligence. Cambridge University Press.'],
'3Simulacro2018Comentarios_011':['Tests de inteligencia','La escala Stanford-Binet se desarrolló originalmente mediante una metodología principalmente:',{a:'Racional.',b:'Factorial.',c:'Proyectiva.',d:'Neurofisiológica.'},'a','La a es correcta: sus tareas se seleccionaron inicialmente por criterios racionales y empíricos de diferenciación evolutiva, antes del predominio factorial moderno. Las otras opciones no describen su construcción original.',REF],
'3Simulacro2018Comentarios_018':['Tests de inteligencia','¿Qué ventaja presenta normalmente la evaluación individual de inteligencia frente a la colectiva?',{a:'Siempre dura menos.',b:'Exige menos entrenamiento profesional.',c:'Impide observar estrategias y conducta durante la ejecución.',d:'Permite una observación clínica más detallada y adaptación estandarizada a incidencias.'},'d','La d es correcta: el formato individual permite observar proceso, motivación y estrategias. No es necesariamente más breve ni exige menos formación; y c invierte precisamente una de sus ventajas.',REF],
'Simu 13 comentado_027':['Tests de inteligencia','Respecto al WAIS-IV, señale la afirmación correcta:',{a:'Mantiene CI verbal y CI manipulativo como sus dos únicos resultados.',b:'Los déficits neuropsicológicos suelen afectar especialmente a Memoria de trabajo y Velocidad de procesamiento.',c:'Todas las pruebas suplementarias son obligatorias para calcular el CI total.',d:'Eliminó Cancelación y añadió Rompecabezas.'},'b','La b es correcta: esos índices son sensibles a atención, eficiencia y velocidad. La a corresponde a versiones anteriores; la c contradice el carácter suplementario; y la d es falsa porque Cancelación permanece como suplementaria y “Rompecabezas” no es una nueva subprueba del WAIS-IV español.',W]
};
function update(id){const q=ev.find(x=>x.id===id),p=U[id];if(!q||!p)throw Error(id);Object.assign(q,{t:[p[0]],e:p[1],o:p[2],c:p[3],x:p[4],r:p[5],v:'VALIDADA_ORIGINAL'});}
const localIds=Object.keys(U);for(const id of localIds)update(id);
function move(id,to,s,t,e,o,c,x,r){const i=ev.findIndex(q=>q.id===id);if(i<0)throw Error(id);const q=ev.splice(i,1)[0];Object.assign(q,{s,t:[t],e,o,c,x,r,v:'VALIDADA_ORIGINAL'});to.push(q)}
move('4Simulacro02018Comentarios_080',child,'Clínica Infantojuvenil','Trastornos de la comunicación','Un menor presenta dificultades persistentes en el uso social de la comunicación verbal y no verbal, sin patrones restrictivos o repetitivos. ¿Qué diagnóstico es más compatible?',{a:'Síndrome de Asperger.',b:'Trastorno de la comunicación social (pragmática).',c:'Trastorno del espectro autista.',d:'Trastorno fonológico.'},'b','La b es correcta: existen déficits pragmáticos sin el criterio de conductas restrictivas/repetitivas necesario para TEA. Asperger ya no es diagnóstico independiente; TEA requiere ambos dominios; el trastorno fonológico afecta producción de sonidos.','American Psychiatric Association (2022). DSM-5-TR, “Social (Pragmatic) Communication Disorder”.');
move('4Simulacro02018Comentarios_040',pers,'Psicología de la Personalidad y Diferencial','Teorías biológicas de la personalidad','¿Quién propuso la tipología corporal pícnico, atlético, leptosómico y displásico?',{a:'Kretschmer.',b:'Sheldon.',c:'Hipócrates.',d:'Gall.'},'a','La a es correcta. Sheldon propuso endomorfia, mesomorfia y ectomorfia; Hipócrates, los temperamentos humorales; Gall, la frenología.','Kretschmer, E. (1921). Körperbau und Charakter. Springer.');
move('Simu 11 comentado_102',evo,'Psicología Evolutiva','Las manifestaciones de la función simbólica','Una niña corre repetidamente de un lado a otro por el placer de ejercitar la acción. Según Piaget, realiza:',{a:'Juego de ejercicio o funcional.',b:'Juego constructivo.',c:'Juego de reglas.',d:'Juego simbólico.'},'a','La a es correcta: repite una acción motora por su resultado funcional. El constructivo crea un producto; el de reglas se organiza por normas compartidas; el simbólico representa situaciones ausentes.','Piaget, J. (1946). La formación del símbolo en el niño. Fondo de Cultura Económica.');
move('Simu 11 comentado_149',soc,'Psicología Social','Procesos de interacción social','¿Qué autor utilizó el paradigma azul-verde en estudios clásicos sobre influencia minoritaria?',{a:'Asch.',b:'Sherif.',c:'Janis.',d:'Moscovici.'},'d','La d es correcta: Moscovici y colaboradores estudiaron cómo una minoría consistente influía en juicios de color. Asch investigó conformidad mayoritaria; Sherif, formación de normas; Janis, pensamiento grupal.','Moscovici, S., Lage, E. y Naffrechoux, M. (1969). Influence of a consistent minority on the responses of a majority in a color perception task. Sociometry, 32, 365–380. https://doi.org/10.2307/2786541.');
for(const [name,data] of [['evaluacion_psicologica',ev],['clinica_infantojuvenil',child],['psicologia_de_la_personalidad_y_diferencial',pers],['psicologia_evolutiva',evo],['psicologia_social',soc]])fs.writeFileSync(P+name+'.json',JSON.stringify(data));
const m=JSON.parse(fs.readFileSync(P+'manifest.json'));for(const v of Object.values(m.subjects))v.count=JSON.parse(fs.readFileSync(P+v.slug+'.json')).length;m.total=Object.values(m.subjects).reduce((n,v)=>n+v.count,0);fs.writeFileSync(P+'manifest.json',JSON.stringify(m,null,2)+'\n');console.log(JSON.stringify({local:localIds.length,moved:4,total:m.total}));
