const fs=require('fs'),p='public/banco/clinica_adultos.json',bank=JSON.parse(fs.readFileSync(p)),t='Trastornos de ansiedad';
const DSM='American Psychiatric Association (2022). DSM-5-TR. Trastornos de ansiedad.';
const B='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. II (4.ª ed.). McGraw-Hill, capítulo de trastornos de ansiedad.';
const e={
'SmCm20PIR2024_028':['Respecto a la epidemiología y el curso de los trastornos de ansiedad, señale la afirmación correcta:',{a:'En ansiedad social solo se temen interacciones íntimas.',b:'El TAG es siempre el trastorno de ansiedad con mayor heredabilidad.',c:'El trastorno de pánico es más frecuente en hombres.',d:'La incidencia de agorafobia alcanza un máximo en adolescencia tardía y adultez temprana.'},'d','La d es correcta: la agorafobia suele comenzar antes de los 35 años, con concentración en adolescencia tardía y adultez temprana. La a restringe indebidamente los miedos sociales; la b es falsa porque la heredabilidad varía y agorafobia presenta estimaciones altas; y la c invierte el predominio femenino.',DSM],
'SmCm20PIR2024_029':['Señale la afirmación FALSA sobre los ataques de pánico:',{a:'Sus cambios fisiológicos son cualitativamente exclusivos y no aparecen durante ejercicio intenso.',b:'Suelen alcanzar el máximo en minutos y con frecuencia remiten en torno a media hora.',c:'Los adultos suelen describir más cogniciones catastróficas que los niños.',d:'Palpitaciones, mareo y temblor son síntomas frecuentes.'},'a','La a es falsa: activación autonómica semejante puede aparecer durante ejercicio; lo distintivo es su interpretación y contexto. La b describe el curso típico; la c refleja diferencias evolutivas en elaboración cognitiva; y la d recoge manifestaciones frecuentes.',B],
'SmCm21PIR2025 (2)_016':['¿Qué síntoma NO pertenece al factor cognitivo del pánico descrito por Sandín?',{a:'Miedo a morir.',b:'Miedo a perder el control o volverse loco.',c:'Desrealización o despersonalización.',d:'Náuseas o malestar abdominal.'},'d','La d es correcta: náuseas y malestar abdominal son síntomas somáticos. La a, b y c pertenecen al componente cognitivo o de experiencia subjetiva catastrófica. Se corrige la clave anterior, que marcaba erróneamente miedo a morir.',B],
'SmCm21PIR2025 (2)_028':['¿Qué grupo diagnóstico presenta comorbilidad frecuente con el TAG?',{a:'Solo trastornos por sustancias.',b:'Trastornos depresivos unipolares.',c:'Exclusivamente trastornos de conducta.',d:'Únicamente trastornos neurocognitivos.'},'b','La b es correcta: la depresión mayor y otros trastornos depresivos concurren con frecuencia con TAG. La a puede coexistir, pero “solo” la hace falsa; la c no es la asociación principal; y la d no constituye su comorbilidad característica.',DSM],
'SmCm22PIR2025 (1)_053':['¿Qué componente NO pertenece al modelo de intolerancia a la incertidumbre de Dugas para el TAG?',{a:'Intolerancia a la incertidumbre.',b:'Orientación negativa hacia los problemas.',c:'Creencias negativas sobre la preocupación o metapreocupación.',d:'Evitación cognitiva.'},'c','La c es correcta por ser la excepción: las metapreocupaciones pertenecen al modelo de Wells. Dugas incluye intolerancia a la incertidumbre, creencias positivas sobre la preocupación, orientación negativa y evitación cognitiva; por ello a, b y d sí encajan.',B],
'SmCm22PIR2025 (1)_070':['Según el DSM-5-TR, ¿qué afirmación sobre el trastorno de pánico es correcta?',{a:'Todos los ataques deben ser esperados.',b:'Se exigen al menos dos ataques seguidos de preocupación.',c:'Cinco síntomas permiten diagnosticar un subtipo de pánico limitado.',d:'Al menos un ataque debe ser inesperado y seguirse durante un mes de preocupación persistente o cambio desadaptativo.'},'d','La d es correcta: resume los criterios nucleares. La a invierte el requisito de inesperado; la b añade una cantidad no exigida para el criterio temporal; y la c es falsa porque DSM-5-TR no crea un subtipo diagnóstico de trastorno de pánico con síntomas limitados.',DSM],
'SmCm22PIR2025 (1)_079':['Al comparar ataques de pánico en población clínica y no clínica, ¿qué semejanza se observa?',{a:'En ambas pueden aparecer durante periodos de estrés.',b:'El trastorno de pánico es más frecuente en población no clínica.',c:'Solo la población clínica presenta ataques esperados.',d:'Solo la población no clínica muestra miedo a sensaciones.'},'a','La a es correcta: el estrés puede preceder ataques en ambos grupos. La b confunde ataques aislados con trastorno de pánico; la c es falsa porque ambos pueden tener ataques señalados; y la d es falsa porque el miedo a las sensaciones es especialmente relevante clínicamente.',B],
'SmCm22PIR2025 (1)_083':['¿Quién formuló el modelo del TAG centrado en intolerancia a la incertidumbre?',{a:'Barlow.',b:'Borkovec.',c:'Dugas y colaboradores.',d:'Mennin.'},'c','La c es correcta: Dugas y colaboradores desarrollaron este modelo. Barlow propone una explicación de vulnerabilidades; Borkovec el modelo de evitación cognitiva; y Mennin el modelo de disregulación emocional.',B],
'SmCm22PIR2025_032':['¿Qué diferencia suele observarse entre pánico clínico y ataques aislados no clínicos?',{a:'En el pánico clínico nunca existe estrés previo.',b:'Los ataques aislados implican necesariamente un trastorno.',c:'La población clínica solo presenta ataques esperados.',d:'En el pánico clínico son más intensas y persistentes las interpretaciones catastróficas y la preocupación posterior.'},'d','La d es correcta: la diferencia clínica depende especialmente de interpretación, miedo al miedo, recurrencia e interferencia. La a y c son absolutos falsos; y la b confunde una experiencia transdiagnóstica con un diagnóstico.',B],
'SmCm22PIR2025_035':['Respecto a la agorafobia, señale la afirmación INCORRECTA:',{a:'El miedo y la evitación duran típicamente seis meses o más.',b:'El inicio después de los 45 años es poco frecuente.',c:'Su curso suele ser inestable y desaparecer espontáneamente en la adultez.',d:'Es más prevalente en mujeres.'},'c','La c es incorrecta: sin tratamiento el curso suele ser persistente y crónico, con remisión completa poco frecuente. La a corresponde al criterio temporal; la b al patrón de inicio; y la d al predominio femenino.',DSM],
'SmCm23PIR2025 (2)_056':['¿Qué síntoma pertenece al factor cognitivo del pánico?',{a:'Miedo a morir.',b:'Mareo.',c:'Náuseas.',d:'Sudoración.'},'a','La a es correcta: miedo a morir es una cognición catastrófica. Mareo, náuseas y sudoración son manifestaciones somáticas. Se corrige la clave anterior, que señalaba náuseas.',B],
'SmCm23PIR2025 (2)_065':['¿Qué dos dimensiones empleó Barlow para clasificar los ataques de pánico?',{a:'Señalados/no señalados y esperados/inesperados.',b:'Clínicos/no clínicos y leves/graves.',c:'Situacionales/nocturnos y simples/complejos.',d:'Fisiológicos/cognitivos y agudos/crónicos.'},'a','La a es correcta: distingue presencia de señal y expectativa. Las restantes mezclan gravedad, contexto o agrupaciones sintomáticas que no forman esa clasificación bidimensional.',B],
'SmCm23PIR2025_061':['¿Qué teoría NO pertenece estrictamente a las teorías del aprendizaje sobre los trastornos de ansiedad?',{a:'Procesamiento bioinformacional de Lang.',b:'Preparación de Seligman.',c:'Incubación de Eysenck.',d:'Modelo bifactorial de Mowrer.'},'a','La a es correcta: Lang formula una teoría representacional del procesamiento emocional. Seligman amplía el aprendizaje con preparación biológica; Eysenck explica incremento del miedo con exposiciones breves; y Mowrer integra condicionamiento clásico y operante.',B],
'SmCm24PIR2025 (1)_039':['Señale la afirmación correcta sobre fobia específica:',{a:'Suele comenzar exclusivamente después de los 18 años.',b:'Todos los subtipos presentan la misma edad de inicio.',c:'Los niños pequeños siempre verbalizan con precisión su evitación.',d:'En personas mayores son relativamente relevantes los miedos a caídas y a estímulos del entorno natural.'},'d','La d es correcta: en mayores cambian los estímulos y consecuencias temidas. La a es falsa porque suele comenzar en infancia; la b porque los subtipos difieren; y la c porque niños pequeños pueden expresar miedo mediante llanto, bloqueo o aferramiento sin conceptualizar evitación.',DSM],
'SmCm24PIR2025 (1)_050':['¿Qué ejemplo puede clasificarse como fobia específica de “otro tipo”?',{a:'Procedimientos invasivos, siempre clasificados como situacional.',b:'Situaciones que pueden provocar vómito o atragantamiento.',c:'Alturas, tormentas y agua.',d:'Viajar en avión.'},'b','La b es correcta: miedo a vomitar, atragantarse o contraer una enfermedad puede entrar en “otro tipo”. La c corresponde al entorno natural; la d al tipo situacional; y la a suele vincularse a sangre-inyección-daño, no necesariamente a “otro”.',DSM],
'SmCm24PIR2025 (1)_062':['¿Qué patrón evolutivo se describe en ansiedad social?',{a:'Los adolescentes pueden presentar un patrón más amplio de miedo y evitación.',b:'Los adultos jóvenes siempre muestran ansiedad más baja en más situaciones.',c:'Los adultos mayores presentan necesariamente más ansiedad que todos los grupos.',d:'La edad no modifica situaciones temidas ni su expresión.'},'a','La a es correcta: con la adolescencia se amplían demandas sociales y situaciones evaluativas. La b y c usan comparaciones universales no respaldadas; y la d ignora cambios evolutivos y contextuales.',DSM],
'SmCm26PIR2025_088':['¿Cuál NO está establecido como factor de riesgo prospectivo del trastorno de pánico?',{a:'Ansiedad por separación grave en la infancia.',b:'Historia de episodios intensos de miedo o pánico.',c:'Tabaquismo.',d:'Una alteración autonómica concreta suficiente y necesaria para el diagnóstico.'},'d','La d es correcta: no existe una alteración autonómica única, necesaria y suficiente. La a, b y c se han asociado con mayor riesgo; aun así, ninguno determina por sí solo el trastorno.',DSM],
'SmCm26PIR2025_096':['Según la teoría de preparación de Seligman, ¿qué propiedades caracterizan las fobias?',{a:'Equipotencialidad, adquisición lenta, racionalidad y extinción rápida.',b:'Selectividad, adquisición difícil, racionalidad y fácil extinción.',c:'Ausencia de selectividad y dependencia exclusiva del aprendizaje verbal.',d:'Selectividad, fácil adquisición, resistencia a la extinción e irracionalidad.'},'d','La d es correcta: ciertos estímulos están preparados filogenéticamente, se asocian con facilidad, persisten y pueden resultar desproporcionados. Las a, b y c niegan o invierten estas propiedades.',B],
'SmCm26PIR2025_108':['En relación con fobia específica, señale la afirmación FALSA:',{a:'Suele ser más prevalente en mujeres, con menor diferencia sexual en sangre-inyección-daño.',b:'Es uno de los trastornos de ansiedad más prevalentes.',c:'Las fobias iniciadas en la infancia o adolescencia nunca remiten.',d:'Se asocia con mayor riesgo de conducta suicida, especialmente con comorbilidad.'},'c','La c es falsa por el término “nunca”: algunas fobias infantiles remiten, aunque la persistencia aumenta si continúan en adultez. La a y b reflejan epidemiología; y la d describe una asociación que no implica causalidad directa.',DSM],
'SmCm27PIR2025 (1)_004':['Sobre epidemiología y curso de agorafobia, señale la afirmación INCORRECTA:',{a:'Aproximadamente el 30% alcanza remisión completa espontánea en un año.',b:'Muchos casos comienzan en adolescencia tardía o adultez temprana.',c:'Es aproximadamente dos veces más frecuente en mujeres.',d:'El inicio habitual ocurre antes de los 35 años.'},'a','La a es incorrecta: la remisión completa espontánea anual es mucho menor y el curso suele ser persistente. La b, c y d corresponden al patrón epidemiológico y evolutivo descrito.',DSM],
'SmCm27PIR2025 (1)_100':['¿Qué trastorno de ansiedad aparece con frecuencia como diagnóstico secundario junto a otros trastornos de ansiedad?',{a:'Fobia específica.',b:'Mutismo selectivo.',c:'Agorafobia exclusivamente.',d:'Trastorno de ansiedad inducido por sustancias exclusivamente.'},'a','La a es correcta: por su elevada prevalencia y coexistencia, la fobia específica aparece frecuentemente como diagnóstico adicional. La b es infrecuente en adultos; y c y d son falsas por presentar una exclusividad no respaldada.',DSM],
'SmCm27PIR2025 (1)_194':['¿Con qué trastorno se ha descrito una asociación del gen COMT dependiente del sexo, especialmente en mujeres?',{a:'Trastorno de pánico.',b:'Mutismo selectivo.',c:'Fobia específica.',d:'TAG.'},'a','La a es correcta: el DSM-5-TR recoge hallazgos de dimorfismo sexual relacionados con COMT en pánico. La b, c y d no son la asociación concreta solicitada. Este hallazgo no es una prueba diagnóstica.',DSM],
'SmCm28PIR2025_073':['¿Qué afirmación sobre los cambios del DSM-5 en trastornos de ansiedad es INCORRECTA?',{a:'Separó TOC y trastornos relacionados en un capítulo propio.',b:'Mantuvo el TEPT dentro del capítulo de trastornos de ansiedad.',c:'Eliminó el requisito de que el adulto reconozca que su miedo fóbico es excesivo o irracional.',d:'Separó ansiedad por separación y mutismo selectivo del bloque exclusivo de inicio infantil.'},'b','La b es incorrecta: el TEPT pasó a trastornos relacionados con traumas y factores de estrés. La a, c y d son cambios introducidos en DSM-5 y mantenidos en DSM-5-TR.',DSM],
'SmCm28PIR2025_074':['Señale la afirmación FALSA sobre diferencias por sexo/género en trastornos de ansiedad:',{a:'En sangre-inyección-daño la diferencia entre sexos es menor que en otros subtipos fóbicos.',b:'Los ataques de pánico se notifican con mayor frecuencia en mujeres.',c:'En muestras clínicas de ansiedad social siempre hay una mayoría clara de mujeres.',d:'El TAG es más frecuente en mujeres.'},'c','La c es falsa: el predominio femenino poblacional puede atenuarse o invertirse en muestras clínicas por patrones de consulta. La a, b y d reflejan tendencias epidemiológicas generales.',DSM],
'SmCm28PIR2025_078':['Según la caracterización de Belloch, ¿cuál es uno de los síntomas más frecuentes del ataque de pánico?',{a:'Temblores aislados.',b:'Palpitaciones o aceleración cardíaca.',c:'Amnesia del episodio.',d:'Pérdida prolongada de conciencia.'},'b','La b es correcta: palpitaciones y taquicardia figuran entre los síntomas más frecuentes. Los temblores pueden aparecer, pero no son el síntoma destacado; amnesia y pérdida prolongada de conciencia no son características típicas.',B],
'SmCm29PIR2025_052':['¿Qué modelo de ansiedad social integra explicaciones evolucionistas, genéticas, psicológicas y socioculturales y considera adaptativos algunos miedos sociales?',{a:'Rapee y Heimberg.',b:'Botella, Baños y Perpiñá.',c:'Clark y Wells.',d:'Gilbert y Trower.'},'b','La b es correcta: el modelo integrador de Botella y colaboradores combina niveles explicativos y reconoce la función adaptativa de ciertos miedos. Rapee-Heimberg y Clark-Wells son modelos cognitivo-conductuales específicos; Gilbert-Trower enfatiza rango social y evolución, pero no es la formulación integradora solicitada.',B],
'SmCm29PIR2025_078':['¿Cuál es la principal diferencia dimensional entre ansiedad social y personalidad evitativa?',{a:'La personalidad evitativa no se considera en el diagnóstico diferencial.',b:'En personalidad evitativa la evitación es más específica y leve.',c:'En ansiedad social la organización de la personalidad está necesariamente más afectada.',d:'En personalidad evitativa la evitación es más generalizada, estable y afecta a más áreas del funcionamiento.'},'d','La d es correcta: el patrón evitativo de personalidad es más penetrante y organiza múltiples contextos vitales. La a es falsa porque sí forma parte del diagnóstico diferencial; la b invierte la amplitud; y la c atribuye mayor globalidad al TAS.',DSM],
'SmCm30PIR2025 (1)_029':['En el modelo tripartito de Clark y Watson, ¿qué componente es relativamente específico de la depresión?',{a:'Alto afecto negativo.',b:'Bajo afecto positivo o anhedonia.',c:'Hiperactivación fisiológica.',d:'Preocupación verbal.'},'b','La b es correcta: el bajo afecto positivo caracteriza especialmente depresión. El alto afecto negativo es común a ansiedad y depresión; la hiperactivación fisiológica es más específica de ansiedad; y la preocupación verbal no constituye el tercer componente del modelo.','Clark, L. A. y Watson, D. (1991). Tripartite model of anxiety and depression. Journal of Abnormal Psychology, 100(3), 316–336. https://doi.org/10.1037/0021-843X.100.3.316'],
'SmCm3PIR2024_098':['¿Qué afirmación refleja el modelo de autoeficacia aplicado al pánico?',{a:'La expectativa de no poder controlar o afrontar las sensaciones incrementa miedo y evitación.',b:'La preocupación reduce siempre la activación fisiológica.',c:'Las metapreocupaciones constituyen el único mecanismo del pánico.',d:'La intolerancia a la incertidumbre explica por sí sola cada ataque.'},'a','La a es correcta: una baja autoeficacia percibida para manejar sensaciones y situaciones favorece ansiedad anticipatoria y evitación. La b pertenece a explicaciones de preocupación; la c al modelo metacognitivo del TAG; y la d al modelo de Dugas, no al pánico.',B],
'SmCm7PIR2024_061':['¿Qué modelo del pánico integra hiperventilación y condicionamiento interoceptivo, evaluación cognitiva y condicionamiento de señales externas?',{a:'Modelo de hiperventilación de Ley.',b:'Modelo integrativo cognitivo-conductual de Sandín.',c:'Modelo cognitivo de Clark exclusivamente.',d:'Modelo tripartito ansiedad-depresión.'},'b','La b es correcta: Sandín integra mecanismos fisiológicos, aprendizaje interoceptivo y externo y valoración cognitiva. Ley enfatiza hiperventilación; Clark interpretación catastrófica; y el modelo tripartito explica dimensiones de ansiedad y depresión.',B],
'SmCm7PIR2024_064':['En el modelo transdiagnóstico jerárquico de los trastornos emocionales, ¿en qué nivel aparece la reevaluación?',{a:'Nivel 1.',b:'Nivel 2.',c:'Nivel 3.',d:'Nivel 4.'},'c','La c es correcta: reevaluación es una estrategia de regulación emocional situada en el nivel 3. El nivel 1 recoge temperamento general; el 2 vulnerabilidades o procesos intermedios; y el 4 no es la ubicación asignada en este modelo.',B]
};
let n=0;for(const[id,v]of Object.entries(e)){const q=bank.find(x=>x.id===id);if(!q)throw Error('missing '+id);const[en,o,c,x,r]=v;Object.assign(q,{e:en,o,c,x,r,v:'VALIDADA_ORIGINAL'});n++;}if(n!==31)throw Error('expected31 '+n);
const pq=bank.find(x=>x.id==='PERSEV_AGO25_U1_059');if(!pq)throw Error('missing paruresis');Object.assign(pq,{e:'¿Con qué trastorno se asocia típicamente la paruresis o «vejiga tímida»?',o:{a:'Trastorno de pánico.',b:'Fobia específica.',c:'Trastorno de ansiedad por separación.',d:'Trastorno de ansiedad social.'},c:'d',x:'La d es correcta: la dificultad para orinar cuando otras personas están presentes o pueden evaluar se vincula al temor de evaluación negativa de la ansiedad social. La a se centra en ataques de pánico inesperados; la b exige miedo circunscrito a un objeto o situación no explicado mejor por evaluación social; y la c se relaciona con separación de figuras de apego.',r:DSM+', apartado de trastorno de ansiedad social.'});
fs.writeFileSync(p,JSON.stringify(bank)+'\n');console.log({reviewed:n,repairedValidated:1,pending:bank.filter(x=>x.t?.includes(t)&&(!x.v||x.v==='REVISAR')).length,total:bank.length});
