const fs=require('fs');const adultPath='public/banco/tratamientos_adultos.json',clinicalPath='public/banco/clinica_adultos.json',childPath='public/banco/tratamientos_infantiles.json';
const a=JSON.parse(fs.readFileSync(adultPath,'utf8')),clinical=JSON.parse(fs.readFileSync(clinicalPath,'utf8')),child=JSON.parse(fs.readFileSync(childPath,'utf8')),m=new Map(a.map(q=>[q.id,q]));
const dsm='American Psychiatric Association (2022). Manual diagnóstico y estadístico de los trastornos mentales, texto revisado (DSM-5-TR). Editorial Médica Panamericana.';
const fon='Fonseca Pedrero, E. (coord.) (2021). Manual de tratamientos psicológicos: Adultos. Pirámide.';
const bel='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. II (4.ª ed.). McGraw Hill.';
function u(id,z){const q=m.get(id);if(!q)throw Error(id);Object.assign(q,z,{v:'VALIDADA_ORIGINAL'});}
u('4Simulacro02018Comentarios_100',{t:['Trastornos depresivos'],e:'¿Cuál de las siguientes no es una característica diferencial habitual del duelo frente a un episodio depresivo mayor?',o:{a:'La autoestima suele estar conservada.',b:'Pueden experimentarse emociones positivas.',c:'El malestar suele aparecer en oleadas vinculadas a recuerdos de la persona fallecida.',d:'El estado de ánimo deprimido es persistente y no se vincula a pensamientos o recuerdos concretos.'},c:'d',x:'La opción d caracteriza mejor la depresión mayor. En el duelo predominan oleadas de vacío o pérdida relacionadas con recuerdos, puede preservarse la autoestima y pueden aparecer emociones positivas.',r:dsm});
u('4Simulacro02018Comentarios_101',{t:['Trastornos depresivos'],e:'Según la CIE-10, señale la opción incorrecta sobre el episodio depresivo:',o:{a:'Para el trastorno depresivo recurrente deben haberse producido al menos dos episodios.',b:'Entre los síntomas nucleares figuran ánimo deprimido, pérdida de interés y disminución de energía.',c:'La pérdida de confianza y autoestima se distingue del autorreproche o culpa excesiva.',d:'Los cambios de la actividad sexual constituyen un criterio diagnóstico independiente.'},c:'d',x:'La CIE-10 contempla disminución de la libido entre los síntomas somáticos asociados, no como criterio independiente del episodio. Las demás afirmaciones son compatibles con su descripción.',r:'Organización Mundial de la Salud (1992). CIE-10: Trastornos mentales y del comportamiento. Descripciones clínicas y pautas para el diagnóstico.'});
u('4Simulacro02018Comentarios_104',{e:'Clásicamente, ¿qué grupo de antidepresivos se ha considerado especialmente eficaz en la depresión con características atípicas?',o:{a:'Litio.',b:'ISRS.',c:'Inhibidores de la monoaminooxidasa (IMAO).',d:'Antidepresivos tricíclicos.'},c:'c',x:'Los IMAO mostraron una eficacia particular frente a tricíclicos en los estudios clásicos de depresión atípica. En la práctica actual suelen reservarse por sus interacciones, restricciones dietéticas y perfil de seguridad.',r:bel});
u('ABRIL-UNO-24_COMENTADO_071',{e:'Señale la afirmación incorrecta sobre la terapia interpersonal para la depresión de Klerman y Weissman:',o:{a:'Es focalizada y limitada en el tiempo.',b:'Relaciona el estado de ánimo con acontecimientos vitales e interpersonales actuales.',c:'Se presenta como una terapia derivada de una teoría etiológica completa de la depresión.',d:'Parte del diagnóstico y trabaja problemas interpersonales actuales.'},c:'c',x:'La TIP es una intervención empíricamente fundamentada, focal y centrada en problemas interpersonales actuales, pero no pretende derivarse de una teoría etiológica completa de la depresión.',r:fon});
u('AGOSTO2_111',{t:['Tratamientos transdiagnósticos'],e:'En el metaanálisis de Sakiris y Berle (2019) sobre el Protocolo Unificado, ¿en qué resultado se encontró un tamaño del efecto moderado?',o:{a:'Regulación emocional.',b:'Síntomas de ansiedad social.',c:'Síntomas del trastorno límite de la personalidad.',d:'Síntomas de ansiedad generalizada.'},c:'a',x:'La revisión comunicó efectos grandes en diversos síntomas emocionales y efectos moderados en regulación emocional, interferencia y calidad de vida.',r:'Sakiris, N. y Berle, D. (2019). A systematic review and meta-analysis of the Unified Protocol as a transdiagnostic emotion regulation based intervention. Clinical Psychology Review, 72, 101751.'});
u('AGOSTO2_155',{e:'¿En qué fase de la terapia interpersonal y de ritmos sociales se evalúa la historia y se decide el foco y las necesidades del tratamiento?',o:{a:'Fase inicial.',b:'Fase intermedia.',c:'Fase de mantenimiento.',d:'Fase final.'},c:'a',x:'En la fase inicial se revisan historia clínica, ritmos sociales y relaciones interpersonales, se proporciona psicoeducación y se selecciona el área problemática.',r:'Frank, E. (2005). Treating Bipolar Disorder: A Clinician\'s Guide to Interpersonal and Social Rhythm Therapy. Guilford Press.'});
u('DICIEMBRE-DOS-24_COMENTADO_099',{e:'¿Cuál es una intervención para el trastorno bipolar administrada mediante una aplicación para teléfono inteligente?',o:{a:'PRISM.',b:'Beating Bipolar.',c:'ORBIT.',d:'MoodSwings.'},c:'a',x:'PRISM se desarrolló como intervención basada en smartphone. Beating Bipolar, ORBIT y MoodSwings son programas principalmente web.',r:fon});
u('DICIEMBRE-UNO-24_COMENTADO_117',{t:['Psicología de la salud — estrés laboral y burnout'],e:'En la tipología de reacciones al estrés de Grossarth-Maticek y Eysenck, ¿qué caracteriza al tipo 5 o racional-antiemocional?',o:{a:'Predominio de la ambivalencia.',b:'Autonomía propia y ajena como principal fuente de bienestar.',c:'Dependencia conformista e inhibición de la intimidad.',d:'Supresión de la expresión emocional y posible predisposición a depresión y cáncer.'},c:'d',x:'El tipo 5 se define por respuestas racionales y antiemocionales, con supresión o negación afectiva. Los autores lo relacionaron hipotéticamente con depresión y cáncer.',r:bel});
u('DICIEMBRE-UNO-24_COMENTADO_158',{e:'Entre las siguientes opciones, ¿qué fármaco se ha recomendado especialmente cuando el trastorno bipolar presenta ciclos rápidos o características mixtas?',o:{a:'Venlafaxina.',b:'Valproato.',c:'Litio.',d:'Buspirona.'},c:'b',x:'Entre estas alternativas, el valproato es la opción tradicionalmente preferida en ciclación rápida o estados mixtos. Los antidepresivos como venlafaxina pueden favorecer viraje; buspirona no es estabilizador. La elección clínica actual debe individualizarse.',r:'Yatham, L. N. et al. (2018). CANMAT and ISBD 2018 guidelines for the management of patients with bipolar disorder. Bipolar Disorders, 20, 97-170.'});
u('DICIEMBRE-UNO-24_COMENTADO_172',{e:'¿En cuántas fases se estructura la terapia interpersonal para la depresión de Klerman y Weissman?',o:{a:'Tres.',b:'Cuatro.',c:'Cinco.',d:'No se divide en fases.'},c:'a',x:'La TIP se organiza en fase inicial, fase intermedia y fase de terminación. Las áreas problema clásicas son duelo, disputas interpersonales, transiciones de rol y déficits interpersonales.',r:fon});
u('DICIEMBRE-UNO-24_COMENTADO_188',{t:['Tratamientos transdiagnósticos'],e:'¿Para qué población se desarrolló originalmente ESTEEM (Effective Skills to Empower Effective Men)?',o:{a:'Personas con cleptomanía.',b:'Personas con compra compulsiva.',c:'Personas con trastorno explosivo intermitente.',d:'Hombres jóvenes gais y bisexuales con problemas de salud mental y sexual relacionados con el estrés de minoría.'},c:'d',x:'ESTEEM es una TCC afirmativa y transdiagnóstica dirigida a hombres jóvenes gais y bisexuales. Aborda procesos de estrés de minoría vinculados a depresión, ansiedad, consumo y riesgo sexual; no fue creado específicamente para el comportamiento sexual compulsivo.',r:'Pachankis, J. E. et al. (2019). Project ESTEEM protocol. BMC Public Health, 19, 1086.'});
u('JULIO2_145',{e:'¿En qué fase de la terapia interpersonal y de ritmos sociales se trabaja activamente la regularización de ritmos y la resolución del problema interpersonal?',o:{a:'Inicial.',b:'Intermedia.',c:'Mantenimiento.',d:'Terminación.'},c:'b',x:'La fase intermedia aplica estrategias para estabilizar ritmos sociales, manejar síntomas afectivos y resolver el área interpersonal seleccionada.',r:'Frank, E. (2005). Treating Bipolar Disorder: A Clinician\'s Guide to Interpersonal and Social Rhythm Therapy. Guilford Press.'});
u('JULIO2_158',{e:'Entre las siguientes opciones, ¿qué fármaco cuenta con especial eficacia preventiva frente a recaídas depresivas en el mantenimiento del trastorno bipolar I?',o:{a:'Valproato.',b:'Carbamazepina.',c:'Oxcarbazepina.',d:'Lamotrigina.'},c:'d',x:'Lamotrigina es una opción de primera línea para mantenimiento y destaca por su efecto preventivo sobre episodios depresivos. Valproato también puede utilizarse en mantenimiento, pero no es la respuesta más específica a la polaridad depresiva entre estas opciones.',r:'Keramatian, K., Chithra, N. K. y Yatham, L. N. (2023). CANMAT and ISBD Guidelines for the Treatment of Bipolar Disorder: Summary and a 2023 Update of Evidence. Focus, 21(4), 344-353.'});
u('JULIO2_163',{t:['Tratamiento de los trastornos alimentarios'],e:'Señale la afirmación correcta sobre el tratamiento farmacológico de la bulimia nerviosa:',o:{a:'La farmacoterapia aislada dispone de mayor respaldo que la TCC.',b:'El ISRS con mejor respaldo y aprobación específica es la paroxetina.',c:'El litio es el tratamiento farmacológico de elección.',d:'Los anticonvulsivantes no constituyen el tratamiento farmacológico estándar de primera elección.'},c:'d',x:'La TCC es el tratamiento de referencia y la fluoxetina es el fármaco con mayor respaldo y aprobación específica. Litio y anticonvulsivantes no son tratamientos estándar de primera elección.',r:fon});
u('JULIO2_172',{t:['Trastornos depresivos y bipolares infantojuvenil'],e:'¿Cuál es un programa preventivo transdiagnóstico de ansiedad y depresión en población infantil o adolescente?',o:{a:'EMOTION.',b:'MATCH.',c:'BIACA.',d:'IPT-A.'},c:'a',x:'EMOTION es un programa grupal de prevención indicada que integra componentes para ansiedad y depresión. MATCH y BIACA son protocolos de tratamiento modular o adaptativo; IPT-A es terapia interpersonal para depresión adolescente.',r:'Fonseca Pedrero, E. (coord.) (2021). Manual de tratamientos psicológicos: Infancia y adolescencia. Pirámide.'});
u('JULIO2_180',{t:['Trastornos depresivos y bipolares infantojuvenil'],e:'Según NICE (2019), ¿cuál de las siguientes no figura entre las opciones psicológicas recomendadas para niños de 5 a 11 años con depresión moderada-grave?',o:{a:'Terapia familiar.',b:'Psicoterapia psicodinámica de corta duración.',c:'Intervención psicosocial breve como opción específica de primera línea para este grupo.',d:'Terapia interpersonal de base familiar.'},c:'c',x:'NICE contempla terapia familiar, IPT de base familiar, psicoterapia psicodinámica e individual CBT según circunstancias. La intervención psicosocial breve no aparece como opción específica de primera línea para 5-11 años en esta recomendación.',r:'National Institute for Health and Care Excellence (2019). Depression in children and young people: identification and management (NG134).'});
u('JUNIO-UNO-24_COMENTADO_149',{e:'¿Cuál de las siguientes es una intervención terapéutica para la depresión posparto, en lugar de un programa preventivo?',o:{a:'ROSE.',b:'Psicoterapia diádica madre-bebé.',c:'Be a Mom.',d:'Curso Mamás y Bebés.'},c:'b',x:'La psicoterapia diádica se utiliza para tratar la depresión posparto y la relación madre-bebé. ROSE, Be a Mom y Mamás y Bebés se han desarrollado principalmente como programas preventivos.',r:fon});
u('JUNIO-UNO-24_COMENTADO_158',{t:['Tratamientos transdiagnósticos'],e:'El protocolo EmotionRegulation de González-Robles y colaboradores:',o:{a:'Se basa principalmente en Super Skills for Life.',b:'Fue diseñado para adolescentes mayores de 14 años en atención primaria.',c:'Fue diseñado exclusivamente para adolescentes por internet.',d:'Es una intervención transdiagnóstica por internet para población adulta.'},c:'d',x:'EmotionRegulation es un protocolo transdiagnóstico online para adultos, basado en gran medida en el Protocolo Unificado y con componentes específicos de regulación emocional. La clave original a era incorrecta.',r:bel});
u('JUNIO-UNO-24_COMENTADO_167',{t:['Tratamiento del TOC y relacionados'],e:'¿Para qué trastorno se emplea especialmente la inversión del hábito de Azrin y Nunn?',o:{a:'Ansiedad por la enfermedad.',b:'Trastorno dismórfico corporal.',c:'Tricotilomanía.',d:'Piromanía.'},c:'c',x:'La inversión del hábito, con entrenamiento en conciencia y respuesta incompatible, es una intervención de referencia para tricotilomanía y otros comportamientos repetitivos centrados en el cuerpo.',r:bel});
u('JUNIO-UNO-24_COMENTADO_181',{t:['Tratamiento de los trastornos de personalidad'],e:'¿En qué grupo diagnóstico se ha utilizado el programa STEPPS?',o:{a:'Trastornos de ansiedad.',b:'Trastornos depresivos.',c:'Trastornos de personalidad, especialmente el trastorno límite.',d:'Trastorno obsesivo-compulsivo.'},c:'c',x:'STEPPS es un programa grupal basado en habilidades y sistemas para personas con trastorno límite de la personalidad.',r:fon});

function move(id,source,target){const i=source.findIndex(q=>q.id===id);if(i>=0){const [q]=source.splice(i,1);if(!target.some(x=>x.id===id))target.push(q);}}
move('4Simulacro02018Comentarios_100',a,clinical);move('4Simulacro02018Comentarios_101',a,clinical);
move('JULIO2_172',a,child);move('JULIO2_180',a,child);
fs.writeFileSync(adultPath,JSON.stringify(a));fs.writeFileSync(clinicalPath,JSON.stringify(clinical));fs.writeFileSync(childPath,JSON.stringify(child));
console.log('Auditado bloque 1 de tratamientos del estado de ánimo.');
