const fs=require('fs');const p='public/banco/clinica_adultos.json';const a=JSON.parse(fs.readFileSync(p,'utf8'));const m=new Map(a.map(q=>[q.id,q]));
const dsm='American Psychiatric Association (2022). Manual diagnóstico y estadístico de los trastornos mentales, texto revisado (DSM-5-TR). Editorial Médica Panamericana.';
const dsm5='American Psychiatric Association (2014). Manual diagnóstico y estadístico de los trastornos mentales (DSM-5). Editorial Médica Panamericana, pp. 451-459.';
const bel='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. II (4.ª ed.). McGraw Hill.';
function u(id,z){let q=m.get(id);if(!q&&id==='SmCm27PIR2025 (1)_193')return;if(!q)throw Error(id);Object.assign(q,z,{v:'VALIDADA_ORIGINAL'});}
u('Simu 12 comentado_080',{e:'Las manifestaciones de la disforia de género varían con la edad. Señale la opción incorrecta:',o:{a:'En adolescentes, las manifestaciones varían según el nivel de desarrollo.',b:'Algunos adultos afrontan la incongruencia viviendo parcialmente en el rol deseado o adoptando un rol no binario.',c:'En la mayoría de los niños existe una disforia anatómica intensa.',d:'Algunas niñas pueden negarse a orinar sentadas.'},c:'c',x:'La c es incorrecta: solo una minoría de niños expresa un rechazo anatómico intenso; este suele hacerse más frecuente al aproximarse la pubertad. Las demás manifestaciones están descritas en el DSM-5.',r:dsm5});
u('Simu 6 comentado__065',{e:'¿Qué especificador incluye el DSM-5 para la disforia de género en niños?',o:{a:'Con un trastorno del desarrollo sexual.',b:'Postransición.',c:'Con antecedentes de tics.',d:'Con ideas paranoides.'},c:'a',x:'En niños puede especificarse «con un trastorno del desarrollo sexual». «Postransición» se reserva para adolescentes y adultos.',r:dsm5});
u('SM_ABRIL_1_SOL_1_040',{e:'Según el DSM-5, señale la afirmación correcta sobre la disforia de género:',o:{a:'El único especificador en adolescentes y adultos es postransición.',b:'La duración mínima de la incongruencia es de doce meses.',c:'El género experimentado no puede incluir identidades no binarias.',d:'Los adolescentes y adultos nacidos mujeres con comienzo temprano presentan casi siempre ginefilia.'},c:'d',x:'El DSM-5 describe ginefilia frecuente en este grupo. La duración mínima es seis meses, admite identidades alternativas y en adolescentes/adultos también existe el especificador relativo al trastorno del desarrollo sexual.',r:dsm5});
u('SM_ABRIL_1_SOL_1_052',{t:['Trastornos por síntomas somáticos y relacionados'],e:'Señale la afirmación correcta sobre la disforia por la integridad corporal:',o:{a:'En algunos estudios, quienes consiguieron la discapacidad deseada comunicaron mejor calidad de vida que quienes no la consiguieron.',b:'Predomina en hombres homosexuales.',c:'Se explica habitualmente por delirios o alucinaciones somáticas.',d:'El deseo suele afectar al lado dominante.'},c:'a',x:'Se ha descrito una mejor calidad de vida autoinformada en algunos sujetos que alcanzaron la discapacidad deseada, sin que ello implique una recomendación terapéutica. No se explica por psicosis; en las muestras predominaban hombres heterosexuales y el lado no dominante.',r:'Organización Mundial de la Salud (2024). CIE-11, 6C21 Disforia por la integridad corporal; '+bel});
u('SM_AGOSTO_1_SOL_1_056',{e:'Señale la afirmación correcta sobre el curso de la disforia de género sin trastorno del desarrollo sexual descrito en el DSM-5:',o:{a:'La persistencia es mayor en nacidos hombres.',b:'En nacidos hombres con comienzo tardío puede haber más fluctuación y ambivalencia ante la cirugía.',c:'En nacidas mujeres predomina el comienzo tardío.',d:'En nacidas mujeres con comienzo temprano predomina la androfilia.'},c:'b',x:'El comienzo tardío en nacidos hombres se asociaba a mayor fluctuación y ambivalencia. La persistencia y el comienzo temprano eran más frecuentes en nacidas mujeres; en estas, el comienzo temprano se asociaba a ginefilia.',r:dsm5});
u('SM_DICIEMBRE_1_SOL_1_045',{e:'Señale la respuesta correcta sobre factores asociados a la disforia de género según el DSM-5:',o:{a:'En nacidos hombres se describió una mayor frecuencia de hermanos mayores varones.',b:'El travestismo fetichista y la autoginefilia se asocian especialmente al comienzo temprano.',c:'Se observaron andrógenos elevados en sujetos 46,XY.',d:'En sujetos 46,XY con trastorno del desarrollo sexual predominaba el cambio de hombre a mujer.'},c:'a',x:'El DSM-5 describía mayor frecuencia de hermanos mayores varones. El patrón travestista/autoginefílico se vinculaba al comienzo tardío; no se hallaron alteraciones hormonales sistémicas en 46,XY y el sentido de la tasa indicada en d está invertido.',r:dsm5});
u('SM_DICIEMBRE_2_SOL_1_047',{e:'Indique la afirmación correcta sobre la disforia de género:',o:{a:'En nacidos hombres, el comienzo tardío puede asociarse con mayor ambivalencia y menor satisfacción ante la cirugía.',b:'Postransición es aplicable también en niños.',c:'La persistencia se correlaciona muy intensamente con la gravedad infantil basal.',d:'Las intervenciones afirmativas están contraindicadas por ser estigmatizantes.'},c:'a',x:'La a recoge la descripción de curso del DSM-5. Postransición se aplica a adolescentes/adultos; la correlación con gravedad basal era modesta y los enfoques afirmativos buscan reducir estigma y favorecer la adaptación.',r:dsm5});
u('SM_ENERO_1_SOL_1_096',{e:'Señale la opción correcta sobre el curso de la disforia de género descrito en el DSM-5:',o:{a:'En adultos, la proporción favorecía a nacidas mujeres salvo en Japón y Polonia.',b:'Los nacidos hombres de comienzo temprano solían buscar tratamiento a edades más tempranas que los de comienzo tardío.',c:'En nacidas mujeres predominaba el comienzo tardío.',d:'La disforia anatómica era más central en niños que en adolescentes y adultos.'},c:'b',x:'El comienzo temprano se asociaba a una búsqueda más precoz de tratamiento. En general la proporción adulta favorecía a nacidos hombres, salvo Japón y Polonia; en nacidas mujeres predominaba el comienzo temprano y la disforia anatómica aumentaba con la pubertad.',r:dsm5});
u('SM_JULIO_1_SOL_1_023',{e:'Según el DSM-5, señale la alternativa incorrecta sobre el desarrollo y curso de la disforia de género:',o:{a:'La persistencia infantil en nacidos varones se situaba entre el 2,2 % y el 30 %.',b:'La persistencia infantil en nacidas mujeres se situaba entre el 12 % y el 50 %.',c:'En el comienzo temprano puede existir un periodo sin disforia seguido de recurrencia.',d:'Los nacidos varones con comienzo temprano sienten atracción casi siempre por mujeres.'},c:'d',x:'La d es incorrecta: el DSM-5 asociaba el comienzo temprano en nacidos varones con androfilia. Las otras opciones reproducen los datos y la descripción de curso del manual.',r:dsm5});
u('SM_JULIO_2_SOL_1_024',{t:['Trastornos parafílicos'],e:'Para diagnosticar trastorno pedofílico según el DSM-5, ¿qué requisito de edad debe cumplirse?',o:{a:'Estar al final de la adolescencia y mantener una relación con una persona de 12 o 13 años.',b:'Tener al menos 18 años y ser cinco años mayor que el menor.',c:'Tener al menos 16 años y ser cinco años mayor que el menor.',d:'Tener cualquier edad si las fantasías duran tres meses.'},c:'c',x:'El individuo debe tener al menos 16 años y ser al menos cinco años mayor que el niño. La nota excluye la relación continuada de un adolescente tardío con una persona de 12 o 13 años; la duración exigida es seis meses.',r:dsm});
u('SM_JULIO_2_SOL_1_047',{e:'Respecto a los especificadores de disforia de género del DSM-5, indique la afirmación correcta:',o:{a:'Postransición puede especificarse en niños.',b:'En adolescentes y adultos no puede coexistir un trastorno del desarrollo sexual.',c:'Postransición puede especificarse en adolescentes y adultos.',d:'En niños no puede coexistir un trastorno del desarrollo sexual.'},c:'c',x:'Postransición se reserva para adolescentes y adultos. En ambos grupos de edad puede coexistir un trastorno del desarrollo sexual y especificarse como tal.',r:dsm5});
u('SM_JUNIO_1_SOL_1_036',{t:['Trastornos parafílicos'],e:'Señale la afirmación incorrecta sobre el trastorno de travestismo:',o:{a:'Es un trastorno frecuente en ambos sexos.',b:'La excitación asociada al travestismo puede disminuir con la edad y transformarse en sensación de confort.',c:'No implica necesariamente incongruencia de género ni deseo de pertenecer a otro género.',d:'Puede asociarse a otras parafilias, como fetichismo o masoquismo.'},c:'a',x:'La a es incorrecta: el diagnóstico es infrecuente y se comunica casi exclusivamente en varones. El travestismo no equivale a disforia de género y puede coexistir con otras parafilias.',r:dsm});
u('SM_MAYO_1_SOL_1_102',{e:'Señale la afirmación correcta sobre la disforia de género según el DSM-5:',o:{a:'Aunque la proporción adulta general favorecía a nacidos varones, en Japón y Polonia favorecía a nacidas mujeres.',b:'En nacidas mujeres, la prevalencia oscilaba entre 0,005 % y 0,014 %.',c:'En nacidos hombres se describía mayor frecuencia de hermanas mayores.',d:'Antes de la transición existía menor riesgo suicida que en la población general.'},c:'a',x:'La excepción de Japón y Polonia figura en el DSM-5. La prevalencia de nacidas mujeres se estimaba en 0,002-0,003 %; se describían hermanos mayores varones y un riesgo suicida aumentado.',r:dsm5});
u('SmCm06PIR2025_045',{e:'¿Qué especificador incluye el DSM-5 para la disforia de género en niños?',o:{a:'Con un trastorno del desarrollo sexual.',b:'Postransición.',c:'Con antecedentes de tics.',d:'Con ideas paranoides.'},c:'a',x:'El especificador infantil es «con un trastorno del desarrollo sexual». La clave original c y la justificación sobre piromanía eran contaminaciones de otra pregunta.',r:dsm5});
u('SmCm12PIR2024 2_044',{t:['Trastornos parafílicos'],e:'¿En qué edición del DSM dejó de clasificarse la homosexualidad como trastorno en sí misma?',o:{a:'DSM-II.',b:'DSM-III.',c:'DSM-III-R.',d:'DSM-IV.'},c:'b',x:'El DSM-III (1980) ya no incluyó la homosexualidad como diagnóstico por sí misma, aunque mantuvo la homosexualidad egodistónica; esta categoría residual se eliminó en el DSM-III-R.',r:'American Psychiatric Association (1980). Diagnostic and Statistical Manual of Mental Disorders (3rd ed.).'});
u('SmCm12PIR2024 2_046',{e:'Las manifestaciones de la disforia de género varían con la edad. Señale la opción incorrecta:',o:{a:'En adolescentes varían según el nivel de desarrollo.',b:'Algunos adultos viven parcialmente en el rol deseado o adoptan un rol no binario.',c:'En la mayoría de los niños existe una disforia anatómica intensa.',d:'Algunas niñas se niegan a orinar sentadas.'},c:'c',x:'La disforia anatómica intensa no aparece en la mayoría de los niños; se hace más frecuente al aproximarse la pubertad. Las demás son manifestaciones descritas.',r:dsm5});
u('SmCm16PIR2025_083',{e:'Con respecto a la disforia de género descrita en el DSM-5, señale la opción correcta:',o:{a:'En nacidas mujeres, el curso más común era el comienzo temprano.',b:'La disforia anatómica era más frecuente en la primera infancia que después de la pubertad.',c:'El riesgo suicida desaparecía tras la transición.',d:'En nacidos hombres era más frecuente tener hermanas mayores.'},c:'a',x:'El DSM-5 describía el comienzo temprano como más habitual en nacidas mujeres. La disforia anatómica aumenta con la pubertad, el riesgo puede persistir y el dato familiar se refería a hermanos mayores varones.',r:dsm5});
u('SmCm16PIR2025_085',{t:['Trastornos neurocognitivos'],e:'¿Cuál de las siguientes enfermedades no produce típicamente una demencia cortical?',o:{a:'Enfermedad de Alzheimer.',b:'Enfermedad de Pick o degeneración frontotemporal.',c:'Enfermedad de Parkinson.',d:'Enfermedad de Creutzfeldt-Jakob.'},c:'c',x:'La demencia asociada a Parkinson se ha clasificado clásicamente como subcortical. Alzheimer, Pick y Creutzfeldt-Jakob producen patrones predominantemente corticales, aunque la distinción cortical-subcortical es una simplificación clínica.',r:bel});
u('SmCm17PIR2025_117',{e:'Señale la afirmación incorrecta sobre la disforia de género descrita en el DSM-5:',o:{a:'El género experimentado puede incluir identidades no binarias.',b:'En el comienzo tardío pueden aparecer travestismo con autoginefilia y problemas psicosociales.',c:'En sujetos 46,XY no se hallaron alteraciones sistémicas de hormonas sexuales y en algunos 46,XX se describieron andrógenos elevados.',d:'En sujetos 46,XY con trastorno del desarrollo sexual era menor la tasa de disforia y transición de mujer a hombre que la de hombre a mujer.'},c:'d',x:'La d invierte el dato del DSM-5: en ese grupo se describía una tasa mayor de disforia y transición de mujer a hombre. Las otras afirmaciones recogen el manual.',r:dsm5});
u('SmCm22PIR2025 (1)_056',{e:'Entre los cambios introducidos por el DSM-5 respecto a la disforia de género, señale la opción incorrecta:',o:{a:'Se ubicó en un capítulo propio.',b:'Se estableció una duración mínima de seis meses.',c:'Se sustituyó la denominación «trastorno de identidad sexual» por «disforia de género».',d:'La clave diagnóstica pasó a ser el deseo de cambiar de género, aunque no exista malestar ni deterioro.'},c:'d',x:'La d es incorrecta: el diagnóstico requiere malestar clínicamente significativo o deterioro asociado a la incongruencia. Los otros tres fueron cambios estructurales y terminológicos del DSM-5.',r:dsm5});
u('SmCm22PIR2025_046',{t:['Trastornos disruptivos del control de los impulsos y de la conducta'],e:'Según la CIE-11, ¿cuál de las siguientes afirmaciones de clasificación es correcta?',o:{a:'El juego de apuestas y el uso de videojuegos se clasifican como trastornos del control de los impulsos.',b:'Los comportamientos repetitivos centrados en el cuerpo se clasifican como trastornos del control de los impulsos.',c:'Piromanía, cleptomanía, trastorno explosivo intermitente y comportamiento sexual compulsivo se incluyen entre los trastornos del control de los impulsos.',d:'El trastorno antisocial, el trastorno de conducta y el negativista desafiante se incluyen entre los trastornos del control de los impulsos.'},c:'c',x:'La CIE-11 sitúa piromanía, cleptomanía, trastorno explosivo intermitente y comportamiento sexual compulsivo en el grupo de control de impulsos. Juego y videojuegos son conductas adictivas; los comportamientos centrados en el cuerpo se agrupan con TOC y relacionados.',r:'Organización Mundial de la Salud (2024). CIE-11, capítulo 6.'});
u('SmCm22PIR2025_048',{t:['Trastornos adictivos y relacionados con sustancias'],e:'¿Qué fenómenos pueden observarse tanto en adicciones a sustancias como en determinadas adicciones conductuales?',o:{a:'Dependencia psicológica y tolerancia, pero nunca abstinencia.',b:'Dependencia psicológica, tolerancia y abstinencia.',c:'Tolerancia y abstinencia, pero no dependencia psicológica.',d:'Dependencia psicológica y abstinencia, pero nunca tolerancia.'},c:'b',x:'En determinadas conductas adictivas pueden aparecer pérdida de control o dependencia psicológica, tolerancia y síntomas de abstinencia, aunque su expresión no es idéntica a la de las sustancias.',r:bel});
u('SmCm22PIR2025_051',{t:['Trastornos parafílicos'],e:'En el DSM-5, ¿qué duración mínima se exige para el patrón de fantasías, impulsos o conductas de los trastornos parafílicos especificados?',o:{a:'Un mes.',b:'Tres meses.',c:'Seis meses.',d:'Doce meses.'},c:'c',x:'Los criterios A de los trastornos parafílicos especificados establecen una duración mínima de seis meses.',r:dsm});
u('SmCm23PIR2025 (2)_067',{t:['Trastornos depresivos'],e:'¿En qué grupo de modelos explicativos de la depresión se encuadra la teoría reformulada de la indefensión aprendida de Abramson, Seligman y Teasdale?',o:{a:'Modelos puramente conductuales.',b:'Teorías del procesamiento de la información.',c:'Teorías cognitivo-sociales.',d:'Modelos psicodinámicos.'},c:'c',x:'La reformulación atribucional de la indefensión aprendida integra cogniciones, atribuciones y contexto social, por lo que se clasifica entre las teorías cognitivo-sociales.',r:bel});
u('SmCm23PIR2025 (2)_069',{t:['Trastornos de la conducta alimentaria'],e:'¿Cuál de los siguientes fue incorporado por el DSM-5 como diagnóstico independiente?',o:{a:'Trastorno por atracones.',b:'Pica.',c:'Trastorno de rumiación.',d:'Bulimia nerviosa.'},c:'a',x:'El trastorno por atracones pasó de figurar en el apéndice de investigación del DSM-IV a ser un diagnóstico independiente en el DSM-5. Los otros diagnósticos ya existían.',r:dsm});
u('SmCm23PIR2025 (2)_070',{e:'Una persona con disforia de género vive plenamente en el género deseado, recibe tratamiento hormonal y espera una intervención quirúrgica. ¿Qué especificador del DSM-5 corresponde?',o:{a:'No puede codificarse.',b:'Atípica.',c:'No especificada.',d:'Postransición.'},c:'d',x:'Postransición se aplica cuando la persona vive a tiempo completo en el género deseado y ha recibido o se prepara para recibir al menos una intervención médica de afirmación de género.',r:dsm5});
u('SmCm27PIR2025 (1)_119',{e:'Señale la opción incorrecta sobre la disforia de género según el DSM-5:',o:{a:'Las estimaciones de prevalencia adulta eran mayores en nacidos varones que en nacidas mujeres.',b:'Los trastornos del desarrollo sexual conducen en la mayoría de los casos a disforia de género.',c:'La estigmatización y discriminación pueden asociarse a problemas de salud mental y acceso a servicios.',d:'Existen conceptos culturalmente relacionados en sociedades con categorías de género institucionalizadas distintas de hombre y mujer.'},c:'b',x:'La b es incorrecta: aunque puede existir conducta de género atípica, la mayoría de las personas con trastornos del desarrollo sexual no desarrolla disforia de género. Las demás afirmaciones están documentadas.',r:dsm5});
u('SmCm27PIR2025 (1)_193',{t:['Trastornos de la comunicación'],e:'¿Cuál de las siguientes afirmaciones sobre el trastorno del lenguaje es falsa?',o:{a:'A partir de los cuatro años suele aumentar la estabilidad de las diferencias individuales en capacidad lingüística.',b:'Las dificultades exclusivamente expresivas suelen tener peor pronóstico que las dificultades receptivas.',c:'Los síntomas comienzan durante las primeras fases del desarrollo.',d:'Puede afectar al vocabulario, la estructura gramatical y el discurso.'},c:'b',x:'La b es falsa: las dificultades receptivas suelen asociarse a peor pronóstico que las exclusivamente expresivas. Las restantes describen características del trastorno del lenguaje.',r:dsm});
u('SmCm29PIR2025_092',{t:['Trastornos de ansiedad'],e:'¿Cuál de los siguientes no es un criterio del trastorno de ansiedad por separación?',o:{a:'Preocupación excesiva por perder a las figuras de apego.',b:'Quejas repetidas de síntomas físicos cuando se anticipa la separación.',c:'Incapacidad para iniciar interacciones sociales o responder apropiadamente, con respuestas inhibidas o hipervigilantes.',d:'Resistencia persistente a salir de casa o acudir a la escuela por miedo a la separación.'},c:'c',x:'La c corresponde al trastorno reactivo del apego, no a la ansiedad por separación. Se sustituyó el distractor original sobre cociente intelectual porque también era obviamente ajeno y dejaba dos respuestas correctas.',r:dsm});
u('SmCm29PIR2025_094',{t:['Trastornos depresivos'],e:'¿Cuál de las siguientes afirmaciones sobre el trastorno de desregulación disruptiva del estado de ánimo es correcta?',o:{a:'En menores de seis años los síntomas deben aparecer casi a diario.',b:'Los accesos de cólera ocurren, en promedio, tres o más veces por semana.',c:'Puede diagnosticarse simultáneamente con un episodio maníaco.',d:'El primer diagnóstico puede hacerse hasta los 18 años.'},c:'b',x:'Se requieren accesos de cólera tres o más veces por semana. No se diagnostica por primera vez antes de los 6 ni después de los 18 años, y nunca ha debido existir un episodio maníaco o hipomaníaco de duración completa.',r:dsm});
u('SmCm3PIR2024_152',{e:'El uso de estrógenos o antiandrógenos en algunas personas con disforia de género suele producir:',o:{a:'Un aumento generalizado de la ansiedad.',b:'Un empeoramiento habitual del estado de ánimo y la calidad de vida.',c:'Una mayor aversión hacia los genitales.',d:'Una reducción de la libido, aunque la vivencia sexual puede mejorar en algunas personas.'},c:'d',x:'La supresión androgénica y los estrógenos suelen reducir el deseo sexual y las erecciones espontáneas. No obstante, la disminución de la disforia y una mejor congruencia corporal pueden mejorar el interés o la satisfacción sexual en algunas personas.',r:'Coleman, E. et al. (2022). Standards of Care for the Health of Transgender and Gender Diverse People, Version 8. International Journal of Transgender Health, 23(S1), S1-S259.'});
u('PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-UNO-23_077',{e:'Señale la alternativa incorrecta sobre la disforia de género descrita en el DSM-5:',o:{a:'En Japón y Polonia, las proporciones clínicas citadas favorecían a nacidas mujeres.',b:'La persistencia infantil descrita era mayor en nacidas mujeres que en nacidos hombres.',c:'La persistencia se correlacionaba modestamente con la gravedad medida en la infancia.',d:'La aceptación cultural de la diversidad de género elimina necesariamente el malestar clínicamente significativo.'},c:'d',x:'La d es incorrecta: un contexto menos estigmatizante puede reducir el sufrimiento social, pero no permite afirmar que elimine necesariamente toda disforia. Las otras opciones recogen datos del DSM-5.',r:dsm5});

// El trastorno del lenguaje pertenece al banco de clínica infantojuvenil, no al de adultos.
const infantPath='public/banco/clinica_infantojuvenil.json';
const infant=JSON.parse(fs.readFileSync(infantPath,'utf8'));
const moveId='SmCm27PIR2025 (1)_193';
const moveIndex=a.findIndex(q=>q.id===moveId);
if(moveIndex>=0){const [q]=a.splice(moveIndex,1);if(!infant.some(x=>x.id===moveId))infant.push(q);}
// Conservamos la versión más reciente de dos pares que eran duplicados reales.
for(const duplicateId of ['Simu 12 comentado_080','Simu 6 comentado__065']){
  const i=a.findIndex(q=>q.id===duplicateId);if(i>=0)a.splice(i,1);
}
fs.writeFileSync(p,JSON.stringify(a));
fs.writeFileSync(infantPath,JSON.stringify(infant));
console.log('Auditadas las 32 preguntas finales de disforia de género.');
