import fs from 'node:fs';import path from 'node:path';import{fileURLToPath}from'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),bank=path.join(root,'public','banco');
const m=JSON.parse(fs.readFileSync(path.join(bank,'manifest.json'),'utf8'));const ds=new Map(Object.entries(m.subjects).map(([s,v])=>[s,JSON.parse(fs.readFileSync(path.join(bank,v.slug+'.json'),'utf8'))]));const ta=ds.get('Tratamientos Adultos');
const F='Fonseca-Pedrero, E. (coord.) (2019). Tratamientos psicológicos para la psicosis. Pirámide.';
const updates={
'SmCm12PIR2024 2_110':{e:'NAVIGATE es un tratamiento integral y multidisciplinar para primeros episodios psicóticos. Señale la afirmación que NO describe correctamente el programa:',o:{a:'Se desarrolló en el proyecto RAISE, impulsado por el National Institute of Mental Health.',b:'Requiere coordinación del equipo y reuniones semanales para mantener un enfoque compartido.',c:'Consta únicamente de tres componentes: manejo farmacológico, psicoeducación individual y apoyo educativo-laboral.',d:'Su beneficio tiende a ser mayor cuanto menor es la duración de la psicosis no tratada.'},c:'c',x:'La opción c es la que NO describe correctamente NAVIGATE: el programa no se limita a esos tres elementos; integra cuatro componentes principales, incluido el tratamiento individual centrado en la resiliencia, además del manejo farmacológico, la intervención familiar y el apoyo educativo y laboral. La a es correcta porque NAVIGATE forma parte de RAISE. La b es correcta porque la coordinación y las reuniones del equipo son esenciales. La d es correcta porque los mejores resultados se han asociado con una menor duración de la psicosis no tratada.',r:'Mueser, K. T. et al. (2015). The NAVIGATE program for first-episode psychosis. Psychiatric Services, 66(7), 680–690. https://doi.org/10.1176/appi.ps.201400413.'},
'SmCm13PIR2025_135':{e:'¿Qué módulos incluye la intervención cognitivo-conductual específica desarrollada en la clínica PACE para personas con alto riesgo de psicosis?',o:{a:'Manejo del estrés; síntomas positivos; síntomas negativos y depresión; y comorbilidad.',b:'Valoración y compromiso; terapia; y terminación.',c:'Normalización; autoobservación; y prueba de realidad como tres módulos independientes.',d:'Psicoeducación parental; manejo de conductas; y manejo de emociones.'},c:'a',x:'La opción a es correcta: la intervención PACE organiza el trabajo en manejo del estrés, síntomas positivos, síntomas negativos o depresión y problemas comórbidos. La b describe fases generales de un proceso terapéutico, no sus módulos clínicos. La c enumera técnicas que pueden emplearse dentro del abordaje de síntomas positivos, pero no constituye la estructura modular completa. La d corresponde a intervenciones familiares o parentales y no al protocolo PACE preguntado.',r:'Yung, A. R. et al. (2003). A randomised controlled trial of interventions for young people at ultra high risk of psychosis. Schizophrenia Research, 60(1), 21–32. https://doi.org/10.1016/S0920-9964(02)00367-6; '+F},
'SmCm15PIR2025_119':{e:'La TCC de van der Gaag para estados mentales de alto riesgo se basa en el modelo de French y Morrison y añade dos componentes específicos. ¿Cuáles son?',o:{a:'Rehabilitación cognitiva y manejo farmacológico.',b:'Psicoeducación sobre la dopamina y entrenamiento sobre sesgos cognitivos.',c:'Entrenamiento en habilidades sociales y mindfulness.',d:'Foro entre iguales y prevención de recaídas.'},c:'b',x:'La opción b es correcta: el protocolo añade psicoeducación sobre la relación entre dopamina y experiencias psicóticas y trabajo explícito sobre sesgos cognitivos. La a es falsa porque no define esas dos adiciones específicas. La c combina procedimientos que no constituyen los componentes añadidos por este protocolo. La d pertenece a intervenciones digitales o de mantenimiento, no a la TCC de van der Gaag.',r:'van der Gaag, M. et al. (2012). Cognitive behavioral therapy for subjects at ultrahigh risk for developing psychosis. Schizophrenia Bulletin, 38(6), 1180–1188. https://doi.org/10.1093/schbul/sbs105.'},
'SmCm19PIR2024_033':{e:'¿Qué programa multimodal se caracteriza por ofrecer un tratamiento integral y flexible a jóvenes con un primer episodio psicótico o en situación de alto riesgo?',o:{a:'McLean OnTrack.',b:'Programa 2000.',c:'MOVE.',d:'NAVIGATE.'},c:'b',x:'La opción b es correcta: el Programa 2000 se diseñó como una atención integral, flexible, comunitaria y prolongada para jóvenes con primeros episodios o riesgo de psicosis. La a es otro servicio de intervención temprana, pero no el programa descrito en la fuente de la pregunta. La c se orienta principalmente a motivación y participación en personas con esquizofrenia. La d es un paquete coordinado para primeros episodios dentro de RAISE, con componentes definidos, pero no la denominación correspondiente a esta descripción.',r:F+' Apartado sobre tratamientos integrados multimodales.'}}
for(const[id,u]of Object.entries(updates)){const q=ta.find(x=>x.id===id);if(!q)throw Error(id);Object.assign(q,u,{v:'VALIDADA_ORIGINAL'});}
const moves={'Simu 32 comentado hardcore 2_168':['Tratamientos Infantiles','Trastornos de conducta infantojuvenil'],'SM_ABRIL_1_SOL_1_188':['Clínica Adultos','Trastornos del espectro de la esquizofrenia'],'SM_ABRIL_2_SOL_1_169':['Clínica Adultos','Trastornos del espectro de la esquizofrenia'],'SM_DICIEMBRE_1_SOL_1_132':['Clínica Adultos','Trastornos del espectro de la esquizofrenia']};
for(const[id,[s,t]]of Object.entries(moves)){const i=ta.findIndex(q=>q.id===id);if(i<0)throw Error(id);const[q]=ta.splice(i,1);ds.get(s).push({...q,s,t:[t],v:'REVISAR'});}
const all=[...ds.values()].flat();if(all.length!==m.total||new Set(all.map(q=>q.id)).size!==all.length)throw Error('integridad');for(const[s,d]of ds){m.subjects[s].count=d.length;fs.writeFileSync(path.join(bank,m.subjects[s].slug+'.json'),JSON.stringify(d)+'\n');}fs.writeFileSync(path.join(bank,'manifest.json'),JSON.stringify(m,null,2)+'\n');console.log(JSON.stringify({validated:4,rehomed:4,total:all.length},null,2));
