const fs=require('fs');
const ap='public/banco/tratamientos_adultos.json',cp='public/banco/tratamientos_infantiles.json';
const a=JSON.parse(fs.readFileSync(ap,'utf8')),child=JSON.parse(fs.readFileSync(cp,'utf8')),m=new Map(a.map(q=>[q.id,q]));
const F='Fonseca Pedrero, E. (coord.) (2021). Manual de tratamientos psicológicos: Adultos. Pirámide.';
const B='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. II (4.ª ed.). McGraw Hill.';
function set(id,z){const q=m.get(id);if(!q)throw Error(id);Object.assign(q,z,{v:'VALIDADA_ORIGINAL'});}
function move(id,target,topic){const i=a.findIndex(q=>q.id===id);if(i<0)throw Error('move '+id);const[q]=a.splice(i,1);q.t=[topic];q.v='REVISAR';if(!target.some(x=>x.id===id))target.push(q);}
for(const [id,topic] of [
 ['Simu 8 comentado _201','Técnicas psicológicas generales'],['simu 9 comentado_055','Tratamiento de la psicosis y esquizofrenia'],
 ['SM_ABRIL_1_SOL_1_101','Tratamiento de las adicciones'],['SM_DICIEMBRE_2_SOL_1_208','Tratamiento de los trastornos de personalidad'],
 ['SM_ENERO_1_SOL_1_163','Tratamiento de las disfunciones sexuales'],['SM_JUNIO_1_SOL_1_102','Tratamiento de los trastornos de personalidad'],
 ['SM_JUNIO_1_SOL_1_175','Tratamientos transdiagnósticos'],['SM_JUNIO_2_SOL_1_125','Introducción'],
 ['SmCm08PIR2025_074','Componentes y eficacia de la psicoterapia'],['SmCm10PIR2025_007','Tratamiento de los trastornos de ansiedad'],
 ['SmCm10PIR2025_105','Técnicas psicológicas generales'],['SmCm14PIR2025_121','Tratamiento de la psicosis y esquizofrenia']
])move(id,a,topic);
move('SM_JULIO_2_SOL_1_078',child,'Trastornos depresivos y bipolares infantojuvenil');

set('Simu 15 comentado_183',{e:'¿Qué limitación se ha señalado para la psicoeducación en el trastorno bipolar?',o:{a:'Su efecto puede ser menor en personas con numerosos episodios previos o enfermedad muy evolucionada.',b:'Solo funciona si se administra individualmente.',c:'No puede mejorar la adherencia farmacológica.',d:'Produce necesariamente un aumento del estigma.'},c:'a',x:'La psicoeducación puede perder capacidad preventiva cuando se inicia tras muchos episodios, lo que apoya ofrecerla tempranamente. Puede aplicarse individual o grupalmente y suele mejorar conocimiento y adherencia.',r:F});
set('Simu 6 comentado__171',{e:'¿Qué característica corresponde a la terapia interpersonal para la depresión?',o:{a:'Se centra principalmente en pensamientos automáticos, como la terapia cognitiva.',b:'Busca explicar los conflictos actuales reconstruyendo exclusivamente la infancia.',c:'Pretende modificar directamente la estructura básica de personalidad.',d:'Utiliza un modelo médico de la depresión y relaciona los síntomas con problemas interpersonales actuales.'},c:'d',x:'La TIP conceptualiza la depresión como una enfermedad tratable y vincula el episodio con el contexto interpersonal presente. No se centra en reestructurar personalidad ni en analizar exclusivamente infancia o cogniciones.',r:F});
set('Simu 7 comentado _185',{e:'Señale la afirmación correcta sobre los tratamientos de la depresión:',o:{a:'Los tricíclicos son preferentes en depresión atípica por encima de los IMAO en los estudios clásicos.',b:'El CBASP de McCullough se desarrolló para personas con depresión crónica.',c:'La terapia cognitiva es obligatoriamente el tratamiento único de elección en todos los casos.',d:'La terapia interpersonal carece todavía de eficacia empírica establecida.'},c:'b',x:'El CBASP se diseñó específicamente para la depresión crónica. La elección terapéutica depende de gravedad, preferencias y antecedentes; la TIP posee respaldo empírico, y los estudios clásicos de depresión atípica favorecieron IMAO frente a tricíclicos.',r:'McCullough, J. P. (2003). Journal of Clinical Psychology, 59, 833-846; '+F});
set('Simu 8 comentado _145',{e:'¿Qué conjunto recoge los componentes principales del Curso para el Afrontamiento de la Depresión de Lewinsohn?',o:{a:'Incremento de actividades agradables, entrenamiento en habilidades sociales y modificación de cogniciones.',b:'Exposición interoceptiva, prevención de respuesta y relajación aplicada.',c:'Interpretación de sueños, asociación libre y análisis de la transferencia.',d:'Mentalización, validación dialéctica y manejo de contingencias.'},c:'a',x:'El CAD es un programa psicoeducativo multicomponente que trabaja actividades agradables, habilidades sociales y cogniciones asociadas a la depresión.',r:F});
set('simu 9 comentado_156',{e:'¿Cuál es la intervención psicológica más difundida y utilizada en el trastorno bipolar?',o:{a:'Psicoeducación.',b:'Terapia interpersonal y de ritmos sociales.',c:'Cuidado sistemático.',d:'Terapia cognitiva basada en mindfulness.'},c:'a',x:'La psicoeducación es una de las intervenciones más extendidas en bipolaridad y constituye un componente de numerosos programas. Favorece conocimiento, adherencia y detección precoz de recaídas.',r:F});
set('simu 9 comentado_159',{e:'¿Qué afirmación describe mejor la selección del tratamiento para la depresión?',o:{a:'La terapia cognitiva es siempre superior a cualquier alternativa.',b:'La activación conductual solo sirve como complemento farmacológico.',c:'La TIP debe utilizarse obligatoriamente en todos los episodios.',d:'Existen varias intervenciones psicológicas eficaces y la elección debe considerar gravedad, necesidades, preferencias y tratamientos previos.'},c:'d',x:'No existe una psicoterapia única obligatoria para toda depresión. TCC, activación conductual, TIP y otras intervenciones estructuradas pueden estar indicadas según características clínicas y preferencias.',r:'National Institute for Health and Care Excellence (2022). Depression in adults: treatment and management (NG222).'});
set('SM_ABRIL_1_SOL_1_175',{e:'Respecto a la terapia interpersonal para la depresión, señale la afirmación correcta:',o:{a:'Es una intervención ilimitada en el tiempo.',b:'Se deriva de una teoría etiológica completa de la depresión.',c:'Las emociones asociadas a un cambio vital importante se trabajan como transición de rol.',d:'Solo se ha adaptado a terapia de pareja, no a otros formatos.'},c:'c',x:'Las transiciones de rol implican cambios vitales que generan tristeza, ira, confusión o impotencia. La TIP es focal y temporalmente delimitada, pragmática y adaptable a diversos formatos.',r:F});
set('SM_ABRIL_1_SOL_1_176',{e:'¿Qué consideración es correcta al elegir un tratamiento para la depresión?',o:{a:'Un déficit aislado determina automáticamente una terapia concreta.',b:'Debe elegirse según la preferencia personal del profesional.',c:'Deben integrarse evidencia, características clínicas, riesgos, preferencias y tratamientos previos.',d:'La mayor parte del cambio aparece necesariamente en la última sesión.'},c:'c',x:'La decisión terapéutica requiere valoración individual y decisión compartida; no puede deducirse de un único déficit ni de las preferencias del profesional.',r:'National Institute for Health and Care Excellence (2022). Depression in adults: treatment and management (NG222).'});
set('SM_DICIEMBRE_1_SOL_1_149',{e:'¿Cuál de las siguientes es una intervención digital administrada principalmente vía web para el trastorno bipolar?',o:{a:'MONARCA.',b:'ORBIT.',c:'PRISM.',d:'SIMPLe.'},c:'b',x:'ORBIT es una intervención web. MONARCA y SIMPLe son aplicaciones móviles y PRISM se desarrolló para teléfonos inteligentes.',r:F});
set('SM_DICIEMBRE_1_SOL_1_151',{e:'¿Qué área de la terapia interpersonal se explora especialmente cuando no se identifican desencadenantes interpersonales próximos de los síntomas depresivos?',o:{a:'Duelo.',b:'Disputas de rol.',c:'Transiciones de rol.',d:'Déficits interpersonales.'},c:'d',x:'Los déficits interpersonales comprenden aislamiento, soledad y pobreza de relaciones y se consideran cuando no aparece una pérdida, disputa o transición cercana que explique el episodio.',r:F});
set('SM_DICIEMBRE_2_SOL_1_137',{e:'¿Cuál NO es un elemento básico de la terapia interpersonal y de ritmos sociales?',o:{a:'Regular las rutinas diarias y los ciclos de sueño-vigilia.',b:'Entrenamiento general en regulación emocional como componente independiente central.',c:'Relacionar el estado de ánimo con acontecimientos interpersonales.',d:'Apoyar hábitos relacionados con la medicación.'},c:'b',x:'La IPSRT integra terapia de ritmos sociales, terapia interpersonal y psicoeducación o apoyo a la adherencia. Un módulo general independiente de regulación emocional no es uno de sus elementos básicos.',r:'Frank, E. (2005). Treating Bipolar Disorder. Guilford Press.'});
set('SM_DICIEMBRE_2_SOL_1_152',{e:'Señale la afirmación correcta sobre la terapia interpersonal para la depresión:',o:{a:'Es focalizada pero no está limitada temporalmente.',b:'Niega la conceptualización médica de la depresión.',c:'Cuenta con una adaptación breve denominada consejo interpersonal.',d:'Las tareas obligatorias entre sesiones constituyen su elemento central.'},c:'c',x:'El consejo interpersonal adapta los principios de la TIP a un formato breve y sencillo. La TIP es temporalmente delimitada, emplea un rol de enfermo transitorio y no se centra en tareas entre sesiones.',r:F});
set('SM_ENERO_1_SOL_1_136',{e:'Respecto a la terapia interpersonal de Klerman y Weissman, señale la afirmación correcta:',o:{a:'Se fundamenta principalmente en el condicionamiento clásico y operante.',b:'Posee más fundamento teórico que empírico.',c:'Solo contempla duelo, disputas y transiciones de rol.',d:'Considera la depresión una enfermedad multifactorial y atiende especialmente a los cambios del entorno interpersonal.'},c:'d',x:'La TIP adopta un modelo médico multifactorial y trabaja la relación recíproca entre síntomas y acontecimientos interpersonales. Cuenta con cuatro áreas, incluida la de déficits interpersonales.',r:F});
set('SM_ENERO_1_SOL_1_140',{e:'Clásicamente, ¿para qué presentación del trastorno bipolar se ha recomendado el valproato?',o:{a:'Como opción preferente durante el embarazo.',b:'Ciclación rápida.',c:'Depresión bipolar aguda en monoterapia como primera elección universal.',d:'Mujeres con posibilidad de embarazo sin medidas especiales.'},c:'b',x:'La respuesta clásica del manual es ciclación rápida. El valproato posee elevada teratogenicidad y debe evitarse en embarazo y, salvo ausencia de alternativas, en mujeres con capacidad de gestación.',r:'Yatham, L. N. et al. (2018). CANMAT and ISBD 2018 guidelines. Bipolar Disorders, 20, 97-170.'});
set('SM_JULIO_2_SOL_1_171',{e:'Según la teoría de la vulnerabilidad fluida de Rudd, ¿qué proceso favorece que una crisis progrese desde ideación hasta conducta suicida?',o:{a:'La capacidad adquirida para lesionarse como único mecanismo.',b:'Exclusivamente que el dolor supere la conectividad social.',c:'La activación de un modo suicida caracterizado por rigidez cognitiva, intensa activación afectiva y dificultades de regulación.',d:'La imitación como explicación necesaria.'},c:'c',x:'El modelo distingue una vulnerabilidad basal relativamente estable y estados agudos fluctuantes. En crisis se activa un sistema suicida rígido de cogniciones, emociones, activación y conductas que estrecha las alternativas percibidas.',r:'Rudd, M. D. (2006). Fluid vulnerability theory: A cognitive approach to understanding the process of acute and chronic suicide risk. En T. E. Ellis (ed.), Cognition and Suicide. APA.'});
set('SmCm08PIR2025_073',{e:'¿Qué principio caracteriza la activación conductual para la depresión?',o:{a:'El tratamiento se guía por el análisis funcional de evitación, rutinas y consecuencias.',b:'Su mecanismo consiste exclusivamente en disputar creencias irracionales.',c:'Solo se utiliza para prevenir recaídas después de una TCC completa.',d:'Prescribe actividades agradables de forma idéntica para todas las personas.'},c:'a',x:'La activación conductual es individualizada: analiza los patrones que mantienen la depresión y programa acciones vinculadas a objetivos y valores. No se limita a prevención ni a prescripciones genéricas.',r:'Martell, C. R., Dimidjian, S. y Herman-Dunn, R. (2010). Behavioral Activation for Depression. Guilford Press.'});
set('SmCm08PIR2025_077',{e:'¿Cuál de las siguientes intervenciones NO es un tratamiento específico con eficacia establecida para la depresión?',o:{a:'Terapia cognitivo-conductual de Beck.',b:'Terapia interpersonal.',c:'Activación conductual.',d:'MERIT, desarrollada para recuperación metacognitiva en psicosis.'},c:'d',x:'MERIT se desarrolló para trastornos del espectro psicótico, no como tratamiento específico de la depresión. TCC, TIP y activación conductual cuentan con respaldo para cuadros depresivos.',r:'National Institute for Health and Care Excellence (2022). Depression in adults: treatment and management (NG222); '+F});
set('SmCm08PIR2025_208',{e:'En un modelo escalonado clásico de atención a la depresión adulta, ¿qué caracteriza al segundo nivel?',o:{a:'Únicamente información general, vigilancia y ejercicio.',b:'Ingreso hospitalario y terapia electroconvulsiva.',c:'Intervenciones psicológicas estructuradas de baja intensidad y, según gravedad o guía, tratamiento farmacológico.',d:'Tratamiento combinado intensivo obligatorio para cualquier caso.'},c:'c',x:'Tras evaluación y medidas iniciales, el segundo escalón incorpora tratamiento psicológico estructurado de menor intensidad y puede considerar medicación según el cuadro. Hospitalización y TEC corresponden a necesidades de mayor complejidad.',r:F});
set('SmCm09PIR2025_022',{e:'¿Cuál NO es una meta específica de la terapia interpersonal y de ritmos sociales?',o:{a:'Mantener rutinas diarias y ciclos de sueño-vigilia regulares.',b:'Reducir exclusivamente estresores familiares mediante una intervención familiar independiente.',c:'Adquirir hábitos que ayuden a prevenir futuros episodios.',d:'Reducir la cantidad y gravedad de estresores interpersonales.'},c:'b',x:'La IPSRT trabaja ritmos, prevención de episodios y problemas interpersonales. La intervención familiar independiente corresponde a otros programas, aunque la familia pueda participar en la psicoeducación.',r:'Frank, E. (2005). Treating Bipolar Disorder. Guilford Press.'});
set('SmCm09PIR2025_023',{e:'¿Cuál es uno de los componentes principales del Curso para el Afrontamiento de la Depresión de Lewinsohn?',o:{a:'Modificación de cogniciones asociadas a la depresión.',b:'Exposición interoceptiva a sensaciones de pánico.',c:'Prevención de respuesta ante obsesiones.',d:'Interpretación sistemática de sueños.'},c:'a',x:'El CAD combina modificación cognitiva con incremento de actividades agradables y entrenamiento en habilidades sociales.',r:F});

fs.writeFileSync(ap,JSON.stringify(a));fs.writeFileSync(cp,JSON.stringify(child));
console.log('Bloque 5: 20 auditadas y 13 reubicadas.');
