const fs=require('fs'),path=require('path'),file=path.join(__dirname,'..','public','banco','clinica_adultos.json');
const b=JSON.parse(fs.readFileSync(file,'utf8'));
const ref='American Psychiatric Association (2022). DSM-5-TR, capítulo «Personality Disorders» y modelo alternativo de la sección III. American Psychiatric Association Publishing; Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología (4.ª ed.), capítulo de trastornos de la personalidad. McGraw Hill.';
const data={
'ABRIL-UNO-24_COMENTADO_062':['b','Respecto al trastorno narcisista de la personalidad, señale la opción correcta:',{a:'Aproximadamente el 75 % de los casos corresponde a mujeres.',b:'La autoestima suele ser frágil y vulnerable a la crítica.',c:'Conserva una empatía plena aunque explota las relaciones.',d:'La arrogancia impide que sienta envidia.'},'La b es correcta. La autoestima puede ser muy vulnerable; existe deterioro de la empatía, puede aparecer envidia y en muestras clínicas predominan los hombres.'],
'ABRIL-UNO-24_COMENTADO_139':['c','Respecto a modelos explicativos del trastorno límite de la personalidad (TLP), señale la opción correcta:',{a:'El modelo de cascadas emocionales sostiene que la rumiación reduce la desregulación.',b:'El modelo de comunicación social es uno de los modelos clásicos de cascadas emocionales.',c:'El modelo de Fonagy destaca la confianza epistémica y la comunicación social en el desarrollo temprano del TLP.',d:'El modelo biosocial propone vulnerabilidad exclusivamente psicológica, sin componente biológico.'},'La c es correcta. La rumiación intensifica la cascada emocional y el modelo biosocial de Linehan plantea vulnerabilidad emocional de base biológica en interacción con un ambiente invalidante.'],
'ABRIL-UNO-24_COMENTADO_140':['a','En el modelo alternativo de los trastornos de la personalidad del DSM-5-TR, señale la opción correcta:',{a:'Primero se evalúa el funcionamiento de la personalidad mediante el criterio A.',b:'El funcionamiento se valora mediante intimidad, autodirección, empatía e introspección.',c:'El trastorno evitativo no está representado entre sus seis diagnósticos.',d:'Sus niveles de gravedad son idénticos a los de la CIE-11.'},'La a es correcta. Los cuatro componentes son identidad, autodirección, empatía e intimidad; el modelo incluye personalidad evitativa y no coincide exactamente con el sistema de gravedad de la CIE-11.'],
'AGOSTO2_060':['b','¿Qué trastorno de la personalidad presenta falta de deseo y disfrute de las relaciones personales, incluida la pertenencia a una familia?',{a:'Esquizotípico.',b:'Esquizoide.',c:'Evitativo.',d:'Obsesivo-compulsivo.'},'La b es correcta. El desapego de las relaciones sociales y la escasa necesidad de intimidad caracterizan el trastorno esquizoide.'],
'DICIEMBRE-DOS-24_COMENTADO_040':['c','En el modelo alternativo del DSM-5-TR, ¿a qué dominio pertenece la faceta de suspicacia?',{a:'Antagonismo.',b:'Psicoticismo.',c:'Desapego.',d:'Desinhibición.'},'La c es correcta: la suspicacia es una de las facetas incluidas en el dominio de desapego.'],
'DICIEMBRE-DOS-24_COMENTADO_041':['d','¿En qué dimensión transdiagnóstica del TLP se sitúan los síntomas disociativos y psicóticos transitorios de mayor gravedad?',{a:'Desregulación emocional.',b:'Desregulación conductual.',c:'Hipersensibilidad interpersonal.',d:'Alteraciones de la identidad.'},'La d es correcta según el modelo dimensional utilizado en el manual: los fenómenos disociativos y psicóticos transitorios se agrupan con las alteraciones de identidad.'],
'DICIEMBRE-DOS-24_COMENTADO_076':['d','En el modelo alternativo del DSM-5-TR, ¿qué dominios de rasgos caracterizan principalmente al trastorno esquizotípico de la personalidad?',{a:'Antagonismo y desinhibición.',b:'Afectividad negativa, desinhibición y antagonismo.',c:'Afectividad negativa y desapego exclusivamente.',d:'Psicoticismo y desapego.'},'La d es correcta. El perfil se define principalmente por psicoticismo y desapego, aunque pueden especificarse facetas adicionales.'],
'DICIEMBRE-UNO-24_COMENTADO_101':['d','¿Qué alteración cognitiva o perceptiva forma parte del criterio diagnóstico del TLP?',{a:'Pensamiento y discurso persistentemente raros.',b:'Ideas de referencia estables.',c:'Creencias mágicas persistentes.',d:'Ideación paranoide transitoria relacionada con el estrés.'},'La d es correcta. El TLP puede presentar ideación paranoide transitoria o síntomas disociativos intensos relacionados con el estrés; las otras opciones son más propias del patrón esquizotípico.'],
'JULIO1_094':['b','Según la CIE-11, ¿dónde se encuadra la «dificultad de personalidad» cuando los rasgos problemáticos no alcanzan gravedad de trastorno?',{a:'Dentro de los trastornos de la personalidad como un trastorno leve.',b:'Entre los factores que influyen en el estado de salud o el contacto con los servicios sanitarios.',c:'Entre los síndromes mentales secundarios a enfermedades clasificadas en otra parte.',d:'Como otro trastorno mental especificado.'},'La b es correcta. La dificultad de personalidad no se diagnostica como trastorno mental, sino como un factor que puede influir en la atención clínica.','World Health Organization (2024). ICD-11 Clinical Descriptions and Diagnostic Requirements, Personality Disorders and related traits; '+ref],
'JULIO1_095':['a','Según la propuesta de Cleckley sobre la «demencia semántica» en la psicopatía, señale la opción correcta:',{a:'Existe una discrepancia entre lenguaje y experiencia emocional, sin correspondencia adecuada entre expresión verbal y activación afectiva.',b:'La baja respuesta refleja aparece únicamente ante estímulos negativos.',c:'La frialdad afectiva constituye por sí sola toda la tétrada descrita.',d:'El desarrollo moral se mantiene necesariamente en un nivel convencional.'},'La a es correcta. Cleckley señaló un uso aparentemente normal del lenguaje emocional que carece de la correspondiente profundidad afectiva.'],
'JULIO1_097':['d','¿En qué dimensión transdiagnóstica del TLP se agrupan los síntomas disociativos y psicóticos transitorios?',{a:'Desregulación emocional generalizada.',b:'Desregulación comportamental.',c:'Hipersensibilidad interpersonal.',d:'Alteraciones de la identidad.'},'La d es correcta. Se corrige la denominación imprecisa «alteraciones de la personalidad» de la versión anterior.'],
'JULIO2_063':['b','¿Qué trastorno de la personalidad NO forma parte de los seis diagnósticos del modelo alternativo de la sección III del DSM-5-TR?',{a:'Límite.',b:'Dependiente.',c:'Esquizotípico.',d:'Evitativo.'},'La b es correcta. El modelo conserva antisocial, evitativo, límite, narcisista, obsesivo-compulsivo y esquizotípico; el dependiente no figura como diagnóstico específico.'],
'JUNIO-UNO-24_COMENTADO_080':['a','¿Qué trastorno de la personalidad se caracteriza por desconfianza y suspicacia generalizadas, interpretando como maliciosas las intenciones ajenas?',{a:'Paranoide.',b:'Esquizoide.',c:'Esquizotípico.',d:'Antisocial.'},'La a es correcta. La descripción reproduce el patrón nuclear del trastorno paranoide. Se corrige la clave antigua, que señalaba erróneamente el trastorno esquizoide.'],
'JUNIO1_093':['b','¿Qué cuatro trastornos no están incluidos como diagnósticos específicos en el modelo alternativo de la sección III del DSM-5-TR?',{a:'Esquizotípico, histriónico, narcisista y dependiente.',b:'Esquizoide, paranoide, histriónico y dependiente.',c:'Límite, histriónico, narcisista y obsesivo-compulsivo.',d:'Paranoide, histriónico, evitativo y dependiente.'},'La b es correcta. Esos cuatro se describen dimensionalmente mediante deterioro del funcionamiento y rasgos, pero no aparecen entre los seis tipos conservados.'],
'JUNIO1_102':['b','¿En qué trastorno de la personalidad señala DSM-5-TR una distribución aproximadamente equivalente entre hombres y mujeres?',{a:'Obsesivo-compulsivo.',b:'Evitativo.',c:'Esquizoide.',d:'Límite.'},'La b es correcta. El trastorno evitativo aparece aproximadamente por igual en ambos sexos; otros diagnósticos presentan diferencias clínicas o epidemiológicas descritas.'],
'JUNIO1_121':['c','¿Qué dimensión transdiagnóstica del TLP incluye dificultades de autodirección y sentimientos crónicos de vacío?',{a:'Desregulación emocional.',b:'Desregulación comportamental.',c:'Alteraciones de la identidad.',d:'Hipersensibilidad interpersonal.'},'La c es correcta. La inestabilidad del sentido del yo, la falta de dirección y el vacío crónico pertenecen a las alteraciones de identidad.'],
'MAYO-DOS-24_COMENTADO_168':['b','Señale la afirmación incorrecta sobre el trastorno evitativo de la personalidad:',{a:'La estimación de prevalencia citada por DSM-5 ronda el 2,4 %.',b:'Es claramente más frecuente en mujeres.',c:'Puede diagnosticarse junto con personalidad dependiente.',d:'Quienes lo presentan suelen vigilar cuidadosamente los gestos y expresiones de otras personas.'},'La b es incorrecta: DSM-5-TR describe una frecuencia aproximadamente equivalente entre hombres y mujeres. Las demás afirmaciones son compatibles con su descripción clínica.'],
'MAYO-DOS-24_COMENTADO_169':['c','En el modelo alternativo del DSM-5-TR, ¿de qué dominio forma parte la faceta de suspicacia?',{a:'Psicoticismo.',b:'Antagonismo.',c:'Desapego.',d:'Desinhibición.'},'La c es correcta: suspicacia se incluye en desapego.'],
'MAYO-DOS-24_COMENTADO_170':['a','¿Cuál NO forma parte de las cuatro dimensiones transdiagnósticas del TLP empleadas en el manual?',{a:'Desregulación cognitiva.',b:'Desregulación comportamental.',c:'Desregulación emocional.',d:'Hipersensibilidad interpersonal.'},'La a es correcta como excepción. Las cuatro dimensiones son desregulación emocional, desregulación comportamental, hipersensibilidad interpersonal y alteraciones de la identidad.'],
'MAYO-DOS-24_COMENTADO_171':['c','Señale la afirmación incorrecta sobre el TLP:',{a:'El suicidio consumado se ha estimado en torno al 8-10 %, y son frecuentes autolesiones, amenazas e intentos.',b:'La impulsividad puede expresarse mediante juego, gastos, atracones, sustancias, sexo de riesgo o conducción temeraria.',c:'La mayoría alcanza mayor estabilidad por primera vez durante las décadas de los 50 y 60 años.',d:'Ante el abandono, el TLP suele reaccionar con vacío, rabia y exigencias, mientras la personalidad dependiente incrementa sumisión y busca otra relación de cuidado.'},'La c es incorrecta. La descripción DSM sitúa la mayor estabilidad relacional y laboral de muchas personas durante las décadas de los 30 y 40, no por primera vez en los 50-60.']};
let n=0;for(const [id,[c,e,o,x,r=ref]] of Object.entries(data)){const q=b.find(z=>z.id===id);if(!q)throw Error(id);Object.assign(q,{c,e,o,x,r,v:'VALIDADA_ORIGINAL'});n++}if(n!==20)throw Error('Expected 20');fs.writeFileSync(file,JSON.stringify(b));console.log({audited:n});
