const fs=require('fs');
const ap='public/banco/tratamientos_adultos.json';
const a=JSON.parse(fs.readFileSync(ap,'utf8')),m=new Map(a.map(q=>[q.id,q]));
const F='Fonseca Pedrero, E. (coord.) (2021). Manual de tratamientos psicológicos: Adultos. Pirámide.';
const B='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. II (4.ª ed.). McGraw Hill.';
function set(id,z){const q=m.get(id);if(!q)throw Error(id);Object.assign(q,z,{v:'VALIDADA_ORIGINAL'});}
function rehome(id,topic){const q=m.get(id);if(!q)throw Error(id);q.t=[topic];q.v='REVISAR';}
rehome('SmCm20PIR2024_062','Tratamiento de los trastornos alimentarios');

set('SmCm3PIR2024_170',{e:'¿Cuál de los siguientes NO es un tratamiento farmacológico específico del trastorno bipolar?',o:{a:'Litio.',b:'Quetiapina.',c:'Lamotrigina.',d:'Clordiazepóxido.'},c:'d',x:'Clordiazepóxido es una benzodiacepina y no un tratamiento específico para las fases agudas o el mantenimiento bipolar. Litio, quetiapina y lamotrigina poseen indicaciones concretas según fase y polaridad.',r:'Yatham, L. N. et al. (2018). CANMAT and ISBD 2018 guidelines. Bipolar Disorders, 20, 97-170.'});
set('SmCm4PIR2024_172',{e:'En la terapia focalizada en la emoción aplicada a la depresión, ¿qué significa «sobreproducción emocional»?',o:{a:'Coexistencia de tristeza con otras emociones negativas secundarias, como ira, miedo, ansiedad o vergüenza.',b:'Que la tristeza debe ser necesariamente extrema para diagnosticar depresión.',c:'Que toda depresión comienza con una reacción emocional desproporcionada.',d:'Que la tristeza ha de mantenerse intensa durante toda la historia vital.'},c:'a',x:'La sobreproducción alude a la acumulación o coexistencia de diversas respuestas emocionales problemáticas que dificultan identificar y procesar la emoción primaria.',r:F});
set('SmCm4PIR2024_174',{e:'¿Cuál de las siguientes estrategias NO pertenece a la terapia cognitiva clásica de Beck para la depresión?',o:{a:'Programación de actividades gratificantes.',b:'Cuestionamiento de reglas rígidas y autocríticas.',c:'Acceso y transformación de una emoción primaria adaptativa como procedimiento central.',d:'Detección y modificación de enunciados del tipo «debería».'},c:'c',x:'El acceso a emociones primarias adaptativas es característico de terapias experienciales o focalizadas en la emoción. La terapia de Beck combina técnicas conductuales y cognitivas para modificar pensamientos, supuestos y esquemas.',r:'Beck, A. T. et al. (1979). Cognitive Therapy of Depression. Guilford Press.'});
set('PERSEV_AGO25_U1_067',{e:'¿Qué afirmación es correcta sobre el síndrome de retirada o discontinuación de antidepresivos?',o:{a:'Se asocia sobre todo a fármacos de vida media muy larga y nunca a los de vida media corta.',b:'Náuseas e hipersensibilidad sensorial son síntomas patognomónicos.',c:'Puede incluir mareo, desequilibrio, zumbidos, parestesias y sensaciones semejantes a descargas eléctricas.',d:'Solo aparece después de una reducción muy lenta y nunca tras una retirada brusca.'},c:'c',x:'La reducción o suspensión, especialmente brusca, puede ocasionar síntomas gripales, insomnio, náuseas, desequilibrio, alteraciones sensoriales e hiperactivación. No existen síntomas patognomónicos y el riesgo varía entre fármacos.',r:'National Institute for Health and Care Excellence (2022). Depression in adults: treatment and management (NG222), retirada de antidepresivos.'});
set('JUNIO-UNO-24_COMENTADO_169',{e:'¿En qué situación deben evitarse o utilizarse con especial cautela los antidepresivos en el trastorno bipolar?',o:{a:'Ciclación rápida o características mixtas.',b:'Cualquier episodio depresivo, aunque se combinen con un tratamiento antimaníaco.',c:'Toda combinación con litio o valproato.',d:'Toda combinación con un antipsicótico atípico.'},c:'a',x:'Los antidepresivos pueden acelerar los ciclos o favorecer viraje, especialmente ante ciclación rápida, características mixtas o antecedentes de viraje. En bipolar I no deben utilizarse en monoterapia.',r:'Yatham, L. N. et al. (2018). CANMAT and ISBD 2018 guidelines. Bipolar Disorders, 20, 97-170.'});
set('PERSEVER___SIMULACRO_COMENTADO_ABRIL-DOS-23_089',{e:'Señale la afirmación correcta sobre los antidepresivos en el trastorno bipolar I:',o:{a:'Se recomiendan como monoterapia de mantenimiento.',b:'Si se utilizan en depresión bipolar, deben añadirse a un estabilizador o antipsicótico adecuado y seleccionarse con cautela.',c:'Eliminan el riesgo de viraje cuando existe ciclación rápida.',d:'Son de primera elección en presencia de características mixtas.'},c:'b',x:'Los antidepresivos no deben emplearse en monoterapia en bipolar I. Su posible uso es coadyuvante, con beneficio modesto y valoración del riesgo de viraje; deben evitarse o extremarse las precauciones en ciclación rápida o estados mixtos.',r:'Yatham, L. N. et al. (2018). CANMAT and ISBD 2018 guidelines. Bipolar Disorders, 20, 97-170.'});
set('PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-DOS-23_069',{e:'¿Qué afirmación es correcta sobre valproato y embarazo?',o:{a:'Es el estabilizador preferente durante cualquier embarazo.',b:'Carece de riesgos relevantes para el desarrollo fetal.',c:'Debe evitarse en el embarazo y no utilizarse en mujeres con capacidad de gestación salvo que no exista una alternativa adecuada y se cumplan estrictas medidas preventivas.',d:'Puede prescribirse sin información anticonceptiva ni consentimiento específico.'},c:'c',x:'Valproato presenta un riesgo elevado de malformaciones y trastornos del neurodesarrollo. Las restricciones actuales son más estrictas que la formulación antigua y exigen evitarlo salvo circunstancias excepcionales.',r:'Agencia Española de Medicamentos y Productos Sanitarios. Medidas para evitar la exposición a valproato durante el embarazo; European Medicines Agency, valproate pregnancy prevention programme.'});
set('PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-UNO-23_147',{e:'¿Qué antiepiléptico destaca por su eficacia en la prevención de recaídas depresivas del trastorno bipolar?',o:{a:'Valproato.',b:'Carbamazepina.',c:'Lamotrigina.',d:'Aripiprazol, que no es un antiepiléptico.'},c:'c',x:'Lamotrigina es una opción de mantenimiento especialmente vinculada a la prevención de episodios depresivos. Aripiprazol es un antipsicótico, no un antiepiléptico.',r:'Keramatian, K., Chithra, N. K. y Yatham, L. N. (2023). CANMAT and ISBD Guidelines: 2023 Update. Focus, 21, 344-353.'});
set('PERSEVER___SIMULACRO_COMENTADO_ENERO-UNO-23_152',{e:'¿Cuál de los siguientes fármacos NO es un tratamiento específico del trastorno bipolar?',o:{a:'Lamotrigina.',b:'Quetiapina.',c:'Litio.',d:'Clordiazepóxido.'},c:'d',x:'Clordiazepóxido es una benzodiacepina sin indicación específica como estabilizador del ánimo. Las restantes opciones tienen usos reconocidos en bipolaridad.',r:'Yatham, L. N. et al. (2018). CANMAT and ISBD 2018 guidelines. Bipolar Disorders, 20, 97-170.'});
set('PERSEVER___SIMULACRO_COMENTADO_MAYO-UNO-23_129',{e:'¿Para qué trastorno se desarrolló el sistema móvil MONARCA?',o:{a:'Psicosis.',b:'Depresión unipolar.',c:'Ansiedad infantil.',d:'Trastorno bipolar.'},c:'d',x:'MONARCA se desarrolló para monitorización e intervención mediante teléfono inteligente en el trastorno bipolar. No debe confundirse con ORBIT, que es una intervención principalmente web.',r:F});
set('PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-UNO-23_082',{e:'Según la recomendación clásica recogida en el manual, ¿qué estabilizador se elegiría preferentemente entre estas opciones ante trastorno bipolar con ciclación rápida?',o:{a:'Litio.',b:'Valproato.',c:'Aripiprazol.',d:'Fluvoxamina.'},c:'b',x:'La respuesta clásica es valproato, dado el peor rendimiento relativo del litio descrito en algunos cicladores rápidos y el riesgo de desestabilización con antidepresivos. La evidencia actual no permite una regla universal y exige individualización.',r:B});
set('PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-DOS-23_170',{e:'¿Qué fármaco se utiliza especialmente para prevenir recaídas depresivas en el mantenimiento del trastorno bipolar I?',o:{a:'Antidepresivo en monoterapia.',b:'Lamotrigina.',c:'Haloperidol como opción específica para la polaridad depresiva.',d:'Clordiazepóxido.'},c:'b',x:'Lamotrigina destaca por la prevención de episodios depresivos. La clave original «valproato» era menos específica y se ha sustituido por una opción inequívoca.',r:'Keramatian, K., Chithra, N. K. y Yatham, L. N. (2023). CANMAT and ISBD Guidelines: 2023 Update. Focus, 21, 344-353.'});
set('PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-UNO-23_150',{e:'¿Qué fármaco posee especial respaldo para prevenir episodios depresivos en el trastorno bipolar?',o:{a:'Clozapina.',b:'Lamotrigina.',c:'Fluoxetina en monoterapia.',d:'Aripiprazol como opción específicamente antidepresiva.'},c:'b',x:'Lamotrigina es una intervención de mantenimiento de primera línea con especial utilidad preventiva frente a la polaridad depresiva.',r:'Keramatian, K., Chithra, N. K. y Yatham, L. N. (2023). CANMAT and ISBD Guidelines: 2023 Update. Focus, 21, 344-353.'});
set('Simu 11 comentado_162',{e:'Señale la actuación incorrecta al evaluar a una persona deprimida con posible ideación suicida:',o:{a:'Preguntar específicamente por deseo de morir, ideación, planes, intención y conductas previas.',b:'Comenzar de forma rígida con un interrogatorio estructurado sin establecer rapport ni permitir una descripción abierta.',c:'Distinguir pensamientos pasivos de ideación activa y valorar su evolución.',d:'Consultar información relevante de allegados cuando existan dudas y resulte clínicamente necesario.'},c:'b',x:'La evaluación debe ser directa y sistemática, pero integrada en una entrevista empática que comience permitiendo explicar la situación. Las otras actuaciones aportan información esencial para formular el riesgo.',r:'National Institute for Health and Care Excellence (2022). Self-harm: assessment, management and preventing recurrence (NG225).'});
set('PERSEV_AGO25_U1_122',{e:'¿Para qué trastorno se desarrolló PRISM como intervención apoyada en teléfono inteligente?',o:{a:'Depresión unipolar.',b:'Psicosis.',c:'Trastorno bipolar.',d:'Trastorno obsesivo-compulsivo.'},c:'c',x:'PRISM combina psicoeducación individualizada y monitorización o avisos mediante teléfono inteligente para personas con trastorno bipolar. La formulación antigua «basada en web» era imprecisa.',r:'Depp, C. A. et al. (2015). Augmenting psychoeducation with a mobile intervention for bipolar disorder: a randomized controlled trial. Journal of Affective Disorders, 174, 23-30.'});
set('Simu 14 comentado _080',{e:'¿Cuál NO es una de las cuatro áreas problemáticas de la terapia interpersonal para la depresión?',o:{a:'Duelo.',b:'Déficits interpersonales.',c:'Disputas de rol.',d:'Reestructuración de rasgos básicos de personalidad.'},c:'d',x:'Las áreas son duelo, disputas de rol, transiciones de rol y déficits interpersonales. La modificación estructural de la personalidad no es un foco propio de la TIP.',r:F});
set('Simu 16 comentado_143',{e:'¿Qué mostró STEP-BD sobre TCC, terapia centrada en la familia e IPSRT intensivas para la depresión bipolar?',o:{a:'Las tres superaron globalmente al cuidado colaborativo breve y no hubo diferencias estadísticamente significativas entre ellas.',b:'Fueron menos eficaces que el cuidado colaborativo.',c:'Solo la TCC intensiva mostró eficacia.',d:'Añadir psicoterapia intensiva a la farmacoterapia no aportó beneficios.'},c:'a',x:'Las psicoterapias intensivas aceleraron la recuperación y aumentaron el tiempo de bienestar frente al cuidado colaborativo breve; no se observaron diferencias significativas entre las tres modalidades.',r:'Miklowitz, D. J. et al. (2007). Psychosocial treatments for bipolar depression: a 1-year randomized trial from STEP-BD. Archives of General Psychiatry, 64, 419-426.'});
set('SmCm19PIR2024_128',{e:'¿Qué antidepresivo, perteneciente a los IMAO, mostró eficacia clásica en la depresión con características atípicas?',o:{a:'Isocarboxazida.',b:'Escitalopram.',c:'Mianserina.',d:'Paliperidona.'},c:'a',x:'Isocarboxazida es un IMAO. Los estudios clásicos observaron una respuesta particularmente favorable a IMAO en depresión atípica, aunque hoy suelen reservarse por seguridad e interacciones.',r:'Pae, C. U. et al. (2009). Atypical depression: a comprehensive review. CNS Drugs, 23, 1023-1037.'});
set('SmCm24PIR2025 (1)_082',{e:'Clásicamente, ¿qué presentación depresiva se ha asociado con mejor respuesta relativa a antidepresivos tricíclicos que la depresión atípica?',o:{a:'Depresión catatónica.',b:'Depresión atípica.',c:'Depresión melancólica.',d:'Depresión posparto.'},c:'c',x:'La distinción clásica asocia la depresión melancólica con mejor respuesta a tricíclicos y la atípica con mejor respuesta a IMAO. No implica que los tricíclicos sean hoy la primera opción universal.',r:'Pae, C. U. et al. (2009). Atypical depression: a comprehensive review. CNS Drugs, 23, 1023-1037.'});

const duplicateIds=[
  'PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-UNO-23_099',
  'SM_ABRIL_1_SOL_1_175',
  'PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-UNO-23_173',
  'SIM_ABR25_206',
  'SM_DICIEMBRE_2_SOL_1_152',
  'SmCm16PIR2025_139',
  'SmCm18PIR2025_172',
  'SmCm2PIR2024_158'
];
for(const id of duplicateIds){
  const i=a.findIndex(q=>q.id===id);
  if(i<0)throw Error(`Duplicado no encontrado: ${id}`);
  a.splice(i,1);
}

fs.writeFileSync(ap,JSON.stringify(a));
console.log('Cierre: 19 auditadas, 1 reubicada a trastornos alimentarios y 8 copias literales eliminadas.');
