const fs = require('fs');
const path = 'public/banco/clinica_adultos.json';
const data = JSON.parse(fs.readFileSync(path, 'utf8'));

const U = {
  'ABRIL-UNO-24_COMENTADO_130': {e:'Respecto al trastorno de estrés postraumático (TEPT) en adultos, señale la afirmación correcta:',o:{a:'La hipermnesia facilita principalmente la evitación del trauma.',b:'La amnesia disociativa facilita la reexperimentación del trauma.',c:'La culpa y la rabia facilitan principalmente la evitación del trauma.',d:'La vergüenza puede favorecer la evitación de recuerdos y situaciones relacionados con el trauma.'},c:'d',x:'La d es correcta: la vergüenza favorece el ocultamiento y la evitación de recordatorios del trauma. La a es falsa porque la hipermnesia se vincula con el recuerdo intrusivo, no con la evitación. La b invierte la relación: la amnesia disociativa dificulta el acceso a aspectos del suceso. La c es falsa porque culpa y rabia se asocian más con reexperimentación, rumiación y peor recuperación que con una función específicamente evitativa.',r:'Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. II (4.ª ed.). McGraw Hill, capítulo sobre trauma y factores de estrés.'},
  'ABRIL-UNO-24_COMENTADO_134': {e:'En relación con el curso del TEPT, señale la afirmación correcta:',o:{a:'En aproximadamente la mitad de los casos los síntomas comienzan durante los tres primeros meses, aunque en algunos pueden demorarse meses o incluso años.',b:'El TEPT solo puede diagnosticarse a partir de los dos años de edad.',c:'La mitad de los adultos alcanza la recuperación completa a los seis meses.',d:'Los sueños aterradores, los cambios de humor y la menor exploración son características propias de las personas mayores.'},c:'a',x:'La a es correcta: el comienzo suele producirse en los primeros meses, pero puede existir expresión retardada. La b es falsa porque puede aparecer desde el primer año de vida. La c fija una cifra y un plazo que no constituyen un criterio general del DSM-5-TR. La d atribuye a personas mayores manifestaciones descritas especialmente en niños pequeños.',r:'American Psychiatric Association (2022). DSM-5-TR. Trastorno de estrés postraumático, apartados Desarrollo y curso; Belloch, Sandín y Ramos (coords.) (2024), Manual de psicopatología, vol. II, capítulo sobre TEPT.'},
  'ABRIL-UNO-24_COMENTADO_171': {e:'Una persona presenta, desde hace un mes, malestar emocional y alteraciones conductuales clínicamente significativas tras un estresor que no cumple el criterio de acontecimiento traumático. ¿Qué diagnóstico es el más compatible?',o:{a:'Trastorno de apego reactivo.',b:'Trastorno de adaptación.',c:'Trastorno de estrés postraumático.',d:'Trastorno de estrés agudo.'},c:'b',x:'La b es correcta: el trastorno de adaptación aparece como respuesta a uno o más estresores identificables, sin exigir un trauma del criterio A. La a es un trastorno infantil ligado a cuidados insuficientes extremos. La c y la d requieren exposición a muerte, lesión grave o violencia sexual; además, el trastorno de estrés agudo dura de tres días a un mes y el TEPT más de un mes.',r:'American Psychiatric Association (2022). DSM-5-TR. Trastornos de adaptación; trastorno de estrés agudo; trastorno de estrés postraumático.'},
  'AGOSTO2_041': {e:'Según el DSM-5-TR, ¿cuántos síntomas se requieren para diagnosticar un trastorno de estrés agudo?',o:{a:'Cinco o más.',b:'Seis o más.',c:'Nueve o más.',d:'Cuatro o más.'},c:'c',x:'La c es correcta: se requieren nueve o más síntomas de cualquiera de las cinco categorías de intrusión, estado de ánimo negativo, disociación, evitación y activación. Las opciones a, b y d proponen umbrales inferiores que no corresponden al criterio B. Además, la duración debe ser de tres días a un mes tras el trauma.',r:'American Psychiatric Association (2022). DSM-5-TR. Trastorno de estrés agudo, criterios B y C.'},
  'AGOSTO2_068': {e:'Según la clasificación de Echeburúa y colaboradores de las variables facilitadoras del trauma, ¿cuál es un factor de mantenimiento postraumático?',o:{a:'El estrés acumulativo.',b:'La intencionalidad del suceso traumático.',c:'La negación cognitiva o emocional del suceso.',d:'Una personalidad vulnerable.'},c:'c',x:'La c es correcta: la negación cognitiva o emocional impide elaborar el suceso y puede mantener el malestar. La a y la d son factores predisponentes previos al trauma. La b es una característica precipitante del propio acontecimiento traumático, no un mecanismo de mantenimiento posterior.',r:'Echeburúa, E., de Corral, P. y Amor, P. J. (2011). Estrategias de afrontamiento ante los sentimientos de culpa. Análisis y Modificación de Conducta, 27; síntesis en Belloch, Sandín y Ramos (coords.) (2024), Manual de psicopatología, vol. II.'},
  'DICIEMBRE-DOS-24_COMENTADO_057': {e:'Según el modelo de factores de vulnerabilidad y mantenimiento del trauma, ¿cuál es un factor de mantenimiento postraumático?',o:{a:'El tipo de suceso traumático.',b:'La gravedad del suceso traumático.',c:'La necesidad persistente de buscar culpables.',d:'El estrés acumulativo previo.'},c:'c',x:'La c es correcta: la búsqueda persistente de culpables puede anclar a la persona al pasado y mantener el malestar. La a y la b describen características precipitantes del suceso. La d es un factor predisponente previo. Se corrige la clave original, que señalaba erróneamente la opción a.',r:'Caballo, V. E., Salazar, I. C. y Carrobles, J. A. (dirs.) (2014). Manual de psicopatología y trastornos psicológicos. Pirámide, p. 303.'},
  'DICIEMBRE-DOS-24_COMENTADO_080': {e:'Respecto a los factores asociados con la recuperación tras un suceso traumático, señale la afirmación correcta:',o:{a:'La culpa y la rabia predicen una recuperación más favorable.',b:'Un grupo de autoayuda puede constituir una rémora para algunas víctimas.',c:'La implicación en actividades lúdicas cotidianas predice peor recuperación.',d:'La rumiación y la evitación de pensamientos intrusivos son estrategias cognitivas favorables.'},c:'b',x:'La b es correcta: algunas víctimas se recuperan mejor con su red natural y un grupo puede reforzar el anclaje en el trauma. La a es falsa porque culpa y rabia se relacionan con peor evolución. La c es falsa: retomar actividades cotidianas es un indicador favorable. La d es falsa porque rumiación y evitación cognitiva contribuyen al mantenimiento del problema.',r:'Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. II (4.ª ed.). McGraw Hill, capítulo sobre reacciones al trauma.'},
  'DICIEMBRE-UNO-24_COMENTADO_092': {t:['Trastornos disociativos'],e:'En el DSM-5-TR, ¿en qué categoría se incluyen las «reacciones disociativas agudas a sucesos estresantes»?',o:{a:'Otro trastorno del espectro de la esquizofrenia especificado y otro trastorno psicótico.',b:'Otro trastorno relacionado con traumas y factores de estrés especificado.',c:'Otro trastorno de síntomas somáticos y trastornos relacionados especificado.',d:'Otro trastorno disociativo especificado.'},c:'d',x:'La d es correcta: esta presentación figura como ejemplo de otro trastorno disociativo especificado. La a agrupa presentaciones psicóticas especificadas; la b contiene cuadros relacionados con trauma que no cumplen otra categoría, pero no esta denominación disociativa; y la c corresponde a presentaciones somáticas especificadas. Se reubica por tratarse de clasificación de los trastornos disociativos.',r:'American Psychiatric Association (2022). DSM-5-TR. Otro trastorno disociativo especificado.'},
  'JULIO2_020': {t:['Trastornos de ansiedad'],e:'Según el DSM-5-TR, ¿qué trastorno exige una duración mínima distinta en niños y adolescentes que en adultos?',o:{a:'Trastorno de ansiedad por separación.',b:'Mutismo selectivo.',c:'Trastorno de estrés postraumático.',d:'Fobia específica.'},c:'a',x:'La a es correcta: la ansiedad por separación debe durar al menos cuatro semanas en niños y adolescentes y, típicamente, seis meses o más en adultos. La b exige al menos un mes; la c, más de un mes; y la d, típicamente seis meses o más, sin establecer esos dos umbrales según edad. Se reubica en trastornos de ansiedad.',r:'American Psychiatric Association (2022). DSM-5-TR. Trastorno de ansiedad por separación, criterio F; mutismo selectivo; fobia específica; trastorno de estrés postraumático.'},
  'JULIO2_056': {e:'¿Cuál de los siguientes se clasifica específicamente como factor psicológico de vulnerabilidad ante un suceso traumático?',o:{a:'Antecedentes de otros sucesos traumáticos.',b:'Baja resistencia psicobiológica al estrés.',c:'Falta de apoyo familiar.',d:'Inestabilidad emocional previa.'},c:'d',x:'La d es correcta: la inestabilidad emocional previa es un factor psicológico personal. La a corresponde a antecedentes traumáticos o psicopatológicos; la b se clasifica como vulnerabilidad psicobiológica; y la c es un factor sociofamiliar. La distinción depende del tipo de vulnerabilidad solicitado, no de que los otros factores carezcan de relevancia.',r:'Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. II (4.ª ed.). McGraw Hill, capítulo sobre trauma; Echeburúa, E. (2004), factores de vulnerabilidad y resistencia.'},
  'JULIO2_208': {e:'Respecto a las modalidades y factores de complejidad del TEPT, señale la afirmación correcta:',o:{a:'La expresión retardada exige que los criterios completos aparezcan al menos tres meses después del trauma.',b:'El TEPT complejo presenta una sintomatología menos variada y menor comorbilidad.',c:'El DSM-5-TR especifica un subtipo persistente definido por ansiedad e intranquilidad.',d:'La complejidad aumenta cuando el trauma es grave o prolongado, ocurre tempranamente, lo causa un cuidador o persiste el contacto con el agresor.'},c:'d',x:'La d es correcta: esas condiciones aumentan el riesgo de una presentación compleja. La a es falsa porque la expresión retardada se especifica cuando los criterios completos no se cumplen hasta al menos seis meses después. La b invierte la relación: el TEPT complejo presenta síntomas más variados y mayor complejidad. La c es falsa porque el especificador es «con síntomas disociativos» —despersonalización o desrealización—, no de ansiedad.',r:'American Psychiatric Association (2022). DSM-5-TR. Trastorno de estrés postraumático, especificadores; World Health Organization (2024). ICD-11 CDDR, complex PTSD.'},
  'JUNIO-UNO-24_COMENTADO_078': {e:'¿Cuál es un factor psicobiológico de vulnerabilidad personal ante un suceso traumático?',o:{a:'La falta de apoyo familiar.',b:'La baja resistencia al estrés.',c:'Los escasos recursos de afrontamiento.',d:'Los trastornos psiquiátricos previos.'},c:'b',x:'La b es correcta porque se clasifica como vulnerabilidad psicobiológica. La a es un factor sociofamiliar; la c, psicológico; y la d, psicopatológico. Todos pueden elevar el riesgo, pero solo b pertenece al tipo solicitado.',r:'Caballo, V. E., Salazar, I. C. y Carrobles, J. A. (dirs.) (2014). Manual de psicopatología y trastornos psicológicos. Pirámide, p. 303.'},
  'JUNIO1_109': {e:'Según el DSM-5-TR, ¿cuál es un predictor robusto del trastorno de estrés agudo?',o:{a:'Un afrontamiento basado en la confrontación.',b:'Las evaluaciones catastrofistas de la experiencia traumática.',c:'Una baja reactividad fisiológica previa al trauma.',d:'Un bajo nivel de afecto negativo.'},c:'b',x:'La b es correcta: las valoraciones catastrofistas —daño futuro exagerado, culpa o desesperanza— predicen de forma robusta el trastorno. La a es falsa porque el riesgo se asocia al afrontamiento evitativo. La c invierte el hallazgo: una reactividad elevada aumenta el riesgo. La d también lo invierte, pues el factor de riesgo es un afecto negativo elevado.',r:'American Psychiatric Association (2022). DSM-5-TR. Trastorno de estrés agudo, factores de riesgo y pronóstico.'},
  'JUNIO1_110': {e:'¿Qué modelo del TEPT explica específicamente la reexperimentación mediante estructuras de miedo que no han sido procesadas e integradas adecuadamente?',o:{a:'Modelo cognitivo de Ehlers y Clark.',b:'Teoría de la indefensión aprendida y la evaluación cognitiva.',c:'Teoría del procesamiento emocional de Foa.',d:'Teoría bifactorial de Mowrer.'},c:'c',x:'La c es correcta: Foa explica la reexperimentación por una estructura de miedo patológica y un procesamiento emocional incompleto. La a se centra en la sensación persistente de amenaza actual derivada de valoraciones negativas y características de la memoria. La b explica pasividad, culpa y síntomas depresivos ante incontrolabilidad. La d explica adquisición del miedo por condicionamiento clásico y mantenimiento de la evitación por refuerzo negativo.',r:'Foa, E. B. y Kozak, M. J. (1986). Emotional processing of fear. Psychological Bulletin, 99, 20–35. https://doi.org/10.1037/0033-2909.99.1.20; Ehlers, A. y Clark, D. M. (2000). Behaviour Research and Therapy, 38, 319–345.'},
  'MAYO-DOS-24_COMENTADO_154': {e:'Señale la afirmación INCORRECTA sobre el TEPT según el DSM-5-TR:',o:{a:'Tras traumas prolongados y graves pueden aparecer dificultades de regulación emocional, relaciones inestables o síntomas disociativos.',b:'La prevalencia anual estimada entre adultos estadounidenses es aproximadamente del 3,5 %.',c:'Los síntomas comienzan generalmente dentro de los primeros seis meses posteriores al trauma.',d:'Entre los factores de riesgo pretraumáticos se incluyen el sexo femenino y, en adultos, una edad más joven durante la exposición.'},c:'c',x:'La c es la incorrecta: el DSM-5-TR señala que los síntomas suelen comenzar dentro de los tres primeros meses, aunque el cumplimiento completo puede retrasarse meses o años. La a describe consecuencias asociadas a traumas prolongados. La b reproduce la estimación anual estadounidense citada por el manual. La d recoge factores de riesgo reconocidos. Por tanto, solo c altera el intervalo habitual de tres a seis meses.',r:'American Psychiatric Association (2022). DSM-5-TR. Trastorno de estrés postraumático, prevalencia, desarrollo y curso, y factores de riesgo y pronóstico.'},
  'MAYO-DOS-24_COMENTADO_155': {e:'Según la CIE-11, ¿qué característica nuclear del trastorno de adaptación se refiere a pensamientos recurrentes y angustiosos sobre el estresor o sus consecuencias?',o:{a:'La evitación fóbica.',b:'La impulsividad externalizante.',c:'La recuperación espontánea.',d:'La preocupación por el estresor y sus consecuencias.'},c:'d',x:'La d es correcta: la preocupación por el estresor incluye pensamientos recurrentes, rumiación e inquietud excesiva por sus consecuencias. La a puede aparecer, pero no define este núcleo. La b tampoco es una característica esencial, aunque puedan presentarse conductas problemáticas. La c describe una posible evolución al cesar el estresor, no un síntoma diagnóstico nuclear.',r:'World Health Organization (2024). ICD-11 Clinical Descriptions and Diagnostic Requirements for Mental, Behavioural or Neurodevelopmental Disorders. Adjustment disorder (6B43); Belloch, Sandín y Ramos (coords.) (2024), Manual de psicopatología, vol. II.'},
  'MAYO-DOS-24_COMENTADO_156': {e:'Según el modelo de trastorno de adaptación de Botella, Baños y Guillén, señale la afirmación correcta:',o:{a:'La persona minusvalora el estresor y magnifica sus recursos de afrontamiento.',b:'Los sentimientos de indefensión son infrecuentes.',c:'La intervención modifica creencias disfuncionales, desarrolla recursos de afrontamiento y entrena regulación emocional.',d:'El objetivo inicial es reinterpretar inmediatamente los problemas como oportunidades de crecimiento.'},c:'c',x:'La c es correcta: esos son componentes centrales de la intervención. La a invierte el modelo, pues se magnifica el estresor y se minusvaloran los recursos propios. La b es falsa porque esas valoraciones favorecen indefensión. La d confunde el objetivo final —recobrar confianza y una perspectiva de crecimiento— con el objetivo inicial.',r:'Botella, C., Baños, R. M. y Guillén, V. (2008). Creciendo en la adversidad: una propuesta de tratamiento para los trastornos adaptativos. Enfoque clínico cognitivo-conductual.'},
  'MAYO-UNO-24_COMENTADO_028': {e:'Señale la afirmación INCORRECTA sobre los criterios DSM-5-TR del TEPT:',o:{a:'La duración debe ser superior a un mes tanto en adultos como en menores de seis años.',b:'En mayores de seis años se valoran intrusión, evitación, cogniciones/estado de ánimo y activación/reactividad.',c:'La conducta imprudente o autodestructiva forma parte del criterio de activación en menores de seis años.',d:'En menores de seis años, evitación y alteraciones negativas de cognición/estado de ánimo se agrupan en un mismo criterio.'},c:'c',x:'La c es la incorrecta: la conducta imprudente o autodestructiva aparece en el conjunto de criterios para mayores de seis años, no en el subtipo preescolar. La a es correcta porque ambos exigen duración superior a un mes. La b resume los cuatro grupos sintomáticos de mayores de seis años. La d es correcta: en preescolares evitación y alteraciones negativas se combinan y basta al menos un síntoma de ese grupo.',r:'American Psychiatric Association (2022). DSM-5-TR. Trastorno de estrés postraumático y trastorno de estrés postraumático en niños de seis años o menores.'},
  'MAYO-UNO-24_COMENTADO_035': {e:'En relación con el trastorno de adaptación, señale la afirmación INCORRECTA:',o:{a:'Su diagnóstico exige comprobar que los síntomas no cumplen criterios para otro trastorno y no son una exacerbación de uno preexistente.',b:'La CIE-11 exige preocupación por el estresor o sus consecuencias y dificultad para adaptarse.',c:'Según el modelo de Botella y Baños, una autoeficacia personal elevada predispone al trastorno.',d:'Puede presentar una comorbilidad elevada con trastornos de la personalidad en muestras clínicas.'},c:'c',x:'La c es la incorrecta: el modelo destaca baja autoeficacia, escasos recursos y afrontamiento inadecuado, no autoeficacia elevada. La a refleja el criterio de exclusión DSM-5-TR. La b recoge los dos núcleos CIE-11. La d es compatible con la elevada comorbilidad descrita en muestras clínicas, aunque su magnitud varía entre estudios.',r:'American Psychiatric Association (2022). DSM-5-TR. Trastornos de adaptación; World Health Organization (2024). ICD-11 CDDR, adjustment disorder; Botella, Baños y Guillén (2008).'},
  'MAYO-UNO-24_COMENTADO_042': {e:'Según Schalinski y colaboradores, ¿qué asociación temporal se observó entre negligencia infantil y síntomas en la edad adulta?',o:{a:'La negligencia a los 4–5 años se asoció específicamente con síntomas depresivos.',b:'La negligencia a los 8–9 años se asoció específicamente con síntomas disociativos.',c:'La negligencia a los 4–5 años se asoció con síntomas disociativos en la edad adulta.',d:'La asociación dependió solo de la duración, no de la edad de exposición.'},c:'c',x:'La c es correcta: el estudio identificó una ventana de 4–5 años asociada a síntomas disociativos posteriores. La a intercambia el resultado con la sintomatología depresiva; la b también invierte las ventanas temporales; y la d es falsa porque el objetivo del estudio fue precisamente analizar el efecto diferencial del momento de exposición. Se corrige el año erróneo «2026».',r:'Schalinski, I. et al. (2016). Type and timing of adverse childhood experiences differentially affect severity of PTSD, dissociative and depressive symptoms in adult inpatients. BMC Psychiatry, 16, 295. https://doi.org/10.1186/s12888-016-1004-5.'}
};

for (const [id, patch] of Object.entries(U)) {
  const q = data.find(x => x.id === id);
  if (!q) throw new Error('No encontrado: ' + id);
  Object.assign(q, patch, {v:'VALIDADA_ORIGINAL'});
}
fs.writeFileSync(path, JSON.stringify(data));

const manifestPath='public/banco/manifest.json';
const manifest=JSON.parse(fs.readFileSync(manifestPath,'utf8'));
const topics=[...new Set(data.flatMap(q=>q.t||[]))];
manifest.subjects['Clínica Adultos'].count=data.length;
manifest.subjects['Clínica Adultos'].topics=manifest.subjects['Clínica Adultos'].topics.filter(t=>topics.includes(t));
fs.writeFileSync(manifestPath, JSON.stringify(manifest,null,2)+'\n');
console.log('Actualizadas',Object.keys(U).length);
