const fs=require('fs'),P='public/banco/';
let adult=JSON.parse(fs.readFileSync(P+'clinica_adultos.json','utf8'));
let child=JSON.parse(fs.readFileSync(P+'clinica_infantojuvenil.json','utf8'));
const DSM='American Psychiatric Association (2022). DSM-5-TR. Trastornos relacionados con traumas y factores de estrés.';
const CIE='World Health Organization (2024). ICD-11 CDDR. Disorders specifically associated with stress.';
const BEL='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. II (4.ª ed.). McGraw Hill.';
const U={
'SM_DICIEMBRE_2_SOL_1_057':{t:['Trastornos disociativos'],e:'Según Schalinski y colaboradores, ¿qué asociación se observó entre el momento de la negligencia infantil y síntomas adultos?',o:{a:'Negligencia a los 4–5 años con ansiedad y a los 8–9 con psicosis.',b:'Negligencia a los 4–5 años con psicosis y a los 8–9 con ansiedad.',c:'Negligencia a los 4–5 años con depresión y a los 8–9 con disociación.',d:'Negligencia a los 4–5 años con disociación y a los 8–9 con síntomas depresivos.'},c:'d',x:'La d es correcta: el estudio identificó ventanas temporales diferenciales, asociando 4–5 años con disociación adulta y 8–9 con depresión. Las opciones a, b y c intercambian los resultados o introducen ansiedad/psicosis no correspondientes. Se reubica en trastornos disociativos por el constructo principal.',r:'Schalinski, I. et al. (2016). Type and timing of adverse childhood experiences differentially affect severity of PTSD, dissociative and depressive symptoms in adult inpatients. BMC Psychiatry, 16, 295. https://doi.org/10.1186/s12888-016-1004-5.'},
'SM_JUNIO_1_SOL_1_052':{e:'Señale la afirmación INCORRECTA sobre el TEPT:',o:{a:'La duración y prevalencia son similares en hombres y mujeres.',b:'Los problemas emocionales infantiles y los trastornos mentales previos son factores de riesgo.',c:'Una mayor gravedad del trauma incrementa el riesgo.',d:'El abuso infantil se asocia con mayor riesgo de conducta suicida.'},c:'a',x:'La a es incorrecta: prevalencia y duración suelen ser mayores en mujeres. La b recoge factores temperamentales pretraumáticos. La c es compatible con una relación dosis-respuesta. La d es correcta porque el abuso infantil incrementa el riesgo suicida y de otros desenlaces adversos.',r:DSM},
'SmCm06PIR2025_031':{e:'¿Cuántos síntomas exige el criterio B del trastorno de estrés agudo?',o:{a:'Cinco.',b:'Siete.',c:'Nueve.',d:'Once.'},c:'c',x:'La c es correcta: se requieren nueve o más síntomas de cualquiera de las cinco categorías. Las opciones a, b y d proponen umbrales distintos del DSM-5-TR.',r:DSM},
'SmCm08PIR2025_168':{e:'¿Cuál NO es un factor predisponente previo al trauma?',o:{a:'Exposición previa a traumas.',b:'Gravedad del acontecimiento traumático.',c:'Personalidad vulnerable.',d:'Estrés acumulativo.'},c:'b',x:'La b es correcta: la gravedad pertenece al propio acontecimiento precipitante. La a, c y d están presentes antes del trauma y aumentan vulnerabilidad.',r:BEL},
'SmCm10PIR2025_019':{e:'¿Para qué trastorno desarrolló el grupo de Maercker un modelo que integra estresor, preocupación, fracaso de adaptación y deterioro funcional?',o:{a:'TEPT.',b:'Trastorno de estrés agudo.',c:'Trastorno de adaptación.',d:'Trastorno de apego reactivo.'},c:'c',x:'La c es correcta: Maercker y colaboradores desarrollaron un modelo para el trastorno de adaptación que influyó en su conceptualización CIE-11. La a y b requieren trauma del criterio A; la d es un trastorno infantil vinculado con cuidados insuficientes.',r:'Maercker, A. et al. (2013). Diagnosis and classification of disorders specifically associated with stress: proposals for ICD-11. World Psychiatry, 12, 198–206. https://doi.org/10.1002/wps.20057.'},
'SmCm10PIR2025_020':{e:'¿Qué clasificación incluye formalmente el trastorno de estrés postraumático complejo?',o:{a:'DSM-IV-TR.',b:'DSM-5-TR.',c:'CIE-10.',d:'CIE-11.'},c:'d',x:'La d es correcta: la CIE-11 incluye TEPT complejo como diagnóstico propio. DSM-IV-TR, DSM-5-TR y CIE-10 no lo incorporan como entidad independiente.',r:CIE+' Complex PTSD (6B41).'},
'SmCm11PIR2025_171':{e:'¿En qué grupo se incluyen los flashbacks o reacciones disociativas del TEPT en mayores de seis años?',o:{a:'Intrusión.',b:'Evitación.',c:'Alteraciones cognitivas y afectivas.',d:'Activación y reactividad.'},c:'a',x:'La a es correcta: los flashbacks forman parte del criterio B de intrusión. Las restantes opciones corresponden a otros grupos diagnósticos.',r:DSM},
'SmCm12PIR2024 2_034':{e:'Las creencias negativas persistentes y exageradas sobre uno mismo, los demás o el mundo en el TEPT pertenecen a:',o:{a:'Activación y reactividad.',b:'Evitación.',c:'Alteraciones negativas de cognición y estado de ánimo.',d:'Intrusión.'},c:'c',x:'La c es correcta y corresponde al criterio D. La a incluye irritabilidad, hipervigilancia y sobresalto; b, evitación de recuerdos o claves; y d, recuerdos, sueños y flashbacks.',r:DSM},
'SmCm13PIR2025_054':{e:'Señale la afirmación INCORRECTA sobre el trastorno de adaptación:',o:{a:'Afecta aproximadamente al 30 % de todos los pacientes ambulatorios y al 60 % de todos los hospitalizados, con independencia del contexto.',b:'La conducta suicida puede relacionarse con conflictos interpersonales y problemas económicos.',c:'Puede asociarse con disminución del rendimiento y cambios transitorios en relaciones sociales.',d:'La valoración del estresor y de la respuesta depende del contexto cultural.'},c:'a',x:'La a es incorrecta: presenta cifras rígidas y universaliza estimaciones que varían ampliamente por población, servicio y método. La b, c y d son características clínicas reconocidas: riesgo suicida ligado al estresor, deterioro funcional transitorio y necesidad de considerar la cultura.',r:DSM},
'SmCm13PIR2025_055':{e:'¿Qué criterio temporal distingue el TEPT del trastorno de estrés agudo?',o:{a:'En el TEPT la alteración dura más de un mes.',b:'En el TEPT debe durar más de tres meses.',c:'En el TEPT debe durar más de seis meses.',d:'En el TEPT debe durar más de un año.'},c:'a',x:'La a es correcta: el TEPT exige duración superior a un mes; el estrés agudo dura de tres días a un mes. Las opciones b, c y d corresponden a límites que el DSM-5-TR no exige. Se elimina el antiguo especificador DSM-IV de TEPT crónico superior a tres meses.',r:DSM},
'SmCm14PIR2025_073':{t:['TOC'],e:'¿Cuál de los siguientes trastornos presenta, en términos generales, una distribución por sexo más equilibrada?',o:{a:'Agorafobia.',b:'Trastorno de estrés postraumático.',c:'Trastorno obsesivo-compulsivo.',d:'Trastorno depresivo mayor.'},c:'c',x:'La c es correcta: el TOC adulto muestra una distribución por sexo aproximadamente similar. Agorafobia, TEPT y depresión mayor son más frecuentes en mujeres. Se reubica en TOC.',r:'American Psychiatric Association (2022). DSM-5-TR. Trastorno obsesivo-compulsivo, prevalencia y aspectos relacionados con sexo y género.'},
'SmCm14PIR2025_075':{e:'Para que el conocimiento de la muerte de un familiar o amigo íntimo cumpla el criterio A del trastorno de estrés agudo, la muerte debe haber sido:',o:{a:'Provocada necesariamente por otra persona.',b:'Presenciada directamente.',c:'Esperada por enfermedad natural.',d:'Violenta o accidental.'},c:'d',x:'La d es correcta: cuando el suceso se conoce indirectamente, la muerte o amenaza debe ser violenta o accidental. La a es demasiado restrictiva; b describe otra vía de exposición; y c no cumple esa condición.',r:DSM},
'SmCm15PIR2025_036':{e:'¿Cuál NO es un síntoma negativo descrito en la caracterización clínica clásica del TEPT?',o:{a:'Evitación.',b:'Apatía.',c:'Embotamiento afectivo.',d:'Sensación de indefensión.'},c:'a',x:'La a es correcta según la clasificación concreta del manual: la evitación se agrupa con respuestas activas/positivas, mientras apatía, embotamiento e indefensión se describen como negativas. Esta clasificación no debe confundirse con los cuatro grupos DSM-5-TR.',r:BEL+' Capítulo sobre TEPT.'},
'SmCm17PIR2025_010':{e:'Respecto a la evolución temporal tras un trauma, señale la afirmación INCORRECTA:',o:{a:'Tras la fase inmediata pueden aparecer ansiedad, depresión, pérdida de autoestima y culpa.',b:'A medio plazo pueden aparecer irritabilidad, dependencia, pasividad y embotamiento.',c:'A corto plazo se produce una transformación persistente de la personalidad que mejora rápidamente.',d:'A largo plazo el trauma puede presentarse de forma enmascarada mediante depresión, sueño alterado, alcohol o distanciamiento.'},c:'c',x:'La c es incorrecta: una transformación persistente, por definición, no es una reacción breve ni necesariamente mejora rápidamente. La a y b recogen manifestaciones posteriores tempranas e intermedias. La d describe presentaciones tardías o indirectas posibles.',r:BEL},
'SmCm18PIR2025_068':{e:'¿Cuál es un factor peritraumático de riesgo de TEPT?',o:{a:'Que el trauma sea perpetrado por un cuidador.',b:'Adversidad infantil previa.',c:'Un trastorno mental previo.',d:'Exposición repetida a recordatorios después del trauma.'},c:'a',x:'La a es correcta porque caracteriza el contexto del acontecimiento. La b y c son factores pretraumáticos. La d es postraumática.',r:DSM},
'SmCm18PIR2025_069':{e:'¿Cuál NO es un indicador favorable de recuperación tras TEPT?',o:{a:'Recuperar la expresión verbal de sentimientos.',b:'Reaparecer expresiones gestuales de afecto.',c:'Retomar actividades lúdicas cotidianas.',d:'Usar evasión mental como afrontamiento.'},c:'d',x:'La d es correcta: la evasión mantiene evitación y dificulta procesamiento. La a, b y c reflejan recuperación emocional, interpersonal y conductual.',r:BEL},
'SmCm19PIR2024_063':{e:'¿Qué afirmación corresponde a la teoría del procesamiento emocional de Foa y Kozak aplicada al TEPT?',o:{a:'Los sentimientos extremos predicen por sí solos el curso.',b:'La incontrolabilidad genera exclusivamente indefensión aprendida.',c:'Botella y Baños explican así el trastorno de adaptación.',d:'Una estructura cognitiva de miedo patológico explica la reexperimentación y debe modificarse mediante procesamiento emocional.'},c:'d',x:'La d es correcta: Foa y Kozak describen estructuras de miedo con asociaciones erróneas. La a es insuficiente; b corresponde a indefensión aprendida; y c al modelo del trastorno de adaptación.',r:'Foa, E. B. y Kozak, M. J. (1986). Emotional processing of fear. Psychological Bulletin, 99, 20–35. https://doi.org/10.1037/0033-2909.99.1.20.'},
'SmCm21PIR2025 (2)_042':{e:'¿Qué acontecimiento presenta mayor riesgo condicional de TEPT entre los siguientes?',o:{a:'Terremoto.',b:'Accidente de tráfico.',c:'Agresión sexual.',d:'Accidente ferroviario.'},c:'c',x:'La c es correcta: la violencia sexual interpersonal se asocia con riesgo condicional especialmente alto. Los accidentes y desastres pueden causar TEPT, pero su probabilidad media es menor.',r:DSM+' Apartado de prevalencia y factores de riesgo.'},
'SmCm22PIR2025 (1)_060':{e:'¿Cuál NO forma parte de las alteraciones de autoorganización características del TEPT complejo?',o:{a:'Problemas persistentes de regulación afectiva.',b:'Autoconcepto negativo.',c:'Dificultades persistentes en las relaciones.',d:'Deseos de morir como requisito diagnóstico obligatorio.'},c:'d',x:'La d es correcta: la ideación suicida puede aparecer, pero no es requisito nuclear. Las opciones a, b y c constituyen los tres dominios de alteración de autoorganización de la CIE-11.',r:CIE+' Complex PTSD (6B41).'},
'SmCm22PIR2025 (1)_061':{e:'¿Cuál es una característica nuclear del TEPT en la CIE-11?',o:{a:'Los síntomas deben comenzar siempre dentro de seis meses.',b:'La percepción persistente de amenaza actual puede manifestarse mediante sobresalto exagerado.',c:'La reviviscencia debe darse simultáneamente en varias modalidades sensoriales.',d:'Se exige invariablemente una duración mínima exacta de un mes.'},c:'b',x:'La b es correcta: la amenaza actual se expresa mediante hipervigilancia o sobresalto aumentado. La a impone un inicio que CIE-11 no exige siempre. La c es falsa porque la reviviscencia no requiere varias modalidades. La d transforma una guía temporal en un umbral rígido no formulado así por CIE-11.',r:CIE+' Post traumatic stress disorder (6B40).'},
'SmCm22PIR2025_028':{e:'¿Qué modelo sostiene que el TEPT persiste porque la persona procesa el trauma de modo que genera una sensación de amenaza actual?',o:{a:'Procesamiento emocional de Foa y Kozak.',b:'Modelo cognitivo de Ehlers y Clark.',c:'Indefensión aprendida.',d:'Representación dual de Brewin.'},c:'b',x:'La b es correcta: Ehlers y Clark sitúan la amenaza actual como núcleo. La a se centra en estructuras de miedo; c, incontrolabilidad; y d, dos sistemas de memoria traumática.',r:'Ehlers, A. y Clark, D. M. (2000). A cognitive model of PTSD. Behaviour Research and Therapy, 38, 319–345. https://doi.org/10.1016/S0005-7967(99)00123-0.'},
'SmCm24PIR2025 (1)_009':{e:'¿Cuál NO es un factor de riesgo reconocido para desarrollar TEPT?',o:{a:'Ser mujer.',b:'Elevada activación fisiológica durante o inmediatamente después del trauma.',c:'Estar casado, por sí mismo.',d:'Mayor intensidad y duración del trauma.'},c:'c',x:'La c es correcta: el estado civil aislado no constituye un factor de riesgo general. La a, b y d se asocian con mayor probabilidad de TEPT.',r:DSM},
'SmCm25PIR2025_028':{e:'¿Qué modelo propone que el trauma se representa mediante memoria verbalmente accesible y memoria situacionalmente accesible?',o:{a:'Indefensión aprendida.',b:'Procesamiento emocional de Foa.',c:'Representación dual de Brewin.',d:'Modelo cognitivo de Ehlers y Clark.'},c:'c',x:'La c es correcta: Brewin distingue representaciones verbalmente y situacionalmente accesibles. La a explica incontrolabilidad; b, estructuras de miedo; y d, amenaza actual y memoria poco elaborada.',r:'Brewin, C. R., Dalgleish, T. y Joseph, S. (1996). A dual representation theory of PTSD. Psychological Review, 103, 670–686. https://doi.org/10.1037/0033-295X.103.4.670.'},
'SmCm25PIR2025_046':{e:'¿Cuál es un problema vigente en la delimitación del trastorno de adaptación?',o:{a:'La facilidad absoluta para separarlo de respuestas normales.',b:'La existencia de marcadores positivos altamente específicos.',c:'El solapamiento y la diferenciación respecto a otros cuadros.',d:'La sólida validación de todos sus subtipos.'},c:'c',x:'La c es correcta: existe solapamiento con depresión, ansiedad y respuestas normales. La a y b niegan esa dificultad. La d es falsa porque la evidencia de los subtipos ha sido cuestionada.',r:BEL},
'SmCm25PIR2025_049':{t:['Trastornos depresivos'],e:'¿A qué especificador depresivo pertenece la parálisis plúmbea?',o:{a:'Con características mixtas.',b:'Con características melancólicas.',c:'Con características atípicas.',d:'Con características psicóticas.'},c:'c',x:'La c es correcta: la parálisis plúmbea —sensación intensa de pesadez en brazos o piernas— forma parte de las características atípicas. La a combina síntomas maníacos/hipomaníacos; b se asocia con anhedonia, falta de reactividad y cambios vegetativos; d requiere delirios o alucinaciones. Se reconstruye y reubica el registro, que estaba gravemente contaminado.',r:'American Psychiatric Association (2022). DSM-5-TR. Especificador «con características atípicas» para trastornos depresivos.'},
'SmCm29PIR2025_054':{e:'Señale la afirmación INCORRECTA sobre los cambios DSM-5 en el TEPT:',o:{a:'La duración mínima pasó de más de un mes a más de tres meses.',b:'Se diferenciaron criterios para menores de seis años.',c:'Se incorporó el comportamiento imprudente o autodestructivo en activación/reactividad.',d:'Las reacciones fisiológicas intensas ante recordatorios se incluyen en intrusión.'},c:'a',x:'La a es incorrecta: la duración continuó siendo superior a un mes. La b, c y d reflejan criterios DSM-5. Se corrige la clave original c.',r:DSM},
'SmCm29PIR2025_067':{e:'Desde una perspectiva psicológica amplia, ¿qué característica es menos necesaria para que una experiencia se viva como traumática?',o:{a:'Valoración extremadamente negativa.',b:'Sensación de falta de control.',c:'Carácter repentino o inesperado.',d:'Existencia objetiva de peligro físico o muerte.'},c:'d',x:'La d es correcta en la formulación psicológica amplia: puede existir traumatización sin peligro físico objetivo, aunque el criterio A DSM para TEPT sea más restrictivo. La valoración negativa, incontrolabilidad e imprevisibilidad aumentan el impacto. No debe confundirse «experiencia traumática» amplia con el criterio diagnóstico A.',r:BEL},
'SmCm2PIR2024_066':{e:'Desde el condicionamiento aplicado a víctimas de agresiones sexuales, señale la afirmación correcta:',o:{a:'Las víctimas presentan más miedo y ansiedad que las no víctimas.',b:'La repetición reduce necesariamente el miedo.',c:'La ansiedad anticipatoria no favorece evitación.',d:'Las claves asociadas siguen siendo estímulos incondicionados.'},c:'a',x:'La a es correcta. La b es falsa porque la repetición puede intensificar y generalizar miedo. La c es falsa porque la anticipación favorece evitación. La d es falsa porque claves inicialmente neutras adquieren función condicionada.',r:BEL},
'SmCm30PIR2025 (1)_036':{e:'¿Cuál es un factor postraumático de mantenimiento?',o:{a:'Personalidad vulnerable.',b:'Estrés acumulativo.',c:'Gravedad del trauma.',d:'Anclaje persistente en el pasado.'},c:'d',x:'La d es correcta. La a y b son predisponentes; c pertenece al acontecimiento precipitante.',r:BEL},
'SmCm30PIR2025 (1)_048':{e:'¿Qué afirmación sobre sexo y riesgo de TEPT es correcta?',o:{a:'El riesgo femenino es menor en preescolares.',b:'A lo largo de la vida el riesgo es mayor en mujeres.',c:'En mayores el riesgo es necesariamente mayor en hombres.',d:'En mediana edad el riesgo femenino es menor.'},c:'b',x:'La b es correcta: el TEPT es más frecuente en mujeres durante la vida. Las opciones a, c y d invierten o absolutizan patrones no respaldados.',r:DSM},
'SmCm11PIR2025_049':{e:'¿Cuántos síntomas se requieren para diagnosticar trastorno de estrés agudo?',o:{a:'Cinco.',b:'Siete.',c:'Nueve.',d:'Once.'},c:'c',x:'La c es correcta: el DSM-5-TR exige nueve o más síntomas. Las restantes cifras no corresponden al umbral. Se reconstruyen las opciones vacías y se corrige la clave.',r:DSM}
};
for(const [id,p] of Object.entries(U)){const q=adult.find(x=>x.id===id);if(!q)throw Error(id);Object.assign(q,p,{v:'VALIDADA_ORIGINAL'});}
const move='SmCm19PIR2024_062',i=adult.findIndex(q=>q.id===move);if(i<0)throw Error(move);const q=adult.splice(i,1)[0];Object.assign(q,{s:'Clínica Infantojuvenil',t:['Trastornos relacionados con traumas y factores de estrés infantojuveniles'],e:'En menores de seis años con TEPT, ¿cuál pertenece a las alteraciones negativas de cognición y estado de ánimo?',o:{a:'Evitar conversaciones y encuentros.',b:'Arrebatos de ira.',c:'Conducta socialmente retraída.',d:'Problemas de concentración.'},c:'c',x:'La c es correcta: la conducta socialmente retraída figura en el criterio C preescolar. La a corresponde a evitación; b y d a activación/reactividad. Se reubica en trauma infantojuvenil.',r:DSM+' Criterios para niños de seis años o menores.',v:'VALIDADA_ORIGINAL'});child.push(q);
fs.writeFileSync(P+'clinica_adultos.json',JSON.stringify(adult));fs.writeFileSync(P+'clinica_infantojuvenil.json',JSON.stringify(child));
const mp=P+'manifest.json',m=JSON.parse(fs.readFileSync(mp));m.subjects['Clínica Adultos'].count=adult.length;m.subjects['Clínica Infantojuvenil'].count=child.length;fs.writeFileSync(mp,JSON.stringify(m,null,2)+'\n');
console.log(JSON.stringify({updated:Object.keys(U).length,moved:move,adult:adult.length,child:child.length}));
