const fs=require('fs'),p='public/banco/clinica_adultos.json',a=JSON.parse(fs.readFileSync(p));
const DSM='American Psychiatric Association (2022). DSM-5-TR. Capítulo «Trastornos disociativos». Editorial Médica Panamericana.';
const BEL='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. II (4.ª ed.). McGraw Hill, cap. 8, pp. 295–322.';
const U={
'JULIO2_050':{x:'La a es correcta: el DSM-5-TR destaca la comorbilidad del trastorno de identidad disociativo con los trastornos límite y evitativo de la personalidad. La b añade el dependiente, que no integra esta asociación específica; la c sustituye el evitativo por el obsesivo-compulsivo; y la d omite el patrón límite.',r:DSM+' '+BEL},
'OCTUBRE-UNO-24_COMENTADO_035':{x:'La d es correcta: en el trastorno de despersonalización/desrealización se describen especialmente los patrones evitativo, límite y obsesivo-compulsivo. Las opciones a, b y c combinan trastornos que no forman el conjunto específico señalado por el manual.',r:DSM+' '+BEL},
'PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-DOS-23_023':{x:'La b es correcta: en la amnesia disociativa se señala comorbilidad especialmente con los trastornos dependiente, evitativo y límite de la personalidad. Las opciones a, c y d omiten alguno de ellos o introducen patrones no incluidos en esa asociación concreta.',r:DSM+' '+BEL},
'PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-DOS-23_036':{x:'La d es correcta: Hilgard concibe sistemas o estructuras cognitivas organizados jerárquicamente que pueden buscar o evitar entradas y facilitar o inhibir salidas. La a introduce una desconexión cerebelosa ajena a la teoría; la b formula incorrectamente sus fenómenos centrales; y la c niega la organización jerárquica postulada.',r:'Hilgard, E. R. (1977). Divided Consciousness: Multiple Controls in Human Thought and Action. Wiley; '+BEL},
'PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-DOS-23_079':{e:'¿Qué sentimientos se han relacionado con la amnesia disociativa posterior a sucesos traumáticos?',o:{a:'Reexperimentación, evitación, activación y alteraciones cognitivas.',b:'Culpa, rabia y vergüenza.',c:'Respuestas de alarma y pesadillas.',d:'Tristeza y conducta violenta, necesariamente.'},c:'b',x:'La b es correcta: culpa, rabia y vergüenza pueden favorecer la evitación o inaccesibilidad de recuerdos traumáticos desagradables. La a enumera grupos sintomáticos del TEPT, no sentimientos explicativos; la c mezcla activación e intrusión; y la d combina manifestaciones inespecíficas y las presenta indebidamente como necesarias.',r:BEL},
'Simu 15 comentado_080':{e:'¿Qué trastorno se define por la incapacidad para recordar información autobiográfica importante, generalmente traumática o estresante, incompatible con el olvido ordinario?',o:{a:'Amnesia disociativa.',b:'Trastorno de identidad disociativo.',c:'Trastorno de despersonalización/desrealización.',d:'Fuga disociativa.'},c:'a',x:'La a es correcta y reproduce el núcleo diagnóstico de la amnesia disociativa. La b exige además una perturbación de identidad con dos o más estados; la c se caracteriza por despersonalización o desrealización con juicio de realidad intacto; y la fuga es un especificador de desplazamiento aparentemente intencionado asociado a amnesia, no el diagnóstico general definido.',r:DSM},
'SM_JULIO_1_SOL_1_038':{x:'La a es correcta: la alteración de identidad debida a persuasión coercitiva intensa y prolongada es un ejemplo de «otro trastorno disociativo especificado». La pseudociesis se clasifica entre síntomas somáticos y relacionados; el ataque de nervios es un concepto cultural de malestar; y jikoshu-kyofu se relaciona con temor interpersonal de emitir una apariencia u olor ofensivos.',r:DSM},
'SM_DICIEMBRE_2_SOL_1_041':{t:['Trastornos por síntomas somáticos y relacionados'],e:'La pseudociesis —creencia falsa de estar embarazada acompañada de signos y síntomas de embarazo— se clasifica en el DSM-5-TR como:',o:{a:'Un trastorno disociativo independiente.',b:'Un trastorno delirante necesariamente.',c:'Otro trastorno de síntomas somáticos y trastornos relacionados especificado.',d:'Otro trastorno disociativo especificado.'},c:'c',x:'La c es correcta: el DSM-5-TR incluye la pseudociesis como ejemplo de otro trastorno de síntomas somáticos y trastornos relacionados especificado. La a es falsa porque no constituye un diagnóstico disociativo independiente; la b es demasiado absoluta y no refleja su clasificación; y la d la sitúa erróneamente entre los trastornos disociativos especificados.',r:'American Psychiatric Association (2022). DSM-5-TR. «Otro trastorno de síntomas somáticos y trastornos relacionados especificado». Editorial Médica Panamericana.'}
};
for(const [id,z] of Object.entries(U)){const q=a.find(x=>x.id===id);if(!q)throw Error(id);Object.assign(q,z,{v:'VALIDADA_ORIGINAL'});}
fs.writeFileSync(p,JSON.stringify(a));console.log({validated:Object.keys(U).length});
