const fs=require('fs'),path=require('path'),file=path.join(__dirname,'..','public','banco','clinica_adultos.json'),bank=JSON.parse(fs.readFileSync(file,'utf8'));
const ids=['Simu 6 comentado__071','Simu 7 comentado _098','Simu 7 comentado _111','Simu 8 comentado _047','Simu 8 comentado _050','simu 9 comentado_082','SM_ABRIL_1_SOL_1_028','SM_ABRIL_2_SOL_1_056','SM_ABRIL_2_SOL_1_060','SM_ABRIL_2_SOL_1_091','SM_AGOSTO_1_SOL_1_086','SM_DICIEMBRE_1_SOL_1_020','SM_DICIEMBRE_2_SOL_1_043','SM_DICIEMBRE_2_SOL_1_072','SM_ENERO_1_SOL_1_100','SM_JULIO_1_SOL_1_041','SM_JULIO_1_SOL_1_044','SM_JULIO_1_SOL_1_204','SM_JULIO_2_SOL_1_037','SM_JULIO_2_SOL_1_050'];
const X={
'Simu 6 comentado__071':'La c es correcta: el trastorno ciclotímico suele comenzar de forma insidiosa en la adolescencia o adultez temprana. Las restantes opciones convierten cifras variables o antecedentes no necesarios en criterios.',
'Simu 7 comentado _098':'La c es correcta: ciclos rápidos exige al menos cuatro episodios afectivos en doce meses, separados por remisión total o parcial de al menos dos meses o por cambio de polaridad.',
'Simu 7 comentado _111':'La b es correcta: la manía dura al menos una semana, salvo hospitalización. La depresión mayor exige dos semanas y la hipomanía cuatro días; «episodio afectivo» no establece una duración única.',
'Simu 8 comentado _047':'La c es correcta: la hipomanía produce un cambio inequívoco y observable, pero no deterioro marcado, hospitalización ni psicosis. La gravedad o psicosis hacen que el episodio se considere maníaco.',
'Simu 8 comentado _050':'La b es correcta en el supuesto planteado: describe un viraje desde polaridad depresiva hacia manía o hipomanía durante tratamiento. No se limita siempre a una dirección ni se define por intervalos fijos de remisión.',
'simu 9 comentado_082':'La b es correcta: el tipo bipolar I½ de Akiskal describe episodios hipomaníacos sin episodios depresivos. Es una clasificación de espectro y no una categoría oficial DSM-5-TR.',
'SM_ABRIL_1_SOL_1_028':'La b es correcta: la recuperación funcional, especialmente ocupacional, suele quedar rezagada respecto a la remisión sintomática. No siempre hay recuperación completa ni inmediata entre episodios.',
'SM_ABRIL_2_SOL_1_056':'La a es correcta: una primera manía tardía exige descartar afecciones neurológicas o médicas y efectos de sustancias o medicamentos. La edad no confirma bipolaridad primaria ni elimina causas secundarias.',
'SM_ABRIL_2_SOL_1_060':'La a es correcta: en la comparación clínica clásica, la depresión puede mostrar mejoría vespertina. La manía es más distraíble, las quejas subjetivas de memoria son más depresivas y la conciencia suele reducirse en manía.',
'SM_ABRIL_2_SOL_1_091':'La d es correcta: el parto puede desencadenar hipomanía temprana y se han descrito tasas del 10-20 % en muestras no clínicas. La discapacidad de bipolar II procede sobre todo de la depresión; la creatividad puede dificultar buscar tratamiento; su inicio suele ser posterior a bipolar I y anterior a depresión mayor.',
'SM_AGOSTO_1_SOL_1_086':'La c es incorrecta y es la respuesta: la pérdida de apetito se describe más en depresión unipolar. Atipicidad, catatonía e hipersomnia aparecen con mayor frecuencia en depresión bipolar.',
'SM_DICIEMBRE_1_SOL_1_020':'La c es correcta: bipolar I½ en la clasificación de Akiskal corresponde a hipomanía sin episodios depresivos. No debe confundirse con las categorías DSM de bipolar I o II.',
'SM_DICIEMBRE_2_SOL_1_043':'La a es correcta: en población general la ciclotimia presenta frecuencia semejante por sexo. En menores exige un año, no dos, y presenta períodos sintomáticos subumbrales, no episodios completos.',
'SM_DICIEMBRE_2_SOL_1_072':'La b es correcta: la conciencia de enfermedad suele estar muy reducida en manía y mejor conservada en depresión. Las demás opciones invierten los patrones de apetito, deseo sexual y memoria.',
'SM_ENERO_1_SOL_1_100':'La a es correcta: ante una primera manía en edad tardía deben investigarse causas médicas, neurológicas, tóxicas y farmacológicas. Las demás opciones excluyen injustificadamente ese diagnóstico diferencial.',
'SM_JULIO_1_SOL_1_041':'La a es correcta: quejas somáticas, insomnio, pérdida de apetito y ansiedad se describen más en depresión unipolar. Cronicidad, riesgo suicida y agregación familiar son mayores en bipolaridad.',
'SM_JULIO_1_SOL_1_044':'La a es correcta: la conciencia suele conservarse más en depresión y estar marcadamente reducida en manía. Las opciones b, c y d invierten los patrones de conducta, sexualidad y memoria.',
'SM_JULIO_1_SOL_1_204':'La b es correcta: el DSM-5-TR recoge que aproximadamente el 60 % de las personas con bipolar II presenta tres o más trastornos mentales concurrentes. Ansiedad y consumo son frecuentes, pero no exclusivos.',
'SM_JULIO_2_SOL_1_037':'La c es correcta: la prevalencia de bipolar I es aproximadamente semejante en mujeres y hombres. Sí existen diferencias en presentación, como mayor frecuencia de ciclos rápidos y rasgos mixtos en mujeres.',
'SM_JULIO_2_SOL_1_050':'La d es falsa y es la respuesta: esa duración de dos años y presencia sintomática durante la mitad del tiempo corresponde a ciclotimia. Ciclos rápidos exige cuatro o más episodios en doce meses con separación válida.'};
let n=0;for(const q of bank)if(ids.includes(q.id)){q.x=X[q.id];q.v='VALIDADA_ORIGINAL';if(q.id==='simu 9 comentado_082')q.e='Según la clasificación de Akiskal, ¿qué tipo bipolar se caracteriza por episodios hipomaníacos sin episodios depresivos?';n++;}if(n!==20)throw Error(`Expected 20, got ${n}`);fs.writeFileSync(file,JSON.stringify(bank));console.log(`Audited ${n}.`);
