const fs=require('fs');
const ap='public/banco/tratamientos_adultos.json',cp='public/banco/tratamientos_infantiles.json';
const a=JSON.parse(fs.readFileSync(ap,'utf8')),child=JSON.parse(fs.readFileSync(cp,'utf8')),m=new Map(a.map(q=>[q.id,q]));
const F='Fonseca Pedrero, E. (coord.) (2021). Manual de tratamientos psicológicos: Adultos. Pirámide.';
const B='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. II (4.ª ed.). McGraw Hill.';
function set(id,z){const q=m.get(id);if(!q)throw Error(id);Object.assign(q,z,{v:'VALIDADA_ORIGINAL'});}
function move(id,target,topic){const i=a.findIndex(q=>q.id===id);if(i<0)throw Error('move '+id);const[q]=a.splice(i,1);q.t=[topic];q.v='REVISAR';if(!target.some(x=>x.id===id))target.push(q);}
for(const [id,topic] of [
 ['SmCm15PIR2025_147','Tratamiento de los trastornos neurocognitivos'],['SmCm16PIR2025_141','Tratamiento de los trastornos de ansiedad'],
 ['SmCm16PIR2025_158','Tratamientos transdiagnósticos'],['SmCm17PIR2025_009','Tratamiento de la psicosis y esquizofrenia'],
 ['SmCm18PIR2025_162','Tratamiento de los trastornos somáticos'],['SmCm19PIR2024_122','Componentes y eficacia de la psicoterapia'],
 ['SmCm19PIR2024_152','Tratamiento de las adicciones'],['SmCm20PIR2025 (1)_185','Tratamiento de los trastornos de ansiedad'],
 ['SmCm22PIR2025 (1)_034','Tratamiento del TOC y relacionados'],['SmCm22PIR2025 (1)_110','Tratamiento de los trastornos neurocognitivos'],
 ['SmCm25PIR2025_148','Tratamiento de los trastornos somáticos'],['SmCm25PIR2025_165','Tratamiento de la psicosis y esquizofrenia']
])move(id,a,topic);
for(const [id,topic] of [['SmCm1PIR2024_209','Tratamientos transdiagnósticos infantojuveniles'],['SmCm26PIR2025_034','Trastornos depresivos y bipolares infantojuvenil']])move(id,child,topic);

set('SmCm09PIR2025_024',{e:'En términos generales, ¿qué diferencia puede observarse entre antidepresivos y psicoterapia estructurada durante el tratamiento agudo de la depresión?',o:{a:'Los fármacos son siempre más eficaces en cualquier depresión grave.',b:'La medicación puede producir una mejoría inicial más rápida.',c:'La medicación previene necesariamente mejor las recaídas tras retirarla.',d:'Ambos tratamientos producen el mismo tipo y frecuencia de efectos adversos.'},c:'b',x:'La farmacoterapia puede mostrar una respuesta más rápida al comienzo. La eficacia relativa depende del cuadro; las psicoterapias pueden ofrecer efectos más persistentes tras finalizar y no comparten el perfil de efectos adversos farmacológicos.',r:F});
for(const id of ['SmCm10PIR2025_074','SmCm16PIR2025_139'])set(id,{e:'¿Qué terapia para la depresión utiliza los acrónimos TRAP y TRAC?',o:{a:'Terapia de aceptación y compromiso.',b:'Terapia centrada en la compasión.',c:'Activación conductual.',d:'Terapia cognitiva basada en mindfulness.'},c:'c',x:'La activación conductual emplea TRAP para identificar desencadenante, respuesta y patrón de evitación, y TRAC para sustituir la evitación por una respuesta alternativa de afrontamiento.',r:'Martell, C. R., Dimidjian, S. y Herman-Dunn, R. (2010). Behavioral Activation for Depression. Guilford Press.'});
set('SmCm10PIR2025_075',{e:'¿Qué tres grupos de habilidades se trabajan en el entrenamiento en habilidades sociales para la depresión de Lewinsohn?',o:{a:'Aserción positiva, aserción negativa y habilidades conversacionales.',b:'Relajación, exposición y prevención de respuesta.',c:'Ensayo de conducta, modelado y reforzamiento como tres habilidades finales.',d:'Atención plena, aceptación y defusión.'},c:'a',x:'El programa trabaja expresar reconocimiento positivo, defender o expresar desacuerdo de forma adecuada y mantener conversaciones. Ensayo, modelado y feedback son procedimientos para enseñarlas.',r:F});
set('SmCm10PIR2025_083',{e:'Respecto a la terapia centrada en la familia para el trastorno bipolar, señale la afirmación falsa:',o:{a:'Adapta estrategias familiares empleadas previamente en esquizofrenia.',b:'Se realiza únicamente con el paciente, sin participación de familiares o cuidadores.',c:'Incluye psicoeducación, entrenamiento en comunicación y solución de problemas.',d:'Se utiliza como complemento del tratamiento farmacológico.'},c:'b',x:'La FFT implica al paciente y a familiares o cuidadores significativos. Sus módulos centrales son psicoeducación, mejora de la comunicación y solución de problemas, generalmente junto con farmacoterapia.',r:'Miklowitz, D. J. y Goldstein, M. J. (1997). Bipolar Disorder: A Family-Focused Treatment Approach. Guilford Press.'});
set('SmCm12PIR2024 2_117',{e:'¿Para qué se utiliza el diagrama TRAP en activación conductual para la depresión?',o:{a:'Para establecer una causa etiológica única de la depresión.',b:'Para prescribir directamente una respuesta alternativa sin analizar el patrón.',c:'Para identificar desencadenante, respuesta emocional o conductual y patrón de evitación que mantienen el problema.',d:'Para clasificar esquemas cognitivos nucleares.'},c:'c',x:'TRAP organiza Trigger, Response y Avoidance Pattern y facilita comprender ciclos de evitación. TRAC añade la respuesta alternativa de afrontamiento para romperlos.',r:'Martell, C. R., Dimidjian, S. y Herman-Dunn, R. (2010). Behavioral Activation for Depression. Guilford Press.'});
set('SmCm12PIR2024 2_120',{e:'¿Qué componente NO pertenece al Curso para el Afrontamiento de la Depresión de Lewinsohn?',o:{a:'Entrenamiento en habilidades sociales.',b:'Entrenamiento formal en mindfulness como módulo central original.',c:'Planificación para mantener las ganancias y afrontar el futuro.',d:'Modificación de cogniciones y estrategias de relajación.'},c:'b',x:'El CAD original incluye actividades agradables, habilidades sociales, modificación cognitiva, relajación y mantenimiento. Mindfulness no es uno de sus módulos centrales originales.',r:F});
set('SmCm13PIR2025_146',{e:'¿Qué programa combina actividades agradables, entrenamiento en habilidades sociales y modificación de cogniciones?',o:{a:'Terapia cognitiva de Beck.',b:'Curso para el Afrontamiento de la Depresión de Lewinsohn.',c:'Terapia racional-emotiva conductual.',d:'Terapia de solución de problemas de D’Zurilla y Goldfried.'},c:'b',x:'El CAD de Lewinsohn es un programa psicoeducativo multicomponente que integra esos tres bloques principales.',r:F});
set('SmCm14PIR2025_126',{e:'Según la clasificación de apoyo empírico utilizada en el manual para el trastorno bipolar, ¿qué intervención posee apoyo modesto tanto para síntomas maníacos como depresivos?',o:{a:'Terapia cognitivo-conductual.',b:'Psicoeducación como intervención carente de evidencia.',c:'Cuidado sistemático exclusivamente para manía.',d:'Activación conductual aislada.'},c:'a',x:'La clasificación citada atribuye a la terapia cognitivo-conductual un apoyo modesto para ambas polaridades. La pregunta queda vinculada expresamente al sistema de evidencia del manual.',r:F});
set('SmCm14PIR2025_127',{e:'Según la gradación recogida en el manual, ¿qué nivel de evidencia presenta la terapia centrada en la familia para el trastorno bipolar?',o:{a:'1++.',b:'1+.',c:'2+.',d:'2-.'},c:'b',x:'El manual sitúa la terapia centrada en la familia en nivel 1+; esta gradación se refiere a su tabla concreta y no debe confundirse con otros sistemas de clasificación.',r:F});
set('SmCm14PIR2025_129',{e:'Según la tabla de recomendaciones del manual, ¿qué intervención para depresión NO alcanza el grado A?',o:{a:'Activación conductual.',b:'Terapia cognitiva de Beck.',c:'Terapia de aceptación y compromiso.',d:'Terapia interpersonal.'},c:'c',x:'En esa clasificación, activación conductual, terapia cognitiva y TIP alcanzan grado A, mientras ACT presenta un respaldo inferior. Se mantiene la referencia explícita al manual porque los grados dependen del sistema y fecha.',r:F});
set('SmCm15PIR2025_150',{e:'¿Cuál de las siguientes psicoterapias cuenta con eficacia establecida para la depresión?',o:{a:'Psicoterapia psicodinámica no estructurada como única opción.',b:'Terapia sistémica genérica.',c:'Terapia interpersonal.',d:'Una supuesta terapia del sueño indiferenciada.'},c:'c',x:'La TIP es una intervención breve y estructurada con eficacia para depresión. Las otras alternativas no describen una intervención específica con respaldo general equivalente.',r:'National Institute for Health and Care Excellence (2022). Depression in adults: treatment and management (NG222); '+F});
set('SmCm15PIR2025_153',{e:'Señale la afirmación incorrecta sobre la terapia de solución de problemas de Nezu aplicada a la depresión:',o:{a:'Busca mejorar el afrontamiento eficaz de problemas.',b:'Trabaja tanto la orientación hacia los problemas como habilidades sistemáticas de solución.',c:'Se apoya en el modelo de D’Zurilla y Goldfried.',d:'Solo puede administrarse en grupo y nunca individualmente.'},c:'d',x:'La terapia puede aplicarse individualmente o en grupo; por tanto, la exclusividad grupal es falsa. Combina orientación constructiva hacia los problemas con definición, generación de alternativas, decisión y puesta en práctica.',r:'Nezu, A. M., Nezu, C. M. y D’Zurilla, T. J. (2013). Problem-Solving Therapy. Springer.'});
set('SmCm17PIR2025_165',{e:'¿Qué tres habilidades básicas se trabajan en el entrenamiento en habilidades sociales para la depresión?',o:{a:'Aserción positiva, aserción negativa y comunicación no verbal.',b:'Aserción positiva, conversación y solución de problemas.',c:'Aserción positiva, aserción negativa y habilidades conversacionales.',d:'Aserción positiva, comunicación no verbal y relajación.'},c:'c',x:'El programa organiza el aprendizaje en aserción positiva, aserción negativa y habilidades conversacionales.',r:F});
set('SmCm17PIR2025_166',{e:'¿Cuál es un componente del entrenamiento en habilidades sociales para la depresión?',o:{a:'Aserción positiva.',b:'Mindfulness como único componente.',c:'Inducción de cogniciones negativas en situaciones sociales.',d:'Relajación muscular como núcleo del entrenamiento social.'},c:'a',x:'La aserción positiva —expresar aprobación, afecto o reconocimiento— es una de las áreas básicas, junto con la aserción negativa y las habilidades conversacionales.',r:F});
set('SmCm18PIR2025_172',{e:'¿Cuál NO es una característica de la terapia interpersonal para la depresión?',o:{a:'Es breve y temporalmente delimitada.',b:'Conceptualiza la depresión como una enfermedad tratable.',c:'Su objetivo principal es modificar la estructura básica de personalidad a largo plazo.',d:'Es específica en sus estrategias, aunque utiliza técnicas compartidas con otras terapias.'},c:'c',x:'La TIP persigue la reducción de síntomas y resolución de la crisis interpersonal actual, no una reorganización profunda de la personalidad. Es breve y estratégica, aunque muchas técnicas no son exclusivas.',r:F});
set('SmCm19PIR2024_148',{e:'Señale la afirmación incorrecta sobre el tratamiento farmacológico del trastorno bipolar:',o:{a:'Lamotrigina es útil para prevenir episodios depresivos en el mantenimiento del bipolar I.',b:'Valproato se ha utilizado en perfiles con consumo de sustancias o características mixtas.',c:'Carbamazepina no es una opción de primera elección para depresión bipolar aguda en monoterapia.',d:'El litio carece de utilidad especial cuando existe riesgo suicida.'},c:'d',x:'La d es incorrecta: el litio destaca por su asociación con reducción de conducta suicida. Las otras opciones describen usos o limitaciones reconocidos, aunque toda prescripción debe individualizarse.',r:'Yatham, L. N. et al. (2018). CANMAT and ISBD 2018 guidelines. Bipolar Disorders, 20, 97-170; '+B});
set('SmCm19PIR2024_150',{e:'¿Qué aspecto se trabaja explícitamente al finalizar la terapia interpersonal para la depresión?',o:{a:'Se evita hablar de la terminación para no generar dependencia.',b:'Se comunica que la terapia continuará sin límite temporal.',c:'La finalización se aborda como una experiencia de separación o duelo y se revisan logros y necesidades futuras.',d:'Se retira el rol de enfermo desde la primera sesión, antes de mejorar.'},c:'c',x:'La terminación es planificada y puede evocar sentimientos semejantes a un duelo. Se revisan logros, señales de recaída y estrategias futuras.',r:'Weissman, M. M., Markowitz, J. C. y Klerman, G. L. (2018). The Guide to Interpersonal Psychotherapy. Oxford University Press.'});
set('SmCm20PIR2024_163',{e:'¿Qué resultado general se observó en el NIMH Treatment of Depression Collaborative Research Program?',o:{a:'Solo la medicación fue eficaz al finalizar el tratamiento.',b:'La imipramina produjo una reducción más rápida a mitad del tratamiento, pero al final no hubo diferencias significativas entre imipramina, TCC y TIP.',c:'La terapia cognitiva superó claramente a todos los tratamientos en la terminación.',d:'La medicación produjo necesariamente mayor satisfacción.'},c:'b',x:'Los análisis mostraron mayor rapidez con imipramina durante la fase intermedia, pero no diferencias significativas entre los tres tratamientos activos al terminar. Se elimina la antigua afirmación imprecisa sobre una superioridad global a los 18 meses.',r:'Blatt, S. J. et al. (2000). Short- and long-term effects of medication and psychotherapy in the brief treatment of depression. Psychotherapy Research, 10, 34-47.'});
set('SmCm20PIR2024_193',{e:'¿Cuál de los siguientes fármacos NO es un anticonvulsivante?',o:{a:'Valproato.',b:'Topiramato.',c:'Gabapentina.',d:'Doxepina.'},c:'d',x:'Doxepina es un antidepresivo tricíclico. Valproato, topiramato y gabapentina son anticonvulsivantes, aunque su utilidad como estabilizadores del ánimo no es equivalente.',r:'Agencia Española de Medicamentos y Productos Sanitarios. Fichas técnicas de doxepina, valproato, topiramato y gabapentina.'});

fs.writeFileSync(ap,JSON.stringify(a));fs.writeFileSync(cp,JSON.stringify(child));
console.log('Bloque 6: 20 auditadas y 14 reubicadas.');
