const fs=require('fs');
const p='public/banco/tratamientos_adultos.json';
const bank=JSON.parse(fs.readFileSync(p));
const topic='Tratamiento de la psicosis y esquizofrenia';
const F='Fonseca-Pedrero, E. (coord.) (2019). Tratamientos psicológicos para la psicosis. Pirámide.';
const NICE='National Institute for Health and Care Excellence (2014, updated 2019). Psychosis and schizophrenia in adults: prevention and management (CG178).';
const ACT='Bach, P. y Hayes, S. C. (2002). The use of acceptance and commitment therapy to prevent the rehospitalization of psychotic patients. Journal of Consulting and Clinical Psychology, 70(5), 1129–1139. https://doi.org/10.1037/0022-006X.70.5.1129';
const AV='Leff, J. et al. (2014). Computer-assisted therapy for medication-resistant auditory hallucinations. British Journal of Psychiatry, 204(6), 428–433. https://doi.org/10.1192/bjp.bp.113.138586';
const OD='Seikkula, J. y Olson, M. E. (2003). The Open Dialogue approach to acute psychosis. Family Process, 42(3), 403–418. https://doi.org/10.1111/j.1545-5300.2003.00403.x';
const edits={
'SmCm06PIR2025_076':{e:'¿Cuántas fases comprende el programa STOPP descrito para la intervención psicológica en psicosis?',o:{a:'Cuatro fases.',b:'Dos fases.',c:'Tres fases.',d:'Cinco fases.'},c:'a',x:'La opción a es correcta: STOPP se estructura en cuatro fases progresivas. La b y la c reducen indebidamente la secuencia; y la d añade una quinta fase que no pertenece a la estructura registrada del programa.',r:F+', capítulo de intervenciones psicológicas específicas.'},
'SmCm08PIR2025_071':{e:'En la intervención grupal de Terapia Centrada en la Compasión para la psicosis, ¿qué se establece al inicio?',o:{a:'Exposición intensiva a recuerdos traumáticos.',b:'El grupo como base segura y una orientación compartida hacia la recuperación.',c:'Disputa directa de todas las creencias psicóticas.',d:'Prevención de recaídas como único objetivo.'},c:'b',x:'La opción b es correcta: al comienzo se construyen seguridad, afiliación y una dirección de recuperación que permitan desarrollar compasión. La a no constituye el inicio estándar; la c contradice el enfoque compasivo y no confrontativo; y la d reduce indebidamente la intervención a un único objetivo.',r:'Braehler, C. et al. (2013). Exploring change processes in compassion focused therapy in psychosis. British Journal of Clinical Psychology, 52(2), 199–214. https://doi.org/10.1111/bjc.12009'},
'SmCm13PIR2025_119':{e:'¿Cuál NO es un elemento nuclear de ACT aplicada a la psicosis?',o:{a:'Explorar la desesperanza creativa ante estrategias de control ineficaces.',b:'Desarrollar disposición a experimentar eventos internos.',c:'Determinar mediante debate si las experiencias psicóticas son objetivamente verdaderas.',d:'Plantear que el problema puede residir en el control rígido de la experiencia.'},c:'c',x:'La opción c es correcta porque ACT no busca resolver la verdad literal del contenido psicótico. La a examina el coste del control; la b corresponde a aceptación o voluntad; y la d reformula el problema desde la evitación y el control experiencial, todos procesos coherentes con ACT.',r:ACT},
'SmCm13PIR2025_133':{e:'¿Qué intervención grupal, conductual y jerarquizada para la esquizofrenia integra cinco subprogramas desde diferenciación cognitiva hasta solución de problemas interpersonales?',o:{a:'SILS.',b:'Terapia Psicológica Integrada (IPT).',c:'Terapia de cumplimiento.',d:'Terapia de focalización.'},c:'b',x:'La opción b es correcta: la IPT de Brenner y colaboradores organiza cinco subprogramas jerárquicos que conectan cognición y funcionamiento social. SILS entrena habilidades de vida independiente; la terapia de cumplimiento se centra en adherencia; y la focalización aborda principalmente alucinaciones auditivas.',r:'Roder, V., Brenner, H. D., Kienzle, N. y Fuentes, I. (2007). Terapia psicológica integrada para la esquizofrenia. Alborán.'},
'SmCm13PIR2025_134':{e:'Para reducir recaídas y mejorar el funcionamiento en la esquizofrenia, ¿qué debe complementar al tratamiento farmacológico?',o:{a:'Intervenciones psicológicas estructuradas basadas en evidencia.',b:'Hipnosis como primera elección.',c:'Expresión artística como único tratamiento psicosocial.',d:'Hospitalizaciones preventivas programadas sin indicación clínica.'},c:'a',x:'La opción a es correcta: TCC, intervención familiar y rehabilitación se integran según las necesidades. La b no es una recomendación estándar; la c puede ser complementaria pero no sustituye los tratamientos indicados; y la d contradice la atención menos restrictiva y comunitaria.',r:NICE},
'SmCm14PIR2025_017':{e:'¿Cuál NO pertenece a los procesos CHIME de recuperación personal trabajados en REFOCUS?',o:{a:'Empoderamiento y responsabilidad.',b:'Esperanza y optimismo.',c:'Conexión social.',d:'Mantener una identidad dominada por el estigma y el rol pasivo.'},c:'d',x:'La opción d es correcta por ser la excepción: la recuperación pretende transformar una identidad dominada por enfermedad y estigma. La a corresponde a empowerment; la b a hope; y la c a connectedness, tres componentes del marco CHIME.',r:'Leamy, M. et al. (2011). Conceptual framework for personal recovery in mental health. British Journal of Psychiatry, 199(6), 445–452. https://doi.org/10.1192/bjp.bp.110.083733'},
'SmCm16PIR2025_155':{e:'En el modelo de rehabilitación de Liberman, ¿cuál es un objetivo propio de la fase aguda de la esquizofrenia?',o:{a:'Consolidar un proyecto laboral a largo plazo.',b:'Completar la reinserción comunitaria avanzada.',c:'Alcanzar autonomía residencial plena.',d:'Identificar y tratar factores precipitantes y estabilizar la crisis.'},c:'d',x:'La opción d es correcta: en fase aguda se priorizan seguridad, estabilización y factores asociados al episodio. La a, b y c son objetivos funcionales de fases posteriores de estabilización y recuperación, no prioridades inmediatas de la crisis.',r:'Liberman, R. P. (2008). Recovery from Disability: Manual of Psychiatric Rehabilitation. American Psychiatric Publishing.'},
'SmCm16PIR2025_156':{e:'¿Qué afirmación sobre Cognitive Enhancement Therapy (CET) está respaldada en la esquizofrenia de curso temprano?',o:{a:'Se limita a 45 sesiones individuales de una hora.',b:'Carece de entrenamiento en cognición social.',c:'Entrena atención y memoria exclusivamente en formato grupal.',d:'Se ha asociado con preservación de sustancia gris además de beneficios cognitivos y sociales.'},c:'d',x:'La opción d es correcta: en esquizofrenia de curso temprano se observaron efectos neuroprotectores sobre sustancia gris. La a es falsa porque CET es prolongada y combina formatos; la b es falsa porque la cognición social es central; y la c es falsa porque el entrenamiento neurocognitivo informatizado no es exclusivamente grupal.',r:'Eack, S. M. et al. (2010). Neuroprotective effects of cognitive enhancement therapy. Archives of General Psychiatry, 67(7), 674–682. https://doi.org/10.1001/archgenpsychiatry.2010.63'},
'SmCm17PIR2025_144':{e:'¿Cuál NO pertenece a los tres componentes clásicos de la terapia de Kingdon y Turkington para delirios y alucinaciones?',o:{a:'Desafío verbal colaborativo.',b:'Normalización racional.',c:'Psicodrama.',d:'Prueba de realidad.'},c:'c',x:'La opción c es correcta por ser la excepción: el protocolo utiliza normalización, examen verbal y pruebas de realidad. La a, b y d son componentes descritos; el psicodrama es una modalidad distinta y no integra esa tríada.',r:'Kingdon, D. G. y Turkington, D. (2005). Cognitive Therapy of Schizophrenia. Guilford Press.'},
'SmCm17PIR2025_162':{e:'¿Qué procedimiento es menos congruente con ACT para la psicosis cuando existe alta vulnerabilidad a la absorción o desorganización?',o:{a:'Usar metáforas y ejercicios breves adaptados.',b:'Practicar defusión respecto del lenguaje.',c:'Modificar el contexto funcional de los síntomas.',d:'Realizar ejercicios de mindfulness largos, abstractos y sin adaptación clínica.'},c:'d',x:'La opción d es correcta: las prácticas deben ser breves, concretas y adaptadas para evitar absorción o desorganización. La a facilita aprendizaje experiencial; la b reduce fusión; y la c expresa el objetivo funcional de ACT en lugar de eliminar directamente los síntomas.',r:ACT},
'SmCm17PIR2025_164':{e:'¿Qué objetivo es coherente con ACT aplicada a la esquizofrenia?',o:{a:'Garantizar esperanza mediante supresión de síntomas.',b:'Aumentar la fusión con el lenguaje para controlar la conducta.',c:'Desarrollar disposición a experimentar eventos internos al servicio de valores.',d:'Convertir la desesperanza creativa en el problema principal.'},c:'c',x:'La opción c es correcta: ACT promueve aceptación o voluntad y acción valiosa. La a promete control sintomático y no define ACT; la b invierte la defusión; y la d confunde una estrategia terapéutica para examinar el control ineficaz con el problema clínico.',r:ACT},
'SmCm18PIR2025_039':{e:'En Diálogo Abierto, ¿qué principio permite conectar experiencias antes inconexas y construir una narrativa con significado?',o:{a:'Externalización narrativa.',b:'Confrontación constructiva.',c:'Dialogicidad.',d:'Continuidad farmacológica.'},c:'c',x:'La opción c es correcta: la dialogicidad prioriza generar diálogo, nuevas palabras y significados compartidos. La a procede de terapia narrativa y no nombra este principio; la b introduce confrontación, contraria a tolerar incertidumbre; y la d puede formar parte de decisiones clínicas, pero no describe el proceso señalado.',r:OD},
'SmCm18PIR2025_140':{e:'¿Qué modalidad se centra de forma directa en asertividad, comunicación verbal y no verbal y respuestas sociales apropiadas en personas con psicosis?',o:{a:'Entrenamiento genérico en habilidades sociales.',b:'Entrenamiento en cognición social y de interacción (SCIT).',c:'Módulos de vida independiente UCLA-FAST.',d:'CBSST como combinación exclusiva de reestructuración cognitiva.'},c:'a',x:'La opción a es correcta: el entrenamiento genérico practica conductas sociales mediante instrucción, modelado, ensayo y retroalimentación. SCIT trabaja percepción emocional, teoría de la mente y sesgos; UCLA-FAST se orienta a dominios funcionales; y CBSST combina TCC y habilidades sociales, por lo que no se define como reestructuración exclusiva.',r:'Bellack, A. S. et al. (2004). Social Skills Training for Schizophrenia. Guilford Press.'},
'SmCm18PIR2025_169':{e:'¿Qué afirmación describe correctamente ACT para la psicosis?',o:{a:'Pretende reducir síntomas mediante refutación directa de su contenido.',b:'Busca construir un yo conceptual más rígido y elaborado.',c:'Solo resulta útil en primeros episodios hospitalizados.',d:'Explora el impacto de la fusión cognitiva y promueve flexibilidad ante las experiencias.'},c:'d',x:'La opción d es correcta: ACT analiza cómo la fusión y evitación restringen la conducta y fomenta respuestas flexibles. La a confunde ACT con disputa cognitiva; la b invierte el yo como contexto; y la c es falsa porque se ha estudiado en distintos momentos y perfiles clínicos.',r:ACT},
'SmCm19PIR2024_131':{e:'En TCC para la psicosis, ¿qué caracteriza el trabajo con esquemas cognitivos básicos?',o:{a:'Limitarse a normalizar el fenómeno sin explorar la historia personal.',b:'Abordar vulnerabilidades emocionales y creencias nucleares que organizan la interpretación de uno mismo y de los demás.',c:'Trabajar únicamente la frecuencia de las voces mediante exposición.',d:'Aplicarlo siempre al inicio, antes de construir alianza y formulación.'},c:'b',x:'La opción b es correcta: los esquemas nucleares ayudan a comprender emociones, delirios, voces y patrones vitales. La a es incompleta; la c reduce el trabajo a un síntoma y una técnica; y la d es falsa porque suele requerir alianza, estabilidad y formulación suficientes.',r:'Garety, P. A. et al. (2001). A cognitive model of the positive symptoms of psychosis. Psychological Medicine, 31(2), 189–195. https://doi.org/10.1017/S0033291701003312'},
'SmCm1PIR2024_087':{e:'¿Cuál es un tratamiento multimodal integrado desarrollado específicamente para la esquizofrenia?',o:{a:'Terapia interpersonal de Fairburn.',b:'Terapia interpersonal y de ritmos sociales.',c:'Terapia Psicológica Integrada (IPT).',d:'Terapia interpersonal metacognitiva para trastornos de personalidad.'},c:'c',x:'La opción c es correcta: IPT integra subprogramas cognitivos y sociales para esquizofrenia. La a se relaciona con trastornos alimentarios; la b con trastorno bipolar; y la d es un tratamiento para trastornos de personalidad, no el programa multimodal solicitado.',r:'Roder, V. et al. (2007). Terapia psicológica integrada para la esquizofrenia. Alborán.'},
'SmCm1PIR2024_162':{e:'Señale la afirmación INCORRECTA sobre TCC para la psicosis:',o:{a:'Puede normalizar el delirio como intento de dar sentido a experiencias extrañas.',b:'Debe aplicar desdramatización antes de identificar pensamientos y emociones asociados al episodio.',c:'Puede poner a prueba tanto la creencia delirante como una explicación alternativa.',d:'Figura en guías clínicas como intervención psicológica recomendada.'},c:'b',x:'La opción b es incorrecta: primero se evalúan antecedentes, pensamientos, emociones y consecuencias; la desdramatización no sustituye esa identificación. La a es una estrategia de normalización; la c evita confirmar solo una hipótesis; y la d refleja la recomendación de TCC en guías como NICE.',r:NICE},
'SmCm1PIR2024_164':{e:'En TCC aplicada a los delirios, ¿qué secuencia es adecuada?',o:{a:'Realizar comprobaciones empíricas después de una exploración y análisis verbal colaborativos.',b:'Trabajar esquemas profundos sin atender al insight ni a la alianza.',c:'Limitar el análisis verbal exclusivamente a la lógica formal.',d:'Comenzar confrontando directamente la falsedad de la creencia.'},c:'a',x:'La opción a es correcta: la prueba conductual se diseña tras comprender la creencia y generar alternativas. La b ignora condiciones clínicas necesarias; la c omite evidencias, emociones y consecuencias; y la d aumenta resistencia y rompe el empirismo colaborativo.',r:'Kingdon, D. G. y Turkington, D. (2005). Cognitive Therapy of Schizophrenia. Guilford Press.'},
'SmCm1PIR2024_166':{e:'¿Qué función desempeña el terapeuta en la terapia AVATAR para voces resistentes?',o:{a:'Ninguna, porque es una aplicación autoadministrada.',b:'Limitarse a configurar la imagen sin participar en el diálogo.',c:'Representar de forma verosímil la voz y graduar el diálogo para aumentar poder y asertividad del paciente.',d:'Atacar directamente a la voz sin graduación ni colaboración.'},c:'c',x:'La opción c es correcta: el terapeuta habla mediante el avatar, ajusta el grado de confrontación y apoya una respuesta más autónoma. La a y la b eliminan funciones esenciales; y la d es falsa porque el trabajo es gradual, seguro y formulado conjuntamente.',r:AV},
'SmCm1PIR2024_208':{e:'¿Qué creencias sobre las voces son centrales en el modelo de Chadwick, Birchwood y Trower?',o:{a:'Solo su localización interna o externa.',b:'Exclusivamente esquemas nucleares generales.',c:'Poder, identidad, propósito o intención y control.',d:'Ninguna, porque el modelo se centra solo en frecuencia.'},c:'c',x:'La opción c es correcta: estas valoraciones median el malestar y las respuestas de sumisión o resistencia. La a es demasiado limitada; la b confunde creencias sobre voces con esquemas generales; y la d contradice el fundamento cognitivo del modelo.',r:'Chadwick, P., Birchwood, M. y Trower, P. (1996). Cognitive Therapy for Delusions, Voices and Paranoia. Wiley.'},
'SmCm20PIR2024_160':{e:'¿Qué enfoque entiende las manifestaciones psicóticas en una crisis como respuestas con significado ante experiencias o contextos abrumadores, en lugar de asumirlas solo como signos de una enfermedad subyacente?',o:{a:'Modelo biomédico estricto.',b:'Modelo farmacológico de mantenimiento.',c:'Modelo de déficit neurocognitivo.',d:'Diálogo Abierto.'},c:'d',x:'La opción d es correcta: Diálogo Abierto escucha las experiencias dentro de su contexto relacional y busca generar significado sin imponer una explicación cerrada. La a y la b priorizan enfermedad y tratamiento biológico; y la c explica déficits cognitivos, no el sentido contextual descrito.',r:OD},
'SmCm20PIR2024_190':{e:'¿Qué programa incluye un subprograma específico de solución de problemas interpersonales?',o:{a:'TCC de Kingdon y Turkington.',b:'Remediación cognitiva de Wykes y Reeder.',c:'Potenciación de estrategias de afrontamiento de Tarrier.',d:'Terapia Psicológica Integrada (IPT).'},c:'d',x:'La opción d es correcta: solución de problemas interpersonales es el quinto subprograma de IPT. La a trabaja formulación y síntomas; la b entrena cognición; y la c fortalece afrontamiento, pero ninguna contiene ese módulo nominal dentro de una jerarquía de cinco subprogramas.',r:'Roder, V. et al. (2007). Terapia psicológica integrada para la esquizofrenia. Alborán.'},
'SmCm20PIR2025 (1)_063':{e:'¿Qué principio de Diálogo Abierto implica no apresurarse a imponer una explicación diagnóstica o una decisión definitiva durante la crisis?',o:{a:'Responsabilidad compartida.',b:'Continuidad psicológica.',c:'Flexibilidad y movilidad.',d:'Tolerancia a la incertidumbre.'},c:'d',x:'La opción d es correcta: tolerar la incertidumbre permite sostener el diálogo y evitar cierres prematuros. La a se refiere a asumir la respuesta asistencial; la b mantiene coherencia del equipo y la red; y la c adapta la ayuda a necesidades cambiantes, pero no describe la demora deliberada del cierre explicativo.',r:OD}
};
// La pregunta sobre salto a las conclusiones es psicopatología, no tratamiento.
const moveClinical='SmCm1PIR2024_086';
// PRIDE pertenece a terapia de interacción padres-hijos.
const moveChild='SmCm19PIR2024_036';
let n=0;for(const [id,v] of Object.entries(edits)){const q=bank.find(x=>x.id===id);if(!q)throw Error('missing '+id);Object.assign(q,v,{v:'VALIDADA_ORIGINAL'});n++;}
function move(id,file,s,t,patch){const i=bank.findIndex(x=>x.id===id);if(i<0)throw Error('missing move '+id);const [q]=bank.splice(i,1);Object.assign(q,patch,{s,t:[t],v:'VALIDADA_ORIGINAL'});const arr=JSON.parse(fs.readFileSync(file));if(arr.some(x=>x.id===id))throw Error('duplicate '+id);arr.push(q);fs.writeFileSync(file,JSON.stringify(arr)+'\n');n++;}
move(moveClinical,'public/banco/clinica_adultos.json','Clínica Adultos','Trastornos del espectro de la esquizofrenia',{e:'El sesgo de salto a las conclusiones se asocia especialmente con:',o:{a:'Alucinaciones visuales aisladas.',b:'Ausencia de ideas delirantes.',c:'Ideas delirantes, especialmente cuando se toman decisiones con muy poca evidencia.',d:'Un fenómeno exclusivo de población clínica.'},c:'c',x:'La opción c es correcta: el salto a las conclusiones se observa con mayor frecuencia en personas con delirios y se operacionaliza mediante decisiones basadas en pocas pruebas. La a no constituye su asociación principal; la b invierte la relación; y la d es falsa porque también aparece, con menor frecuencia, en población general.',r:'Dudley, R. et al. (2016). Jumping to conclusions in individuals with psychosis. Schizophrenia Bulletin, 42(3), 652–665. https://doi.org/10.1093/schbul/sbv150'});
move(moveChild,'public/banco/tratamientos_infantiles.json','Tratamientos Infantiles','Trastornos de conducta infantojuvenil',{e:'En la terapia de interacción padres-hijos (PCIT), ¿qué representa el acrónimo PRIDE durante la interacción dirigida por el niño?',o:{a:'Praise, Reflect, Imitate, Describe y Enjoyment.',b:'Prevent, Redirect, Instruct, Discipline y Evaluate.',c:'Praise, Reward, Ignore, Direct y Explain.',d:'Play, Reinforce, Interpret, Demand y Empathize.'},c:'a',x:'La opción a es correcta: PRIDE resume elogiar, reflejar, imitar, describir y mostrar disfrute, habilidades usadas para fortalecer la relación. Las restantes combinan instrucciones, disciplina o términos que no forman el acrónimo.',r:'Eyberg, S. M. y Funderburk, B. (2011). Parent-Child Interaction Therapy Protocol. PCIT International.'});
if(n!==25)throw Error('expected25 '+n);
fs.writeFileSync(p,JSON.stringify(bank)+'\n');
const mpath='public/banco/manifest.json',m=JSON.parse(fs.readFileSync(mpath));
for(const [name,file] of [['Tratamientos Adultos','tratamientos_adultos.json'],['Clínica Adultos','clinica_adultos.json'],['Tratamientos Infantiles','tratamientos_infantiles.json']])m.subjects[name].count=JSON.parse(fs.readFileSync('public/banco/'+file)).length;
m.total=Object.values(m.subjects).reduce((a,s)=>a+s.count,0);fs.writeFileSync(mpath,JSON.stringify(m)+'\n');
console.log({reviewed:n,pending:bank.filter(q=>q.t?.includes(topic)&&(!q.v||q.v==='REVISAR')).length,total:m.total});
