const fs=require('fs'),p='public/banco/clinica_adultos.json',a=JSON.parse(fs.readFileSync(p));
const D='American Psychiatric Association (2022). DSM-5-TR. Capítulo «Trastornos disociativos». Editorial Médica Panamericana.';
const B='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. II (4.ª ed.). McGraw Hill, cap. 8, pp. 295–322.';
const U={
'SM_JULIO_1_SOL_1_043':['En relación con los modelos explicativos de la disociación, señale la afirmación correcta:',{a:'El modelo autohipnótico postula la escisión entre personalidad emocional y personalidad aparentemente normal.',b:'La teoría de la disociación estructural se organiza mediante los componentes SIBAM.',c:'El modelo BASK plantea que el procesamiento integrado requiere la coordinación de conducta, afecto, sensación y conocimiento.',d:'El modelo SIBAM explica la disociación exclusivamente por una elevada hipnotizabilidad.'},'c','La c es correcta: BASK corresponde a conducta, afecto, sensación y conocimiento. La a atribuye al modelo autohipnótico un planteamiento de la disociación estructural; la b confunde esta teoría con SIBAM; y la d atribuye a SIBAM la explicación autohipnótica.',B],
'PERSEVER___SIMULACRO_COMENTADO_MAYO-DOS-23_032':['Respecto a la amnesia disociativa, señale la afirmación correcta:',{a:'Se define por lapsos cotidianos recurrentes y alternancia de identidades.',b:'La fuga es infrecuente en la amnesia disociativa, pero puede observarse con mayor frecuencia en el trastorno de identidad disociativo.',c:'Al remitir la amnesia disminuyen necesariamente los síntomas de TEPT.',d:'La despersonalización es siempre su alteración cognitiva principal.'},'b','La b es correcta. La a mezcla criterios del trastorno de identidad disociativo; la c es falsa porque la recuperación de recuerdos puede intensificar el malestar postraumático; y la d convierte una manifestación posible en característica necesaria y principal.',D],
'PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-UNO-23_079':['Según la CIE-11, ¿qué caracteriza al trastorno de trance?',{a:'La identidad habitual es sustituida necesariamente por un agente poseedor externo.',b:'Consiste exclusivamente en apatía o ausencia total de respuesta al entorno.',c:'Es cualquier reacción disociativa aguda de menos de un mes.',d:'Existe una pérdida temporal del sentido de identidad personal y una restricción de la conciencia del entorno, fuera de prácticas culturales aceptadas y no explicada mejor por otro trastorno.'},'d','La d es correcta y recoge el núcleo del trance patológico y sus exclusiones. La a describe trance de posesión; la b no define el cuadro; y la c mezcla el trance con otras reacciones disociativas agudas.', 'World Health Organization (2024). ICD-11 Clinical Descriptions and Diagnostic Requirements, «Trance disorder» (6B62).'],
'ABRIL-UNO-24_COMENTADO_159':['Sobre factores etiológicos relacionados con la disociación, señale la afirmación correcta:',{a:'Episodios repetidos de desregulación emocional durante la infancia pueden favorecer respuestas disociativas.',b:'El trauma del desarrollo afecta específicamente y solo a la mielinización temporal.',c:'Janet explicó la disociación mediante una fijación en la etapa oral.',d:'Solo las experiencias de apego secundarias, y no las tempranas, influyen en su desarrollo.'},'a','La a es correcta: trauma temprano y desregulación repetida pueden interferir en la integración de experiencias. La b localiza de manera exclusiva un efecto que implica redes más amplias; la c atribuye a Janet un concepto psicosexual freudiano; y la d excluye indebidamente las relaciones tempranas de apego.',B],
'SEPTIEMBRE-DOS-24_COMENTADO_075':['Respecto a la amnesia disociativa, señale la afirmación correcta:',{a:'Suele afectar de forma retrógrada y selectiva a acontecimientos con elevada carga emocional.',b:'Exige una lesión cerebral demostrable.',c:'La pérdida de memoria es habitualmente irreversible.',d:'La memoria semántica general suele quedar profundamente destruida.'},'a','La a es correcta: habitualmente afecta información autobiográfica pasada ligada a trauma o estrés. La b es falsa porque no se explica por daño neurológico; la c es falsa porque puede remitir; y la d es falsa porque el conocimiento semántico general suele conservarse.',D],
'SmCm06PIR2025_032':['Según la clasificación funcional de Tyrer, señale la asociación INCORRECTA:',{a:'Estados de trance: disociación de conductas complejas.',b:'Conversión: disociación de movimientos o sensaciones.',c:'Despersonalización: disociación de la función cognitiva.',d:'Personalidad múltiple: disociación de la personalidad.'},'c','La c es la asociación incorrecta: Tyrer sitúa la despersonalización entre alteraciones de la percepción, no de la función cognitiva. Las opciones a, b y d reproducen las asociaciones de su clasificación.', 'Tyrer, P. (1989). Classification of neurosis. Wiley; '+B],
'SM_JULIO_2_SOL_1_040':['Respecto a la amnesia disociativa, señale la afirmación correcta:',{a:'Supone pérdida general del conocimiento conceptual.',b:'La pérdida de memoria asociada a una fuga disociativa puede ser especialmente resistente al tratamiento.',c:'El riesgo suicida aparece únicamente cuando la amnesia remite lentamente.',d:'El TEPT rara vez aparece de forma comórbida.'},'b','La b es correcta. La a es falsa porque la alteración es autobiográfica, no una pérdida semántica global; la c es falsa porque el riesgo puede aumentar con la recuperación brusca de recuerdos; y la d es falsa porque la comorbilidad postraumática es frecuente.',D],
'MAYO-DOS-24_COMENTADO_123':['¿Cuál de las siguientes constituye una alteración de la conciencia del yo?',{a:'Escisión de la unidad del yo.',b:'Desorientación temporal.',c:'Coma.',d:'Obnubilación.'},'a','La a es correcta: implica experimentar una fractura de la unidad subjetiva. La desorientación afecta orientación; coma y obnubilación son alteraciones cuantitativas del nivel de conciencia, no de la conciencia del yo.',B],
'MAYO2_068':['¿Qué nombre NO corresponde a un autor o grupo que haya formulado un modelo explicativo específico de la disociación?',{a:'Farina y colaboradores.',b:'Van der Hart y colaboradores.',c:'Schimmenti y colaboradores.',d:'Wilhelm.'},'d','La d es correcta: no identifica uno de los modelos recogidos en la fuente. Farina distingue desintegración y disociación; Van der Hart desarrolla la disociación estructural; y Schimmenti ha formulado modelos vinculados a trauma y apego.',B],
'ABRIL-UNO-24_COMENTADO_152':['Sobre el trastorno de despersonalización/desrealización, señale la afirmación correcta:',{a:'La sensación de ser un autómata implica pérdida del juicio de realidad.',b:'La experiencia puede incluir extrañeza corporal, entumecimiento emocional y distorsiones temporales.',c:'La edad media de inicio es 14 años y es habitual comenzar después de los 40.',d:'Las personas describen siempre sus experiencias con facilidad.'},'b','La b es correcta. La a es falsa porque se conserva el juicio de realidad; la c altera la edad media descrita y la aparición después de los 40 es infrecuente; la d es falsa porque estas experiencias suelen ser difíciles de expresar.',D],
'PERSEVER___SIMULACRO_COMENTADO_ENERO-UNO-23_069':['¿Cuál de las siguientes afirmaciones es FALSA respecto a la desrealización?',{a:'Implica sensación subjetiva de extrañeza o irrealidad del entorno.',b:'La persona mantiene una convicción delirante de que el entorno ha cambiado realmente.',c:'Puede aparecer en contextos y trastornos semejantes a la despersonalización.',d:'Puede entenderse como pérdida subjetiva de la familiaridad o realidad del mundo externo.'},'b','La b es falsa y constituye la respuesta: en la desrealización se mantiene intacta la prueba de realidad. Las opciones a, c y d describen adecuadamente la vivencia subjetiva y su relación con la despersonalización.',D],
'SEPTIEMBRE-UNO-24_COMENTADO_148':['¿Con qué trastornos de personalidad se describe comorbilidad especialmente relevante en la amnesia disociativa?',{a:'Límite, evitativo y dependiente.',b:'Límite, evitativo y narcisista.',c:'Límite, paranoide y dependiente.',d:'Obsesivo-compulsivo, evitativo y dependiente.'},'a','La a es correcta: se destacan los patrones límite, evitativo y dependiente. Las opciones b, c y d sustituyen alguno de ellos por narcisista, paranoide u obsesivo-compulsivo, que no forman el conjunto señalado.',D],
'SmCm08PIR2025_173':['¿Cuál NO es uno de los cuatro dominios del modelo 4-D de Frewen y Lanius?',{a:'Emocional.',b:'Somático.',c:'Tiempo y memoria.',d:'Conducta.'},'d','La d es correcta: el modelo comprende conciencia, emoción, tiempo/memoria y cuerpo. Las opciones a, b y c corresponden a dominios del modelo; conducta no constituye uno de los cuatro dominios.', 'Frewen, P. y Lanius, R. (2015). Healing the Traumatized Self. Norton.'],
'Simu 14 comentado _002':['¿Qué modalidad de amnesia disociativa presenta un componente anterógrado, al afectar los acontecimientos desde un momento determinado hasta el presente?',{a:'Localizada.',b:'Continua.',c:'Selectiva.',d:'Sistematizada.'},'b','La b es correcta: la amnesia continua abarca lo sucedido desde un punto temporal hasta el presente. La localizada afecta un periodo pasado concreto; la selectiva solo parte de un acontecimiento; y la sistematizada una categoría de información.',B],
'SM_MAYO_1_SOL_1_084':['El trastorno de despersonalización/desrealización presenta comorbilidad especialmente con:',{a:'Trastornos evitativo, límite y obsesivo-compulsivo de la personalidad.',b:'Exclusivamente trastorno bipolar.',c:'Únicamente TEPT.',d:'Exclusivamente trastorno de conversión.'},'a','La a es correcta. Las opciones b, c y d son falsas porque formulan asociaciones exclusivas: también son frecuentes trastornos depresivos y de ansiedad, y pueden coexistir otras condiciones.',D],
'SmCm16PIR2025_064':['Respecto al trastorno de identidad disociativo, señale la afirmación correcta:',{a:'Los impulsos intrusivos se experimentan habitualmente como egosintónicos.',b:'La mayoría muestra alternancias de identidad evidentes durante la entrevista.',c:'Pueden producirse fugas disociativas o viajes que la persona no recuerda.',d:'Los pacientes suelen exagerar deliberadamente sus lagunas amnésicas.'},'c','La c es correcta. La a es falsa porque los impulsos pueden vivirse como ajenos o egodistónicos; la b es falsa porque las alternancias pueden ser encubiertas; y la d es falsa porque es más frecuente minimizar o no reconocer la amnesia que exagerarla deliberadamente.',D],
'PERSEVER___SIMULACRO_COMENTADO_MAYO-DOS-23_036':['Señale la afirmación INCORRECTA sobre el trastorno de despersonalización/desrealización:',{a:'La edad media de inicio se sitúa aproximadamente en la adolescencia.',b:'Suele observarse hiperreactividad fisiológica ante estímulos emocionales.',c:'Puede acompañarse de preocupación obsesiva y rumiación.',d:'La comorbilidad con TEPT es menor que con trastornos depresivos y de ansiedad.'},'b','La b es incorrecta: se ha descrito hiporreactividad fisiológica ante estímulos emocionales. La a es compatible con el inicio habitual temprano; la c describe una característica asociada; y la d refleja que depresión y ansiedad son las comorbilidades más frecuentes.',D],
'SmCm08PIR2025_171':['Respecto al trastorno de identidad disociativo, señale la afirmación INCORRECTA:',{a:'La mayoría de estados de posesión culturalmente aceptados no constituyen un trastorno.',b:'Su fisiopatología se limita de forma demostrada al lóbulo parietal inferior y al eje hipotálamo-hipófisis-suprarrenal.',c:'En mujeres pueden observarse presentaciones disociativas agudas.',d:'En niños pueden predominar solapamientos e interferencias entre estados frente a cambios claramente observables.'},'b','La b es incorrecta: no existe una localización fisiopatológica exclusiva y demostrada en esas estructuras; los hallazgos son heterogéneos. La a recoge la exclusión cultural; la c describe una presentación posible; y la d refleja diferencias evolutivas descritas.',D],
'PERSEVER___SIMULACRO_COMENTADO_MAYO-UNO-23_103':['¿En qué diagnóstico se utiliza el especificador «con fuga disociativa»?',{a:'Amnesia disociativa.',b:'Trastorno de identidad disociativo.',c:'Trastorno de despersonalización/desrealización.',d:'Otro trastorno disociativo no especificado.'},'a','La a es correcta: DSM-5-TR incorporó la fuga como especificador de amnesia disociativa. Las opciones b y c son diagnósticos diferentes; la d no emplea ese especificador.',D],
'SEPTIEMBRE-UNO-24_COMENTADO_149':['¿Qué criterio es necesario para diagnosticar trastorno de identidad disociativo?',{a:'Despersonalización persistente como única manifestación.',b:'Lagunas recurrentes de memoria sobre acontecimientos cotidianos, información personal importante o sucesos traumáticos, incompatibles con el olvido ordinario.',c:'Desrealización persistente como única manifestación.',d:'Una única laguna de información traumática sin alteración de identidad.'},'b','La b es correcta y recoge el criterio amnésico del trastorno. La a y la c corresponden al dominio de despersonalización/desrealización y no bastan; la d describe mejor amnesia disociativa y omite la perturbación de identidad necesaria.',D],
'MAYO2_064':['¿Cuál NO pertenece al capítulo de trastornos disociativos del DSM-5-TR?',{a:'Trastorno de despersonalización/desrealización.',b:'Amnesia disociativa.',c:'Trastorno facticio.',d:'Trastorno de identidad disociativo.'},'c','La c es correcta: el trastorno facticio se clasifica entre los trastornos de síntomas somáticos y relacionados. Las opciones a, b y d son los diagnósticos principales del capítulo de trastornos disociativos.',D]
};
for(const [id,z] of Object.entries(U)){const q=a.find(x=>x.id===id);if(!q)throw Error(id);Object.assign(q,{e:z[0],o:z[1],c:z[2],x:z[3],r:z[4],v:'VALIDADA_ORIGINAL'});}fs.writeFileSync(p,JSON.stringify(a));console.log({validated:Object.keys(U).length});
