const fs=require('fs'),p='public/banco/clinica_adultos.json',a=JSON.parse(fs.readFileSync(p));
const D='American Psychiatric Association (2022). DSM-5-TR. Capítulo «Trastornos disociativos». Editorial Médica Panamericana.';
const B='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. II (4.ª ed.). McGraw Hill, cap. 8, pp. 295–322.';
const U={
'SIM_ABR25_147':['La amnesia disociativa se caracteriza principalmente por:',{a:'Incapacidad para recordar información autobiográfica importante, generalmente traumática o estresante, incompatible con el olvido ordinario.',b:'Incapacidad permanente para adquirir cualquier aprendizaje nuevo.',c:'Una creencia delirante sobre la propia identidad.',d:'Alucinaciones persistentes sin alteración de memoria.'},'a','La a es correcta y recoge el núcleo diagnóstico. La b describe una amnesia anterógrada global de causa orgánica, no necesariamente disociativa; la c es un delirio; y la d es una alteración perceptiva que no define este trastorno.',D],
'SmCm17PIR2025_111':['Respecto al inicio de la amnesia disociativa, señale la afirmación correcta:',{a:'Es exclusiva de los varones.',b:'Comienza necesariamente después de los 50 años.',c:'Puede comenzar de forma repentina tras un acontecimiento traumático o estresante.',d:'Siempre dura entre dos y cuatro semanas.'},'c','La c es correcta: el inicio puede ser súbito y relacionarse temporalmente con trauma o estrés. La a es falsa porque no es exclusiva de un sexo; la b impone una edad inexistente; y la d fija una duración que puede variar desde minutos u horas hasta periodos prolongados.',D],
'SmCm7PIR2024_020':['¿Cómo se clasifica la fuga disociativa en el DSM-5-TR?',{a:'Como especificador del trastorno de despersonalización/desrealización.',b:'Como especificador de la amnesia disociativa.',c:'Como trastorno relacionado con traumas independiente.',d:'Como trastorno de síntomas somáticos.'},'b','La b es correcta: «con fuga disociativa» es un especificador de la amnesia disociativa. La a la vincula al diagnóstico equivocado; la c conserva una categoría independiente que DSM-5 eliminó; y la d la sitúa en otro capítulo.',D],
'SmCm22PIR2025 (1)_064':['¿Cuál es una duración posible de la amnesia disociativa?',{a:'Nunca supera treinta minutos.',b:'Se limita siempre a varias horas.',c:'No puede prolongarse más de un mes.',d:'Puede persistir durante periodos prolongados, incluso años en algunos casos.'},'d','La d es correcta: la duración es muy variable y puede extenderse durante años. Las opciones a, b y c establecen límites máximos que el DSM-5-TR no exige.',D],
'SmCm19PIR2024_070':['¿Qué formas de amnesia disociativa pueden ser difíciles de detectar por afectar solo a periodos o contenidos delimitados?',{a:'Generalizada y continua.',b:'Localizada y selectiva.',c:'Generalizada y sistematizada exclusivamente.',d:'Continua y generalizada exclusivamente.'},'b','La b es correcta: la localizada afecta a un periodo circunscrito y la selectiva a parte de lo ocurrido, por lo que pueden pasar inadvertidas. La generalizada implica pérdida extensa de identidad e historia vital y suele ser llamativa; la continua afecta lo sucedido desde un momento hasta el presente.',B],
'SmCm30PIR2025 (1)_019':['Respecto al curso de la amnesia disociativa, señale la afirmación correcta:',{a:'Un episodio puede aumentar la vulnerabilidad a episodios posteriores.',b:'La remisión súbita reduce necesariamente el riesgo suicida.',c:'La amnesia generalizada comienza siempre de forma gradual.',d:'Al remitir la amnesia disminuyen necesariamente los síntomas postraumáticos.'},'a','La a es correcta: haber presentado un episodio puede predisponer a recurrencias ante nuevos estresores. La b es falsa porque la recuperación brusca de recuerdos puede aumentar el malestar y el riesgo; la c es falsa porque la generalizada suele tener inicio agudo; y la d es falsa porque al recuperar recuerdos pueden intensificarse síntomas de TEPT.',D],
'Simu 7 comentado _079':['¿Qué describe la fuga disociativa?',{a:'Un desplazamiento aparentemente intencionado o deambulación desconcertada asociado a amnesia de identidad u otra información autobiográfica.',b:'Una pérdida de memoria limitada exclusivamente a habilidades motoras.',c:'Una experiencia de irrealidad del entorno con memoria intacta.',d:'Una alternancia obligatoria entre dos estados de personalidad.'},'a','La a es correcta: la fuga combina viaje o deambulación con amnesia autobiográfica. La b no corresponde porque las habilidades procedimentales suelen preservarse; la c define desrealización; y la d alude de forma incompleta al trastorno de identidad disociativo. Se reformula para evitar duplicar otra pregunta sobre su clasificación.',D],
'SmCm10PIR2025_037':['¿Qué modalidad de amnesia disociativa afecta a los acontecimientos que ocurren desde un momento determinado hasta el presente?',{a:'Localizada.',b:'Continua.',c:'Generalizada.',d:'Sistematizada.'},'b','La b es correcta: la amnesia continua compromete los sucesos desde un punto concreto en adelante y posee, por ello, un componente anterógrado. La localizada afecta un periodo delimitado pasado; la generalizada abarca la historia vital; y la sistematizada afecta categorías concretas de información.',B],
'SmCm22PIR2025_042':['¿En qué síndrome aparecen las respuestas aproximadas o paralógicas —por ejemplo, responder «tres» a 2 + 2—?',{a:'Síndrome de Briquet.',b:'Trastorno de trance.',c:'Síndrome de Ganser.',d:'Síndrome de Usher.'},'c','La c es correcta: las respuestas aproximadas son el rasgo clásico del síndrome de Ganser. Briquet se relaciona históricamente con somatización; el trance implica restricción de conciencia e identidad; y Usher combina sordera y retinitis pigmentaria.',B],
'SmCm09PIR2025_072':['¿Qué modelo de disociación propuso Braun en 1988?',{a:'Teoría neodisociativa.',b:'Modelo BASK.',c:'Teoría de la disociación estructural.',d:'Modelo SIBAM.'},'b','La b es correcta: Braun propuso BASK, acrónimo de conducta, afecto, sensación y conocimiento. La teoría neodisociativa corresponde a Hilgard; la disociación estructural a Van der Hart y colaboradores; y SIBAM se vincula a Levine.',B],
'Simu 7 comentado _078':['¿Cuál de las siguientes manifestaciones puede asociarse a la amnesia disociativa y exige valorar especialmente el riesgo?',{a:'Comportamiento mecánico como criterio obligatorio.',b:'Analgesia como síntoma nuclear.',c:'Autolesiones o intentos de suicidio.',d:'Macropsia o micropsia como criterio diagnóstico.'},'c','La c es correcta: pueden aparecer conductas autolesivas y suicidas, en particular cuando regresan recuerdos traumáticos. La a puede observarse, pero no es un criterio ni el riesgo principal preguntado; la b no constituye el núcleo; y la d se asocia a alteraciones perceptivas, no a la amnesia disociativa.',D],
'SmCm11PIR2025_151':['El modelo BASK de Braun incluye cuatro dimensiones. ¿Cuál NO pertenece al modelo?',{a:'Conducta.',b:'Imágenes.',c:'Sensaciones.',d:'Afecto.'},'b','La b es correcta: BASK corresponde a Behavior, Affect, Sensation y Knowledge —conducta, afecto, sensación y conocimiento—. Por tanto, a, c y d sí pertenecen; «imágenes» forma parte del modelo SIBAM, no de BASK.',B],
'SmCm26PIR2025_118':['¿Cuál NO se describe como circunstancia capaz de precipitar la manifestación del trastorno de identidad disociativo?',{a:'La retirada de una situación traumática prolongada.',b:'Que los hijos alcancen la edad a la que la persona sufrió el trauma.',c:'La muerte o enfermedad del agresor.',d:'Tener simplemente un familiar de primer grado con el diagnóstico.'},'d','La d es correcta: el mero parentesco no figura como desencadenante clínico de inicio. La retirada del contexto traumático, los recordatorios evolutivos al crecer los hijos y cambios relacionados con el agresor pueden hacer emerger síntomas previamente encubiertos.',D],
'SmCm12PIR2024 2_035':['¿Cuál NO es una característica transdiagnóstica de la disociación descrita por Cardeña y Carlson?',{a:'Pérdida de continuidad subjetiva con intrusiones involuntarias y no deseadas.',b:'Sensación de desconexión respecto de uno mismo o del entorno.',c:'Intrusiones voluntarias y deliberadamente deseadas en conciencia y conducta.',d:'Incapacidad para acceder a información o controlar funciones mentales normalmente accesibles.'},'c','La c es correcta porque convierte las intrusiones en voluntarias y deseadas, lo contrario de la descripción. Las opciones a, b y d recogen respectivamente discontinuidad, desconexión experiencial e inaccesibilidad o pérdida de control.', 'Cardeña, E. y Carlson, E. B. (2011). Acute Stress Disorder Revisited. Annual Review of Clinical Psychology, 7, 245–267. https://doi.org/10.1146/annurev-clinpsy-032210-104502.'],
'SmCm2PIR2024_064':['Según Kihlstrom, los trastornos disociativos pueden entenderse principalmente como trastornos de:',{a:'La percepción sensorial.',b:'La memoria y su integración con la representación del yo.',c:'La inteligencia general.',d:'La motivación biológica.'},'b','La b es correcta: Kihlstrom explica la disociación mediante alteraciones de memoria y desconexión entre recuerdos autobiográficos y representación del yo. Las opciones a, c y d no constituyen el núcleo de su modelo.', 'Kihlstrom, J. F. (2005). Dissociative disorders. Annual Review of Clinical Psychology, 1, 227–253. https://doi.org/10.1146/annurev.clinpsy.1.102803.143925.' ],
'SmCm24PIR2025 (1)_051':['¿Cuál es menos específico del trastorno de identidad disociativo?',{a:'Experiencias de distanciamiento o irrealidad respecto del entorno.',b:'Lagunas recurrentes al recordar acontecimientos cotidianos.',c:'Discontinuidad marcada del sentido del yo y de la agencia.',d:'Alteraciones relacionadas de afecto, conducta, conciencia y memoria.'},'a','La a es correcta: la desrealización puede aparecer en diversos trastornos y define especialmente el trastorno de despersonalización/desrealización. Las opciones b, c y d forman parte de la descripción nuclear del trastorno de identidad disociativo.',D],
'SmCm2PIR2024_063':['En el modelo jerárquico de Van der Hart, Van der Kolk y Boon, la disociación primaria implica:',{a:'Procesamiento fragmentado y no integrado del acontecimiento traumático.',b:'Observar el trauma sin experimentar todo su impacto emocional.',c:'Desarrollo de identidades separadas.',d:'Integración completa del recuerdo traumático.'},'a','La a es correcta: la disociación primaria supone fragmentación del procesamiento del trauma. La b corresponde a disociación secundaria; la c, a terciaria; y la d describe integración, no disociación.', 'Van der Hart, O., Van der Kolk, B. A. y Boon, S. (1998). Treatment of dissociative disorders. En J. D. Bremner y C. R. Marmar (eds.), Trauma, Memory, and Dissociation. American Psychiatric Press; '+B],
'Simu 8 comentado _007':['La experiencia extrema de observarse como desde fuera del propio cuerpo se asocia principalmente con:',{a:'Trastorno de conversión.',b:'Amnesia disociativa.',c:'Despersonalización.',d:'Fuga disociativa.'},'c','La c es correcta: la despersonalización incluye experiencias de irrealidad o separación del propio yo, incluso sensación extracorporal, conservando el juicio de realidad. La a afecta funciones motoras o sensoriales; la b implica amnesia autobiográfica; y la d añade desplazamiento asociado a amnesia.',D],
'simu 9 comentado_089':['¿Qué autores propusieron un modelo jerárquico que distingue tres niveles de disociación patológica?',{a:'Van der Hart, Van der Kolk y Boon.',b:'Levine.',c:'Kihlstrom.',d:'Dell.'},'a','La a es correcta: estos autores distinguieron disociación primaria, secundaria y terciaria. Levine desarrolló SIBAM; Kihlstrom formuló un modelo cognitivo de memoria; y Dell propuso otros modelos dimensionales de disociación.',B],
'SmCm25PIR2025_208':['¿Cuál NO es un ejemplo de «otro trastorno disociativo especificado» en el DSM-5-TR?',{a:'Trance disociativo.',b:'Fuga disociativa.',c:'Síndromes crónicos y recurrentes de síntomas disociativos mixtos.',d:'Alteración de identidad debida a persuasión coercitiva prolongada e intensa.'},'b','La b es correcta: la fuga disociativa es un especificador de la amnesia disociativa. El trance disociativo, los síndromes mixtos crónicos y la alteración de identidad por persuasión coercitiva son ejemplos de otro trastorno disociativo especificado.',D]
};
for(const [id,z] of Object.entries(U)){const q=a.find(x=>x.id===id);if(!q)throw Error(id);Object.assign(q,{e:z[0],o:z[1],c:z[2],x:z[3],r:z[4],v:'VALIDADA_ORIGINAL'});}fs.writeFileSync(p,JSON.stringify(a));console.log({validated:Object.keys(U).length});
