const fs=require('fs');
const ap='public/banco/tratamientos_adultos.json',cp='public/banco/tratamientos_infantiles.json';
const a=JSON.parse(fs.readFileSync(ap,'utf8')),child=JSON.parse(fs.readFileSync(cp,'utf8')),m=new Map(a.map(q=>[q.id,q]));
const F='Fonseca Pedrero, E. (coord.) (2021). Manual de tratamientos psicológicos: Adultos. Pirámide.';
const FI='Fonseca Pedrero, E. (coord.) (2021). Manual de tratamientos psicológicos: Infancia y adolescencia. Pirámide.';
const B='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. II (4.ª ed.). McGraw Hill.';
function set(id,z,valid=true){const q=m.get(id);if(!q)throw Error(id);Object.assign(q,z);if(valid)q.v='VALIDADA_ORIGINAL';}
function move(id,target,topic){const i=a.findIndex(q=>q.id===id);if(i<0)throw Error('move '+id);const[q]=a.splice(i,1);q.t=[topic];q.v='REVISAR';if(!target.some(x=>x.id===id))target.push(q);}

// Reubicaciones detectadas al preparar el bloque.
for(const [id,topic] of [
 ['PERSEVER___SIMULACRO_COMENTADO_JULIO-UNO-23_103','Tratamiento del TOC y relacionados'],
 ['PERSEVER___SIMULACRO_COMENTADO_JULIO-UNO-23_130','Técnicas psicológicas generales'],
 ['PERSEVER___SIMULACRO_COMENTADO_JUNIO-DOS-23_162','Tratamiento de las adicciones'],
 ['PERSEVER___SIMULACRO_COMENTADO_MAYO-UNO-23_180','Técnicas psicológicas generales'],
 ['PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-DOS-23_097','Tratamiento de los trastornos del sueño'],
 ['PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-DOS-23_109','Introducción'],
 ['PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-UNO-23_058','Psicología de la salud — estrés laboral y burnout'],
 ['PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-DOS-23_163','Tratamientos transdiagnósticos'],
 ['PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-UNO-23_168','Tratamiento de los trastornos de personalidad'],
 ['PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-UNO-23_172','Tratamiento de los trastornos de personalidad']
])move(id,a,topic);
move('SEPTIEMBRE-UNO-24_COMENTADO_084',child,'Trastornos depresivos y bipolares infantojuvenil');

set('PERSEVER___SIMULACRO_COMENTADO_JULIO-UNO-23_131',{e:'Respecto a la terapia interpersonal y de ritmos sociales para el trastorno bipolar, señale la afirmación correcta:',o:{a:'Se diseñó para sustituir sistemáticamente la medicación.',b:'En la fase intermedia se regularizan los ritmos sociales y se trabaja el problema interpersonal seleccionado.',c:'Es una intervención centrada principalmente en experiencias remotas del pasado.',d:'Su grado de recomendación en la clasificación del manual es A.'},c:'b',x:'La fase intermedia combina estabilización de rutinas y sueño-vigilia con el trabajo del área interpersonal. La IPSRT suele complementar la farmacoterapia, se centra en problemas actuales y el manual le asigna grado B.',r:'Frank, E. (2005). Treating Bipolar Disorder: A Clinician\'s Guide to Interpersonal and Social Rhythm Therapy. Guilford Press; '+F});
set('PERSEVER___SIMULACRO_COMENTADO_JUNIO-DOS-23_157',{e:'¿Cuál NO es una característica de la terapia interpersonal para la depresión?',o:{a:'Es focalizada y temporalmente delimitada.',b:'Está orientada desde el tratamiento y prescinde de la formulación diagnóstica.',c:'Se centra en el aquí y ahora.',d:'Analiza el afecto suscitado por las circunstancias interpersonales.'},c:'b',x:'La b es falsa: la TIP se considera orientada desde el diagnóstico. Es focal, breve, centrada en el presente y presta atención al vínculo entre afecto y acontecimientos interpersonales.',r:F});
set('PERSEVER___SIMULACRO_COMENTADO_JUNIO-UNO-23_132',{e:'¿Para qué objetivo resulta especialmente útil la lamotrigina en el trastorno bipolar?',o:{a:'Prevención de episodios depresivos.',b:'Tratamiento específico de la patología dual con alcohol.',c:'Control preferente de la manía aguda con ciclación rápida.',d:'Sustitución de cualquier estabilizador mal tolerado, con independencia de la polaridad.'},c:'a',x:'Lamotrigina destaca en mantenimiento por su capacidad para prevenir recaídas depresivas. No es un tratamiento principal de la manía aguda; las otras opciones atribuyen indicaciones más propias de otros estabilizadores.',r:'Keramatian, K., Chithra, N. K. y Yatham, L. N. (2023). CANMAT and ISBD Guidelines for the Treatment of Bipolar Disorder: Summary and a 2023 Update of Evidence. Focus, 21(4), 344-353.'});
set('PERSEVER___SIMULACRO_COMENTADO_MAYO-DOS-23_073',{e:'Señale la afirmación falsa sobre la terapia interpersonal de Klerman y Weissman:',o:{a:'Está orientada desde el diagnóstico.',b:'No concede un papel central a las tareas entre sesiones.',c:'Las transiciones de rol se seleccionan especialmente cuando no existe ningún desencadenante interpersonal cercano.',d:'Su formato agudo clásico suele comprender alrededor de 12-16 sesiones.'},c:'c',x:'Cuando no se identifica un desencadenante interpersonal próximo se exploran los déficits interpersonales, no las transiciones de rol. Estas últimas implican cambios vitales que obligan a abandonar un rol y asumir otro.',r:F});
set('PERSEVER___SIMULACRO_COMENTADO_MAYO-DOS-23_079',{e:'Según la clasificación de evidencia utilizada en el manual de referencia, ¿qué nivel y grado recibe la terapia interpersonal y de ritmos sociales para el trastorno bipolar?',o:{a:'1+/A.',b:'1+/B.',c:'2+/C.',d:'1-/B.'},c:'b',x:'En la tabla empleada por el manual, la IPSRT presenta nivel de evidencia 1+ y grado de recomendación B. La formulación queda vinculada a esa clasificación concreta.',r:F});
set('PERSEVER___SIMULACRO_COMENTADO_MAYO-UNO-23_128',{e:'Clásicamente, ¿en cuál de las siguientes situaciones se considera menos probable una buena respuesta al litio?',o:{a:'Manía eufórica clásica.',b:'Manía disfórica o con características mixtas.',c:'Potenciación antidepresiva en depresión recurrente resistente.',d:'Prevención de recaídas en trastorno bipolar.'},c:'b',x:'El litio responde mejor en manía eufórica clásica y mantenimiento. La presencia de características mixtas o disfóricas se ha asociado tradicionalmente con peor respuesta relativa, aunque la elección clínica actual depende del perfil individual.',r:B});
set('PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-UNO-23_065',{e:'¿Qué intervención breve de contacto y seguimiento cuenta con recomendación para personas atendidas tras un intento de suicidio?',o:{a:'Brief Intervention and Contact de la OMS (WHO BIC).',b:'Plan de Seguridad de Stanley y Brown.',c:'Volitional Help Sheet.',d:'Attempted Suicide Short Intervention Program.'},c:'a',x:'WHO BIC combina una intervención breve con contactos periódicos de seguimiento después del intento. Se corrige «suicidio consumado»: tras una muerte por suicidio la intervención se dirige a supervivientes o allegados y se denomina posvención.',r:'World Health Organization (2008). Preventing suicide: A resource for media professionals; Fleischmann, A. et al. (2008). Bulletin of the World Health Organization, 86, 703-709.'});
set('PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-UNO-23_099',{e:'Respecto a la terapia interpersonal para la depresión, señale la afirmación correcta:',o:{a:'Se aplica exclusivamente como mantenimiento.',b:'Carece de delimitación temporal.',c:'El duelo es el único problema que puede coexistir con las demás áreas.',d:'Utiliza el rol de enfermo para reducir culpa y legitimar temporalmente la necesidad de ayuda.'},c:'d',x:'La TIP utiliza de forma temporal el rol de enfermo para disminuir culpa y facilitar la implicación terapéutica. Es una intervención delimitada y las áreas problemáticas pueden coexistir, aunque se prioriza un foco.',r:F});
set('PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-UNO-23_161',{e:'Señale la afirmación correcta sobre la terapia interpersonal para la depresión:',o:{a:'Tiene más fundamento teórico que empírico.',b:'Su tratamiento agudo se divide en cuatro fases.',c:'Está orientada desde el diagnóstico.',d:'Se basa principalmente en tareas obligatorias entre sesiones.'},c:'c',x:'La TIP parte del diagnóstico, es pragmática y empíricamente fundamentada. Su formato agudo clásico se organiza en fases inicial, intermedia y de terminación, sin conceder a las tareas entre sesiones el papel central que poseen en otras terapias.',r:F});
set('PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-UNO-23_173',{e:'Respecto a la terapia interpersonal y de ritmos sociales para el trastorno bipolar, señale la afirmación correcta:',o:{a:'Es necesariamente una terapia de larga duración.',b:'La estabilización activa inicial de ritmos se reserva para la fase final.',c:'Se limita a pacientes candidatos a tratamiento asertivo comunitario.',d:'Incluye psicoeducación para favorecer hábitos y rutinas compatibles con la adherencia farmacológica.'},c:'d',x:'La IPSRT combina terapia interpersonal, regulación de ritmos y psicoeducación, incluida la adherencia a la medicación. No se limita al perfil propio del tratamiento asertivo comunitario.',r:'Frank, E. (2005). Treating Bipolar Disorder. Guilford Press.'});
set('PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-UNO-23_180',{e:'¿Cuál es uno de los elementos básicos de la terapia interpersonal y de ritmos sociales?',o:{a:'Prescribir cambios impredecibles de horario para aumentar flexibilidad.',b:'Psicoeducar para apoyar hábitos y rutinas relacionados con la medicación.',c:'Evitar relacionar los acontecimientos interpersonales con el estado de ánimo.',d:'Trabajar exclusivamente con la familia.'},c:'b',x:'La psicoeducación y el apoyo a la adherencia forman parte de la IPSRT, junto con la terapia interpersonal y la regulación de ritmos sociales.',r:'Frank, E. (2005). Treating Bipolar Disorder. Guilford Press.'});
set('SEPTIEMBRE-DOS-24_COMENTADO_139',{e:'Entre las siguientes opciones, ¿qué tratamiento farmacológico se ha recomendado tradicionalmente en el trastorno bipolar con ciclación rápida?',o:{a:'Litio.',b:'Valproato.',c:'Carbamazepina.',d:'Lamotrigina.'},c:'b',x:'Entre estas alternativas, el valproato es la respuesta clásica para ciclación rápida. Lamotrigina destaca en prevención depresiva y el litio suele mostrar menor eficacia relativa en este perfil.',r:'Yatham, L. N. et al. (2018). CANMAT and ISBD 2018 guidelines. Bipolar Disorders, 20, 97-170.'});
set('SEPTIEMBRE-DOS-24_COMENTADO_140',{e:'¿Cuál de las siguientes intervenciones se diseñó principalmente para prevenir la depresión posparto?',o:{a:'Curso Mamás y Bebés.',b:'Mellow Babies.',c:'MomMoodBooster.',d:'MUMentum.'},c:'a',x:'Mamás y Bebés es un programa preventivo cognitivo-conductual durante el periodo perinatal. Mellow Babies y MomMoodBooster son tratamientos para síntomas o depresión posparto; MUMentum aborda ansiedad y depresión perinatal.',r:F});
set('SEPTIEMBRE-DOS-24_COMENTADO_157',{e:'Según la terapia interpersonal, señale la afirmación correcta sobre sus áreas problemáticas:',o:{a:'El duelo se define por un desacuerdo con otra persona.',b:'Las disputas de rol consisten en cualquier cambio vital.',c:'Los déficits interpersonales se exploran especialmente cuando no aparece un desencadenante interpersonal próximo claro.',d:'Las transiciones de rol equivalen al aislamiento social crónico.'},c:'c',x:'Los déficits interpersonales abarcan aislamiento, soledad y pobreza relacional y se consideran cuando no se identifica un acontecimiento interpersonal cercano. Las otras opciones intercambian las definiciones de duelo, disputa y transición.',r:F});
set('SEPTIEMBRE-UNO-24_COMENTADO_005',{e:'En relación con la terapia interpersonal para la depresión, señale la afirmación correcta:',o:{a:'Solo contempla duelo, disputas y transiciones de rol.',b:'Es abierta e ilimitada en el tiempo.',c:'Analiza el afecto o emoción suscitado por las circunstancias interpersonales.',d:'Ofrece una teoría etiológica completa de la depresión con mayor apoyo teórico que empírico.'},c:'c',x:'La TIP analiza el vínculo entre acontecimientos interpersonales, afecto y síntomas. Es focal y temporalmente delimitada, y contempla cuatro áreas, incluida la de déficits interpersonales.',r:F});
set('SIM_ABR2_036',{e:'¿Para qué presentación depresiva se desarrolló específicamente el CBASP de McCullough?',o:{a:'Depresión crónica o persistente.',b:'Trastorno de pánico.',c:'Fobia específica.',d:'TDAH.'},c:'a',x:'El Sistema de Análisis Cognitivo-Conductual de Psicoterapia fue desarrollado específicamente para la depresión crónica, atendiendo especialmente a sus patrones interpersonales.',r:'McCullough, J. P. (2000). Treatment for Chronic Depression: Cognitive Behavioral Analysis System of Psychotherapy. Guilford Press.'});
set('SIM_ABR2_044',{e:'¿Cuáles son las cuatro áreas problemáticas clásicas de la terapia interpersonal para la depresión?',o:{a:'Duelo, disputas de rol, transiciones de rol y déficits interpersonales.',b:'Activación, exposición, reestructuración y prevención de recaídas.',c:'Trabajo, familia, ocio y autocuidado.',d:'Apego, mentalización, transferencia y contratransferencia.'},c:'a',x:'La TIP organiza el foco en duelo, disputas, transiciones y déficits interpersonales. Se selecciona prioritariamente el área más vinculada con el episodio actual.',r:F});
set('SIM_ABR2_068',{e:'¿Cuál es el objetivo central de la activación conductual para la depresión?',o:{a:'Aumentar el contacto con fuentes de reforzamiento mediante actividades acordes con objetivos y valores.',b:'Interpretar el contenido latente de los sueños.',c:'Eliminar toda emoción negativa.',d:'Modificar directamente rasgos estables de personalidad.'},c:'a',x:'La activación conductual busca romper los patrones de retirada y evitación aumentando conductas potencialmente reforzantes y funcionales.',r:'Martell, C. R., Dimidjian, S. y Herman-Dunn, R. (2010). Behavioral Activation for Depression. Guilford Press.'});
set('SIM_ABR2_091',{e:'¿Qué proceso de mantenimiento intenta reducir especialmente la activación conductual en la depresión?',o:{a:'La evitación y retirada de actividades.',b:'La experiencia de cualquier emoción.',c:'La necesidad fisiológica de dormir.',d:'La exposición a todo acontecimiento vital.'},c:'a',x:'La evitación proporciona alivio inmediato, pero reduce el contacto con refuerzos y mantiene el ánimo depresivo. La activación sustituye progresivamente ese patrón por acciones funcionales.',r:'Martell, C. R., Dimidjian, S. y Herman-Dunn, R. (2010). Behavioral Activation for Depression. Guilford Press.'});
set('SIM_ABR2_116',{e:'¿Cuál es una técnica central de la activación conductual para la depresión?',o:{a:'Registro y programación estructurada de actividades.',b:'Interpretación de sueños.',c:'Hipnosis como procedimiento principal.',d:'Confrontación agresiva de las creencias.'},c:'a',x:'El registro permite identificar relaciones entre actividad y estado de ánimo; la programación ayuda a incrementar gradualmente actividades relevantes y reducir la evitación.',r:'Martell, C. R., Dimidjian, S. y Herman-Dunn, R. (2010). Behavioral Activation for Depression. Guilford Press.'});

fs.writeFileSync(ap,JSON.stringify(a));fs.writeFileSync(cp,JSON.stringify(child));
console.log('Bloque 3: 20 auditadas y 11 reubicadas.');
