const fs=require('fs');
const ap='public/banco/tratamientos_adultos.json',cp='public/banco/tratamientos_infantiles.json';
const a=JSON.parse(fs.readFileSync(ap,'utf8')),child=JSON.parse(fs.readFileSync(cp,'utf8')),m=new Map(a.map(q=>[q.id,q]));
const F='Fonseca Pedrero, E. (coord.) (2021). Manual de tratamientos psicológicos: Adultos. Pirámide.';
const B='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. II (4.ª ed.). McGraw Hill.';
function set(id,z){const q=m.get(id);if(!q)throw Error(id);Object.assign(q,z,{v:'VALIDADA_ORIGINAL'});}
function move(id,target,topic){const i=a.findIndex(q=>q.id===id);if(i<0)throw Error('move '+id);const[q]=a.splice(i,1);q.t=[topic];q.v='REVISAR';if(!target.some(x=>x.id===id))target.push(q);}
for(const [id,topic] of [
 ['SmCm22PIR2025 (1)_125','Tratamiento del TOC y relacionados'],['SmCm23PIR2025 (2)_178','Tratamiento de los trastornos de ansiedad'],
 ['SmCm27PIR2025 (1)_038','Tratamiento de los trastornos de ansiedad'],['SmCm29PIR2025_167','Técnicas psicológicas generales'],
 ['SmCm30PIR2025 (1)_078','Tratamiento de los trastornos de ansiedad'],['SmCm4PIR2024_147','Técnicas psicológicas generales'],
 ['SmCm4PIR2024_168','Tratamiento de los trastornos de ansiedad'],['SmCm4PIR2024_173','Introducción']
])move(id,a,topic);
move('SmCm2PIR2024_151',child,'Trastornos de ansiedad infantojuvenil');

set('SmCm20PIR2025 (1)_186',{e:'¿Qué grupo de antidepresivos suele considerarse inicialmente por su equilibrio entre eficacia, tolerabilidad y seguridad?',o:{a:'Antidepresivos tricíclicos.',b:'Inhibidores de la monoaminooxidasa.',c:'Inhibidores selectivos de la recaptación de serotonina.',d:'Sales de litio.'},c:'c',x:'Los ISRS suelen considerarse una primera opción farmacológica por tolerabilidad y seguridad relativa. La elección concreta depende de síntomas, riesgos, interacciones, preferencias y respuesta previa.',r:'National Institute for Health and Care Excellence (2022). Depression in adults: treatment and management (NG222).'});
set('SmCm22PIR2025 (1)_113',{e:'¿Cuál de los siguientes programas NO fue diseñado para tratar la depresión?',o:{a:'Terapia interpersonal de Klerman y Weissman.',b:'Programa PIENSA para primeros episodios psicóticos.',c:'Terapia cognitiva basada en mindfulness para prevenir recaídas depresivas.',d:'Terapia de autocontrol de Rehm.'},c:'b',x:'PIENSA es un programa para jóvenes con primeros episodios psicóticos y sus familias. TIP y autocontrol se desarrollaron para depresión; MBCT se utiliza especialmente en prevención de recaídas.',r:F});
set('SmCm22PIR2025_210',{e:'Según el planteamiento de la terapia conductual de pareja para la depresión, ¿cómo puede entenderse la relación entre síntomas depresivos y problemas de pareja?',o:{a:'Los problemas de pareja causan siempre la depresión.',b:'La depresión causa siempre el deterioro de pareja.',c:'Ambos fenómenos son necesariamente independientes.',d:'La influencia puede ser bidireccional o depender de terceros factores; no existe una dirección causal única.'},c:'d',x:'La depresión puede deteriorar la interacción de pareja y los conflictos pueden mantener o agravar síntomas; también pueden compartir antecedentes. La formulación funcional debe establecerse en cada caso.',r:F});
set('SmCm25PIR2025_069',{e:'¿Cuál de las siguientes NO es una adaptación habitual de la terapia interpersonal de Klerman y Weissman?',o:{a:'Formato de pareja o conjunto.',b:'Formato grupal.',c:'Consejo interpersonal breve.',d:'Formato multifamiliar como adaptación canónica específica de la TIP.'},c:'d',x:'La TIP se ha adaptado a formatos conjuntos, grupales y breves. El formato multifamiliar no figura como una adaptación canónica específica de la intervención.',r:'Markowitz, J. C. y Weissman, M. M. (2012). Interpersonal psychotherapy: past, present and future. Clinical Psychology & Psychotherapy, 19, 99-105.'});
set('SmCm25PIR2025_149',{e:'¿Cuál de las siguientes circunstancias NO constituye por sí sola una indicación suficiente de terapia electroconvulsiva en la depresión?',o:{a:'Falta de respuesta a un único antidepresivo, sin valorar adecuación, alternativas, gravedad ni urgencia.',b:'Depresión grave con síntomas psicóticos y marcada inhibición o agitación.',c:'Compromiso físico grave que exige una respuesta rápida.',d:'Buena respuesta previa a TEC junto con escasa respuesta a otros tratamientos.'},c:'a',x:'El fracaso aislado de un solo fármaco no basta automáticamente. La TEC se considera en depresión grave cuando se necesita respuesta rápida, existe riesgo vital o han fallado tratamientos adecuados, integrando antecedentes y preferencias.',r:'National Institute for Health and Care Excellence (2022). Depression in adults: treatment and management (NG222).'});
set('SmCm26PIR2025_035',{e:'¿Qué terapia se diseñó específicamente para la depresión crónica, es altamente estructurada y trabaja intensamente las relaciones interpersonales?',o:{a:'Terapia interpersonal de Klerman.',b:'Terapia cognitiva de Beck.',c:'Psicoterapia dinámica breve.',d:'CBASP de McCullough.'},c:'d',x:'El CBASP fue creado para depresión crónica y utiliza análisis situacional, aprendizaje interpersonal disciplinado y otras estrategias estructuradas.',r:'McCullough, J. P. (2003). Treatment for chronic depression using CBASP. Journal of Clinical Psychology, 59, 833-846.'});
set('SmCm26PIR2025_036',{e:'¿Qué intervención preventiva de la depresión posparto trabaja con la díada madre-bebé y se apoya en la relación entre sueño o inquietud infantil y estado de ánimo materno?',o:{a:'Curso Mamás y Bebés.',b:'ROSE.',c:'Be a Mom.',d:'PREPP.'},c:'d',x:'PREPP es una intervención conductual iniciada durante el embarazo que enseña estrategias de cuidado infantil orientadas al sueño y llanto y busca reducir síntomas depresivos posparto. Se corrige el acrónimo original «PREP».',r:'Werner, E. A. et al. Practical Resources for Effective Postpartum Parenting (PREPP): intervención preventiva diádica madre-bebé.'});
for(const id of ['SmCm26PIR2025_037','SmCm2PIR2024_158'])set(id,{e:'¿Qué tratamiento para la depresión utiliza los acrónimos TRAP y TRAC para identificar evitación y promover afrontamiento alternativo?',o:{a:'Terapia interpersonal.',b:'Terapia cognitiva clásica de Beck.',c:'Curso para el Afrontamiento de la Depresión.',d:'Activación conductual.'},c:'d',x:'TRAP identifica desencadenante, respuesta y patrón de evitación; TRAC sustituye este último por una respuesta alternativa de afrontamiento. Ambos pertenecen a la activación conductual.',r:'Martell, C. R., Dimidjian, S. y Herman-Dunn, R. (2010). Behavioral Activation for Depression. Guilford Press.'});
set('SmCm27PIR2025 (1)_040',{e:'En la evaluación de una persona con depresión e ideación suicida, señale la actuación correcta:',o:{a:'Interpretar la negación de ideación como prueba suficiente de que no existe riesgo.',b:'Evitar siempre consultar a allegados aunque existan dudas relevantes.',c:'Preguntar de forma clara, directa y natural sobre ideación, planes, intención y acceso a medios.',d:'No valorar posibles riesgos para terceros incluidos en el plan.'},c:'c',x:'Preguntar directamente no induce conducta suicida y permite valorar el riesgo. La evaluación debe integrar información clínica y, cuando resulte necesario y esté justificado, información de allegados y riesgo para otras personas.',r:'National Institute for Health and Care Excellence (2022). Self-harm: assessment, management and preventing recurrence (NG225).'});
set('SmCm29PIR2025_168',{e:'Señale la afirmación incorrecta sobre intervenciones respaldadas para la depresión:',o:{a:'La solución de problemas puede utilizarse en determinadas depresiones menos graves.',b:'La terapia cognitiva basada en mindfulness se emplea especialmente para prevenir recaídas.',c:'Las intervenciones de menor intensidad pueden incluir autoayuda guiada y activación conductual.',d:'La psicoterapia de apoyo inespecífica es necesariamente superior a TCC y activación conductual.'},c:'d',x:'La d atribuye una superioridad que no está respaldada. La selección depende de gravedad y preferencias; solución de problemas, MBCT e intervenciones estructuradas de baja intensidad poseen indicaciones concretas.',r:'National Institute for Health and Care Excellence (2022). Depression in adults: treatment and management (NG222).'});
set('SmCm29PIR2025_169',{e:'¿Cuáles son las áreas problemáticas clásicas de la terapia interpersonal para la depresión?',o:{a:'Duelo, culpa, habilidades sociales y déficits interpersonales.',b:'Habilidades sociales, autocuidado, déficit interpersonal y transición.',c:'Duelo, autocuidado, asertividad y aislamiento.',d:'Duelo, disputas de rol, transiciones de rol y déficits interpersonales.'},c:'d',x:'La TIP organiza la intervención en duelo, disputas, transiciones y déficits interpersonales, priorizando el foco más relacionado con el episodio actual.',r:F});
set('SmCm2PIR2024_152',{e:'¿Cuál de los siguientes fármacos NO constituye un tratamiento específico del trastorno bipolar?',o:{a:'Litio.',b:'Quetiapina.',c:'Lamotrigina.',d:'Clordiazepóxido.'},c:'d',x:'Clordiazepóxido es una benzodiacepina y no es un tratamiento específico del trastorno bipolar. Litio, quetiapina y lamotrigina poseen indicaciones concretas según fase y polaridad.',r:'Yatham, L. N. et al. (2018). CANMAT and ISBD 2018 guidelines. Bipolar Disorders, 20, 97-170.'});
set('SmCm2PIR2024_154',{e:'¿Qué tres fases del autocontrol presentan déficits en el modelo de depresión de Rehm?',o:{a:'Motivación, tratamiento y prevención de recaídas.',b:'Conducta, cognición y experiencia.',c:'Autoobservación, autoevaluación y autorrefuerzo.',d:'Autocontemplación, identificación y conciencia de enfermedad.'},c:'c',x:'Rehm propone alteraciones en autoobservación, autoevaluación y autorrefuerzo: atención sesgada, criterios exigentes o atribuciones inadecuadas y escaso autorrefuerzo.',r:'Rehm, L. P. (1977). A self-control model of depression. Behavior Therapy, 8, 787-804.'});
set('SmCm2PIR2024_155',{e:'¿Qué terapia para la depresión se focaliza en resolver una crisis actual relacionada con duelo, disputa, transición de rol o déficits interpersonales?',o:{a:'Terapia racional-emotiva.',b:'Terapia de aceptación y compromiso.',c:'Terapia cognitiva de Beck.',d:'Terapia interpersonal.'},c:'d',x:'La TIP vincula el episodio depresivo con una de cuatro áreas interpersonales y trabaja la crisis actual para reducir síntomas y recuperar funcionamiento.',r:F});
set('SmCm2PIR2024_156',{e:'Señale la afirmación correcta sobre el Curso para el Afrontamiento de la Depresión de Lewinsohn:',o:{a:'Excluye deliberadamente cualquier componente cognitivo.',b:'El terapeuta adopta un papel completamente no directivo.',c:'Se diseñó inicialmente para adultos y posteriormente se adaptó a otras poblaciones.',d:'No dispone de estudios de eficacia.'},c:'c',x:'El CAD se desarrolló para adultos y dio lugar a adaptaciones, incluida la versión adolescente. Es estructurado, directivo y multicomponente, con actividades, habilidades sociales y cogniciones.',r:F});
set('SmCm30PIR2025 (1)_074',{e:'En terapia interpersonal, ¿qué área aborda cambios vitales que obligan a abandonar un rol y asumir otro, pudiendo vivirse como una pérdida?',o:{a:'Disputa de rol.',b:'Difusión de rol.',c:'Indefinición de rol.',d:'Transición de rol.'},c:'d',x:'Las transiciones incluyen jubilación, maternidad, enfermedad, cambio laboral o convertirse en cuidador. Se trabajan las pérdidas del rol anterior y las demandas del nuevo.',r:F});
set('SmCm30PIR2025 (1)_075',{e:'¿Qué afirmación describe correctamente el Curso para el Afrontamiento de la Depresión de Lewinsohn?',o:{a:'Consta necesariamente de seis sesiones.',b:'Fue diseñado originalmente solo para adolescentes.',c:'Promueve actividades agradables y entrena habilidades sociales, además de trabajar cogniciones.',d:'Es una variante directa de la terapia cognitiva de Beck.'},c:'c',x:'El CAD es un programa conductual-educativo multicomponente con actividades agradables, habilidades sociales y modificación cognitiva. No deriva simplemente de la terapia de Beck.',r:F});
set('SmCm3PIR2024_137',{e:'¿Qué intervención se diseñó especialmente para prevenir recaídas en personas con depresión recurrente actualmente en remisión?',o:{a:'Activación conductual como única intervención posible.',b:'Terapia interpersonal aguda.',c:'Terapia cognitiva estándar sin adaptación preventiva.',d:'Terapia cognitiva basada en mindfulness.'},c:'d',x:'MBCT se desarrolló para reducir la reactivación de patrones depresivos y prevenir recaídas, especialmente en personas con episodios recurrentes.',r:'Segal, Z. V., Williams, J. M. G. y Teasdale, J. D. (2013). Mindfulness-Based Cognitive Therapy for Depression (2nd ed.). Guilford Press.'});
set('SmCm3PIR2024_167',{e:'En análisis funcional, ¿qué diferencia existe entre un estímulo condicionado y un estímulo discriminativo?',o:{a:'El condicionado elicita una respuesta aprendida; el discriminativo señala que una conducta tendrá determinadas consecuencias.',b:'El condicionado causa solo emociones y el discriminativo solo respuestas motoras.',c:'Ambos términos son sinónimos.',d:'El condicionado precede conductas involuntarias y el discriminativo siempre conductas plenamente conscientes.'},c:'a',x:'El EC adquiere capacidad para elicitar una respuesta por asociación con otro estímulo. El Ed señala una contingencia operante: en su presencia, determinada respuesta probablemente será reforzada o castigada.',r:'Miltenberger, R. G. (2017). Modificación de conducta: principios y procedimientos. Pirámide.'});

fs.writeFileSync(ap,JSON.stringify(a));fs.writeFileSync(cp,JSON.stringify(child));
console.log('Bloque 7: 20 auditadas y 9 reubicadas.');
