const fs=require('fs');
const paths={adult:'public/banco/tratamientos_adultos.json',child:'public/banco/tratamientos_infantiles.json'};
const adult=JSON.parse(fs.readFileSync(paths.adult,'utf8'));
const child=JSON.parse(fs.readFileSync(paths.child,'utf8'));
const m=new Map(adult.map(q=>[q.id,q]));
const F='Fonseca Pedrero, E. (coord.) (2021). Manual de tratamientos psicológicos: Adultos. Pirámide.';
const FI='Fonseca Pedrero, E. (coord.) (2021). Manual de tratamientos psicológicos: Infancia y adolescencia. Pirámide.';
const B='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. II (4.ª ed.). McGraw Hill.';
function set(id,z){const q=m.get(id);if(!q)throw Error('No existe '+id);Object.assign(q,z,{v:'VALIDADA_ORIGINAL'});}
function move(id,target,topic){const i=adult.findIndex(q=>q.id===id);if(i<0)throw Error('No existe para mover '+id);const [q]=adult.splice(i,1);q.t=[topic];q.v='VALIDADA_ORIGINAL';if(!target.some(x=>x.id===id))target.push(q);}

// Criba: preguntas inequívocamente ajenas al tema que aparecían antes del bloque útil.
set('JUNIO-UNO-24_COMENTADO_183',{e:'Según el modelo biosocial de Linehan, ¿cuál NO es una característica básica de la vulnerabilidad emocional?',o:{a:'Alta sensibilidad ante estímulos emocionales.',b:'Respuestas emocionales muy intensas.',c:'Retorno lento a la línea de base emocional.',d:'Bajo afecto positivo como componente definitorio independiente.'},c:'d',x:'La d es la excepción. Linehan describe sensibilidad elevada, respuesta intensa y retorno lento a la línea de base; el bajo afecto positivo no integra esa tríada definitoria.',r:'Linehan, M. M. (1993). Cognitive-Behavioral Treatment of Borderline Personality Disorder. Guilford Press.'});
move('JUNIO-UNO-24_COMENTADO_183',adult,'Tratamiento de los trastornos de personalidad');
set('MAYO-UNO-24_COMENTADO_077',{e:'Respecto al tratamiento farmacológico de la anorexia nerviosa, señale la afirmación incorrecta:',o:{a:'No existe un tratamiento farmacológico específico claramente establecido.',b:'Los antidepresivos tricíclicos no se recomiendan como tratamiento de elección.',c:'La evidencia disponible para el litio es escasa.',d:'Los IMAO constituyen un tratamiento de primera elección respaldado por evidencia sólida.'},c:'d',x:'La d es incorrecta: los IMAO no son tratamiento de primera elección. La intervención nutricional y psicológica constituye la base; los fármacos pueden reservarse para indicaciones concretas o comorbilidad.',r:F});
move('MAYO-UNO-24_COMENTADO_077',adult,'Tratamiento de los trastornos alimentarios');
set('MAYO-UNO-24_COMENTADO_124',{e:'Según las recomendaciones clínicas españolas sobre el TDAH, señale la afirmación correcta:',o:{a:'El metilfenidato es el único fármaco empleado en cualquier grupo de edad.',b:'Entre las opciones farmacológicas se encuentran metilfenidato, atomoxetina, lisdexanfetamina y guanfacina, según edad, autorización e indicación clínica.',c:'Los antidepresivos son tratamiento farmacológico de primera elección en todos los adultos.',d:'Antes de los cinco años se recomienda iniciar sistemáticamente medicación antes que intervención psicosocial.'},c:'b',x:'La b recoge las principales alternativas farmacológicas, cuya autorización concreta depende de edad y ficha técnica. Las demás opciones generalizan o invierten la prioridad de intervención en preescolares.',r:'Ministerio de Sanidad (2017). Guía de práctica clínica sobre las intervenciones terapéuticas en el TDAH.'});
move('MAYO-UNO-24_COMENTADO_124',child,'TDAH');
set('MAYO2_138',{e:'Señale la afirmación incorrecta sobre los procedimientos paradójicos:',o:{a:'La restricción paradójica puede emplearse ante resistencia y oposición al cambio.',b:'La prescripción del síntoma es una de sus modalidades más habituales.',c:'Subrayar posibles inconvenientes de mejorar puede disminuir la resistencia.',d:'En el sabotaje benévolo se premia a quien intensifique más una escalada de gritos y amenazas.'},c:'d',x:'La d es incorrecta: el sabotaje benévolo interrumpe de forma indirecta una secuencia problemática; no prescribe premiar la escalada agresiva. Las otras opciones describen usos paradójicos clásicos.',r:'Ruiz Fernández, M. A. et al. Manual de técnicas de intervención cognitivo-conductuales.'});
move('MAYO2_138',adult,'Técnicas psicológicas generales');
for(const [id,e,o,c,x] of [
 ['MAYO2_140','¿En qué programa transdiagnóstico infantil se utiliza la figura del «detective de emociones» para analizar sensaciones físicas, pensamientos y conductas?',{a:'MATCH-ADTC.',b:'EMOTION.',c:'Super Skills for Life.',d:'Group Behavioral Activation Therapy.'},'b','EMOTION enseña a los menores a investigar las claves de sus emociones atendiendo a sensaciones, pensamientos y acciones.'],
 ['OCTUBRE-UNO-24_COMENTADO_105','Señale la afirmación incorrecta al comparar el programa ACTION de Stark y el Curso de Afrontamiento de la Depresión para Adolescentes de Lewinsohn:',{a:'El curso de Lewinsohn carece de entrenamiento en habilidades interpersonales.',b:'ACTION se dirige aproximadamente a niños de 8 a 13 años.',c:'El curso adolescente se desarrolla habitualmente durante unas ocho semanas.',d:'ACTION comprende alrededor de treinta sesiones.'},'a','La a es incorrecta: el curso incluye entrenamiento en habilidades sociales e interpersonales. Las restantes opciones recogen diferencias habituales de población y formato.'],
 ['PERSEV_JUL25_D2_087','¿Qué afirmación diferencia correctamente ACTION del Curso de Afrontamiento de la Depresión para Adolescentes?',{a:'El curso de Lewinsohn se dirige principalmente a niños de 8 a 13 años.',b:'ACTION incluye educación emocional.',c:'El curso de Lewinsohn dura treinta semanas.',d:'Ambos se administran exclusivamente de forma individual.'},'b','ACTION incluye educación emocional y se orienta a niños; el curso de Lewinsohn se dirige a adolescentes, es grupal y no dura treinta semanas.'],
 ['PERSEVER___SIMULACRO_COMENTADO_ABRIL-UNO-23_183','Respecto al programa EMOTION, señale la afirmación correcta:',{a:'Es una intervención grupal de veinte sesiones para niños de 8 a 13 años con síntomas de ansiedad o depresión.',b:'Su enfoque es exclusivamente conductual.',c:'Excluye cualquier participación de los padres.',d:'Todas sus sesiones se dedican únicamente a practicar habilidades con los niños.'},'a','EMOTION es un programa grupal transdiagnóstico de veinte sesiones para niños de 8 a 13 años e incorpora componentes cognitivos, conductuales y participación parental.']
]){set(id,{e,o,c,x,r:FI});move(id,child,'Trastornos depresivos y bipolares infantojuvenil');}
set('PERSEVER___SIMULACRO_COMENTADO_ABRIL-DOS-23_055',{e:'Entre los motivos habituales por los que una persona con trastorno de personalidad solicita atención, ¿cuál es menos característico?',o:{a:'Reconocer de forma estable que sus rasgos de personalidad constituyen el problema principal y solicitar cambiarlos.',b:'Conductas disruptivas que deterioran la adaptación social.',c:'Dificultades asociadas al curso de una enfermedad física.',d:'Problemas interpersonales.'},c:'a',x:'La a es la menos habitual porque los rasgos suelen ser egosintónicos y la consulta se produce con frecuencia por crisis, síntomas asociados, problemas interpersonales o consecuencias funcionales.',r:B});
move('PERSEVER___SIMULACRO_COMENTADO_ABRIL-DOS-23_055',adult,'Tratamiento de los trastornos de personalidad');

// Segundo bloque: veinte preguntas que sí pertenecen a depresión y trastornos del ánimo.
set('JUNIO-UNO-24_COMENTADO_205',{e:'Tras la remisión de un episodio depresivo mayor, ¿cuál es la duración mínima habitual recomendada para continuar el antidepresivo a la misma dosis eficaz?',o:{a:'Dos años en todos los casos.',b:'Al menos seis meses.',c:'Solo tres meses.',d:'Puede suspenderse inmediatamente tras la remisión.'},c:'b',x:'Se recomienda mantener el tratamiento al menos seis meses tras la remisión. En personas con riesgo elevado de recaída puede prolongarse dos años o más; por eso no debe formularse esa duración como regla universal.',r:'National Institute for Health and Care Excellence (2022). Depression in adults: treatment and management (NG222).'});
set('JUNIO1_135',{e:'Entre las siguientes opciones, ¿qué estabilizador del ánimo se ha recomendado tradicionalmente para episodios maníacos con características mixtas?',o:{a:'Carbamazepina.',b:'Valproato.',c:'Lamotrigina.',d:'Oxcarbazepina.'},c:'b',x:'Entre estas alternativas, el valproato es la respuesta clásica para manía con características mixtas. Lamotrigina se emplea sobre todo en depresión bipolar y prevención de recaídas depresivas; la elección actual debe individualizarse.',r:'Yatham, L. N. et al. (2018). CANMAT and ISBD 2018 guidelines for the management of patients with bipolar disorder. Bipolar Disorders, 20, 97-170.'});
set('MAYO-UNO-24_COMENTADO_092',{e:'Respecto a la terapia interpersonal de Klerman y Weissman para la depresión, señale la afirmación correcta:',o:{a:'Es focalizada y limitada en el tiempo.',b:'Se centra principalmente en conflictos remotos del pasado.',c:'Evita formular un diagnóstico.',d:'Se fundamenta solo en teoría, sin apoyo empírico.'},c:'a',x:'La TIP es una terapia breve, focal, vinculada al diagnóstico y centrada en problemas interpersonales actuales relacionados con el episodio depresivo.',r:F});
set('OCTUBRE-UNO-24_COMENTADO_113',{e:'En la prevención de la conducta suicida, ¿qué caracteriza a una estrategia de prevención indicada?',o:{a:'Se dirige por igual a toda la población.',b:'Se dirige únicamente a grupos definidos por riesgo estadístico, aunque nadie presente signos.',c:'Solo se aplica después de un suicidio consumado.',d:'Se dirige a personas concretas que ya muestran signos, síntomas o conductas de riesgo suicida.'},c:'d',x:'La prevención indicada se dirige a individuos que ya presentan señales o conductas de riesgo. La universal alcanza a toda la población y la selectiva a subgrupos con mayor riesgo.',r:'World Health Organization (2014). Preventing suicide: A global imperative.'});
set('OCTUBRE-UNO-24_COMENTADO_149',{e:'¿Cuál de los siguientes programas digitales fue diseñado específicamente para tratar la depresión posparto?',o:{a:'Be a Mom.',b:'ROSE.',c:'MomMoodBooster.',d:'Curso Mamás y Bebés.'},c:'c',x:'MomMoodBooster es una intervención cognitivo-conductual web guiada para mujeres con depresión posparto. ROSE, Be a Mom y Mamás y Bebés se han estudiado principalmente como programas preventivos.',r:'Danaher, B. G. et al. (2013). Web-Based Intervention for Postpartum Depression: Formative Research and Design of the MomMoodBooster Program. JMIR Research Protocols, 2(2), e18.'});
set('PERSEV_AGO25_U1_145',{e:'¿En qué fase de la terapia interpersonal y de ritmos sociales se consolidan las habilidades y se anticipan amenazas interpersonales o alteraciones de rutinas que podrían favorecer una recaída?',o:{a:'Inicial.',b:'Intermedia.',c:'Mantenimiento o prevención.',d:'Terminación.'},c:'c',x:'La fase de mantenimiento consolida lo aprendido, fortalece la autonomía y anticipa amenazas a la estabilidad. La fase intermedia es donde se regularizan activamente los ritmos y se trabaja el problema interpersonal.',r:'Frank, E. (2005). Treating Bipolar Disorder: A Clinician\'s Guide to Interpersonal and Social Rhythm Therapy. Guilford Press.'});
set('PERSEV_JUL25_D2_130',{e:'¿Cuál de las siguientes intervenciones digitales para el trastorno bipolar se administra principalmente a través de una plataforma web?',o:{a:'MONARCA.',b:'ORBIT.',c:'SIMPLe.',d:'PRISM.'},c:'b',x:'ORBIT es una intervención web para el trastorno bipolar. SIMPLe, MONARCA y PRISM se desarrollaron como intervenciones o sistemas vinculados al teléfono móvil.',r:F});
set('PERSEVER___SIMULACRO_COMENTADO_ABRIL-DOS-23_085',{e:'¿Cuál de las siguientes es una intervención basada en web para personas con trastorno bipolar?',o:{a:'MONARCA.',b:'ORBIT.',c:'PRISM.',d:'SIMPLe.'},c:'b',x:'ORBIT se administra mediante web. SIMPLe y MONARCA son intervenciones móviles, y PRISM se diseñó para teléfonos inteligentes. Se corrige la clave original, que marcaba erróneamente PRISM.',r:F});
set('PERSEVER___SIMULACRO_COMENTADO_ABRIL-UNO-23_176',{e:'Respecto a la terapia interpersonal para la depresión, señale la afirmación correcta:',o:{a:'Es una intervención principalmente teórica y poco pragmática.',b:'Cuenta con adaptaciones para formatos de pareja y de grupo.',c:'El consejo interpersonal breve carece de eficacia.',d:'Niega que la depresión pueda conceptualizarse como una enfermedad médica.'},c:'b',x:'La TIP dispone de adaptaciones a distintos formatos, entre ellos pareja y grupo. Es pragmática y empírica, acepta el rol de enfermedad y cuenta con versiones breves.',r:F});
set('PERSEVER___SIMULACRO_COMENTADO_ABRIL-UNO-23_179',{e:'Entre las siguientes intervenciones psicológicas para el trastorno bipolar, ¿cuál ha presentado tradicionalmente menor apoyo empírico?',o:{a:'Rehabilitación cognitiva y funcional.',b:'Cuidado sistemático.',c:'Terapia centrada en la familia.',d:'Terapia interpersonal y de ritmos sociales.'},c:'a',x:'En la clasificación utilizada por el manual, la rehabilitación cognitiva y funcional dispone de menor respaldo que el cuidado sistemático, la terapia familiar y la IPSRT.',r:F});
set('PERSEVER___SIMULACRO_COMENTADO_ABRIL-UNO-23_194',{e:'¿Cuáles son las modalidades más habituales del cuidado sistemático o atención comunitaria continuada en el trastorno bipolar?',o:{a:'Equipos de crisis exclusivamente.',b:'Gestión de casos y tratamiento asertivo comunitario.',c:'Hospitalización prolongada y terapia electroconvulsiva.',d:'Todas las modalidades se utilizan con idéntica frecuencia.'},c:'b',x:'La gestión de casos y el tratamiento asertivo comunitario son las formas principales de organizar una atención continuada e integrada en la comunidad.',r:F});
set('PERSEVER___SIMULACRO_COMENTADO_ABRIL-UNO-23_195',{e:'En terapia interpersonal para la depresión, ¿qué área problemática se aborda cuando predominan soledad, aburrimiento y escasez de relaciones significativas?',o:{a:'Duelo.',b:'Disputas de rol.',c:'Transiciones de rol.',d:'Déficits interpersonales.'},c:'d',x:'Los déficits interpersonales se seleccionan cuando existe aislamiento o dificultad persistente para iniciar y mantener relaciones. No se describe una pérdida, disputa o cambio de rol concreto.',r:F});
set('PERSEVER___SIMULACRO_COMENTADO_AGOSTO-UNO-23_056',{e:'Entre los siguientes estabilizadores del ánimo, ¿cuál se ha recomendado tradicionalmente en el trastorno bipolar con ciclación rápida?',o:{a:'Valproato.',b:'Carbamazepina.',c:'Oxcarbazepina.',d:'Lamotrigina.'},c:'a',x:'El valproato es la respuesta clásica entre estas opciones para ciclación rápida. Se corrige la clave original «oxcarbazepina», que no es la recomendación de referencia.',r:'Yatham, L. N. et al. (2018). CANMAT and ISBD 2018 guidelines. Bipolar Disorders, 20, 97-170.'});
set('PERSEVER___SIMULACRO_COMENTADO_AGOSTO-UNO-23_179',{e:'En la terapia interpersonal y de ritmos sociales para el trastorno bipolar, ¿en qué fase se trabaja activamente la regularización de los ritmos y la resolución del problema interpersonal?',o:{a:'Inicial.',b:'Intermedia.',c:'Mantenimiento.',d:'Terminación.'},c:'b',x:'Estas tareas corresponden a la fase intermedia. La fase inicial evalúa y selecciona el foco; mantenimiento consolida y previene recaídas; terminación revisa logros y vulnerabilidades.',r:'Frank, E. (2005). Treating Bipolar Disorder. Guilford Press.'});
set('PERSEVER___SIMULACRO_COMENTADO_AGOSTO-UNO-23_193',{e:'¿Cuántas sesiones comprende habitualmente el «consejo interpersonal», adaptación breve y sencilla de la terapia interpersonal?',o:{a:'1-2.',b:'3-8.',c:'9-12.',d:'16-20.'},c:'b',x:'El consejo interpersonal es una adaptación de baja intensidad que suele desarrollarse en tres a ocho sesiones.',r:F});
set('PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-DOS-23_151',{e:'¿Qué afirmación describe correctamente la terapia interpersonal y de ritmos sociales para el trastorno bipolar?',o:{a:'Se desarrolló originalmente como tratamiento grupal independiente de la medicación.',b:'Fue creada por el Grupo de Barcelona.',c:'Se fundamenta exclusivamente en la emoción expresada familiar.',d:'Integra terapia del ritmo social, terapia interpersonal y psicoeducación.'},c:'d',x:'La IPSRT integra regulación de ritmos sociales, estrategias interpersonales y psicoeducación. Fue desarrollada por Frank y colaboradores y suele complementar el tratamiento farmacológico.',r:'Frank, E. (2005). Treating Bipolar Disorder. Guilford Press.'});
set('PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-UNO-23_148',{e:'Según la gradación de evidencia recogida en el manual de referencia, ¿qué programa preventivo de depresión posparto alcanza el nivel más alto entre estas opciones?',o:{a:'ROSE.',b:'Mellow Babies.',c:'Be a Mom.',d:'Curso Mamás y Bebés.'},c:'d',x:'En la tabla comparativa del manual, el Curso Mamás y Bebés recibe el nivel de evidencia y grado de recomendación más elevados entre estas alternativas. La pregunta se formula expresamente según esa clasificación, que puede cambiar con nueva evidencia.',r:F});
set('PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-UNO-23_159',{e:'En terapia interpersonal para la depresión, ¿qué situación constituye una transición de rol?',o:{a:'Asumir de forma estable el cuidado de una persona dependiente.',b:'Tener un desacuerdo puntual con un compañero.',c:'No encontrar ningún desencadenante interpersonal cercano.',d:'Presentar únicamente pensamientos automáticos negativos.'},c:'a',x:'Convertirse en cuidador implica abandonar un rol previo y asumir otro con nuevas demandas, por lo que se conceptualiza como transición de rol.',r:F});
set('PERSEVER___SIMULACRO_COMENTADO_JULIO-UNO-23_091',{e:'¿Cuál de las siguientes intervenciones digitales para el trastorno bipolar fue diseñada como aplicación móvil?',o:{a:'ORBIT.',b:'SIMPLe.',c:'iCBT.',d:'Beating Bipolar.'},c:'b',x:'SIMPLe es una aplicación para teléfono inteligente. ORBIT, iCBT y Beating Bipolar se describen principalmente como intervenciones web.',r:F});
set('PERSEVER___SIMULACRO_COMENTADO_JULIO-UNO-23_100',{e:'¿Cuál de las siguientes intervenciones se dirige al tratamiento de la depresión posparto mediante trabajo diádico madre-bebé?',o:{a:'ROSE.',b:'Be a Mom.',c:'Mellow Babies.',d:'PREP.'},c:'c',x:'Mellow Babies es una intervención diádica dirigida a madres con depresión y sus bebés. Las demás alternativas se plantean principalmente como prevención.',r:F});

fs.writeFileSync(paths.adult,JSON.stringify(adult));
fs.writeFileSync(paths.child,JSON.stringify(child));
console.log('Criba inicial: 9 reubicadas. Bloque 2: 20 preguntas del estado de ánimo auditadas.');
