const fs=require('fs'),path=require('path'),file=path.join(__dirname,'..','public','banco','clinica_adultos.json'),bank=JSON.parse(fs.readFileSync(file,'utf8'));
const ids=['SM_JUNIO_1_SOL_1_027','SM_JUNIO_2_SOL_1_044','SM_JUNIO_2_SOL_1_051','SM_MAYO_1_SOL_1_090','SmCm09PIR2025_065','SmCm10PIR2025_204','SmCm12PIR2024 2_024','SmCm14PIR2025_068','SmCm16PIR2025_003','SmCm16PIR2025_072','SmCm17PIR2025_101','SmCm19PIR2024_076','SmCm19PIR2024_077','SmCm19PIR2024_078','SmCm20PIR2024_059','SmCm20PIR2025 (1)_074','SmCm22PIR2025 (1)_059','SmCm26PIR2025_103','SmCm29PIR2025_074','SmCm30PIR2025 (1)_201'];
const X={
'SM_JUNIO_1_SOL_1_027':'La c es correcta según la tabla comparativa citada: la cronicidad media se estima alrededor del 25 % en trastornos bipolares. La edad media de inicio depresivo es mayor, «episodios vitales» no se mide en meses y la recaída unipolar supera ampliamente el 10-15 %.',
'SM_JUNIO_2_SOL_1_044':'La d es correcta: bipolar II½ corresponde a depresión sobre temperamento ciclotímico. El III se asocia a hipomanía inducida por tratamiento, el IV a temperamento hipertímico y el V a depresión con hipomanía mixta.',
'SM_JUNIO_2_SOL_1_051':'La d es correcta para adultos: se exigen dos años con numerosos períodos de síntomas hipomaníacos y depresivos subumbrales. Un año se aplica a niños y adolescentes; los episodios completos orientan a otros diagnósticos.',
'SM_MAYO_1_SOL_1_090':'La c es correcta: la dependencia de alcohol u otras sustancias y el mal ajuste premórbido son factores de mal pronóstico. Baja comorbilidad, buen ajuste y episodios breves se asocian a evolución más favorable.',
'SmCm09PIR2025_065':'La b es correcta: bipolar I½ designa hipomanía sin episodios depresivos en el espectro de Akiskal. Es una propuesta histórica, no una categoría DSM-5-TR.',
'SmCm10PIR2025_204':'La b es correcta: Beck aplicó a la manía una tríada cognitiva expansiva, con visiones exageradamente positivas del yo, el mundo y el futuro. No equivale a alegría normal ni explica específicamente esquizofrenia.',
'SmCm12PIR2024 2_024':'La d es correcta: logorrea y fuga de ideas reflejan aceleración y alteración del curso del pensamiento, por lo que se clasifican entre manifestaciones cognitivas de la manía.',
'SmCm14PIR2025_068':'La a es correcta: en adultos la ciclotimia exige dos años de períodos hipomaníacos y depresivos subumbrales. Un episodio maníaco o depresivo mayor completo orientaría a otro diagnóstico.',
'SmCm16PIR2025_003':'La b es correcta: más del 90 % de quienes han tenido un episodio maníaco presenta recurrencias afectivas. Las demás opciones minimizan o atribuyen exclusivamente a causas externas el curso recurrente.',
'SmCm16PIR2025_072':'La b es correcta: en bipolar II, los ciclos rápidos y las características mixtas se describen más en mujeres. El sexo no determina la manía y la hipomanía puede aparecer en el posparto.',
'SmCm17PIR2025_101':'La a es correcta: la labilidad afectiva crónica puede confundirse con trastornos de personalidad, especialmente del clúster B. El diagnóstico diferencial no se limita a una única entidad.',
'SmCm19PIR2024_076':'La c es correcta: bipolar II exige episodio depresivo mayor e hipomanía y excluye manía. No es una forma necesariamente leve ni tiene una edad obligatoria de inicio.',
'SmCm19PIR2024_077':'La b es la respuesta: la pérdida de inhibiciones sociales puede observarse, pero no es una formulación del criterio B DSM-5-TR. Distraibilidad, presión del habla y aumento de actividad sí figuran expresamente.',
'SmCm19PIR2024_078':'La a es correcta: ciclos rápidos significa cuatro o más episodios afectivos en doce meses, separados por cambio de polaridad o remisión parcial o completa de al menos dos meses.',
'SmCm20PIR2024_059':'La d es la respuesta: el embotamiento cognitivo no es un síntoma diagnóstico de manía. Distraibilidad, actividad dirigida a objetivos y grandiosidad sí pertenecen al criterio sintomático.',
'SmCm20PIR2025 (1)_074':'La a es correcta: bipolar II suele comenzar hacia la mitad de la veintena. Puede aparecer antes o después, pero el inicio tardío no es la norma y los episodios depresivos suelen ser clínicamente relevantes.',
'SmCm22PIR2025 (1)_059':'La d es correcta: el DSM-5-TR recoge que aproximadamente el 60 % de las personas con bipolar II presenta tres o más trastornos mentales concurrentes. Las demás cifras o tipos de comorbilidad no coinciden con lo descrito.',
'SmCm26PIR2025_103':'La d es correcta: bipolar II requiere al menos un episodio hipomaníaco y uno depresivo mayor, sin manía previa. La manía determina bipolar I y los síntomas subumbrales crónicos sugieren ciclotimia.',
'SmCm29PIR2025_074':'La c es correcta: la autoestima exagerada y los delirios de grandeza pertenecen al plano cognitivo. Deben distinguirse de la elevación afectiva y de la activación motivacional o conductual.',
'SmCm30PIR2025 (1)_201':'La b es correcta: bipolar I requiere al menos un episodio maníaco y que no se explique mejor por un trastorno psicótico primario. La manía dura habitualmente una semana; la psicosis excluye hipomanía.'};
let n=0;for(const q of bank)if(ids.includes(q.id)){q.x=X[q.id];q.v='VALIDADA_ORIGINAL';n++;}if(n!==20)throw Error(`Expected 20, got ${n}`);fs.writeFileSync(file,JSON.stringify(bank));console.log(`Audited ${n}.`);
