const fs=require('fs'),path=require('path'),file=path.join(__dirname,'..','public','banco','clinica_adultos.json'),b=JSON.parse(fs.readFileSync(file,'utf8'));
const ref='American Psychiatric Association (2022). DSM-5-TR, capítulo «Personality Disorders» y modelo alternativo de la sección III; Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología (4.ª ed.), capítulo de trastornos de la personalidad.';
const rows={
'Simu 16 comentado_104':['c','La c es la incorrecta: la timidez infantil puede preceder al patrón evitativo, pero en la mayoría disminuye gradualmente en vez de agravarse inevitablemente durante la adolescencia.'],
'Simu 31 comentado Hardcore 1_095':['b','La b es correcta: personalidad antisocial exige evidencia de trastorno de conducta antes de los 15 años y una edad mínima actual de 18 años.'],
'Simu 31 comentado Hardcore 1_096':['a','La a es correcta: la falta de deseo o disfrute de relaciones íntimas, incluida la familia, caracteriza la personalidad esquizoide.'],
'Simu 32 comentado hardcore 2_067':['a','La a es correcta: el clúster A agrupa patrones raros o excéntricos —paranoide, esquizoide y esquizotípico—.'],
'Simu 32 comentado hardcore 2_068':['c','La c es la excepción: el TLP puede presentar ideación paranoide transitoria bajo estrés, pero no delirios sistematizados y persistentes sin crítica.'],
'Simu 32 comentado hardcore 2_071':['d','La d es correcta según los estudios citados: el patrón obsesivo-compulsivo aparece genéticamente más diferenciado de los restantes trastornos del clúster C.'],
'Simu 32 comentado hardcore 2_074':['b','La b es correcta: el modelo combina deterioro del funcionamiento de la personalidad —criterio A— y rasgos patológicos —criterio B—.'],
'Simu 32 comentado hardcore 2_081':['d','La d es la incorrecta: el trastorno narcisista se diagnostica con mayor frecuencia en hombres; las demás alternativas describen curso y formulaciones clínicas recogidas en las fuentes.'],
'Simu 32 comentado hardcore 2_082':['a','La a es correcta: el requisito general es un patrón persistente de experiencia interna y conducta que se desvía de las expectativas culturales, es inflexible, estable y causa deterioro o malestar.'],
'Simu 6 comentado__006':['b','La b es correcta entre estas opciones: los diagnósticos del clúster A incluyen exclusiones específicas respecto al curso de esquizofrenia y trastornos con síntomas psicóticos. La opción a sitúa mal el antecedente disocial, que debe ser anterior a los 15 años.'],
'Simu 7 comentado _106':['c','La c es correcta: las ideas de referencia forman parte de los criterios del trastorno esquizotípico de la personalidad.'],
'simu 9 comentado_093':['c','La c es correcta tras corregir la grafía: el modelo biosocial revisado del TLP fue formulado por Crowell y colaboradores a partir del modelo de Linehan.'],
'SM_ABRIL_1_SOL_1_061':['d','La d es correcta: la falta de empatía figura explícitamente entre los criterios del trastorno narcisista de la personalidad.'],
'SM_ABRIL_1_SOL_1_062':['c','La c es correcta: DSM-5-TR describe el trastorno evitativo con frecuencia aproximadamente equivalente en hombres y mujeres.'],
'SM_ABRIL_1_SOL_1_067':['c','La c es correcta: Selby y Joiner proponen que la rumiación sobre afecto negativo exacerba la desregulación y genera cascadas emocionales.'],
'SM_ABRIL_2_SOL_1_052':['a','La a es correcta: en el perfil alternativo narcisista el dominio obligatorio es antagonismo, expresado por grandiosidad y búsqueda de atención.'],
'SM_ABRIL_2_SOL_1_067':['a','La a es correcta como excepción: los estudios citados señalan peor calidad de vida especialmente en personalidad límite, obsesivo-compulsiva y narcisista, no antisocial.'],
'SM_AGOSTO_1_SOL_1_096':['a','La a es correcta según las estimaciones comparadas de la fuente: el trastorno paranoide se encuentra entre los tipos con mayor prevalencia anual de las opciones ofrecidas.']};
const clean=s=>String(s??'').replace(/[�]/g,'').replace(/\b([A-Za-zÁÉÍÓÚáéíóúñÑ]{2,})-\s+([a-záéíóúñ]{2,})\b/g,'$1$2').replace(/\s+/g,' ').trim();
for(const[id,[c,x]]of Object.entries(rows)){const q=b.find(z=>z.id===id);if(!q)throw Error(id);q.c=c;q.e=clean(q.e).replace(/^(?:\d+\s+){1,6}(?=[¿¡A-ZÁÉÍÓÚ])/,'');for(const k of'abcd')q.o[k]=clean(q.o[k]);Object.assign(q,{x,r:ref,v:'VALIDADA_ORIGINAL'})}
const ideas=b.find(q=>q.id==='Simu 7 comentado _106');Object.assign(ideas,{e:'¿Qué trastorno de la personalidad incluye las ideas de referencia entre sus criterios diagnósticos?',o:{a:'Esquizoide.',b:'Evitativo.',c:'Esquizotípico.',d:'Obsesivo-compulsivo.'},c:'c'});
const aps=b.find(q=>q.id==='Simu 31 comentado Hardcore 1_109');Object.assign(aps,{t:['Trastornos del espectro de la esquizofrenia'],e:'Respecto al síndrome de psicosis atenuada (APS), señale la opción correcta:',o:{a:'Su prevalencia estimada en población joven no consultante es aproximadamente del 0,3 %.',b:'El riesgo acumulado de progresión a psicosis alcanza necesariamente el 50 % a los 36 meses.',c:'Figura en la sección principal del DSM-5-TR como diagnóstico oficial.',d:'Quienes lo presentan nunca muestran deterioro clínico suficiente para buscar ayuda.'},c:'a',x:'La a es correcta según el estudio citado. El riesgo de transición es bastante menor del 50 %, APS permanece en la sección de condiciones para estudio y puede asociarse a malestar o deterioro que motive ayuda.',r:'Clark et al. (2024), estudio citado sobre síndrome de psicosis atenuada.',v:'VALIDADA_ORIGINAL'});
const stress=b.find(q=>q.id==='Simu 7 comentado _107');Object.assign(stress,{t:['Psicología de la salud — estrés laboral y burnout'],e:'¿A qué alude el enfoque del estrés psicosocial denominado «estrés de rol»?',o:{a:'Al mantenimiento de la estabilidad fisiológica mediante ajustes acumulativos.',b:'A un proceso metabólico constructivo.',c:'A un proceso metabólico destructivo.',d:'A las dificultades y conflictos derivados de los roles desempeñados en la vida cotidiana.'},c:'d',x:'La d es correcta: el estrés de rol surge de exigencias, conflictos, ambigüedad o sobrecarga vinculados con los papeles sociales de la persona.',r:'Manual de psicología de la salud, capítulo sobre estrés psicosocial.',v:'VALIDADA_ORIGINAL'});
fs.writeFileSync(file,JSON.stringify(b));console.log({audited:20,personality:18,movedToPsychosis:1,movedToStress:1,reconstructed:2});
