const fs=require('fs'),P='public/banco/',topic='Tests de inteligencia y aptitudes';
const bank=JSON.parse(fs.readFileSync(P+'evaluacion_psicologica.json')),m=JSON.parse(fs.readFileSync(P+'manifest.json'));
const all=Object.values(m.subjects).flatMap(s=>JSON.parse(fs.readFileSync(P+s.slug+'.json'))),ok=new Set(['VALIDADA_ORIGINAL','CORREGIDA','VALIDADA']);
const pending=bank.filter(q=>q.t?.includes(topic)&&!ok.has(q.v));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const byText=new Map();for(const q of all){const k=norm(q.e);if(k)(byText.get(k)||byText.set(k,[]).get(k)).push(q.id)}
const rows=pending.map(q=>{const opts=Object.values(q.o||{}),txt=[q.e,...opts,q.x,q.r].join(' '),f=[];
 if(!q.x?.trim())f.push('SIN_JUSTIFICACION');if(!q.r?.trim())f.push('SIN_REFERENCIA');if(!['a','b','c','d'].includes(q.c))f.push('CLAVE_INVALIDA');if(!['a','b','c','d'].every(k=>q.o?.[k]?.trim()))f.push('OPCION_VACIA');
 if(/�|||PSICOLOGÍA|AMIR|\b(?:R[IC]\s*\d|soluci[oó]n|respuesta correcta)\b/i.test(txt))f.push('OCR_BASURA');if(/\b\w{2,}-\s+\w{2,}\b|^(?:\s*\d+){2,}/.test(q.e||''))f.push('OCR_CORTE');
 if(opts.some(v=>/(respuesta|opci[oó]n|alternativa)\s*(?:correcta|incorrecta)|\bR[IC]\s*[1-4]|p[aá]gina\s+\d/i.test(v)))f.push('EXPLICACION_EN_OPCION');
 const dup=(byText.get(norm(q.e))||[]).filter(id=>id!==q.id);if(dup.length)f.push('DUPLICADO_EXACTO');if(q.x?.trim()&&q.x.length<140)f.push('JUSTIFICACION_INSUFICIENTE');if(q.x&&!/(opci[oó]n|alternativa|\ba\b|\bb\b|\bc\b|\bd\b|R[IC][1-4])/i.test(q.x))f.push('SIN_DESCARTE_DISTRACTORES');
 const foreign=[];if(/personalidad|MMPI|NEO-|16PF|temperamento/i.test(q.e||''))foreign.push('Tests de personalidad');if(/demencia|afasia|neuropsicol|memoria epis[oó]dica|funciones ejecutivas/i.test(q.e||''))foreign.push('Evaluación neuropsicológica');if(/ansiedad|depresi[oó]n|adicci[oó]n/i.test(q.e||''))foreign.push('Evaluación clínica específica');if(/fiabilidad|validez|teor[ií]a de respuesta|curva caracter[ií]stica/i.test(q.e||''))foreign.push('Psicometría/Experimental');if(foreign.length)f.push('UBICACION_REVISAR');
 const high=f.some(x=>/CLAVE|VACIA|EXPLICACION|DUPLICADO|UBICACION|OCR_BASURA/.test(x)),med=f.some(x=>/SIN_|OCR_CORTE/.test(x));return{id:q.id,enunciado:q.e,clave:q.c,flags:f,severity:high?'PRIORIDAD_ALTA':med?'PRIORIDAD_MEDIA':'PRIORIDAD_BAJA',destinosSugeridos:foreign,duplicados:dup};});
const ids=k=>rows.filter(x=>x.severity===k).map(x=>x.id),summary={alta:ids('PRIORIDAD_ALTA').length,media:ids('PRIORIDAD_MEDIA').length,baja:ids('PRIORIDAD_BAJA').length,ocr:rows.filter(x=>x.flags.some(f=>f.startsWith('OCR'))).length,sinJustificacion:rows.filter(x=>x.flags.includes('SIN_JUSTIFICACION')).length,sinReferencia:rows.filter(x=>x.flags.includes('SIN_REFERENCIA')).length,explicacionEnOpcion:rows.filter(x=>x.flags.includes('EXPLICACION_EN_OPCION')).length,duplicadosExactos:rows.filter(x=>x.flags.includes('DUPLICADO_EXACTO')).length,ubicacionRevisar:rows.filter(x=>x.flags.includes('UBICACION_REVISAR')).length};
const out='auditorias/evaluacion_aptitudes_criba_20260903.json';fs.mkdirSync('auditorias',{recursive:true});fs.writeFileSync(out,JSON.stringify({createdAt:new Date().toISOString(),subject:'Evaluación Psicológica',topic,totalTema:bank.filter(q=>q.t?.includes(topic)).length,pendingBefore:pending.length,summary,batches:{alta:ids('PRIORIDAD_ALTA'),media:ids('PRIORIDAD_MEDIA'),baja:ids('PRIORIDAD_BAJA')},rows},null,2)+'\n');console.log(JSON.stringify({out,total:rows.length,...summary},null,2));
