const fs=require('fs');
const path=require('path');
const dir='public/banco';
const topic='Trastornos relacionados con estrés y trauma';
const bank=JSON.parse(fs.readFileSync(`${dir}/clinica_adultos.json`,'utf8'));
const manifest=JSON.parse(fs.readFileSync(`${dir}/manifest.json`,'utf8'));
const all=Object.values(manifest.subjects).flatMap(s=>JSON.parse(fs.readFileSync(`${dir}/${s.slug}.json`,'utf8')));
const pending=bank.filter(q=>q.t?.includes(topic)&&(!q.v||q.v==='REVISAR'));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const byText=new Map();
for(const q of all){const k=norm(q.e);if(k)(byText.get(k)||byText.set(k,[]).get(k)).push(q.id)}
const rows=pending.map(q=>{
 const txt=[q.e,...Object.values(q.o||{}),q.x,q.r].join(' ');
 const opts=Object.values(q.o||{});
 const flags=[];
 if(!q.e?.trim())flags.push('ENUNCIADO_VACIO');
 if(!['a','b','c','d'].includes(q.c))flags.push('CLAVE_INVALIDA');
 if(!['a','b','c','d'].every(k=>q.o?.[k]?.trim()))flags.push('OPCION_VACIA');
 if(!q.x?.trim())flags.push('SIN_JUSTIFICACION');
 if(!q.r?.trim())flags.push('SIN_REFERENCIA');
 if(/�|\b(?:rn|sqh|tkbfat|u3t9y|rnal)\w*/i.test(txt))flags.push('OCR_BASURA');
 if(/\b\w{2,}-\s+\w{2,}\b/.test(txt)||/\ba\s+rmaci[oó]n\b|\bespeci\s+car\b|\bprevalen\s+da\b/i.test(txt))flags.push('OCR_CORTE');
 if(opts.some(v=>/(respuesta|alternativa|opci[oó]n)\s*(?:correcta|incorrecta|[1-4])|\bR[IC]\s*[1-4]|DSM-?5.*p[aá]g/i.test(v)))flags.push('EXPLICACION_EN_OPCION');
 if((byText.get(norm(q.e))||[]).length>1)flags.push('DUPLICADO_EXACTO');
 if(q.x?.trim()&&q.x.length<120)flags.push('JUSTIFICACION_INSUFICIENTE');
 if(q.x&& !/(opci[oó]n|alternativa|\ba\b|\bb\b|\bc\b|\bd\b|R[IC][1-4])/i.test(q.x))flags.push('SIN_DESCARTE_DISTRACTORES');
 if(/\b(?:\d+(?:[.,]\d+)?\s*%|prevalencia|incidencia|riesgo|probabilidad)\b/i.test(txt))flags.push('DATO_CUANTITATIVO_REVISAR');
 if(/\b(?:seg[uú]n|modelo|teor[ií]a|escala|cuestionario|inventario)\b/i.test(q.e||''))flags.push('AUTOR_MODELO_REVISAR');
 const foreign=[];
 if(/ansiedad por separaci[oó]n|mutismo selectivo|fobia espec[ií]fica|trastorno de p[aá]nico/i.test(txt))foreign.push('Trastornos de ansiedad');
 if(/despersonalizaci[oó]n|desrealizaci[oó]n|amnesia disociativa|identidad disociativa|trance disociativo/i.test(q.e||''))foreign.push('Trastornos disociativos');
 if(/tratamiento|terapia|exposici[oó]n prolongada|EMDR|intervenci[oó]n/i.test(q.e||''))foreign.push('Tratamientos Adultos');
 if(/niñ[oa]s?|menores de seis|infantojuvenil|adolescen/i.test(q.e||''))foreign.push('Revisar posible Clínica Infantojuvenil');
 if(foreign.length)flags.push('UBICACION_REVISAR:'+foreign.join('|'));
 const severity=flags.some(f=>/CLAVE|VACIA|EXPLICACION_EN_OPCION|DUPLICADO|UBICACION|OCR_BASURA/.test(f))?'PRIORIDAD_ALTA':flags.some(f=>/SIN_REFERENCIA|SIN_JUSTIFICACION|OCR_CORTE|CUANTITATIVO/.test(f))?'PRIORIDAD_MEDIA':'PRIORIDAD_BAJA';
 return {id:q.id,enunciado:q.e,clave:q.c,flags,severity};
});
const group=k=>rows.filter(r=>r.severity===k).map(r=>r.id);
const report={createdAt:new Date().toISOString(),subject:'Clínica Adultos',topic,totalTema:bank.filter(q=>q.t?.includes(topic)).length,pendingBefore:pending.length,summary:{alta:group('PRIORIDAD_ALTA').length,media:group('PRIORIDAD_MEDIA').length,baja:group('PRIORIDAD_BAJA').length,ocr:rows.filter(r=>r.flags.some(f=>f.startsWith('OCR'))).length,explicacionEnOpcion:rows.filter(r=>r.flags.includes('EXPLICACION_EN_OPCION')).length,sinJustificacion:rows.filter(r=>r.flags.includes('SIN_JUSTIFICACION')).length,sinReferencia:rows.filter(r=>r.flags.includes('SIN_REFERENCIA')).length,ubicacionRevisar:rows.filter(r=>r.flags.some(f=>f.startsWith('UBICACION'))).length,duplicadosExactos:rows.filter(r=>r.flags.includes('DUPLICADO_EXACTO')).length},batches:{profundidadPrimero:group('PRIORIDAD_ALTA'),profundidadDespues:group('PRIORIDAD_MEDIA'),revisionRapidaFinal:group('PRIORIDAD_BAJA')},rows};
fs.mkdirSync('auditorias',{recursive:true});
const out='auditorias/clinica_adultos_trauma_criba95_20260902.json';
fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify({out,...report.summary,total:rows.length},null,2));
