const fs=require('fs'),F='public/banco/clinica_adultos.json',a=JSON.parse(fs.readFileSync(F,'utf8'));
const D='American Psychiatric Association (2022). DSM-5-TR. Capítulo «Trastornos disociativos». American Psychiatric Association Publishing.';
const B='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. II (4.ª ed.). McGraw Hill, capítulo «Trastornos disociativos».';
const H='Van der Hart, O., Nijenhuis, E. R. S. y Steele, K. (2006). The Haunted Self. Norton; '+B;
const U={
'PERSEVER___SIMULACRO_COMENTADO_MAYO-DOS-23_032':{e:'¿Qué relación puede existir entre la amnesia disociativa y la fuga disociativa?',o:{a:'Toda amnesia disociativa exige alternancia de identidades.',b:'La fuga es poco frecuente en la amnesia disociativa, pero puede aparecer más a menudo en el trastorno de identidad disociativo.',c:'La fuga impide por definición cualquier recuperación de memoria.',d:'La fuga constituye actualmente un trastorno DSM-5-TR independiente.'},c:'b',x:'La b es correcta: la fuga puede acompañar a la amnesia disociativa y se observa también en el TID. La a añade un requisito propio del TID; la c convierte una posible dificultad de recuperación en imposibilidad absoluta; y la d es falsa porque la fuga figura como especificador de la amnesia disociativa.',r:D},
'SEPTIEMBRE-DOS-24_COMENTADO_075':{e:'¿Qué patrón de pérdida de memoria es característico de la amnesia disociativa?',o:{a:'Amnesia retrógrada, habitualmente localizada o selectiva, para acontecimientos autobiográficos con elevada carga emocional.',b:'Pérdida semántica general causada necesariamente por lesión cerebral.',c:'Amnesia anterógrada progresiva e irreversible en todos los casos.',d:'Deterioro uniforme de toda la memoria de trabajo.'},c:'a',x:'La a es correcta: suele afectar retrospectivamente a recuerdos autobiográficos traumáticos o estresantes y puede ser localizada o selectiva. La b exige una lesión y pérdida semántica que no definen el cuadro; la c describe un patrón orgánico progresivo; y la d no corresponde al dominio autobiográfico característico.',r:D},
'SM_JULIO_2_SOL_1_040':{e:'Cuando la amnesia disociativa se acompaña de fuga, ¿qué afirmación es correcta?',o:{a:'La persona pierde necesariamente todo conocimiento conceptual.',b:'La recuperación de los recuerdos asociados a la fuga puede resultar especialmente difícil.',c:'El riesgo suicida solo existe cuando la recuperación es lenta.',d:'La coexistencia de síntomas de TEPT es excepcional.'},c:'b',x:'La b es correcta: los recuerdos del periodo de fuga pueden ser particularmente resistentes a la recuperación. La a confunde autobiografía con memoria semántica general; la c restringe sin fundamento el riesgo suicida; y la d es falsa porque los síntomas postraumáticos pueden coexistir.',r:D+'; '+B},
'DICIEMBRE-DOS-24_COMENTADO_020':{e:'¿Qué patrón evolutivo caracteriza al trastorno de despersonalización/desrealización?',o:{a:'La edad media de inicio ronda los 16 años y es infrecuente que aparezca por primera vez después de los 40.',b:'Comienza habitualmente después de los 40 años.',c:'Solo puede diagnosticarse durante la infancia.',d:'Siempre se inicia de forma brusca tras consumir una sustancia.'},c:'a',x:'La a es correcta: el inicio medio se sitúa en la adolescencia y un comienzo nuevo después de los 40 años es infrecuente. La b invierte el patrón; la c establece un límite inexistente; y la d convierte un posible precipitante en una condición necesaria.',r:D},
'SmCm2PIR2024_063':{e:'En el modelo jerárquico de Van der Hart y colaboradores, la disociación terciaria implica:',o:{a:'Una sola parte emocional y una parte aparentemente normal.',b:'Separación únicamente entre recuerdo y emoción, sin división de la personalidad.',c:'La fragmentación en varias partes aparentemente normales y varias partes emocionales.',d:'Integración completa del acontecimiento traumático.'},c:'c',x:'La c es correcta: el nivel terciario supone la forma más compleja de división estructural, con varias partes aparentemente normales y emocionales. La a corresponde al nivel primario; la b describe una separación más limitada; y la d es lo contrario de disociación.',r:H},
'PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-UNO-23_179':{e:'En la clasificación funcional de Tyrer, ¿qué fenómenos representan la disociación de conductas complejas?',o:{a:'Fuga disociativa y estados de trance.',b:'Amnesia disociativa.',c:'Despersonalización y desrealización.',d:'Parálisis y anestesia funcionales.'},c:'a',x:'La a es correcta porque fuga y trance implican secuencias conductuales complejas realizadas con alteración de conciencia o memoria. La b afecta a la función cognitiva; la c pertenece a la percepción; y la d a movimientos o sensaciones.',r:B},
'SmCm29PIR2025_072':{e:'¿Qué caracteriza a la modalidad generalizada de la amnesia disociativa?',o:{a:'Olvido de algunos acontecimientos, pero no todos, durante un periodo concreto.',b:'Pérdida completa de la memoria de la propia historia vital, que puede incluir identidad y conocimientos previos y es poco frecuente.',c:'Dificultad para recordar únicamente los minutos posteriores a un trauma.',d:'Incapacidad progresiva para formar recuerdos nuevos por una lesión neurológica.'},c:'b',x:'La b es correcta: la amnesia generalizada comprende la historia vital y puede afectar a identidad y conocimientos bien establecidos; además es rara. La a describe la modalidad selectiva; la c se aproxima a la localizada; y la d describe amnesia anterógrada de posible origen orgánico.',r:D},
'SmCm16PIR2025_064':{e:'Al valorar un posible trastorno de identidad disociativo en un menor, ¿qué precaución diagnóstica exige el DSM-5-TR?',o:{a:'Considerar patológico cualquier amigo imaginario.',b:'Confirmar que la alteración no se explica mejor por compañeros imaginarios u otros juegos de fantasía normales.',c:'Exigir que todas las identidades sean visibles durante la entrevista.',d:'Descartar el diagnóstico siempre que exista imaginación activa.'},c:'b',x:'La b es correcta: en menores la perturbación no debe atribuirse a compañeros imaginarios ni a juegos de fantasía propios del desarrollo. La a patologiza fenómenos normales; la c exige una observación que no es necesaria; y la d excluye indebidamente el diagnóstico por la mera presencia de imaginación.',r:D},
'SmCm16PIR2025_063':{e:'Respecto al curso del trastorno de despersonalización/desrealización, señale la afirmación correcta:',o:{a:'Solo puede seguir un curso episódico.',b:'Solo puede seguir un curso continuo.',c:'Puede presentar un curso episódico o continuo, con intensidad variable.',d:'Siempre remite espontáneamente en menos de un mes.'},c:'c',x:'La c es correcta: el curso puede ser episódico o persistente y la intensidad fluctúa. La a y la b presentan como exclusiva una sola evolución posible; y la d confunde el trastorno con una reacción transitoria y establece una remisión obligatoria inexistente.',r:D}
};
for(const [id,z] of Object.entries(U)){const q=a.find(x=>x.id===id);if(!q)throw Error(id);Object.assign(q,z,{v:'VALIDADA_ORIGINAL'});}
fs.writeFileSync(F,JSON.stringify(a));console.log({diversificadas:Object.keys(U).length});
