const fs=require('fs'),path=require('path'),file=path.join(__dirname,'..','public','banco','clinica_adultos.json');
const b=JSON.parse(fs.readFileSync(file,'utf8'));const get=id=>{const q=b.find(x=>x.id===id);if(!q)throw Error(id);return q};
const opts={
'PERSEVER___SIMULACRO_COMENTADO_JULIO-DOS-23_066':['d','¿Con qué índice de apnea-hipopnea se especifica como grave la apnea obstructiva del sueño?',{a:'Menor de 15 por hora.',b:'De 15 a 30 por hora.',c:'Mayor de 20 por hora.',d:'Mayor de 30 por hora.'}],
'PERSEVER___SIMULACRO_COMENTADO_JULIO-UNO-23_027':['c','Respecto a la narcolepsia, señale la opción correcta:',{a:'Aumentan característicamente las fases N3 del sueño.',b:'Es claramente más prevalente en mujeres.',c:'Una latencia REM nocturna ≤15 minutos puede satisfacer uno de los criterios objetivos, junto con el cuadro clínico requerido.',d:'Sus picos de inicio son exclusivamente 3-8 y 40-60 años.'}],
'PERSEVER___SIMULACRO_COMENTADO_JUNIO-DOS-23_074':['c','¿Cuál NO es un trastorno del despertar del sueño NREM?',{a:'Despertares confusionales.',b:'Sonambulismo.',c:'Síndrome de piernas inquietas.',d:'Terrores nocturnos.'}],
'PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-UNO-23_096':['c','¿Qué especificador de apnea central corresponde al patrón periódico creciente-decreciente del volumen corriente?',{a:'Apnea central idiopática.',b:'Apnea central inducida por opioides.',c:'Respiración de Cheyne-Stokes.',d:'Hipoventilación alveolar central congénita.'}],
'SEPTIEMBRE-DOS-24_COMENTADO_085':['b','Respecto a los marcadores de los trastornos del despertar del sueño NREM, señale la opción correcta:',{a:'La inestabilidad del sueño profundo es un marcador diagnóstico específico del sonambulismo.',b:'Los despertares de los terrores nocturnos se inician bruscamente, sin cambios autonómicos anticipatorios.',c:'Aparecen con mayor frecuencia durante el sueño REM.',d:'Existen marcadores polisomnográficos fiables fuera del episodio.'}],
'SEPTIEMBRE-UNO-24_COMENTADO_183':['d','Respecto al curso del trastorno de insomnio, señale la opción correcta:',{a:'La dificultad de conciliación es siempre el síntoma aislado más frecuente.',b:'Se caracteriza por un EEG de baja frecuencia.',c:'La hiperactividad diurna es más frecuente en personas mayores.',d:'Las estimaciones de cronicidad se sitúan aproximadamente entre el 45 % y el 75 %.'}],
'SM_DICIEMBRE_1_SOL_1_048':['d','¿Qué patrón de hipersomnia presenta el síndrome de Kleine-Levin?',{a:'Agudo.',b:'Subagudo.',c:'Persistente sin remisiones.',d:'Recurrente.'}],
'SM_ENERO_1_SOL_1_071':['b','Respecto al inicio y curso de la hipersomnia idiopática, señale la opción correcta:',{a:'Nunca comienza durante la infancia.',b:'Suele iniciarse en la adolescencia tardía o adultez temprana, generalmente antes de los 30 años.',c:'Es claramente más prevalente en hombres.',d:'Su comienzo es siempre abrupto.'}],
'SM_JULIO_1_SOL_1_021':['d','¿Qué frecuencia y duración mínimas exige DSM-5-TR para el trastorno de hipersomnia?',{a:'Dos veces por semana durante tres meses.',b:'Una vez por semana durante seis meses.',c:'Cuatro veces por semana durante cuatro meses.',d:'Tres veces por semana durante tres meses.'}],
'SM_JULIO_1_SOL_1_025':['c','¿Qué tipo de trastorno del ritmo circadiano presenta períodos de sueño y vigilia variables, sin un período principal de sueño?',{a:'Fases de sueño retrasadas.',b:'Fases de sueño avanzadas.',c:'Sueño-vigilia irregular.',d:'Sueño-vigilia no ajustado a 24 horas.'}],
'SM_MAYO_1_SOL_1_099':['a','Respecto a la narcolepsia, señale la opción correcta:',{a:'Los episodios de sueño son irresistibles y las siestas suelen resultar reparadoras.',b:'Las siestas no son reparadoras.',c:'La narcolepsia tipo 3 es la forma más frecuente en mujeres.',d:'La cataplejía es siempre el primer síntoma.'}],
'SM_MAYO_1_SOL_1_100':['d','¿En qué grupo etario alcanza mayor prevalencia la apnea obstructiva del sueño?',{a:'Niños.',b:'Adolescentes.',c:'Adultos jóvenes.',d:'Personas mayores.'}]};
for(const [id,[c,e,o]] of Object.entries(opts)){const q=get(id);Object.assign(q,{c,e,o,v:'VALIDADA_ORIGINAL'});if(id==='SM_DICIEMBRE_1_SOL_1_048')q.x='La d es correcta. El síndrome de Kleine-Levin cursa con episodios recurrentes de hipersomnia separados por períodos de funcionamiento habitual.'}
fs.writeFileSync(file,JSON.stringify(b));console.log({cleaned:Object.keys(opts).length});
