const fs=require('fs'),path=require('path'),dir=path.join(__dirname,'..','public','banco');
const adultFile=path.join(dir,'clinica_adultos.json'),treatFile=path.join(dir,'tratamientos_adultos.json'),childFile=path.join(dir,'clinica_infantojuvenil.json');
const b=JSON.parse(fs.readFileSync(adultFile,'utf8')),treat=JSON.parse(fs.readFileSync(treatFile,'utf8')),child=JSON.parse(fs.readFileSync(childFile,'utf8')),topic='Trastornos de la conducta alimentaria';
const ids=['PERSEVER___SIMULACRO_COMENTADO_JULIO-DOS-23_079','PERSEVER___SIMULACRO_COMENTADO_JULIO-UNO-23_031','PERSEVER___SIMULACRO_COMENTADO_JULIO-UNO-23_046','PERSEVER___SIMULACRO_COMENTADO_JULIO-UNO-23_202','PERSEVER___SIMULACRO_COMENTADO_JUNIO-DOS-23_036','PERSEVER___SIMULACRO_COMENTADO_JUNIO-DOS-23_037','PERSEVER___SIMULACRO_COMENTADO_JUNIO-DOS-23_055','PERSEVER___SIMULACRO_COMENTADO_JUNIO-UNO-23_072','PERSEVER___SIMULACRO_COMENTADO_MAYO-DOS-23_016','PERSEVER___SIMULACRO_COMENTADO_MAYO-DOS-23_017','PERSEVER___SIMULACRO_COMENTADO_MAYO-DOS-23_018','PERSEVER___SIMULACRO_COMENTADO_MAYO-UNO-23_087','PERSEVER___SIMULACRO_COMENTADO_MAYO-UNO-23_088','PERSEVER___SIMULACRO_COMENTADO_MAYO-UNO-23_090','PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-DOS-23_046','PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-DOS-23_055','PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-DOS-23_061','PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-DOS-23_070','PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-DOS-23_081','PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-UNO-23_137'];
const markers=b.find(q=>q.id==='PERSEVER___SIMULACRO_COMENTADO_JUNIO-UNO-23_072');Object.assign(markers,{e:'¿Qué conjunto de hallazgos puede aparecer asociado a la anorexia nerviosa?',o:{a:'T3 elevada, hipotermia y policitemia.',b:'T3 elevada, hipocarotenemia e hipertensión.',c:'Osteopenia u osteoporosis, emaciación, hipercarotenemia y posible elevación del BUN por deshidratación.',d:'Testosterona elevada en mujeres, estrógenos elevados en hombres y taquicardia habitual.'},c:'c',x:'La c es correcta. La malnutrición puede producir pérdida de densidad ósea, emaciación e hipercarotenemia; la deshidratación puede elevar el nitrógeno ureico. Son más típicas T3 baja, hormonas sexuales bajas, bradicardia e hipotensión.'});
const diabetes=b.find(q=>q.id==='PERSEVER___SIMULACRO_COMENTADO_MAYO-DOS-23_017');Object.assign(diabetes,{c:'c',o:{a:'Las personas con diabetes pueden aumentar la insulina como conducta compensatoria para impedir ganar peso.',b:'Las características disociativas aparecen exclusivamente antes del atracón.',c:'En algunos casos, vomitar se convierte en una finalidad y la persona puede atracarse para vomitar o hacerlo tras una pequeña ingesta.',d:'La prevalencia vital del consumo de sustancias es exactamente del 40 % en todos los casos.'},x:'La c es correcta. En diabetes puede omitirse o reducirse insulina, no aumentarse, para influir en el peso; las experiencias disociativas pueden aparecer durante o después del atracón y la cifra de d no es universal.'});
const nucleus=b.find(q=>q.id==='PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-DOS-23_046');nucleus.e='Según la teoría transdiagnóstica de Fairburn, ¿cuál es la psicopatología nuclear compartida por los trastornos alimentarios?';nucleus.x='La d es correcta: la sobrevaloración del peso, la figura y su control constituye el núcleo psicopatológico común. Aislamiento, afecto negativo y atracones pueden actuar como procesos mantenedores o manifestaciones, pero no definen ese núcleo.';
for(const id of ids){if(id.endsWith('_031')||id.endsWith('_081'))continue;const q=b.find(z=>z.id===id);if(!q||!q.t?.includes(topic)||!q.o?.[q.c]||!q.e||!q.x||!q.r)throw Error('Invalid '+id);q.v='VALIDADA_ORIGINAL'}
function move(id,dest,t,s,e,o,c,x,r){const i=b.findIndex(q=>q.id===id);if(i<0)throw Error(id);const[q]=b.splice(i,1);if(dest.some(z=>z.id===id))throw Error('duplicate '+id);Object.assign(q,{t:[t],s,e,o,c,x,r,v:'VALIDADA_ORIGINAL'});dest.push(q)}
move('PERSEVER___SIMULACRO_COMENTADO_JULIO-UNO-23_031',treat,'Tratamiento de la depresión y trastornos del ánimo','Tratamientos Adultos','Respecto a la amnesia retrógrada asociada a la terapia electroconvulsiva, señale la afirmación incorrecta:',{a:'Es una de las alteraciones de memoria características tras el procedimiento.',b:'Puede afectar a acontecimientos autobiográficos de años anteriores.',c:'Su extensión aumenta con la intensidad y características del tratamiento.',d:'Los recuerdos más recientes se recuperan necesariamente antes que los más antiguos.'},'d','La d es incorrecta: la recuperación suele seguir un gradiente temporal en el que los recuerdos remotos se recuperan antes y los próximos al tratamiento son más vulnerables.','Manual de tratamientos psicológicos y psiquiátricos, apartado de terapia electroconvulsiva y efectos cognitivos.');
move('PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-DOS-23_081',child,'Trastorno por déficit de atención con hiperactividad (TDAH)','Clínica Infantojuvenil','¿En qué trastorno se ha descrito una activación simultánea o insuficientemente segregada de la red neuronal por defecto y la red orientada a tareas?',{a:'Trastorno por déficit de atención con hiperactividad.',b:'Trastorno del espectro autista.',c:'Trastorno de conducta.',d:'Trastorno negativista desafiante.'},'a','La a es correcta: en el TDAH se ha estudiado una interferencia o segregación ineficiente entre la red por defecto y redes de control orientadas a tareas.','Manual de psicopatología infantil, capítulo de TDAH y modelos neurobiológicos.');
fs.writeFileSync(adultFile,JSON.stringify(b));fs.writeFileSync(treatFile,JSON.stringify(treat));fs.writeFileSync(childFile,JSON.stringify(child));console.log({audited:20,remaining:b.filter(q=>q.t?.includes(topic)&&q.v!=='VALIDADA_ORIGINAL').length,moved:2,keyCorrection:'MAYO-DOS-23_017 a→c',reconstructed:2});
