const fs=require('fs'),path=require('path');
const file=path.join(__dirname,'..','public','banco','clinica_adultos.json');
const bank=JSON.parse(fs.readFileSync(file,'utf8')),topic='Trastornos de la conducta alimentaria';
const ids=['SM_AGOSTO_1_SOL_1_068','SM_DICIEMBRE_1_SOL_1_053','SM_DICIEMBRE_1_SOL_1_054','SM_DICIEMBRE_2_SOL_1_071','SM_DICIEMBRE_2_SOL_1_074','SM_DICIEMBRE_2_SOL_1_191','SM_ENERO_1_SOL_1_069','SM_ENERO_1_SOL_1_070','SM_ENERO_1_SOL_1_109','SM_ENERO_1_SOL_1_207','SM_JULIO_1_SOL_1_049','SM_JULIO_1_SOL_1_053','SM_JULIO_1_SOL_1_060','SM_JULIO_2_SOL_1_018','SM_JULIO_2_SOL_1_019','SM_JULIO_2_SOL_1_020','SM_JULIO_2_SOL_1_023','SM_JULIO_2_SOL_1_036','SM_JULIO_2_SOL_1_201','SM_JUNIO_1_SOL_1_045'];
const get=id=>{const q=bank.find(x=>x.id===id);if(!q)throw Error('Missing '+id);return q},set=(id,v)=>Object.assign(get(id),v);
const dsm='American Psychiatric Association (2022). DSM-5-TR, capítulo «Trastornos de la conducta alimentaria y de la ingesta de alimentos». American Psychiatric Association Publishing.';
const bell='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. I (4.ª ed.), cap. 13. McGraw Hill.';
set(ids[0],{e:'Respecto a la etiología y los factores psicológicos asociados a la anorexia nerviosa, señale la afirmación correcta:',o:{a:'Durante la fase aguda se observan necesariamente niveles altos de 5-HIAA.',b:'El riesgo se ha asociado a prematuridad y a menor edad parental.',c:'Tras la recuperación pueden descender la evitación del daño y aumentar la dependencia de la recompensa.',d:'La intolerancia emocional es exclusiva de la anorexia nerviosa.'},x:'La c es la respuesta recogida en el manual. Durante la fase aguda se han descrito niveles bajos de 5-HIAA; la prematuridad se ha relacionado con mayor edad parental, y las dificultades de regulación emocional son transdiagnósticas, aunque la intolerancia emocional se ha destacado especialmente en bulimia.',r:bell});
set(ids[1],{x:'La d es correcta. Rasgos obsesivo-compulsivos como perfeccionismo rígido, hiperresponsabilidad y escrupulosidad pueden preceder al trastorno y persistir tras la recuperación. La regulación emocional también interviene y los hallazgos serotoninérgicos posteriores a la recuperación no se igualan simplemente a los controles.',r:bell});
set(ids[2],{o:{a:'Perfeccionismo clínico.',b:'Baja autoestima nuclear.',c:'Evitación del daño.',d:'Dificultades interpersonales.'},x:'La c es correcta como elemento que no pertenece a los cuatro mecanismos adicionales del modelo transdiagnóstico ampliado: perfeccionismo clínico, baja autoestima nuclear, intolerancia emocional y dificultades interpersonales. La evitación del daño procede del modelo de temperamento y carácter de Cloninger.',r:bell});
set(ids[3],{x:'La d es correcta. El miedo a engordar no suele aliviarse al perder peso; el aumento de actividad puede preceder al trastorno y el inicio puede asociarse a acontecimientos estresantes. La cifra de transición propuesta en c es inferior a la recogida por la fuente.',r:`${dsm}; ${bell}`});
set(ids[4],{e:'Respecto a la bulimia nerviosa, señale la afirmación falsa:',x:'La c es falsa: la gravedad de la bulimia se calcula por la frecuencia de conductas compensatorias inapropiadas, no por el número de atracones. El peso suele ser normal o de sobrepeso, los atracones pueden comenzar durante o después de una dieta y se han investigado antecedentes perinatales asociados.',r:`${dsm}; ${bell}`});
set(ids[5],{o:{a:'Interferencia importante en el funcionamiento psicosocial.',b:'Pérdida de peso significativa.',c:'Dependencia de alimentación enteral o suplementos nutricionales.',d:'Regurgitación repetida de alimentos.'},x:'La d es correcta como opción no relacionada: la regurgitación repetida define el trastorno de rumiación. Las otras tres alternativas pueden satisfacer el criterio de consecuencias del trastorno de evitación/restricción de la ingesta.',r:dsm});
set(ids[6],{x:'La a es correcta: la emaciación es el hallazgo más destacado en la exploración física. La amenorrea no determina por sí sola mayor gravedad; suelen disminuir estrógenos y testosterona, y los rasgos de impulsividad y labilidad son más propios del subtipo con atracones/purgas.',r:`${dsm}; ${bell}`});
set(ids[7],{x:'La b es la incorrecta: la tasa bruta de mortalidad de la bulimia nerviosa se sitúa aproximadamente en el 2 % por década, no en el 5 %. Las demás opciones describen características o conductas compensatorias asociadas.',r:dsm});
set(ids[9],{o:{a:'Al menos una vez a la semana durante tres meses.',b:'Al menos tres veces a la semana durante tres meses.',c:'Al menos una vez a la semana durante un mes.',d:'Al menos tres veces a la semana durante un mes.'},x:'La a es correcta. Tanto los atracones como las conductas compensatorias inapropiadas deben producirse, en promedio, al menos una vez por semana durante tres meses.',r:dsm});
set(ids[10],{x:'La b es correcta. Entre las características asociadas se describen sensación de ineficacia, fuerte necesidad de control, espontaneidad social limitada y contención emocional. En diabetes puede reducirse la insulina, muchas alteraciones nutricionales son reversibles y los síntomas obsesivos no siempre se limitan a la comida.',r:dsm});
set(ids[11],{x:'La d es correcta. La gravedad mínima de la bulimia nerviosa se basa en la frecuencia semanal de conductas compensatorias inapropiadas: 1-3 leve, 4-7 moderada, 8-13 grave y 14 o más extrema.',r:dsm});
set(ids[12],{e:'Respecto a los factores psicológicos asociados a los trastornos de la conducta alimentaria, señale la opción correcta:',x:'La d es correcta: perfeccionismo y necesidad de control se consideran factores transdiagnósticos. La evitación del daño es más elevada en anorexia; en bulimia hay dificultad ante emociones tanto negativas como positivas, y la búsqueda de novedades destaca especialmente en bulimia.',r:bell});
set(ids[13],{o:{a:'Personalidad premórbida desfavorable.',b:'Dificultades sociales.',c:'Duración prolongada y tratamientos previos fallidos.',d:'Máximo peso alcanzado.'},x:'La d es correcta como factor no incluido. La fuente recoge el peso mínimo alcanzado, no el máximo, junto con duración, intentos terapéuticos fallidos, inicio tardío, personalidad premórbida y deterioro interpersonal.',r:bell});
set(ids[14],{o:{a:'En términos generales, es el trastorno alimentario más prevalente.',b:'Está más influido por factores socioculturales que la bulimia nerviosa.',c:'Solo una minoría presenta otro diagnóstico comórbido.',d:'La depresión mayor y la distimia figuran entre sus comorbilidades menos comunes.'},x:'La a es correcta. El trastorno por atracón es, en general, el trastorno alimentario más prevalente. Se considera menos dependiente de factores socioculturales que la bulimia y la comorbilidad es frecuente, especialmente con trastornos depresivos y de ansiedad.',r:bell});
set(ids[15],{o:{a:'La tasa bruta de mortalidad se aproxima al 5 % por década.',b:'La mayoría presenta remisión dentro de los cinco años posteriores al inicio.',c:'Las personas de mayor edad pueden mostrar presentaciones atípicas, como negar el miedo a engordar.',d:'En muestras clínicas, la proporción aproximada entre mujeres y hombres es 10:1.'},x:'La c es falsa: son las personas más jóvenes quienes pueden presentar manifestaciones atípicas como negar el miedo a engordar. Las restantes afirmaciones reproducen datos de curso, mortalidad y distribución clínica recogidos en el DSM-5.',r:dsm});
set(ids[16],{o:{a:'Sobrevaloración de la figura y el peso corporal.',b:'Aparición de atracones.',c:'Afecto negativo.',d:'Preocupación por el efecto de los atracones sobre el peso.'},x:'La a es correcta como opción que no se presenta en esta pregunta como proceso mantenedor: la sobrevaloración de figura y peso constituye la psicopatología nuclear y uno de los puntos de partida del modelo. Atracones, afecto negativo y preocupación posterior por el peso contribuyen al mantenimiento.',r:bell});
set(ids[17],{o:{a:'Trastorno por atracón.',b:'Pica.',c:'Trastorno de evitación/restricción de la ingesta.',d:'Trastorno de rumiación.'},x:'La d es correcta. En lactantes y niños pequeños, el trastorno de rumiación puede acompañarse de arqueamiento de la espalda, cabeza hacia atrás y movimientos de succión con la lengua durante la regurgitación.',r:dsm});
set(ids[19],{o:{a:'Barlow, en su modelo de los trastornos de ansiedad.',b:'Clark y Watson, en el modelo tripartito de ansiedad y depresión.',c:'Ellis, en su teoría de las creencias irracionales.',d:'Fairburn, en el modelo transdiagnóstico de los trastornos alimentarios.'},x:'La d es correcta. Fairburn incorporó perfeccionismo clínico, baja autoestima nuclear, intolerancia emocional y dificultades interpersonales como mecanismos transdiagnósticos adicionales en los trastornos alimentarios.',r:bell});

// Eliminar una copia defectuosa del efecto suelo: ya existe una versión auditada en Tratamiento de los trastornos alimentarios.
const duplicateIndex=bank.findIndex(q=>q.id===ids[8]);if(duplicateIndex<0)throw Error('Missing duplicate');bank.splice(duplicateIndex,1);
// Reubicar la pregunta íntegramente neurocognitiva.
const neuro=get(ids[18]);Object.assign(neuro,{t:['Trastornos neurocognitivos'],e:'Respecto a los trastornos neurocognitivos y al delirium, señale la afirmación falsa:',o:{a:'El trastorno neurocognitivo vascular subcortical puede seguir un curso lentamente progresivo similar al de la enfermedad de Alzheimer.',b:'Un inicio insidioso con progresión gradual de alteraciones conductuales o del lenguaje orienta más a etiología frontotemporal que vascular.',c:'En el trastorno neurocognitivo frontotemporal la supervivencia es mayor y el deterioro más lento que en la enfermedad de Alzheimer típica.',d:'El delirium por abstinencia sustituye al diagnóstico de abstinencia cuando predominan alteraciones graves de atención y cognición que requieren atención clínica.'},c:'c',x:'La c es falsa: en el trastorno neurocognitivo frontotemporal la supervivencia suele ser menor y el deterioro más rápido que en la enfermedad de Alzheimer típica. Las restantes afirmaciones describen curso, diagnóstico diferencial y el uso del especificador de delirium por abstinencia.',r:'American Psychiatric Association (2022). DSM-5-TR, capítulos «Trastornos neurocognitivos» y «Trastornos relacionados con sustancias y trastornos adictivos».',v:'VALIDADA_ORIGINAL'});
for(const id of ids.filter((_,i)=>![8,18].includes(i))){const q=get(id);if(!q.t?.includes(topic)||!q.e||!q.o?.[q.c]||!q.x||!q.r)throw Error('Invalid '+id);q.v='VALIDADA_ORIGINAL'}
fs.writeFileSync(file,JSON.stringify(bank));const qs=bank.filter(q=>q.t?.includes(topic));
console.log({audited:20,movedNeurocognitive:1,removedDuplicate:1,total:qs.length,validated:qs.filter(q=>q.v==='VALIDADA_ORIGINAL').length,pending:qs.filter(q=>q.v!=='VALIDADA_ORIGINAL').length});
