const fs=require('fs'),path=require('path'),dir=path.join(__dirname,'..','public','banco');
const adultFile=path.join(dir,'clinica_adultos.json'),childTreatFile=path.join(dir,'tratamientos_infantiles.json');
const bank=JSON.parse(fs.readFileSync(adultFile,'utf8')),childTreat=JSON.parse(fs.readFileSync(childTreatFile,'utf8')),topic='Trastornos de la conducta alimentaria';
const ids=['Simu 15 comentado_072','Simu 15 comentado_074','Simu 15 comentado_075','Simu 16 comentado_025','Simu 16 comentado_118','Simu 31 comentado Hardcore 1_004','Simu 7 comentado _082','Simu 7 comentado _090','Simu 7 comentado _091','simu 9 comentado_006','simu 9 comentado_077','simu 9 comentado_174','Simulacro06.2018Comentarios_219','SM_ABRIL_1_SOL_1_036','SM_ABRIL_1_SOL_1_037','SM_ABRIL_1_SOL_1_038','SM_ABRIL_2_SOL_1_040','SM_ABRIL_2_SOL_1_041','SM_ABRIL_2_SOL_1_082','SM_AGOSTO_1_SOL_1_067'];
const get=id=>{const q=bank.find(x=>x.id===id);if(!q)throw Error('Missing '+id);return q},set=(id,v)=>Object.assign(get(id),v);
const dsm='American Psychiatric Association (2022). DSM-5-TR. American Psychiatric Association Publishing.';
const bell='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. I (4.ª ed.). McGraw Hill.';
set(ids[0],{e:'Según el modelo multifactorial de Garner y Garfinkel, ¿cuál es un factor perpetuante de la anorexia nerviosa?',x:'La a es la respuesta del modelo: la yatrogenia puede contribuir a perpetuar el trastorno. Los valores socioculturales, la obesidad familiar y la psicopatología afectiva familiar se plantean principalmente como factores predisponentes.',r:`${bell}, capítulo de trastornos alimentarios.`});
set(ids[1],{e:'¿Desde qué edición del DSM tiene el trastorno por atracón categoría diagnóstica propia dentro de los trastornos alimentarios?',x:'La b es correcta. El trastorno por atracón adquirió categoría diagnóstica independiente en el DSM-5; en el DSM-IV-TR figuraba entre los criterios y ejes propuestos para estudios posteriores.',r:`${dsm}, capítulo de trastornos alimentarios.`});
set(ids[2],{e:'¿Qué término se emplea para la reducción deliberada de insulina en una persona con diabetes mellitus tipo 1 con la finalidad de controlar el peso?',o:{a:'Ortorexia nerviosa.',b:'Diabulimia.',c:'Adicción a la comida.',d:'Síndrome de ingesta nocturna.'},x:'La b es correcta. «Diabulimia» es un término clínico no oficial para la omisión o reducción deliberada de insulina con el objetivo de influir en el peso.',r:`${bell}, capítulo de trastornos alimentarios.`});
set(ids[3],{e:'Respecto a la anorexia nerviosa según el DSM-5-TR, señale la opción correcta:',x:'La c es correcta: en niños se ha utilizado un percentil de IMC para la edad inferior al 5 como indicador de peso insuficiente. El inicio antes de la pubertad es menos frecuente, la ayuda suele solicitarla la familia y el cambio entre subtipos no es infrecuente.',r:`${dsm}, capítulo de trastornos alimentarios.`});
set(ids[4],{e:'¿Quién acuñó el término «bulimia nerviosa»?',o:{a:'Richard Morton.',b:'Ernest-Charles Lasègue.',c:'William Gull.',d:'Gerald Russell.'},x:'La d es correcta. Gerald Russell introdujo el término «bulimia nerviosa» en 1979 y describió el cuadro como una variante ominosa de la anorexia nerviosa.',r:'Russell, G. (1979). Bulimia nervosa: an ominous variant of anorexia nervosa. Psychological Medicine, 9(3), 429-448.'});
set(ids[5],{x:'La b es la incorrecta. El trastorno por atracón presenta una proporción de varones mayor que anorexia y bulimia, pero continúa siendo más frecuente en mujeres. La anorexia suele comenzar antes que la bulimia y el riesgo suicida elevado puede justificar ingreso en el nivel asistencial menos restrictivo que garantice seguridad.',r:`${bell}, capítulo de trastornos alimentarios.`});
set(ids[6],{e:'¿En qué consiste la distorsión de la imagen corporal denominada «predecir la desdicha»?',x:'La b es correcta: consiste en anticipar que el propio aspecto físico producirá consecuencias negativas futuras.',r:`${bell}, apartado de psicopatología de la imagen corporal.`});
set(ids[7],{e:'Dentro de «la docena sucia» de Cash y Grant, ¿qué distorsión consiste en minimizar los aspectos físicos propios que sí se valoran positivamente?',x:'La d es correcta: «la ceguera mental» supone ignorar o minimizar los rasgos físicos positivos y atender selectivamente a los negativos.',r:'Cash, T. F. y Grant, J. R. (1996), clasificación de distorsiones cognitivas de la imagen corporal; recogida en manuales de psicopatología de la imagen corporal.'});
set(ids[8],{e:'Según el DSM-5-TR, ¿qué gravedad corresponde a una persona adulta con anorexia nerviosa e IMC de 15,30 kg/m²?',o:{a:'Leve.',b:'Moderada.',c:'Extrema.',d:'Grave.'},x:'La d es correcta. En adultos, un IMC entre 15 y 15,99 kg/m² corresponde a gravedad grave; la categoría extrema exige un IMC inferior a 15.',r:`${dsm}, capítulo de trastornos alimentarios.`});
set(ids[10],{e:'¿Qué hipótesis explica los atracones mediante el efecto de contrarregulación que puede seguir a la transgresión de una dieta restrictiva?',o:{a:'Hipótesis de la activación emocional.',b:'Hipótesis de la restricción.',c:'Hipótesis de la externalidad.',d:'Teoría hipodérmica.'},x:'La b es correcta. La hipótesis de la restricción sostiene que el control dietético rígido favorece una contrarregulación cuando se vulnera la dieta, facilitando la pérdida de control y el atracón.',r:`${bell}, capítulo de trastornos alimentarios.`});
set(ids[12],{e:'Según la clasificación antropométrica utilizada en el manual de referencia, un IMC de 26 kg/m² corresponde a:',o:{a:'Peso normal, sin riesgo añadido.',b:'Sobrepeso de grado I, sin aumento del riesgo en esa tabla.',c:'Obesidad de grado I, con riesgo moderado.',d:'Obesidad de grado II, con riesgo elevado.'},x:'La b es la respuesta conforme a la tabla empleada por la fuente: un IMC de 25-26,9 kg/m² se clasifica como sobrepeso de grado I. La etiqueta de riesgo «nulo» pertenece a esa clasificación histórica y no sustituye la valoración clínica individual actual.',r:`${bell}, apartado de obesidad y clasificación antropométrica.`});
set(ids[13],{x:'La d es correcta. Los trastornos de ansiedad, depresivos y bipolares concurren con frecuencia con anorexia nerviosa. El inicio puede asociarse a estrés vital, el déficit nutricional forma parte del cuadro y la gravedad extrema en adultos corresponde a IMC inferior a 15, no a 14.',r:`${dsm}, capítulo de trastornos alimentarios.`});
set(ids[14],{e:'La distorsión de la imagen corporal denominada «comparación injusta» consiste en:',o:{a:'Comparar el propio aspecto con el ideal estético dominante.',b:'Clasificar el aspecto en extremos sin aceptar puntos intermedios.',c:'Compararse con personas conocidas que poseen atributos físicos deseados.',d:'Pensar que la propia apariencia impide realizar determinadas actividades.'},x:'La c es correcta: la comparación injusta consiste en elegir como referencia a personas que poseen los atributos físicos que se desean y utilizar esa comparación sesgada para evaluarse negativamente.',r:`${bell}, apartado de psicopatología de la imagen corporal.`});
set(ids[15],{x:'La d es correcta. El DSM-5-TR recoge la obesidad infantil y el desarrollo puberal temprano como factores genéticos y fisiológicos que aumentan el riesgo de bulimia nerviosa. El comienzo antes de la pubertad o después de los 40 años es infrecuente.',r:`${dsm}, capítulo de trastornos alimentarios.`});
set(ids[16],{x:'La c es correcta. Algunas personas llegan a considerar el vómito como una finalidad y pueden atracarse para vomitar o provocarlo tras pequeñas cantidades. El umbral diagnóstico es una vez por semana durante tres meses; un atracón ocurre en un período delimitado y la elección de un método compensatorio no implica TOC.',r:`${dsm}, capítulo de trastornos alimentarios.`});
set(ids[17],{o:{a:'Factores estresantes interpersonales.',b:'Aburrimiento.',c:'Estado de ánimo negativo.',d:'Autoevaluación negativa.'},x:'La d es correcta como opción que no constituye un antecedente típico. El estado de ánimo negativo es el antecedente más frecuente; también pueden actuar el estrés interpersonal, la restricción dietética, el malestar por peso o figura y el aburrimiento. La autoevaluación negativa y la disforia se describen como consecuencias posteriores.',r:`${dsm}, capítulo de trastornos alimentarios.`});
set(ids[18],{o:{a:'Las personas jóvenes y algunos adultos suelen reconocer siempre el miedo intenso a engordar.',b:'Aunque muchas alteraciones fisiológicas mejoran con rehabilitación nutricional, la pérdida de densidad mineral ósea puede no ser completamente reversible.',c:'A diferencia de la bulimia nerviosa, no suele existir preocupación por comer en público.',d:'No se han descrito anomalías cerebrales asociadas al trastorno.'},x:'La b es correcta. La densidad mineral ósea puede no recuperarse por completo. Algunas personas niegan el miedo a engordar, la incomodidad al comer en público puede aparecer y se han descrito alteraciones cerebrales asociadas a la malnutrición.',r:`${dsm}, capítulo de trastornos alimentarios.`});
set(ids[19],{e:'Según el DSM-5, ¿qué afirmación sobre la bulimia nerviosa es correcta?',x:'La c es correcta: la prevalencia vital del consumo de sustancias, especialmente alcohol o estimulantes, es de al menos el 30 %. La mortalidad bruta se sitúa cerca del 2 %, puede haber retorno a bulimia tras transición a anorexia y los fenómenos disociativos se describen durante o después del atracón.',r:`${dsm}, capítulo de trastornos alimentarios.`});

function move(id,t,e,o,c,x,r){const i=bank.findIndex(q=>q.id===id);if(i<0)throw Error(id);const[q]=bank.splice(i,1);if(childTreat.some(z=>z.id===id))throw Error('Duplicate '+id);Object.assign(q,{s:'Tratamientos Infantiles',t:[t],e,o,c,x,r,v:'VALIDADA_ORIGINAL'});childTreat.push(q)}
move(ids[9],'Trastorno del Espectro Autista','Respecto a las limitaciones de la investigación sobre tratamientos psicológicos para personas con trastorno del espectro autista (TEA), señale la afirmación incorrecta:',{a:'Todavía es necesario precisar mejor las bases genéticas y etiológicas del TEA.',b:'La heterogeneidad del TEA dificulta adaptar modelos generales a cada perfil individual.',c:'La elevada comorbilidad, descrita hasta aproximadamente en un 70 %, complica la investigación y la intervención.',d:'Hasta un 90 % de las personas con TEA presenta necesariamente otros trastornos comórbidos.'},'d','La d es incorrecta: la cifra recogida por la fuente es aproximadamente del 70 %, no del 90 %. La heterogeneidad clínica, la comorbilidad y el conocimiento todavía incompleto de la etiología dificultan los estudios de intervención.','Fonseca-Pedrero, E. (coord.) (2021). Manual de tratamientos psicológicos: infancia y adolescencia, capítulo sobre TEA.');
move(ids[11],'Trastornos de ansiedad infantojuvenil','Respecto al Protocolo Unificado para el tratamiento transdiagnóstico de trastornos emocionales, señale la opción incorrecta:',{a:'Cuenta con adaptaciones para niños (UP-C) y adolescentes (UP-A).',b:'Trabaja conciencia emocional, flexibilidad cognitiva, reducción de la evitación y exposición a desencadenantes situacionales e interoceptivos.',c:'Se ha empleado tanto con finalidad terapéutica como preventiva.',d:'La adaptación para adolescentes carece de sesiones específicas para padres.'},'d','La d es incorrecta: el UP-A contempla la participación de los padres. Las restantes alternativas describen adaptaciones, objetivos y usos del Protocolo Unificado.','Barlow, D. H. et al. (2018). Unified Protocol for Transdiagnostic Treatment of Emotional Disorders; adaptaciones UP-C y UP-A.');
for(const id of ids.filter((_,i)=>![9,11].includes(i))){const q=get(id);if(!q.t?.includes(topic)||!q.e||!q.o?.[q.c]||!q.x||!q.r)throw Error('Invalid '+id);q.v='VALIDADA_ORIGINAL'}
fs.writeFileSync(adultFile,JSON.stringify(bank));fs.writeFileSync(childTreatFile,JSON.stringify(childTreat));
const qs=bank.filter(q=>q.t?.includes(topic));console.log({audited:20,moved:2,total:qs.length,validated:qs.filter(q=>q.v==='VALIDADA_ORIGINAL').length,pending:qs.filter(q=>q.v!=='VALIDADA_ORIGINAL').length});
