const fs = require('fs');
const path = require('path');
const file = path.join(__dirname, '..', 'public', 'banco', 'clinica_adultos.json');
const bank = JSON.parse(fs.readFileSync(file, 'utf8'));
const topic = 'Trastornos de la conducta alimentaria';
const ids = [
  'PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-UNO-23_146','PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-UNO-23_171','PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-DOS-23_057','PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-DOS-23_058','PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-UNO-23_053','PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-UNO-23_065','PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-DOS-23_025','PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-DOS-23_040','PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-DOS-23_041','PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-DOS-23_053','PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-DOS-23_069','PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-UNO-23_086','PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-UNO-23_089','SEPTIEMBRE-DOS-24_COMENTADO_105','SEPTIEMBRE-DOS-24_COMENTADO_118','SEPTIEMBRE-DOS-24_COMENTADO_119','SEPTIEMBRE-DOS-24_COMENTADO_120','SEPTIEMBRE-DOS-24_COMENTADO_180','SEPTIEMBRE-DOS-24_COMENTADO_207','SEPTIEMBRE-UNO-24_COMENTADO_072'
];
const get = id => { const q = bank.find(x => x.id === id); if (!q) throw new Error(`Missing ${id}`); return q; };
const set = (id, changes) => Object.assign(get(id), changes);
const dsm = 'American Psychiatric Association (2022). DSM-5-TR, capítulo «Trastornos de la conducta alimentaria y de la ingesta de alimentos». American Psychiatric Association Publishing.';
const belloch = 'Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. I (4.ª ed.), cap. 13. McGraw Hill.';

set(ids[0], {e:'Respecto a la transición diagnóstica entre los trastornos de la conducta alimentaria, señale la opción correcta:', x:'La d es correcta: la transición desde el trastorno por atracones hacia otros diagnósticos alimentarios es poco frecuente. Las cifras propuestas en a, b y c no coinciden con las recogidas en el manual de referencia.', r:belloch});
set(ids[1], {e:'Una persona con anorexia nerviosa y diabetes mellitus tipo 1 puede utilizar indebidamente la insulina para influir en su peso. ¿Qué conducta es característica?', x:'La a es correcta: algunas personas omiten o reducen deliberadamente la dosis de insulina para influir en el peso. Aumentarla no produce ese efecto y mantener o seguir correctamente la pauta no constituye esta conducta compensatoria.', r:`${dsm}; ${belloch}`});
set(ids[2], {x:'La b es correcta. El aumento de actividad física puede preceder al inicio y acelerar la pérdida de peso. El intercambio entre subtipos no es infrecuente; en diabetes puede omitirse o reducirse la insulina, y el comienzo puede asociarse a acontecimientos vitales estresantes.', r:dsm});
set(ids[3], {x:'La b es la respuesta prevista en el manual de referencia: en el trastorno por atracón se describen alta evitación del daño y baja autodirección. Se ha relacionado el riesgo con peso elevado, no bajo, al nacer; se considera menos dependiente de factores socioculturales que la bulimia, y el modelo de la espiral de restricción dietética se formuló para esta última.', r:belloch});
set(ids[4], {x:'La a es correcta: a diferencia de la anorexia y la bulimia nerviosas, el trastorno por atracón no se asocia a una persistencia elevada. La desregulación emocional es transdiagnóstica; la búsqueda de novedades destaca sobre todo en bulimia, y el cambio tras la recuperación descrito corresponde a anorexia nerviosa.', r:belloch});
set(ids[5], {o:{a:'Un episodio de atracón requiere solo uno de estos dos elementos: ingesta objetivamente grande o sensación de pérdida de control.',b:'La remisión parcial se define exclusivamente porque los atracones pasan a ser menos de uno por semana.',c:'La autoevaluación está indebidamente influida por la constitución y el peso corporal.',d:'El diagnóstico exige miedo intenso a ganar peso o engordar.'}, x:'La c reproduce el criterio D de bulimia nerviosa. El atracón exige conjuntamente una ingesta objetivamente grande y sensación de falta de control; la remisión parcial no se define mediante el umbral descrito en b, y el miedo intenso de d pertenece a la anorexia nerviosa.', r:dsm});
set(ids[6], {x:'La c es correcta: en bulimia nerviosa, 4-7 episodios semanales de conductas compensatorias corresponden a gravedad moderada. Los subtipos de anorexia se describen según los últimos tres meses; bulimia y trastorno por atracón requieren una frecuencia mínima semanal durante tres meses.', r:dsm});
set(ids[7], {c:'d', o:{a:'Osteoporosis.',b:'Cifosis.',c:'Prolapso de la válvula mitral.',d:'Daño renal.'}, x:'La d es correcta según el manual empleado: el daño renal puede persistir como complicación física a largo plazo de la bulimia nerviosa. Osteoporosis, cifosis y prolapso mitral se enumeran en esa fuente entre las posibles secuelas irreversibles asociadas a anorexia nerviosa.', r:'Caballo, V. E., Salazar, I. C. y Carrobles, J. A. (dirs.) (2014). Manual de psicopatología y trastornos psicológicos, apartado de trastornos alimentarios, p. 622. Pirámide.'});
set(ids[8], {x:'La d es correcta. Los episodios con pérdida de control en los que la cantidad ingerida no es objetivamente grande se denominan atracones subjetivos: no satisfacen el criterio DSM de atracón objetivo, pero poseen relevancia clínica. En bulimia, la autovaloración está influida de forma excesiva por el peso y la figura.', r:`${dsm}; ${belloch}`});
set(ids[9], {x:'La a es la opción recogida en el manual: durante la fase aguda de la anorexia se han descrito concentraciones bajas de 5-HIAA y, tras la recuperación, valores superiores a los de los controles. En bulimia se describen valores basales normales y elevación tras la recuperación.', r:belloch});
set(ids[10], {x:'La c es correcta. El trastorno puede comenzar en la lactancia, infancia, adolescencia o edad adulta. La regurgitación ocurre sin náuseas ni arcadas involuntarias; la postura descrita en b corresponde a niños pequeños, y la rumiación es más frecuente, no menos, en personas con discapacidad intelectual.', r:dsm});
set(ids[11], {x:'La c es correcta: la búsqueda de novedades, vinculada a impulsividad, se ha relacionado con migración diagnóstica y consumo de sustancias. El perfeccionismo y el control no son exclusivos de anorexia; el patrón de b corresponde a pacientes recuperadas de anorexia, y la búsqueda de novedades es menos prominente en trastorno por atracón que en bulimia.', r:belloch});
set(ids[12], {o:{a:'El índice de masa corporal actual tanto en adultos como en niños y adolescentes.',b:'El índice de masa corporal actual en adultos.',c:'La frecuencia de los comportamientos compensatorios inapropiados.',d:'La frecuencia de los episodios de atracón.'}, x:'La b es correcta. En adultos, la gravedad mínima de la anorexia nerviosa se basa en el IMC actual; en niños y adolescentes se utilizan percentiles de IMC. La frecuencia de conductas compensatorias determina la gravedad de la bulimia y la de atracones, la del trastorno por atracón.', r:dsm});
set(ids[13], {x:'La d es correcta. La gravedad mínima de la bulimia nerviosa se basa en la frecuencia semanal de comportamientos compensatorios inapropiados. En anorexia se usa el IMC en adultos o su percentil en menores, y en trastorno por atracón se usa la frecuencia de los atracones.', r:dsm});
set(ids[14], {x:'La b es correcta. El DSM-5-TR incluye la obesidad infantil y el desarrollo puberal temprano entre los factores genéticos y fisiológicos que aumentan el riesgo de bulimia nerviosa.', r:dsm});
set(ids[15], {o:{a:'Comer mucho más rápidamente de lo normal.',b:'Comer hasta sentirse desagradablemente lleno.',c:'Comer grandes cantidades de alimentos cuando se siente hambre físicamente.',d:'Comer a solas por la vergüenza que produce la cantidad ingerida.'}, x:'La c es la incorrecta: el criterio se refiere a comer grandes cantidades cuando no se siente hambre física. Las otras tres conductas figuran entre las características asociadas al atracón; deben estar presentes tres o más.', r:dsm});
set(ids[16], {e:'Según el manual de referencia, ¿qué porcentaje aproximado de pacientes con bulimia nerviosa evoluciona a trastorno por atracón?', x:'La a es la respuesta del manual: aproximadamente un 10 % de los casos de bulimia nerviosa evoluciona a trastorno por atracón. Las demás cifras son distractores.', r:belloch});
set(ids[17], {o:{a:'Se observa regurgitación repetida de alimentos durante un período mínimo de seis meses.',b:'Puede explicarse por una afección gastrointestinal u otra afección médica.',c:'Puede producirse malnutrición pese al hambre aparente y a la ingestión de una cantidad relativamente grande de alimentos.',d:'Solo aparece durante la adolescencia.'}, x:'La c es correcta. La regurgitación debe mantenerse al menos un mes, no puede atribuirse a una enfermedad gastrointestinal u otra afección médica y puede iniciarse en cualquier etapa vital. En casos graves puede causar malnutrición pese a una ingesta aparentemente suficiente.', r:dsm});
set(ids[18], {e:'Entre los siguientes hallazgos físicos, ¿cuál es menos característico de la anorexia nerviosa?', o:{a:'Emaciación.',b:'Amenorrea.',c:'Lanugo.',d:'Hipertensión e hipertermia.'}, x:'La d es correcta: en la anorexia nerviosa son característicos los hallazgos opuestos, hipotensión e hipotermia, además de bradicardia. La emaciación es el hallazgo exploratorio más sobresaliente; también pueden aparecer amenorrea y lanugo.', r:dsm});
set(ids[19], {x:'La a es correcta. El criterio temporal del trastorno de rumiación exige regurgitación repetida de alimentos durante un período mínimo de un mes.', r:dsm});

for (const id of ids) {
  const q = get(id);
  if (!q.t?.includes(topic) || !q.e || !q.o?.[q.c] || !q.x || !q.r) throw new Error(`Invalid ${id}`);
  q.v = 'VALIDADA_ORIGINAL';
}
fs.writeFileSync(file, JSON.stringify(bank));
const questions = bank.filter(q => q.t?.includes(topic));
console.log({audited:ids.length, correctedKey:'SEPTIEMBRE-DOS-23_040 a→d', total:questions.length, validated:questions.filter(q=>q.v==='VALIDADA_ORIGINAL').length, pending:questions.filter(q=>q.v!=='VALIDADA_ORIGINAL').length});
