const fs=require('fs'),path=require('path'),file=path.join(__dirname,'..','public','banco','clinica_adultos.json');
const bank=JSON.parse(fs.readFileSync(file,'utf8')),topic='Disfunciones sexuales';
const ids=['SIM_PERS_AGO25_034','SIM_PERS_AGO25_045','SIM_PERS_AGO25_116','Simu 11 comentado_040','Simu 12 comentado_064','Simu 13 comentado_063','Simu 13 comentado_064','Simu 14 comentado _060','Simu 15 comentado_079','Simu 7 comentado _083','Simu 7 comentado _092','simu 9 comentado_104','SM_ABRIL_2_SOL_1_061','SM_AGOSTO_1_SOL_1_055','SM_DICIEMBRE_1_SOL_1_047','SM_DICIEMBRE_2_SOL_1_045','SM_DICIEMBRE_2_SOL_1_052','SM_DICIEMBRE_2_SOL_1_068','SM_DICIEMBRE_2_SOL_1_079','SM_ENERO_1_SOL_1_089'];
const get=id=>{const q=bank.find(x=>x.id===id);if(!q)throw Error('Missing '+id);return q},set=(id,v)=>Object.assign(get(id),v);
const dsm='American Psychiatric Association (2022). DSM-5-TR, capítulo «Disfunciones sexuales». American Psychiatric Association Publishing.';
const bell='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. I (4.ª ed.), cap. 14. McGraw Hill.';
set(ids[0],{x:'La c es correcta. Salvo las excepciones diagnósticas indicadas, los síntomas principales de las disfunciones sexuales deben persistir aproximadamente seis meses.',r:`${dsm}; ${bell}`});
set(ids[1],{x:'La c es correcta. El DSM-5 fusionó las categorías previas de vaginismo y dispareunia en el trastorno de dolor genito-pélvico/penetración.',r:`${dsm}; ${bell}`});
set(ids[2],{x:'La b es correcta. La eyaculación prematura de por vida se define mediante una latencia aproximada de un minuto después de la penetración vaginal y antes de que la persona lo desee.',r:`${dsm}; ${bell}`});
set(ids[3],{e:'¿Cuál es la disfunción sexual que motiva con mayor frecuencia la consulta clínica entre los hombres según la fuente?',o:{a:'Deseo sexual hipoactivo.',b:'Trastorno eréctil.',c:'Eyaculación prematura.',d:'Eyaculación retardada.'},x:'La b es correcta según los datos de demanda clínica citados por la fuente: el trastorno eréctil es el motivo de consulta sexual masculino más frecuente.',r:'Vallejo Ruiloba, J. Introducción a la psicopatología y la psiquiatría (9.ª ed.), apartado de disfunciones sexuales; '+bell});
set(ids[5],{e:'¿En qué disfunción sexual femenina se ha descrito la preocupación por un posible embarazo como factor de riesgo?',x:'La b es la asociación recogida por la fuente: la preocupación por el embarazo puede contribuir a dificultades orgásmicas femeninas.',r:bell});
set(ids[6],{e:'En una disfunción sexual inducida por sustancias o medicamentos, ¿qué gravedad corresponde si la disfunción aparece aproximadamente en el 90 % de las relaciones sexuales?',o:{a:'Leve.',b:'Moderada.',c:'Grave.',d:'Extrema.'},x:'La c es correcta. En esta categoría, la presencia de la disfunción en el 75-100 % de las ocasiones corresponde a gravedad grave; no existe un nivel denominado extremo.',r:dsm});
set(ids[7],{x:'La c es correcta. Kaplan formuló el modelo trifásico de deseo, excitación y orgasmo, incorporando el deseo a los modelos previos de respuesta sexual.',r:bell});
set(ids[9],{e:'¿Cuál NO es un criterio del trastorno del interés/excitación sexual femenino?',o:{a:'Intensidad reducida de las sensaciones orgásmicas.',b:'Inicio de la actividad sexual y receptividad a las iniciativas de la pareja reducidos o ausentes.',c:'Interés o excitación reducidos ante señales sexuales internas o externas.',d:'Interés por la actividad sexual reducido o ausente.'},x:'La a es correcta como opción ajena al diagnóstico: la intensidad orgásmica reducida pertenece al trastorno orgásmico femenino. Las restantes alternativas forman parte de los síntomas de interés/excitación sexual femenino.',r:dsm});
set(ids[11],{e:'La dispareunia se definía históricamente como un trastorno que podía afectar:',o:{a:'Únicamente a mujeres.',b:'Únicamente a hombres.',c:'Tanto a hombres como a mujeres.',d:'Exclusivamente durante el sueño.'},x:'La c es correcta en la clasificación histórica: la dispareunia podía diagnosticarse en hombres y mujeres. En el DSM-5, vaginismo y dispareunia femenina se integraron en el trastorno de dolor genito-pélvico/penetración, formulado para mujeres.',r:`${dsm}; ${bell}`});
set(ids[13],{e:'¿Cuál NO es un factor psicológico característicamente asociado al trastorno de deseo sexual hipoactivo en el varón?',o:{a:'Educación sexual restrictiva.',b:'Experiencias traumáticas tempranas.',c:'Falta de ejercicio físico.',d:'Sentimientos negativos hacia uno mismo.'},x:'La c es correcta. La falta de ejercicio físico se asocia sobre todo a riesgo vascular y trastorno eréctil; educación restrictiva, trauma temprano y autovaloración negativa pueden contribuir al bajo deseo masculino.',r:bell});
set(ids[14],{e:'Respecto al trastorno orgásmico femenino, señale la afirmación correcta:',o:{a:'La constancia orgásmica suele ser mayor con pareja que durante la masturbación.',b:'Puede existir una satisfacción sexual alta aunque el orgasmo no aparezca en todas las ocasiones.',c:'La menopausia determina por sí sola una mayor probabilidad diagnóstica.',d:'Las dificultades orgásmicas rara vez coexisten con problemas de interés o excitación.'},x:'La b es correcta. La satisfacción sexual global no depende de forma estrecha de experimentar orgasmo en todas las ocasiones. La constancia suele ser mayor en masturbación, la menopausia no determina el diagnóstico y la coexistencia con problemas de interés/excitación es frecuente.',r:`${dsm}; ${bell}`});
set(ids[15],{e:'¿Qué disfunción sexual presenta la menor demanda de ayuda entre los hombres según los datos clínicos citados?',o:{a:'Trastorno eréctil.',b:'Trastorno de deseo sexual hipoactivo.',c:'Eyaculación retardada.',d:'Eyaculación prematura.'},x:'La c es correcta. La eyaculación retardada es uno de los motivos de consulta menos frecuentes entre los hombres y su prevalencia se conoce con menor precisión.',r:`${dsm}; ${bell}`});
set(ids[17],{e:'¿Cuál es una idea central del modelo de Basson sobre la respuesta sexual femenina?',o:{a:'La respuesta procede principalmente de la necesidad de descarga física.',b:'El modelo lineal representa mejor las relaciones consolidadas que el comienzo de la relación.',c:'Las mujeres poseen mayor pulsión biológica de descarga sexual que los hombres.',d:'El deseo puede surgir como respuesta a intimidad, excitación y recompensas, y no ser siempre espontáneo.'},x:'La d es correcta. Basson describe un modelo circular en el que el deseo puede emerger durante la experiencia a partir de intimidad, estimulación y recompensas relacionales, sin requerir un impulso espontáneo inicial.',r:'Basson, R. (2000). The female sexual response: a different model. Journal of Sex & Marital Therapy, 26(1), 51-65; '+bell});
set(ids[18],{e:'Respecto al trastorno orgásmico femenino, señale la afirmación correcta:',o:{a:'La edad del primer orgasmo es menos variable en mujeres que en hombres.',b:'Otros trastornos mentales no sexuales no influyen indirectamente en las experiencias orgásmicas.',c:'La satisfacción sexual global no se correlaciona de manera importante con experimentar orgasmo.',d:'El diagnóstico clínico se basa exclusivamente en cambios fisiológicos objetivos.'},x:'La c es correcta. Muchas mujeres informan satisfacción sexual elevada aunque no alcancen el orgasmo siempre. La edad del primer orgasmo es más variable, otros trastornos pueden influir y el diagnóstico se basa principalmente en lo referido por la mujer.',r:dsm});
for(const id of [ids[4],ids[8],ids[16],ids[19]]){const i=bank.findIndex(q=>q.id===id);if(i<0)throw Error('Missing duplicate '+id);bank.splice(i,1)}
const hyper=get(ids[10]);Object.assign(hyper,{t:['Trastornos disruptivos del control de los impulsos y de la conducta'],e:'En la propuesta histórica de trastorno hipersexual recogida por algunos manuales, ¿qué edad mínima se establecía para aplicar el diagnóstico?',o:{a:'10 años.',b:'16 años.',c:'18 años.',d:'25 años.'},c:'c',x:'La c es la respuesta de la propuesta: se exigía tener al menos 18 años. El trastorno hipersexual no fue incorporado como diagnóstico al DSM-5; la CIE-11 incluye el trastorno por comportamiento sexual compulsivo entre los trastornos del control de los impulsos.',r:'Kafka, M. P. (2010). Hypersexual disorder: a proposed diagnosis for DSM-V. Archives of Sexual Behavior, 39, 377-400; OMS (2022), CIE-11.',v:'VALIDADA_ORIGINAL'});
const compulsive=get(ids[12]);Object.assign(compulsive,{t:['Trastornos disruptivos del control de los impulsos y de la conducta'],e:'¿Qué trastorno está incluido en la CIE-11, pero no como diagnóstico independiente en el DSM-5-TR?',o:{a:'Trastorno explosivo intermitente.',b:'Trastorno negativista desafiante.',c:'Trastorno por comportamiento sexual compulsivo.',d:'Trastorno de conducta.'},c:'c',x:'La c es correcta. La CIE-11 incluye el trastorno por comportamiento sexual compulsivo entre los trastornos del control de los impulsos. El DSM-5-TR no lo reconoce como diagnóstico independiente.',r:'Organización Mundial de la Salud (2022). CIE-11, trastornos del control de los impulsos; American Psychiatric Association (2022). DSM-5-TR.',v:'VALIDADA_ORIGINAL'});
for(const id of ids.filter((_,i)=>![4,8,10,12,16,19].includes(i))){const q=get(id);if(!q.t?.includes(topic)||!q.e||!q.o?.[q.c]||!q.x||!q.r)throw Error('Invalid '+id);q.v='VALIDADA_ORIGINAL'}
fs.writeFileSync(file,JSON.stringify(bank));const qs=bank.filter(q=>q.t?.includes(topic));console.log({audited:20,removedDuplicates:4,movedToImpulseControl:2,total:qs.length,validated:qs.filter(q=>q.v==='VALIDADA_ORIGINAL').length,pending:qs.filter(q=>q.v!=='VALIDADA_ORIGINAL').length});
