const fs=require('fs'),path=require('path'),file=path.join(__dirname,'..','public','banco','clinica_adultos.json');
const bank=JSON.parse(fs.readFileSync(file,'utf8')),topic='Disfunciones sexuales';
const ids=['PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-UNO-23_043','PERSEVER___SIMULACRO_COMENTADO_ENERO-UNO-23_049','PERSEVER___SIMULACRO_COMENTADO_JULIO-DOS-23_029','PERSEVER___SIMULACRO_COMENTADO_JULIO-DOS-23_030','PERSEVER___SIMULACRO_COMENTADO_JULIO-UNO-23_029','PERSEVER___SIMULACRO_COMENTADO_JUNIO-UNO-23_071','PERSEVER___SIMULACRO_COMENTADO_JUNIO-UNO-23_087','PERSEVER___SIMULACRO_COMENTADO_MAYO-DOS-23_012','PERSEVER___SIMULACRO_COMENTADO_MAYO-DOS-23_015','PERSEVER___SIMULACRO_COMENTADO_MAYO-UNO-23_077','PERSEVER___SIMULACRO_COMENTADO_MAYO-UNO-23_078','PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-UNO-23_134','PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-UNO-23_144','PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-DOS-23_043','PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-DOS-23_081','PERSEVER___SIMULACRO_COMENTADO_OCTUBRE-UNO-23_076','PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-DOS-23_034','PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-UNO-23_072','SEPTIEMBRE-DOS-24_COMENTADO_113','SEPTIEMBRE-UNO-24_COMENTADO_133'];
const get=id=>{const q=bank.find(x=>x.id===id);if(!q)throw Error('Missing '+id);return q},set=(id,v)=>Object.assign(get(id),v);
const dsm='American Psychiatric Association (2022). DSM-5-TR, capítulo «Disfunciones sexuales». American Psychiatric Association Publishing.';
const bell='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. I (4.ª ed.), cap. 14. McGraw Hill.';
set(ids[1],{e:'Respecto a la clasificación de las disfunciones sexuales en el DSM-5, señale la opción falsa:',x:'La d es falsa: el DSM-5 mantiene la disfunción sexual inducida por sustancias/medicamentos. Sí elimina la aversión sexual como categoría independiente, diferencia el bajo deseo masculino del interés/excitación femenino y conserva las disfunciones y el dolor sexual bajo este capítulo.',r:`${dsm}; ${bell}`});
set(ids[2],{e:'¿Qué disfunción sexual aumenta significativamente su incidencia a partir de los 50 años?',o:{a:'Eyaculación prematura.',b:'Eyaculación retardada.',c:'Trastorno de dolor genito-pélvico/penetración.',d:'Trastorno orgásmico femenino.'},x:'La b es correcta. La incidencia de eyaculación retardada aumenta de manera significativa a partir de los 50 años; los otros patrones evolutivos no se describen con ese incremento específico.',r:dsm});
set(ids[3],{e:'¿Qué disfunción sexual se ha relacionado con el uso de anticonceptivos orales?',o:{a:'Trastorno eréctil.',b:'Trastorno del interés/excitación sexual femenino.',c:'Trastorno orgásmico femenino.',d:'Trastorno de dolor genito-pélvico/penetración.'},x:'La b es la asociación recogida en la tabla etiológica del manual: el uso de anticonceptivos orales figura entre los factores relacionados con el trastorno del interés/excitación sexual femenino.',r:bell});
set(ids[5],{e:'¿Cuál NO fue un cambio introducido por el DSM-5 respecto al DSM-IV-TR en la clasificación de las disfunciones sexuales?',o:{a:'La aversión sexual dejó de ser una categoría independiente.',b:'El deseo sexual hipoactivo continuó siendo una categoría común para hombres y mujeres.',c:'Dispareunia y vaginismo se integraron en el trastorno de dolor genito-pélvico/penetración.',d:'Desapareció el trastorno sexual debido a otra afección médica como categoría independiente.'},x:'La b es correcta como cambio no realizado: el DSM-5 restringe el trastorno de deseo sexual hipoactivo al varón e integra bajo interés y excitación en la mujer. Las otras tres alternativas sí describen modificaciones del DSM-5.',r:`${dsm}; ${bell}`});
set(ids[6],{e:'El «modelo fantástico de la sexualidad» de Zilbergeld se ha aplicado especialmente a:',x:'La a es correcta. El modelo analiza expectativas rígidas sobre masculinidad, rendimiento, dureza de la erección y funcionamiento automático, y se utiliza para explicar factores psicológicos del trastorno eréctil.',r:'Zilbergeld, B. (1992). The New Male Sexuality; '+bell});
set(ids[7],{e:'¿En qué disfunción sexual masculina establece el DSM-5-TR que la valoración de la reducción o ausencia de deseo debe realizarla el clínico considerando edad y contexto sociocultural?',o:{a:'Eyaculación retardada.',b:'Trastorno eréctil.',c:'Eyaculación prematura.',d:'Trastorno de deseo sexual hipoactivo en el varón.'},x:'La d es correcta. El criterio del trastorno de deseo sexual hipoactivo en el varón exige que el clínico evalúe la deficiencia teniendo en cuenta factores como edad y contexto general y sociocultural.',r:dsm});
set(ids[9],{e:'Respecto a la prevalencia del trastorno eréctil, señale la afirmación correcta:',o:{a:'Se conoce con precisión la prevalencia diferencial de las formas de por vida y adquirida.',b:'El incremento asociado a la edad aparece especialmente antes de los 40 años.',c:'Aproximadamente un 13-21 % de los varones de 40-80 años refiere problemas frecuentes y un 40-50 % de los mayores de 60-70 años puede presentar problemas significativos.',d:'La variabilidad de evaluación no influye en las estimaciones.'},x:'La c es correcta según las cifras recogidas en el DSM. La prevalencia de las formas de por vida y adquirida no se conoce con precisión y el incremento se hace especialmente patente a partir de los 50 años.',r:dsm});
set(ids[11],{e:'Respecto al trastorno orgásmico femenino, señale la afirmación correcta:',o:{a:'Solo un 1 % de las mujeres nunca ha experimentado un orgasmo.',b:'Se considera específicamente causado por la menopausia.',c:'La disminución de frecuencia orgásmica es observable y la intensidad puede valorarse mediante indicadores subjetivos y fisiológicos.',d:'Es la única disfunción que carece del especificador generalizado o situacional.'},x:'La c es la opción prevista. La frecuencia orgásmica puede observarse y la intensidad incluye experiencia subjetiva y correlatos fisiológicos. Alrededor del 10 % nunca ha experimentado orgasmo, no existe una relación diagnóstica específica con menopausia y sí admite el especificador generalizado/situacional.',r:`${dsm}; ${bell}`});
set(ids[12],{e:'Respecto a las disfunciones sexuales masculinas, señale la afirmación correcta:',o:{a:'La eyaculación retardada se define exclusivamente por la evaluación del clínico.',b:'En el deseo sexual hipoactivo basta la valoración subjetiva sin juicio clínico.',c:'En eyaculación prematura, 15-30 segundos corresponde a gravedad grave.',d:'En el trastorno eréctil, la presencia de erecciones espontáneas durante el sueño REM ayuda a valorar una posible etiología orgánica.'},x:'La d es correcta. Las erecciones nocturnas conservadas orientan contra una causa orgánica predominante. La eyaculación retardada depende en buena parte de lo referido por el paciente; el bajo deseo requiere juicio clínico y 15-30 segundos corresponde a gravedad moderada.',r:`${dsm}; ${bell}`});
set(ids[13],{e:'Respecto al trastorno eréctil, señale la afirmación correcta:',o:{a:'El fracaso en la primera relación se asocia a conocer previamente a la pareja y desear el encuentro.',b:'La mayoría de las dificultades iniciales persiste sin intervención.',c:'La forma adquirida se asocia a menudo con factores biológicos como diabetes o enfermedad cardiovascular.',d:'Su incidencia disminuye con la edad.'},x:'La c es correcta. La forma adquirida se relaciona con factores vasculares y metabólicos. Muchas dificultades iniciales remiten espontáneamente y tanto prevalencia como incidencia aumentan con la edad.',r:dsm});
set(ids[14],{e:'Según el modelo de Barlow para la disfunción eréctil, señale la afirmación correcta:',o:{a:'Los distractores neutros reducen la activación sexual de personas sin disfunción, pero pueden no alterarla en personas con disfunción.',b:'Las demandas de rendimiento distraen únicamente a personas sin disfunción.',c:'Las personas con disfunción muestran respuestas afectivas predominantemente positivas en situaciones sexuales.',d:'Las personas con disfunción sobrestiman su control sobre la activación sexual.'},x:'La a es correcta según el modelo. Las personas con disfunción atienden de forma diferente a señales de rendimiento y amenaza, presentan más afecto negativo y suelen infraestimar, no sobrestimar, su control sobre la excitación.',r:'Barlow, D. H. (1986). Causes of sexual dysfunction: the role of anxiety and cognitive interference. Journal of Consulting and Clinical Psychology, 54(2), 140-148; '+bell});
set(ids[15],{e:'Según la CIE-11, ¿qué afirmación es correcta sobre la clasificación de condiciones sexuales?',x:'La c es correcta. La eyaculación retrógrada no figura como disfunción sexual específica en la CIE-11. El comportamiento sexual compulsivo se clasifica entre trastornos del control de los impulsos; el dolor asociado a penetración posee su agrupación propia y la incongruencia de género se ubica entre condiciones relativas a la salud sexual.',r:'Organización Mundial de la Salud (2022). CIE-11, capítulos 06 y 17.'});
set(ids[16],{e:'Respecto al trastorno de deseo sexual hipoactivo en el varón, señale la afirmación correcta:',o:{a:'La valoración de la deficiencia corresponde al clínico, considerando edad y contexto sociocultural.',b:'La persona con menor deseo siempre experimenta abandono y pérdida de autoestima.',c:'La asexualidad afecta necesariamente al 3 % y constituye una disfunción.',d:'Más del 83 % de los hombres está satisfecho con su frecuencia sexual.'},x:'La a es correcta. El clínico debe valorar la reducción o ausencia de fantasías y deseo teniendo en cuenta edad y contexto. La asexualidad no equivale a disfunción y las cifras y atribuciones absolutas de las otras opciones no son correctas.',r:`${dsm}; ${bell}`});
set(ids[17],{e:'Respecto al trastorno de dolor genito-pélvico/penetración, señale la afirmación correcta:',o:{a:'Admite el especificador generalizado o situacional.',b:'Se diagnostica por definición tanto en hombres como en mujeres.',c:'Permite especificar si nunca se ha experimentado un orgasmo.',d:'Puede presentar comorbilidad con síndrome de intestino irritable y otros problemas del suelo pélvico.'},x:'La d es correcta. Puede coexistir con cistitis intersticial, endometriosis, estreñimiento o síndrome de intestino irritable. No usa el especificador generalizado/situacional, está formulado para mujeres y el especificador sobre orgasmo pertenece al trastorno orgásmico femenino.',r:`${dsm}; ${bell}`});
set(ids[18],{x:'La b es incorrecta: «de por vida» significa que la dificultad existe desde las primeras experiencias sexuales. «Adquirido» indica que comenzó después de un período de funcionamiento relativamente normal; generalizado y situacional se definen como recogen a y c.',r:`${dsm}; ${bell}`});
for(const id of [ids[0],ids[4],ids[8],ids[10],ids[19]]){const i=bank.findIndex(q=>q.id===id);if(i<0)throw Error('Missing duplicate '+id);bank.splice(i,1)}
for(const id of ids.filter((_,i)=>![0,4,8,10,19].includes(i))){const q=get(id);if(!q.t?.includes(topic)||!q.e||!q.o?.[q.c]||!q.x||!q.r)throw Error('Invalid '+id);q.v='VALIDADA_ORIGINAL'}
fs.writeFileSync(file,JSON.stringify(bank));const qs=bank.filter(q=>q.t?.includes(topic));console.log({audited:20,removedDuplicates:5,total:qs.length,validated:qs.filter(q=>q.v==='VALIDADA_ORIGINAL').length,pending:qs.filter(q=>q.v!=='VALIDADA_ORIGINAL').length});
