const fs=require('fs'),path=require('path'),file=path.join(__dirname,'..','public','banco','clinica_adultos.json');
const bank=JSON.parse(fs.readFileSync(file,'utf8')),topic='Disfunciones sexuales';
const ids=['1Simulacro02018Comentarios_202','ABRIL-UNO-24_COMENTADO_154','AGOSTO2_052','DICIEMBRE-DOS-24_COMENTADO_022','JULIO1_124','JULIO2_041','JUNIO-UNO-24_COMENTADO_038','JUNIO-UNO-24_COMENTADO_094','JUNIO1_116','MAYO-DOS-24_COMENTADO_131','MAYO2_019','MAYO2_045','OCTUBRE-UNO-24_COMENTADO_036','OCTUBRE-UNO-24_COMENTADO_049','OCTUBRE-UNO-24_COMENTADO_082','PERSEV_JUL25_D2_069','PERSEVER___SIMULACRO_COMENTADO_ABRIL-DOS-23_143','PERSEVER___SIMULACRO_COMENTADO_ABRIL-DOS-23_149','PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-DOS-23_024','PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-DOS-23_042'];
const get=id=>{const q=bank.find(x=>x.id===id);if(!q)throw Error('Missing '+id);return q},set=(id,v)=>Object.assign(get(id),v);
const dsm='American Psychiatric Association (2022). DSM-5-TR, capítulo «Disfunciones sexuales». American Psychiatric Association Publishing.';
const bell='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. I (4.ª ed.), cap. 14. McGraw Hill.';
set(ids[0],{e:'Respecto a las disfunciones sexuales, señale la afirmación correcta:',o:{a:'La prevalencia de dificultades orgásmicas femeninas tiende a disminuir con la edad.',b:'La prevalencia del trastorno eréctil disminuye con la edad.',c:'La eyaculación prematura aumenta claramente su prevalencia con la edad.',d:'La eyaculación retardada exige una duración mínima de tres meses.'},x:'La a es correcta según el patrón evolutivo descrito en la fuente. El trastorno eréctil aumenta con la edad; no se establece el aumento de eyaculación precoz formulado en c y las disfunciones sexuales exigen habitualmente unos seis meses, no tres.',r:`${dsm}; ${bell}`});
set(ids[1],{x:'La c es correcta. Masters y Johnson describieron excitación, meseta, orgasmo y resolución; Kaplan añadió previamente la fase de deseo. El DSM-5 integró el dolor y la penetración en un único trastorno, la conducta sexual compulsiva no es una disfunción sexual en CIE-11 y Barlow formuló su modelo para la disfunción eréctil.',r:bell});
set(ids[2],{o:{a:'Muchas mujeres presentan necesariamente baja satisfacción si rara vez experimentan orgasmos.',b:'Alrededor del 30 % de las mujeres nunca experimenta un orgasmo en su vida.',c:'La constancia del orgasmo es mayor con una pareja que durante la masturbación.',d:'Algunas mujeres con trastorno orgásmico femenino presentan mayores dificultades para comunicarse sobre cuestiones sexuales.'},x:'La d es correcta. Pueden existir dificultades de comunicación sexual. La satisfacción global no se relaciona de forma estrecha con la frecuencia orgásmica; la cifra de anorgasmia de por vida es aproximadamente del 10 % y la constancia orgásmica suele ser mayor durante la masturbación.',r:dsm});
set(ids[3],{x:'La c es correcta. El trastorno de dolor genito-pélvico/penetración no utiliza el especificador generalizado o situacional, que sí se aplica a las restantes disfunciones enumeradas.',r:`${dsm}; ${bell}`});
set(ids[5],{e:'Respecto a la eyaculación prematura, señale la afirmación correcta:',o:{a:'Existe una contribución genética moderada a la presentación de por vida.',b:'Solo se ha asociado con polimorfismos noradrenérgicos.',c:'La cardiopatía coronaria y la diabetes son los principales factores asociados a la forma adquirida.',d:'Los estudios de neuroimagen muestran únicamente activación secundaria del área tegmental ventral.'},x:'La a es correcta. Se describe una contribución genética moderada y asociaciones con genes transportadores de serotonina o dopamina. La forma adquirida se ha relacionado con patología tiroidea, prostatitis y abstinencia de sustancias; la activación mesencefálica descrita no es únicamente secundaria.',r:dsm});
set(ids[6],{x:'La a es correcta. La identificación como asexual, sin malestar clínicamente significativo, no constituye por sí sola un trastorno de deseo sexual hipoactivo ni requiere intervención para modificar la identidad.',r:`${dsm}; ${bell}`});
set(ids[7],{c:'d',e:'En la eyaculación prematura, si la eyaculación aparece aproximadamente entre 15 y 30 segundos después de la penetración vaginal, ¿qué gravedad corresponde?',o:{a:'Extrema.',b:'Leve.',c:'Grave.',d:'Moderada.'},x:'La d es correcta. La gravedad moderada corresponde aproximadamente a 15-30 segundos; leve, a 30-60 segundos, y grave, a antes de la actividad, al inicio o dentro de unos 15 segundos. No existe la categoría extrema.',r:dsm});
set(ids[8],{e:'Según el modelo de Basson sobre la respuesta sexual femenina, señale la afirmación correcta:',o:{a:'El modelo lineal de Masters y Johnson representa mejor las relaciones consolidadas que el inicio de una relación.',b:'La liberación orgásmica debe producirse siempre para completar la respuesta sexual.',c:'La motivación sexual puede surgir de recompensas relacionales y de intimidad, no exclusivamente de una pulsión biológica.',d:'La excitación subjetiva exige necesariamente conciencia de vasocongestión genital.'},c:'c',x:'La c es correcta. Basson propuso un modelo circular en el que intimidad y recompensas no estrictamente sexuales pueden motivar la actividad. El orgasmo puede no ocurrir, la excitación subjetiva no exige conciencia genital y el modelo lineal representa mejor algunas respuestas al inicio de una relación.',r:'Basson, R. (2000). The female sexual response: a different model. Journal of Sex & Marital Therapy, 26(1), 51-65; '+bell});
set(ids[9],{e:'Respecto al trastorno eréctil, señale la afirmación correcta:',o:{a:'Entre sus formulaciones psicológicas se encuentra el denominado modelo fantástico de la sexualidad masculina.',b:'La forma de por vida se asocia principalmente a causas biológicas y responde peor a intervención psicológica que la adquirida.',c:'El escaso control eyaculatorio caracteriza especialmente a varones de mayor edad.',d:'El especificador «con dolor» forma parte del trastorno eréctil.'},x:'La a es la respuesta recogida en el manual: el modelo fantástico vincula masculinidad con tamaño del pene, dureza, rendimiento y resultados. Las demás opciones invierten el patrón evolutivo o atribuyen características y especificadores ajenos al trastorno eréctil.',r:bell});
set(ids[10],{e:'¿En qué disfunción sexual debe indicarse adicionalmente si la mujer nunca ha experimentado un orgasmo en ninguna situación?',o:{a:'Trastorno eréctil.',b:'Trastorno orgásmico femenino.',c:'Trastorno de dolor genito-pélvico/penetración.',d:'Trastorno del interés/excitación sexual femenino.'},x:'La b es correcta. En el trastorno orgásmico femenino se especifica además si nunca se ha experimentado un orgasmo en ninguna situación.',r:dsm});
set(ids[12],{e:'¿Qué disfunción sexual se ha relacionado con polimorfismos del gen transportador de la serotonina o la dopamina?',x:'La b es correcta. Esta asociación genética se ha descrito para la eyaculación prematura; los restantes trastornos presentan otros factores médicos, psicológicos o farmacológicos más característicos.',r:`${dsm}; ${bell}`});
set(ids[13],{e:'Respecto a los factores etiológicos de las disfunciones sexuales, señale la afirmación correcta:',x:'La a es correcta: la comunicación deficiente en la pareja puede mantener la disfunción. El trauma infantil suele considerarse predisponente, las expectativas irreales pueden mantener el problema y la autoobservación o rol de espectador es un mecanismo frecuente, no excepcional.',r:bell});
set(ids[14],{e:'Un varón presenta dolor pélvico urológico durante las relaciones sexuales. Una vez descartadas causas médicas, ¿qué categoría DSM-5-TR puede utilizarse si el patrón causa malestar clínico?',o:{a:'Trastorno de dolor genito-pélvico/penetración.',b:'Eyaculación prematura con dolor.',c:'Otra disfunción sexual especificada o disfunción sexual no especificada.',d:'Trastorno eréctil con dolor.'},x:'La c es correcta. El trastorno de dolor genito-pélvico/penetración está definido para mujeres y los otros diagnósticos no incluyen un especificador «con dolor». En varones puede emplearse otra disfunción sexual especificada o no especificada según la información disponible.',r:`${dsm}; ${bell}`});
set(ids[15],{x:'La d es correcta. El DSM-5 eliminó el trastorno de aversión sexual como categoría independiente; cuando procede, puede registrarse como «otra disfunción sexual especificada» indicando aversión sexual.',r:`${dsm}; ${bell}`});
set(ids[17],{c:'d',e:'¿Qué combinación constituye un mecanismo psicológico central en el mantenimiento del trastorno eréctil?',o:{a:'Polimorfismos serotoninérgicos y autoobservación.',b:'Polimorfismos dopaminérgicos y ansiedad social.',c:'Falta de deseo sexual y ausencia completa de excitación.',d:'Ansiedad de ejecución y autoobservación de la respuesta sexual.'},x:'La d es correcta. La ansiedad de ejecución activa respuestas incompatibles con la erección y la autoobservación desplaza la atención desde los estímulos eróticos hacia el rendimiento, reforzando el problema.',r:bell});
set(ids[18],{e:'¿Cuál es una idea central del modelo de Basson sobre la respuesta sexual femenina?',o:{a:'La respuesta surge principalmente de la necesidad de descarga física y no de intimidad.',b:'La motivación puede proceder de recompensas relacionales no estrictamente sexuales, incluso más relevantes que la pulsión biológica.',c:'La excitación subjetiva siempre exige conciencia de vasocongestión genital.',d:'El orgasmo es obligatorio y ocurre de una única forma.'},x:'La b es correcta. El modelo destaca intimidad, confianza, afecto y otras recompensas relacionales; admite que excitación subjetiva y respuesta genital no siempre coinciden y que el orgasmo puede no aparecer.',r:'Basson, R. (2000). The female sexual response: a different model. Journal of Sex & Marital Therapy, 26(1), 51-65; '+bell});
set(ids[19],{e:'Respecto a la eyaculación prematura de por vida, señale la afirmación correcta:',o:{a:'La valoración diagnóstica no considera edad ni contexto sociocultural.',b:'Un tiempo de latencia eyaculatoria intravaginal de aproximadamente 60 segundos constituye un punto de corte diagnóstico.',c:'La gravedad se especifica exclusivamente por el malestar subjetivo.',d:'Si existe desde la madurez sexual se especifica como adquirida.'},x:'La b es correcta. El DSM-5-TR utiliza aproximadamente un minuto tras la penetración vaginal para la presentación de por vida. La gravedad se gradúa por latencia y la existencia desde la madurez sexual corresponde al subtipo de por vida.',r:dsm});
for(const id of [ids[4],ids[11],ids[16]]){const i=bank.findIndex(q=>q.id===id);if(i<0)throw Error('Missing duplicate '+id);bank.splice(i,1)}
for(const id of ids.filter((_,i)=>![4,11,16].includes(i))){const q=get(id);if(!q.t?.includes(topic)||!q.e||!q.o?.[q.c]||!q.x||!q.r)throw Error('Invalid '+id);q.v='VALIDADA_ORIGINAL'}
fs.writeFileSync(file,JSON.stringify(bank));const qs=bank.filter(q=>q.t?.includes(topic));console.log({audited:20,removedDuplicates:3,keyCorrections:['JUNIO-UNO-24_COMENTADO_094 b→d','PERSEVER..._149 c→d'],total:qs.length,validated:qs.filter(q=>q.v==='VALIDADA_ORIGINAL').length,pending:qs.filter(q=>q.v!=='VALIDADA_ORIGINAL').length});
