const fs=require('fs'),path=require('path'),dir=path.join(__dirname,'..','public','banco');
const adultFile=path.join(dir,'clinica_adultos.json'),basicFile=path.join(dir,'psicologia_basica.json');
const bank=JSON.parse(fs.readFileSync(adultFile,'utf8')),basic=JSON.parse(fs.readFileSync(basicFile,'utf8')),topic='Disfunciones sexuales';
const ids=['SM_JULIO_1_SOL_1_028','SM_JUNIO_1_SOL_1_205','SM_JUNIO_2_SOL_1_035','SM_JUNIO_2_SOL_1_037','SM_MAYO_1_SOL_1_101','SmCm09PIR2025_199','SmCm10PIR2025_055','SmCm11PIR2025_159','SmCm11PIR2025_160','SmCm16PIR2025_066','SmCm18PIR2025_041','SmCm20PIR2024_051','SmCm20PIR2025 (1)_078','SmCm26PIR2025_201','SmCm27PIR2025 (1)_018','SmCm29PIR2025_070','SmCm30PIR2025 (1)_023','SmCm7PIR2024_031','SmCm7PIR2024_208','PERSEVER___SIMULACRO_COMENTADO_JULIO-DOS-23_053'];
const get=id=>{const q=bank.find(x=>x.id===id);if(!q)throw Error('Missing '+id);return q},set=(id,v)=>Object.assign(get(id),v);
const dsm='American Psychiatric Association (2022). DSM-5-TR, capítulo «Disfunciones sexuales». American Psychiatric Association Publishing.';
const bell='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. I (4.ª ed.), cap. 14. McGraw Hill.';
set(ids[0],{e:'¿Cuál de estas afirmaciones NO describe la clasificación de las disfunciones sexuales en el DSM-5?',o:{a:'Las disfunciones no se agrupan formalmente por fases de la respuesta sexual.',b:'La aversión sexual desaparece como categoría independiente.',c:'El deseo sexual hipoactivo queda reservado al varón y en la mujer se integra interés y excitación.',d:'Se mantiene el trastorno sexual debido a enfermedad médica y desaparece la disfunción inducida por sustancias.'},x:'La d es la opción incorrecta: el DSM-5 mantiene la disfunción sexual inducida por sustancias/medicamentos y elimina el trastorno sexual debido a otra afección médica como categoría independiente.',r:`${dsm}; ${bell}`});
set(ids[1],{x:'La c es correcta. El DSM-5 elimina la aversión sexual como categoría independiente y permite registrarla como otra disfunción sexual especificada. No crea un capítulo separado para dolor ni incluye el comportamiento sexual compulsivo; la CIE-11 separa parafilias y condiciones de salud sexual.',r:`${dsm}; Organización Mundial de la Salud (2022). CIE-11.`});
set(ids[2],{e:'Respecto al trastorno eréctil, señale la opción incorrecta:',o:{a:'Es una de las disfunciones sexuales masculinas más atendidas en clínica.',b:'Un 13-21 % de los varones de 40-80 años refiere problemas frecuentes de erección.',c:'La presentación de por vida se relaciona especialmente con factores biológicos como diabetes o enfermedad cardiovascular.',d:'La sumisión se ha descrito como factor de riesgo en varones mayores de 40 años.'},x:'La c es incorrecta: la presentación adquirida se asocia con mayor frecuencia a factores biológicos, mientras que la de por vida se relaciona más con factores psicológicos y puede responder mejor a intervención psicológica.',r:`${dsm}; ${bell}`});
set(ids[4],{e:'¿Qué disfunción sexual femenina no se ha asociado de manera consistente con la menopausia?',o:{a:'Trastorno de dolor genito-pélvico/penetración.',b:'Trastorno del interés sexual femenino.',c:'Trastorno de la excitación sexual femenina.',d:'Trastorno orgásmico femenino.'},x:'La d es correcta. La menopausia no se ha asociado consistentemente con una mayor probabilidad de trastorno orgásmico femenino, aunque la edad y otros factores pueden influir en el funcionamiento sexual.',r:dsm});
set(ids[7],{e:'¿En cuál de estas clasificaciones aparece codificada la eyaculación retrógrada?',o:{a:'DSM-5.',b:'DSM-5-TR.',c:'CIE-10 como disfunción sexual psicógena específica.',d:'CIE-11.'},x:'La d es correcta. La CIE-11 recoge la eyaculación retrógrada con el código MF40.3 dentro de los problemas de los órganos genitales masculinos; no aparece como una disfunción sexual DSM independiente.',r:'Organización Mundial de la Salud (2026). CIE-11 MMS, MF40.3 «Eyaculación retrógrada»; '+dsm});
set(ids[9],{e:'Respecto al trastorno de deseo sexual hipoactivo en el varón, señale la afirmación incorrecta:',o:{a:'La discrepancia de deseo con la pareja no basta por sí sola para diagnosticarlo y la identidad asexual sin malestar no constituye el trastorno.',b:'La frecuencia de bajo deseo aumenta desde varones jóvenes hasta grupos de edad avanzada.',c:'El deseo depende exclusivamente de factores biológicos y no se relaciona con ansiedad, depresión, autovaloración o conexión emocional.',d:'Entre los factores biológicos se incluyen edad, hipogonadismo, hiperprolactinemia y niveles de testosterona.'},x:'La c es incorrecta. Ansiedad, depresión, sentimientos hacia uno mismo, percepción del deseo de la pareja y conexión emocional pueden influir en el deseo. Las demás opciones describen consideraciones diagnósticas, epidemiológicas y fisiológicas.',r:`${dsm}; ${bell}`});
set(ids[10],{e:'Respecto al diagnóstico de eyaculación prematura, señale la opción falsa:',o:{a:'En la presentación de por vida ocurre aproximadamente dentro del minuto siguiente a la penetración vaginal y antes de lo deseado.',b:'Los síntomas deben durar al menos tres meses y aparecer en todas las actividades sexuales.',c:'Es leve cuando la latencia se sitúa aproximadamente entre 30 y 60 segundos.',d:'Es grave cuando ocurre antes, al inicio o dentro de unos 15 segundos tras la penetración.'},x:'La b es falsa. El criterio temporal exige aproximadamente seis meses y que el patrón aparezca en todas o casi todas las ocasiones pertinentes, no una duración de tres meses ni literalmente todas las actividades sexuales.',r:dsm});
set(ids[11],{e:'Según el modelo de Basson, señale la afirmación incorrecta sobre la respuesta sexual femenina:',o:{a:'El modelo lineal puede representar algunas respuestas al inicio de una relación, pero menos una vez consolidada.',b:'La motivación puede proceder de necesidades de intimidad más que de una pulsión física espontánea.',c:'La excitación subjetiva exige ausencia completa de conciencia de cualquier cambio genital o fisiológico.',d:'La excitación puede conducir o no al orgasmo y aun así generar bienestar y satisfacción.'},x:'La c es incorrecta: Basson plantea que la excitación subjetiva puede ir acompañada o no de conciencia de cambios genitales, no que esta deba estar necesariamente ausente. Las restantes opciones describen el carácter circular y contextual del modelo.',r:'Basson, R. (2000). The female sexual response: a different model. Journal of Sex & Marital Therapy, 26(1), 51-65; '+bell});
set(ids[13],{e:'¿Cuál NO es una fase del modelo de respuesta sexual de Masters y Johnson?',o:{a:'Deseo.',b:'Excitación.',c:'Meseta.',d:'Resolución.'},x:'La a es correcta. Masters y Johnson propusieron excitación, meseta, orgasmo y resolución. Kaplan incorporó después el deseo y formuló un modelo trifásico.',r:bell});
set(ids[14],{e:'Respecto a conductas y experiencias de la esfera sexual, señale la afirmación incorrecta:',o:{a:'Violación, incesto y acoso sexual no constituyen diagnósticos mentales independientes en DSM o CIE.',b:'Una parafilia implica un interés sexual intenso y persistente distinto del interés en estimulación genital o caricias preparatorias con parejas fenotípicamente normales, físicamente maduras y que consienten.',c:'En relaciones monógamas heterosexuales se ha descrito que el deseo femenino puede disminuir antes que el masculino conforme avanza la relación.',d:'El deseo sexual de las mujeres permanece necesariamente estable y no se relaciona con la duración o el contexto de la pareja.'},x:'La d es incorrecta. El deseo sexual es contextual y puede variar con la duración y dinámica de la relación. Las otras opciones distinguen comportamientos no diagnósticos, definición de parafilia y hallazgos sobre evolución del deseo en pareja.',r:`${dsm}; ${bell}`});
set(ids[15],{e:'¿Cómo denomina el DSM-5-TR la reducción o ausencia persistente o recurrente de fantasías, pensamientos eróticos y deseo de actividad sexual en un varón?',o:{a:'Trastorno de aversión sexual.',b:'Trastorno de deseo sexual hipoactivo en el varón.',c:'Trastorno eréctil.',d:'Eyaculación retardada.'},x:'La b es correcta. El diagnóstico exige reducción o ausencia persistente o recurrente de fantasías y deseo, valorada por el clínico atendiendo a edad y contexto.',r:dsm});
set(ids[16],{e:'En eyaculación prematura, ¿qué gravedad corresponde a una latencia aproximada de 30-60 segundos tras la penetración vaginal?',o:{a:'Leve.',b:'Moderada.',c:'Grave.',d:'De por vida.'},x:'La a es correcta. La gravedad leve corresponde aproximadamente a 30-60 segundos; moderada, a 15-30, y grave, a antes, al inicio o dentro de unos 15 segundos.',r:dsm});
set(ids[18],{e:'En la evaluación del trastorno del interés/excitación sexual femenino, señale la alternativa incorrecta:',o:{a:'Conviene explorar la preocupación por la repercusión de la sexualidad sobre la relación de pareja.',b:'Cuestionarios como SAI-E, PFSF o WSID pueden aportar información.',c:'La exploración física puede ayudar a detectar atrofia genital u otras condiciones relevantes.',d:'La fotopletismografía vaginal y el dúplex Doppler están plenamente implantados como medidas clínicas rutinarias.'},x:'La d es incorrecta. Estas medidas fisiológicas se utilizan sobre todo en investigación y no están plenamente implantadas para la práctica clínica rutinaria. Entrevista, cuestionarios y exploración médica pueden aportar información relevante.',r:bell});
for(const id of [ids[6],ids[8],ids[12],ids[17]]){const i=bank.findIndex(q=>q.id===id);if(i<0)throw Error('Missing duplicate '+id);bank.splice(i,1)}
const diss=get(ids[3]);Object.assign(diss,{t:['Trastornos disociativos'],e:'¿En qué trastorno disociativo se ha descrito la disfunción sexual entre las posibles características fisiológicas asociadas?',o:{a:'Amnesia disociativa.',b:'Trastorno de identidad disociativo.',c:'Trastorno de despersonalización/desrealización.',d:'Trastorno de estrés postraumático.'},c:'a',x:'La a es la respuesta recogida en el manual de referencia: la disfunción sexual puede aparecer entre las características fisiológicas asociadas a la amnesia disociativa.',r:'Caballo, V. E., Salazar, I. C. y Carrobles, J. A. (dirs.) (2014). Manual de psicopatología y trastornos psicológicos, pp. 482-483. Pirámide.',v:'VALIDADA_ORIGINAL'});
const markerIndex=bank.findIndex(q=>q.id===ids[5]);if(markerIndex<0)throw Error(ids[5]);const[marker]=bank.splice(markerIndex,1);if(basic.some(q=>q.id===marker.id))throw Error('Duplicate marker');Object.assign(marker,{s:'Psicología Básica',t:['Emoción'],e:'Según la hipótesis del marcador somático de Damasio, ¿qué afirmación es correcta?',o:{a:'El procesamiento emocional depende exclusivamente del procesamiento conductual.',b:'El hemisferio izquierdo está especializado en toda representación corporal.',c:'Las lesiones izquierdas producen necesariamente mayor pérdida de regulación corporal.',d:'Las funciones relacionadas con emoción y representación corporal muestran una especialización predominante del hemisferio derecho.'},c:'d',x:'La d es la respuesta prevista: la hipótesis vincula señales corporales y emoción con la toma de decisiones, y describe una especialización relevante del hemisferio derecho para representación corporal y emoción.',r:'Damasio, A. R. (1994). Descartes’ Error. Putnam; manuales de psicología de la emoción.',v:'VALIDADA_ORIGINAL'});basic.push(marker);
const anxiety=get(ids[19]);Object.assign(anxiety,{t:['Trastornos de ansiedad'],e:'Según Ruiz, Caballo y Salazar, ¿qué cognición NO pertenece al factor de temor a la evaluación negativa y la crítica en el trastorno de ansiedad social?',o:{a:'Temor a no caer bien a los demás.',b:'Temor a no saber comportarse con amigos cercanos.',c:'Temor a hablar en público.',d:'Temor a hacer el ridículo.'},c:'b',x:'La b es la opción que no se incluye en ese factor. Temor a no caer bien, hablar en público, decir algo inapropiado o hacer el ridículo sí reflejan preocupación por evaluación negativa.',r:'Ruiz, M. A., Caballo, V. E. y Salazar, I. C. (2008), dimensiones cognitivas del trastorno de ansiedad social.',v:'VALIDADA_ORIGINAL'});
for(const id of ids.filter((_,i)=>![3,5,6,8,12,17,19].includes(i))){const q=get(id);if(!q.t?.includes(topic)||!q.e||!q.o?.[q.c]||!q.x||!q.r)throw Error('Invalid '+id);q.v='VALIDADA_ORIGINAL'}
fs.writeFileSync(adultFile,JSON.stringify(bank));fs.writeFileSync(basicFile,JSON.stringify(basic));const qs=bank.filter(q=>q.t?.includes(topic));console.log({audited:20,removedDuplicates:4,moved:3,total:qs.length,validated:qs.filter(q=>q.v==='VALIDADA_ORIGINAL').length,pending:qs.filter(q=>q.v!=='VALIDADA_ORIGINAL').length});
