const fs=require('fs'),path=require('path');
const file=path.join(__dirname,'..','public','banco','psicopatologia.json');
const bank=JSON.parse(fs.readFileSync(file,'utf8'));
const BEL='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. I (4.ª ed.), capítulo «Psicopatología de la atención». McGraw Hill.';
const COG='Smith, E. E. y Kosslyn, S. M. (2008). Procesos cognitivos: modelos y bases neurales. Pearson, capítulos de atención.';
const SCH='Nuechterlein, K. H. et al. (2015). Identification of separable cognitive factors in schizophrenia. Schizophrenia Research, 161, 15-22; Nuechterlein, K. H. y Dawson, M. E. (1984). Information processing and attentional functioning in schizophrenia. Schizophrenia Bulletin, 10, 160-203.';
const ANX='Bar-Haim, Y. et al. (2007). Threat-related attentional bias in anxious and nonanxious individuals: A meta-analytic study. Psychological Bulletin, 133(1), 1-24; Cisler, J. M. y Koster, E. H. W. (2010). Mechanisms of attentional biases towards threat in anxiety disorders. Clinical Psychology Review, 30, 203-216.';
const AUTO='Schneider, W. y Shiffrin, R. M. (1977). Controlled and automatic human information processing: I. Detection, search, and attention. Psychological Review, 84(1), 1-66.';
const SHAK='Shakow, D. (1962). Segmental set: A theory of the formal psychological deficit in schizophrenia. Archives of General Psychiatry, 6, 1-17.';
const U={};
const set=(id,e,o,c,x,r=BEL)=>U[id]={e,o,c,x,r};

set('PERSEVER___SIMULACRO_COMENTADO_ABRIL-UNO-23_041','Al comparar los perfiles atencionales descritos en depresión, ansiedad y esquizofrenia, señale la afirmación más precisa:',{a:'En la esquizofrenia solo se altera la atención selectiva y la vigilancia permanece intacta.',b:'En la depresión pueden disminuir la concentración y el rendimiento sostenido, especialmente con enlentecimiento y rumiación.',c:'En la ansiedad no aparece sesgo hacia estímulos amenazantes.',d:'La dificultad para desengancharse de la amenaza es exclusiva de la depresión.'},'b','La b es correcta: depresión, enlentecimiento, fatiga y rumiación pueden perjudicar concentración y rendimiento sostenido. La a es falsa porque en esquizofrenia también se alteran vigilancia y preparación atencional. La c niega el sesgo de amenaza característico de la ansiedad. La d atribuye a depresión un mecanismo especialmente estudiado en ansiedad.',`${BEL} ${ANX}`);
set('PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-DOS-23_022','¿Qué combinación resume mejor los déficits atencionales observados en la esquizofrenia?',{a:'Selección de información relevante, vigilancia sostenida y concentración.',b:'Únicamente atención dividida bajo carga elevada.',c:'Hipervigilancia uniforme hacia cualquier estímulo del entorno.',d:'Negligencia hemiespacial contralateral como rasgo nuclear.'},'a','La a es correcta: se han descrito dificultades de filtrado o selección, vigilancia sostenida y concentración. La b reduce el perfil a un solo dominio. La c confunde déficit de procesamiento con hipervigilancia ansiosa generalizada. La d describe típicamente una lesión cerebral focal, no el patrón nuclear de la esquizofrenia.',`${BEL} ${SCH}`);
set('SmCm18PIR2025_004','¿Qué término designa el grado máximo de reducción cuantitativa de la atención, descrito como ausencia completa de disposición atencional?',{a:'Perplejidad.',b:'Aprosexia.',c:'Hipoprosexia.',d:'Pseudoaprosexia.'},'b','La b es correcta: aprosexia designa la abolición o reducción máxima de la atención. La a es una alteración cualitativa de síntesis y comprensión de lo atendido. La c indica disminución, no ausencia completa. La d es apariencia de inatención pese a conservarse la capacidad.',BEL);
set('R0PIR_RESTORE_20260831_006','Dentro de la clasificación funcional de la atención, ¿en qué dimensión se encuadra mejor la «visión en túnel»?',{a:'Atención como vigilancia.',b:'Atención como expectativa.',c:'Atención como activación general.',d:'Atención como selección.'},'d','La d es correcta: la visión en túnel estrecha el foco y selecciona una fracción de la información a costa de los estímulos periféricos. La a se refiere a mantener la detección a lo largo del tiempo. La b describe preparación para un acontecimiento esperado. La c alude al nivel general de alerta, no al contenido seleccionado.',BEL);
set('R0PIR_RESTORE_20260831_009','¿Qué relación entre aprosexia e hipoprosexia es correcta?',{a:'La aprosexia representa ausencia o reducción extrema; la hipoprosexia, una disminución de intensidad variable.',b:'Son sinónimos exactos de pseudoaprosexia.',c:'La hipoprosexia implica siempre mayor activación que la aprosexia.',d:'La aprosexia es una desviación temática del foco y la hipoprosexia una alucinación.'},'a','La a es correcta: ambas son alteraciones cuantitativas, pero la aprosexia ocupa el extremo de ausencia y la hipoprosexia comprende reducciones parciales. La b las confunde con una apariencia conductual de inatención. La c invierte el gradiente cuantitativo. La d atribuye a aprosexia la definición de paraprosexia y convierte erróneamente la hipoprosexia en un fenómeno perceptivo.',BEL);
set('SM_JULIO_1_SOL_1_205','¿Qué define la labilidad atencional emocional?',{a:'Omisión estable de un hemiespacio tras una lesión cerebral.',b:'Descenso progresivo del rendimiento por mantener el esfuerzo durante mucho tiempo.',c:'Oscilación del rendimiento atencional ligada a variaciones intensas de ansiedad o estrés.',d:'Apariencia de inatención pese a conservarse la capacidad para atender.'},'c','La c es correcta: la activación emocional intensa hace inconstante el foco y el rendimiento. La a describe heminegligencia. La b corresponde a fatigabilidad atencional. La d define pseudoaprosexia. Aunque labilidad y distraibilidad pueden solaparse, la primera subraya la dependencia del estado emocional.',BEL);
set('AGOSTO2_032','Una persona rinde adecuadamente cuando está tranquila, pero su atención fluctúa de forma marcada conforme aumenta la ansiedad, sin que medie esfuerzo prolongado. Presenta:',{a:'Labilidad atencional emocional.',b:'Fatigabilidad atencional.',c:'Aprosexia.',d:'Negligencia atencional.'},'a','La a es correcta: la oscilación sigue los cambios de ansiedad. La b exigiría deterioro por mantenimiento prolongado del esfuerzo. La c supone ausencia o reducción máxima, no variación dependiente del estado. La d implica omisión espacial, generalmente asociada a lesión neurológica.',BEL);
set('DICIEMBRE-UNO-24_COMENTADO_128','¿Qué alteración hipoproséxica consiste en dificultad para iniciar o movilizar voluntariamente el foco, aunque estímulos suficientemente intensos pueden captarlo?',{a:'Inhibición atencional.',b:'Distraibilidad.',c:'Fatigabilidad.',d:'Paraprosexia.'},'a','La a es correcta: la inhibición atencional dificulta poner en marcha o desplazar el foco. La b es inestabilidad y captura sucesiva por estímulos irrelevantes. La c es agotamiento tras atención mantenida. La d es dirección anómala o desproporcionada hacia determinados contenidos.',BEL);
set('JULIO2_028','Un paciente tarda mucho en comenzar una tarea y apenas logra dirigir la atención salvo ante estímulos muy intensos; una vez activado, no muestra ausencia total de capacidad. ¿Qué término es más preciso?',{a:'Aprosexia.',b:'Pseudoaprosexia.',c:'Labilidad atencional emocional.',d:'Inhibición atencional.'},'d','La d es correcta: describe dificultad de movilización con cierta capacidad residual. La a exigiría abolición o reducción máxima de la disposición atencional. La b sería solo apariencia de inatención con capacidad conservada. La c produciría oscilaciones ligadas al estrés, no un problema estable de inicio.',BEL);
set('JUNIO-UNO-24_COMENTADO_208','En la esquizofrenia, el rendimiento bajo en una tarea de ejecución continua (CPT) informa principalmente de una alteración de:',{a:'Orientación autobiográfica.',b:'Atención dividida exclusivamente.',c:'Vigilancia o atención sostenida.',d:'Reconocimiento perceptivo elemental.'},'c','La c es correcta: el CPT exige detectar señales infrecuentes durante un periodo y es una medida clásica de vigilancia. La a evalúa orientación personal, no detección sostenida. La b no es su demanda nuclear. La d confunde un déficit de vigilancia con incapacidad sensorial elemental.',`${BEL} ${SCH}`);
set('JUNIO1_067','Una persona registra elementos aislados de la situación, pero no consigue integrarlos ni captar qué está ocurriendo. Esta alteración se denomina:',{a:'Apatía atencional.',b:'Pseudoaprosexia.',c:'Perplejidad atencional.',d:'Distraibilidad.'},'c','La c es correcta: en la perplejidad se atienden fragmentos sin sintetizar su significado global. La a deriva de desinterés y falta de movilización. La b es una apariencia conductual de no atender. La d es inestabilidad y cambio fácil del foco, no incapacidad de integración.',BEL);
set('JUNIO1_072','Según Schneider y Shiffrin, ¿qué propiedad distingue mejor un proceso automático de uno controlado?',{a:'Necesita supervisión consciente continua y consume mucha capacidad.',b:'Se activa mediante asociaciones consolidadas, consume pocos recursos y es relativamente rígido.',c:'Solo puede ejecutarse de forma serial y nunca junto con otra tarea.',d:'Se adquiere en un único ensayo y se modifica voluntariamente con facilidad.'},'b','La b es correcta: la automaticidad surge de asociaciones consolidadas o predispuestas, requiere pocos recursos y pierde flexibilidad. La a define mejor procesamiento controlado. La c es falsa porque los procesos automáticos pueden operar en paralelo. La d combina adquisición instantánea y gran flexibilidad, rasgos que no definen automaticidad.',`${AUTO} ${COG}`);
set('MAYO-DOS-24_COMENTADO_121','¿Qué afirmación describe correctamente el carácter de los déficits atencionales en la esquizofrenia?',{a:'Solo aparecen durante episodios psicóticos floridos.',b:'Desaparecen por definición cuando remiten delirios y alucinaciones.',c:'Son siempre consecuencia directa de la medicación.',d:'Algunos déficits de selección y vigilancia pueden persistir durante la remisión clínica.'},'d','La d es correcta: ciertas dificultades atencionales persisten fuera de la fase aguda y pueden funcionar como rasgos de vulnerabilidad. La a es falsa porque no se limitan a episodios floridos. La b es falsa porque la remisión de delirios y alucinaciones no asegura normalización cognitiva. La c atribuye todos los hallazgos a medicación, pese a observarse también antes del tratamiento y en personas de riesgo.',`${BEL} ${SCH}`);
set('MAYO-UNO-24_COMENTADO_016','Una persona comprende las instrucciones y mantiene capacidad general, pero le cuesta iniciar deliberadamente la concentración. ¿Qué alteración describe mejor el caso?',{a:'Inhibición atencional.',b:'Fatigabilidad atencional.',c:'Apatía atencional.',d:'Pseudoaprosexia.'},'a','La a es correcta: el problema principal es movilizar voluntariamente la atención. La b aparecería como descenso después de sostener el esfuerzo. La c exigiría que la falta de movilización derivara de desinterés. La d implica apariencia de inatención, no necesariamente dificultad subjetiva real de iniciación.',BEL);
set('NOVIEMBRE-DOS-24_COMENTADO_047','¿Qué rasgo permite diferenciar mejor la apatía atencional de la inhibición atencional?',{a:'En la apatía, estímulos habitualmente relevantes no movilizan el foco por falta de interés o motivación.',b:'La apatía aparece únicamente tras mantener atención durante horas.',c:'La apatía consiste en omitir el hemiespacio contralateral.',d:'La apatía supone una dirección excesiva hacia preocupaciones corporales.'},'a','La a es correcta: la apatía atencional se vincula al desinterés, mientras la inhibición destaca la dificultad de puesta en marcha. La b define fatigabilidad. La c describe heminegligencia. La d corresponde mejor a paraprosexia cuando el foco se desvía de forma desproporcionada.',BEL);
set('OCTUBRE-UNO-24_COMENTADO_080','¿Qué diferencia la atención focalizada de la atención selectiva?',{a:'La focalizada permite responder a un estímulo concreto; la selectiva añade inhibir competidores relevantes.',b:'La focalizada mantiene la respuesta durante horas y la selectiva alterna entre tareas.',c:'La focalizada distribuye recursos entre varias tareas y la selectiva mide alerta general.',d:'No existe diferencia conceptual entre ambas.'},'a','La a es correcta: focalizar es responder a un estímulo, mientras seleccionar requiere priorizarlo frente a distractores. La b confunde atención sostenida y alternante. La c describe atención dividida y activación. La d borra una distinción funcional útil en evaluación neuropsicológica.',COG);
set('PERSEVER___SIMULACRO_COMENTADO_JUNIO-DOS-23_049','Según la teoría de la disposición fragmentada de Shakow, una dificultad característica de la esquizofrenia consiste en:',{a:'Mantener una disposición preparatoria global y usar con eficacia señales anticipatorias.',b:'Beneficiarse más que los controles de intervalos preparatorios regulares.',c:'Responder desde disposiciones segmentarias y no aprovechar adecuadamente el contexto preparatorio.',d:'Presentar obligatoriamente negligencia del hemiespacio izquierdo.'},'c','La c es correcta: Shakow propuso una disposición segmentaria que dificulta mantener el set y aprovechar señales preparatorias. La a describe la capacidad que estaría alterada. La b invierte el patrón esperado. La d pertenece a lesiones hemisféricas focales y no a esta teoría de esquizofrenia.',`${BEL} ${SHAK}`);
set('PERSEVER___SIMULACRO_COMENTADO_JUNIO-UNO-23_063','¿Qué conjunto corresponde al síndrome de negligencia atencional y no a una simple distraibilidad?',{a:'Falta de interés global sin asimetría espacial.',b:'Cansancio y errores crecientes tras esfuerzo prolongado.',c:'Oscilaciones ligadas a ansiedad.',d:'Omisión de un lado del espacio, a menudo acompañada de acinesia o extinción.'},'d','La d es correcta: la negligencia es un síndrome espacial, habitualmente contralateral a una lesión, que puede acompañarse de extinción y alteraciones motoras. La a describe apatía. La b es fatigabilidad. La c corresponde a labilidad atencional emocional.',BEL);
set('PERSEVER___SIMULACRO_COMENTADO_MAYO-UNO-23_067','¿Qué dato apoya diagnosticar fatigabilidad atencional?',{a:'El rendimiento empieza adecuado y empeora progresivamente, con más errores, al prolongarse la tarea.',b:'La persona ignora siempre el lado izquierdo desde el primer ensayo.',c:'El foco cambia bruscamente solo cuando aumenta la ansiedad.',d:'Existe apariencia de inatención, pero responde correctamente cuando le conviene.'},'a','La a es correcta: la fatigabilidad se manifiesta por agotamiento y descenso progresivo tras mantener el esfuerzo. La b describe heminegligencia. La c se ajusta a labilidad emocional. La d sugiere pseudoaprosexia porque la capacidad permanece disponible.',BEL);
set('PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-DOS-23_051','En algunos modelos temporales del sesgo atencional en ansiedad social, ¿qué secuencia puede observarse?',{a:'Orientación inicial hacia amenaza social seguida de evitación o retirada atencional.',b:'Ausencia completa de orientación hacia señales sociales negativas.',c:'Vigilancia estable e idéntica durante toda la exposición en todas las personas.',d:'Atención exclusiva a señales de seguridad desde el primer milisegundo.'},'a','La a es correcta: algunos hallazgos son compatibles con vigilancia inicial y evitación posterior, aunque el patrón varía por tarea y momento. La b niega la captación temprana observada. La c convierte un patrón heterogéneo en universal y estable. La d excluye sin fundamento el procesamiento temprano de amenaza.',ANX);
set('SEPTIEMBRE-UNO-24_COMENTADO_135','Una paciente parece no atender al entrevistador, pero demuestra después que registró la conversación y usa la capacidad atencional cuando cambia la situación. ¿Qué término describe mejor la apariencia inicial?',{a:'Perplejidad.',b:'Pseudoaprosexia.',c:'Paraprosexia.',d:'Aprosexia.'},'b','La b es correcta: existe apariencia de ausencia con capacidad preservada y demostrable. La a implicaría incapacidad para sintetizar el significado. La c sería dirección anómala o excesiva del foco. La d supondría abolición o reducción máxima real, incompatible con el registro posterior.',BEL);
set('SIM_ABR2_007','En la aproximación experimental a la esquizofrenia, ¿qué dos procesos han recibido especial atención?',{a:'Filtrado selectivo de estímulos y mantenimiento de la vigilancia.',b:'Reconocimiento facial y memoria autobiográfica exclusivamente.',c:'Hipervigilancia general sin fallos de detección.',d:'Negligencia hemiespacial y simultagnosia.'},'a','La a es correcta: la selección de información relevante y la vigilancia sostenida son focos clásicos de estudio. La b omite los procesos atencionales nucleares y añade una exclusividad falsa. La c niega los fallos de vigilancia. La d reúne síndromes visuoespaciales ligados a lesión neurológica.',`${BEL} ${SCH}`);
set('SIM_ABR25_017','¿Qué patrón describe mejor el sesgo atencional asociado a los trastornos de ansiedad?',{a:'Priorización de señales amenazantes y posibles dificultades para desengancharse de ellas.',b:'Procesamiento siempre más lento de cualquier estímulo emocional, sea positivo o negativo.',c:'Pérdida completa de la atención voluntaria.',d:'Omisión contralateral estable de un hemiespacio.'},'a','La a es correcta: la ansiedad favorece orientación, mantenimiento o dificultad de desenganche respecto a amenaza, según fase y tarea. La b generaliza el efecto a toda emoción. La c define aprosexia, no ansiedad. La d describe heminegligencia neurológica.',ANX);
set('SIM_ABR25_031','En una tarea de sonda atencional, una respuesta más rápida cuando la sonda sustituye a una palabra amenazante sugiere:',{a:'Asignación preferente de atención a la localización de la amenaza.',b:'Amnesia retrógrada para estímulos neutros.',c:'Negligencia del campo visual contralateral.',d:'Ausencia de procesamiento preatencional.'},'a','La a es correcta: la ventaja de respuesta indica que el foco estaba preferentemente en la localización amenazante. La b es un trastorno de memoria no medido por la tarea. La c requeriría un patrón espacial fijo ligado al lado, no al significado. La d contradice la evidencia de prioridad de amenaza.',ANX);
set('SIM_ABR25_097','Durante la fase inicial de hipervigilancia, antes de localizar una amenaza concreta, suele producirse:',{a:'Aumento del escudriñamiento del entorno y preparación para detectar señales potencialmente peligrosas.',b:'Cierre completo de los canales sensoriales.',c:'Focalización estable en una tarea neutra sin explorar el medio.',d:'Pérdida de alerta acompañada de somnolencia.'},'a','La a es correcta: la hipervigilancia eleva alerta y exploración para detectar peligro. La b es falsa porque no cierra los canales sensoriales. La c describe fijación en una tarea neutra, lo contrario del escudriñamiento. La d implica hipoactivación y reducción de vigilancia, no hipervigilancia.',`${BEL} ${ANX}`);
set('SIM_ABR25_201','¿Cuál de estos procesos atencionales puede mantener problemas emocionales de forma transdiagnóstica?',{a:'Orientación selectiva hacia señales de amenaza o preocupación y uso de evitación o señales de seguridad.',b:'Procesamiento necesariamente imparcial de toda información emocional.',c:'Negligencia hemiespacial obligatoria.',d:'Ausencia completa de capacidad para cambiar el foco.'},'a','La a es correcta: selección de señales internas o externas relevantes, evitación y orientación a seguridad atraviesan varios trastornos. La b niega los sesgos. La c es un síndrome neurológico focal, no proceso transdiagnóstico general. La d describe una incapacidad extrema, tampoco un mecanismo común necesario.',`${BEL} ${ANX}`);
set('Simu 31 comentado Hardcore 1_041','¿Qué es la paraprosexia?',{a:'Falta de movilización de la atención por desinterés.',b:'Apariencia de inatención con capacidad conservada.',c:'Dirección anómala o desproporcionada del foco hacia determinados contenidos.',d:'Incapacidad para iniciar voluntariamente la atención.'},'c','La c es correcta: paraprosexia es una desviación cualitativa del foco hacia contenidos poco pertinentes o excesivamente absorbentes. La a define apatía atencional. La b corresponde a pseudoaprosexia. La d describe inhibición atencional, no paraprosexia.',BEL);
set('Simu 7 comentado _137','¿Cuál de las siguientes se clasifica como forma de hipoprosexia?',{a:'Alucinación auditiva.',b:'Inhibición atencional.',c:'Fusión pensamiento-acción.',d:'Despersonalización.'},'b','La b es correcta: la inhibición atencional es una disminución de la capacidad para iniciar o movilizar el foco. La a es una alteración perceptiva. La c es una creencia metacognitiva relacionada con TOC. La d altera la experiencia del yo, no cuantitativamente la atención.',BEL);
set('Simu 8 comentado _081','Respecto a la dinámica temporal de la hipervigilancia, señale la afirmación FALSA:',{a:'Puede aumentar inicialmente la exploración ambiental.',b:'Facilita detectar señales potencialmente amenazantes.',c:'Tras localizar la amenaza puede producirse estrechamiento del foco.',d:'Obliga a mantener el foco siempre amplio, incluso después de identificar el peligro.'},'d','La d es falsa: una vez detectado el peligro, el foco puede estrecharse sobre él. La a describe la fase inicial de escudriñamiento. La b recoge la finalidad funcional de la vigilancia. La c explica la transición posible desde exploración amplia a atención selectiva o visión en túnel.',`${BEL} ${ANX}`);
set('SM_ABRIL_1_SOL_1_025','En el paradigma de tiempo de reacción preparatorio, las personas con esquizofrenia pueden mostrar:',{a:'Uso superior de cualquier señal anticipatoria.',b:'Beneficio preparatorio intacto en todas las condiciones.',c:'Negligencia visual izquierda obligatoria.',d:'Dificultad para mantener el set y beneficiarse de intervalos preparatorios regulares.'},'d','La d es correcta: la alteración del set preparatorio puede reducir el aprovechamiento de señales e intervalos regulares. La a es falsa porque no existe uso superior general de señales. La b niega precisamente el déficit preparatorio. La c confunde una dificultad de preparación atencional con un síndrome espacial por lesión cerebral.',`${BEL} ${SHAK}`);
set('SM_ABRIL_2_SOL_1_057','¿Qué observación permite distinguir una pseudoaprosexia de una aprosexia verdadera?',{a:'La atención se dirige excesivamente al cuerpo.',b:'El rendimiento empeora gradualmente por fatiga.',c:'La capacidad aparece conservada y se manifiesta ante cambios de motivación o situación.',d:'Existe abolición constante de toda respuesta atencional.'},'c','La c es correcta: la discrepancia entre apariencia y capacidad disponible define pseudoaprosexia. La a describe paraprosexia hipocondríaca. La b es fatigabilidad. La d sería compatible con aprosexia real y contradice la conservación funcional.',BEL);
set('SM_DICIEMBRE_1_SOL_1_034','Respecto a la atención en la esquizofrenia durante la remisión, señale la afirmación correcta:',{a:'Todo déficit desaparece al cesar los síntomas positivos.',b:'Pueden persistir dificultades para discriminar estímulos objetivo y mantener vigilancia.',c:'Solo se altera la atención dividida y únicamente por antipsicóticos.',d:'El rendimiento en tareas de ejecución continua debe normalizarse por definición.'},'b','La b es correcta: algunos déficits de discriminación y vigilancia persisten clínicamente estabilizados. La a equipara erróneamente remisión psicótica con normalización cognitiva. La c restringe el perfil y lo atribuye necesariamente a antipsicóticos. La d también presupone una normalización que no define la remisión.',`${BEL} ${SCH}`);
set('SM_JULIO_2_SOL_1_051','¿Qué define mejor la distraibilidad?',{a:'Inestabilidad del foco, captado de manera superficial y sucesiva por estímulos irrelevantes.',b:'Exploración deliberada y organizada para localizar peligro.',c:'Absorción estable en un único contenido interno.',d:'Ausencia completa de disposición atencional.'},'a','La a es correcta: en la distraibilidad el foco cambia con facilidad y no se mantiene. La b describe búsqueda hipervigilante. La c corresponde a hiperconcentración o ausencia mental. La d define aprosexia.',BEL);
set('SM_JUNIO_1_SOL_1_057','En un episodio maníaco, el paciente salta de un estímulo a otro y apenas mantiene el hilo de la entrevista. ¿Qué alteración atencional predomina?',{a:'Apatía atencional.',b:'Pseudoaprosexia.',c:'Distraibilidad.',d:'Perplejidad.'},'c','La c es correcta: la captura rápida por estímulos sucesivos y el cambio constante del foco caracterizan distraibilidad. La a supone desinterés y baja movilización. La b es apariencia de inatención con capacidad preservada. La d implica no sintetizar el significado de lo atendido.',BEL);
set('SmCm08PIR2025_025','¿Qué combinación describe correctamente las dos fases posibles de la hipervigilancia ante amenaza?',{a:'Exploración inicial amplia y posterior estrechamiento sobre la señal detectada.',b:'Somnolencia inicial y aprosexia posterior.',c:'Negligencia izquierda inicial y derecha posterior.',d:'Ausencia de búsqueda inicial y atención neutra posterior.'},'a','La a es correcta: primero puede aumentar el escudriñamiento y, localizada la amenaza, concentrarse los recursos en ella. La b describe hipoactivación extrema. La c combina déficits espaciales neurológicos. La d niega tanto la búsqueda como la focalización amenazante.',`${BEL} ${ANX}`);
set('SmCm17PIR2025_088','Una persona está tan absorbida por un problema que ejecuta automáticamente una rutina y deja de registrar otros estímulos, aunque después dice haber estado «distraída». Este fenómeno es:',{a:'Amnesia orgánica.',b:'Atención dividida eficaz.',c:'Ausencia mental por hiperconcentración.',d:'Aprosexia generalizada.'},'c','La c es correcta: la atención está intensamente concentrada en un contenido y se desatiende el resto; no hay ausencia global de atención. La a exigiría un trastorno de memoria orgánico. La b implicaría atender eficazmente varias fuentes. La d supondría abolición atencional, incompatible con la absorción selectiva.',BEL);
set('SmCm1PIR2024_139','¿Qué característica define la perplejidad atencional?',{a:'Cambio rápido del foco ante estímulos irrelevantes.',b:'Concentración intensa que excluye la periferia.',c:'Ausencia cuantitativa completa de atención.',d:'Incapacidad para sintetizar los elementos atendidos y captar el significado global.'},'d','La d es correcta: la persona percibe o atiende fragmentos, pero no logra integrarlos en una situación comprensible. La a es distraibilidad. La b describe hiperconcentración o estrechamiento. La c corresponde a aprosexia.',BEL);
set('SmCm20PIR2025 (1)_117','¿En qué situación es más congruente observar perplejidad atencional?',{a:'Psicosis aguda con vivencia de extrañeza e incapacidad para comprender el conjunto de la situación.',b:'Disfunción sexual aislada sin alteración cognitiva.',c:'Fobia específica fuera de la exposición al estímulo.',d:'Insomnio ocasional sin somnolencia diurna.'},'a','La a es correcta: en psicosis aguda puede alterarse la síntesis significativa de la experiencia y aparecer perplejidad. La b no implica por sí misma alteración de integración atencional. La c fuera del estímulo no la caracteriza. La d tampoco supone necesariamente incapacidad para comprender lo atendido.',BEL);
set('SmCm22PIR2025_004','¿Qué asociación entre cuadro clínico y alteración atencional es la más precisa?',{a:'Manía—distraibilidad marcada por captura de estímulos sucesivos.',b:'Estado crepuscular—atención amplia y flexible a todo el entorno.',c:'Ansiedad—ausencia de selección preferente de amenaza.',d:'Depresión inhibida—hipervigilancia exploratoria como rasgo definitorio.'},'a','La a es correcta: la manía se asocia típicamente a distraibilidad. La b es falsa porque el estado crepuscular implica estrechamiento del campo de conciencia y atención. La c niega el sesgo selectivo hacia amenaza. La d atribuye a depresión inhibida una exploración hipervigilante más propia de ansiedad.',BEL);
set('SmCm24PIR2025 (1)_013','Durante la entrevista, una persona parece ignorar las preguntas, pero más tarde reproduce detalles exactos y responde cuando obtiene un incentivo. ¿Cuál es la alteración más probable?',{a:'Fatigabilidad.',b:'Pseudoaprosexia.',c:'Apatía atencional.',d:'Inhibición atencional.'},'b','La b es correcta: la capacidad está preservada pese a la apariencia de inatención. La a exigiría empeoramiento progresivo por esfuerzo. La c supondría falta de interés genuina, no registro encubierto demostrado. La d implicaría dificultad real para movilizar el foco.',BEL);
set('SmCm24PIR2025 (1)_014','¿En qué presentación constituye un ejemplo clásico de paraprosexia la concentración desproporcionada en sensaciones corporales?',{a:'Hipocondría o ansiedad por la enfermedad.',b:'Amnesia global transitoria.',c:'Síndrome de negligencia espacial.',d:'Afasia de conducción.'},'a','La a es correcta: la atención se dirige de forma anómala y excesiva hacia sensaciones corporales interpretadas como enfermedad. La b es una alteración mnésica aguda. La c es un déficit espacial por lesión cerebral. La d es un trastorno del lenguaje con repetición alterada, no de dirección atencional.',BEL);
set('SmCm27PIR2025 (1)_025','¿Quién formuló la teoría de la «disposición fragmentada» o segmental set para explicar el déficit formal de respuesta en la esquizofrenia?',{a:'David Shakow.',b:'Germán Berrios.',c:'Gordon Claridge.',d:'Michael Eysenck.'},'a','La a es correcta: Shakow formuló la teoría del segmental set y estudió el aprovechamiento anómalo de intervalos preparatorios. La b destacó en historia y psicopatología descriptiva. La c desarrolló modelos dimensionales de esquizotipia. La d formuló teorías cognitivas de ansiedad, no esta explicación de esquizofrenia.',`${BEL} ${SHAK}`);
set('SmCm28PIR2025_056','Tras una lesión hemisférica derecha, un paciente come solo la mitad derecha del plato, niega objetos situados a su izquierda y no compensa espontáneamente. ¿Cuál es el diagnóstico más probable?',{a:'Heminegligencia espacial izquierda.',b:'Síndrome de Balint.',c:'Heminegligencia derecha por lesión derecha.',d:'Desorientación topográfica.'},'a','La a es correcta: una lesión derecha produce con frecuencia omisión contralateral izquierda. La b exige un síndrome bilateral con simultagnosia, ataxia óptica y apraxia oculomotora. La c coloca negligencia y lesión en el mismo lado. La d afecta orientación y navegación, no la exploración de un hemiespacio.',`${BEL} Vallar, G. y Calzolari, E. (2018). Unilateral spatial neglect after posterior parietal damage. Handbook of Clinical Neurology, 151, 287-312.`);
set('SmCm29PIR2025_102','¿Qué resultado refleja un sesgo atencional hacia amenaza y no simplemente mayor ansiedad subjetiva?',{a:'Detección u orientación preferente hacia estímulos amenazantes frente a neutros en una tarea atencional.',b:'Puntuación alta en un cuestionario de preocupación sin medida de atención.',c:'Recuerdo autobiográfico negativo sin estímulos competidores.',d:'Negligencia constante de un hemicampo visual.'},'a','La a es correcta: compara directamente la prioridad atencional de amenaza y estímulos neutros. La b mide preocupación autoinformada, no atención. La c evalúa memoria y estado de ánimo. La d es un déficit espacial fijo de origen neurológico, no un sesgo por significado amenazante.',ANX);
set('SmCm7PIR2024_046','¿Qué dato permite hablar de inhibición atencional y no de apatía?',{a:'La persona no atiende porque nada le interesa ni le resulta motivador.',b:'Desea atender, pero le cuesta iniciar o desplazar el foco salvo ante estímulos intensos.',c:'El rendimiento cae solo después de una tarea larga.',d:'El foco cambia rápidamente con cada ruido irrelevante.'},'b','La b es correcta: existe intención, pero falla la movilización del foco. La a define apatía atencional por desinterés. La c corresponde a fatigabilidad. La d describe distraibilidad.',BEL);
set('OCTUBRE-UNO-24_COMENTADO_083','¿Cuál de los siguientes NO constituye un proceso atencional transdiagnóstico central en los trastornos emocionales?',{a:'Selección de estímulos externos relacionados con la preocupación.',b:'Heminegligencia espacial contralateral causada por lesión hemisférica.',c:'Atención a señales internas relevantes para la amenaza.',d:'Evitación atencional y orientación hacia señales de seguridad.'},'b','La b es correcta como excepción: la heminegligencia es un síndrome neuropsicológico focal, no un mecanismo transdiagnóstico de los trastornos emocionales. La a sí aparece en diferentes problemas como selección de información congruente. La c recoge vigilancia de sensaciones, pensamientos o imágenes internas. La d incluye estrategias atencionales de evitación y seguridad que pueden mantener varios trastornos.',`${BEL} ${ANX}`);

const topic=bank.filter(q=>q.t?.includes('Psicopatología de la atención'));
if(topic.length!==46)throw Error(`Expected 46 attention questions, got ${topic.length}`);
let changed=0;for(const q of topic){if(!U[q.id])throw Error(`Missing update for ${q.id}`);Object.assign(q,U[q.id],{v:'VALIDADA_ORIGINAL'});changed++;}
if(changed!==46||Object.keys(U).length!==46)throw Error(`Update mismatch: ${changed}/${Object.keys(U).length}`);
// Distribute answer positions to avoid an accidental cue based on option order.
const shifts={
 'PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-DOS-23_022':1,'R0PIR_RESTORE_20260831_009':1,'AGOSTO2_032':1,'DICIEMBRE-UNO-24_COMENTADO_128':1,
 'MAYO-UNO-24_COMENTADO_016':2,'NOVIEMBRE-DOS-24_COMENTADO_047':2,'OCTUBRE-UNO-24_COMENTADO_080':2,'PERSEVER___SIMULACRO_COMENTADO_MAYO-UNO-23_067':2,
 'PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-DOS-23_051':3,'SIM_ABR2_007':3,'SIM_ABR25_017':3
};
const letters=['a','b','c','d'];
for(const q of topic){const n=shifts[q.id];if(!n)continue;const old={...q.o};const remap={};for(let i=0;i<4;i++)remap[letters[i]]=letters[(i+n)%4];q.o={};for(const k of letters)q.o[remap[k]]=old[k];q.o=Object.fromEntries(letters.map(k=>[k,q.o[k]]));q.c=remap[q.c];const marks={};for(const k of letters)marks[k]=`§${k}§`;q.x=q.x.replace(/La ([abcd])\b/g,(_,k)=>marks[k]);for(const k of letters)q.x=q.x.replaceAll(marks[k],`La ${remap[k]}`);}
fs.writeFileSync(file,JSON.stringify(bank));console.log(`Reaudited ${changed} attention questions.`);
