const fs=require('fs'),path=require('path'),file=path.join(__dirname,'..','public','banco','clinica_adultos.json');
const bank=JSON.parse(fs.readFileSync(file,'utf8')),topic='Trastornos de la conducta alimentaria';
const ids=['SmCm24PIR2025 (1)_067','SmCm25PIR2025_032','SmCm25PIR2025_033','SmCm26PIR2025_085','SmCm27PIR2025 (1)_096','SmCm27PIR2025 (1)_108','SmCm27PIR2025 (1)_109','SmCm27PIR2025 (1)_112','SmCm28PIR2025_066','SmCm29PIR2025_068','SmCm2PIR2024_026','SmCm2PIR2024_060','SmCm2PIR2024_062','SmCm30PIR2025 (1)_049','SmCm7PIR2024_028','SmCm7PIR2024_029','SmCm7PIR2024_030','simu 9 comentado_078','SmCm22PIR2025_024'];
const get=id=>{const q=bank.find(x=>x.id===id);if(!q)throw Error('Missing '+id);return q},set=(id,v)=>Object.assign(get(id),v);
const dsm='American Psychiatric Association (2022). DSM-5-TR, capítulo «Trastornos de la conducta alimentaria y de la ingesta de alimentos». American Psychiatric Association Publishing.';
const bell='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. I (4.ª ed.), cap. 13. McGraw Hill.';
set(ids[0],{e:'La elevación de amilasa sérica, hipopotasemia, aumento de las glándulas parótidas y erosión del esmalte dental orientan especialmente a:',o:{a:'Tricotilomanía.',b:'Pica.',c:'Bulimia nerviosa.',d:'Trastorno por consumo de sustancias.'},x:'La c es correcta. Estos hallazgos pueden aparecer por vómitos autoprovocados recurrentes en bulimia nerviosa: la hipopotasemia refleja alteración electrolítica y la exposición al ácido gástrico daña el esmalte; también pueden aumentar parótidas y amilasa.',r:dsm});
set(ids[1],{e:'El grupo de Toronto señaló tres características esenciales de la anorexia nerviosa. ¿Cuál NO pertenece a esa formulación?',o:{a:'Distorsión de la imagen corporal.',b:'Preocupación extrema por la figura y el peso corporal.',c:'Percepción distorsionada de señales propioceptivas.',d:'Sentimiento general de ineficacia personal.'},x:'La b es la opción que no forma parte de esa tríada histórica. El grupo de Toronto destacó distorsión de la imagen corporal, percepción alterada de señales propioceptivas y sentimiento general de ineficacia.',r:bell});
set(ids[2],{e:'Respecto a la epidemiología y el curso de la anorexia nerviosa, señale la afirmación incorrecta:',o:{a:'La prevalencia a 12 meses en mujeres jóvenes se aproxima al 0,4 %.',b:'Las personas más jóvenes pueden mostrar características atípicas.',c:'Pueden persistir alteraciones psicopatológicas pese a estabilizarse el peso.',d:'No se ha encontrado evidencia de heredabilidad.'},x:'La d es incorrecta: existe una contribución genética importante y agregación familiar. Las restantes afirmaciones describen prevalencia, presentaciones en jóvenes y persistencia de psicopatología tras la recuperación ponderal.',r:`${dsm}; ${bell}`});
set(ids[3],{e:'¿Cuál de estas distorsiones cognitivas NO forma parte de «la docena sucia» de Cash y Grant?',o:{a:'La bella o la bestia.',b:'La lupa.',c:'Pensamiento supersticioso.',d:'El espejo malhumorado.'},x:'La c es correcta. «Pensamiento supersticioso» no figura en esa taxonomía específica; «la bella o la bestia», «la lupa» y «el espejo malhumorado» sí pertenecen a ella.',r:`${bell}, apartado de imagen corporal.`});
set(ids[4],{e:'Respecto al trastorno de evitación/restricción de la ingesta de alimentos, señale la afirmación correcta:',o:{a:'Sus consecuencias físicas pueden alcanzar una gravedad similar a las de la anorexia nerviosa.',b:'Puede diagnosticarse exclusivamente durante una anorexia nerviosa activa.',c:'Su rasgo definitorio es el miedo a engordar y la sobrevaloración del peso.',d:'Es necesariamente más frecuente en niñas que en niños.'},x:'La a es correcta. El trastorno puede producir malnutrición y consecuencias médicas graves. No se diagnostica si la restricción se explica exclusivamente por anorexia nerviosa, no exige preocupación por peso o figura y no presenta el marcado predominio femenino de anorexia o bulimia.',r:dsm});
set(ids[5],{e:'Dentro de los modelos explicativos de la ingesta compulsiva, la hipótesis de la activación emocional:',x:'La b es correcta: este modelo subraya el papel de los estados emocionales como desencadenantes de la ingesta compulsiva. La a corresponde a la hipótesis de la externalidad y la d mezcla de forma inadecuada restricción y activación emocional.',r:bell});
set(ids[6],{e:'¿Cuál NO se considera un factor de mal pronóstico de la anorexia nerviosa?',o:{a:'Bajo peso premórbido.',b:'Peso mínimo muy bajo alcanzado durante el trastorno.',c:'Subtipo restrictivo.',d:'Dificultades sociales e interpersonales.'},x:'La c es correcta: el subtipo con atracones/purgas se asocia a peor evolución que el restrictivo. Peso bajo, un mínimo ponderal extremo y dificultades sociales se relacionan con un pronóstico menos favorable.',r:bell});
set(ids[7],{e:'¿Cuál de estas características NO forma parte de los criterios del episodio de atracón en el DSM-5-TR?',o:{a:'Comer mucho más rápidamente de lo normal.',b:'Comer hasta sentirse desagradablemente lleno.',c:'Comer más durante situaciones de elevada tensión emocional.',d:'Sentirse después a disgusto, deprimido o muy avergonzado.'},x:'La c es correcta como opción no incluida en la lista de características diagnósticas. La tensión emocional puede actuar como desencadenante, pero no es uno de los cinco indicadores; a, b y d sí lo son.',r:dsm});
set(ids[8],{e:'Según los modelos multifactoriales, ¿cuál puede actuar como factor precipitante de anorexia nerviosa?',x:'La c es correcta: padecer una enfermedad que ocasiona pérdida de peso puede precipitar el trastorno. Obesidad y adolescencia se consideran factores predisponentes y el ejercicio excesivo suele funcionar como conducta mantenedora o manifestación.',r:bell});
set(ids[9],{e:'¿Cuál de las siguientes es una de las áreas relevantes en la evaluación integral de los trastornos alimentarios?',o:{a:'Preferencia política.',b:'Dominancia manual.',c:'Clima y funcionamiento familiar.',d:'Aptitud musical.'},x:'La c es correcta. El clima y el funcionamiento familiar forman parte de la evaluación integral porque pueden influir en el inicio, mantenimiento, apoyo y planificación terapéutica.',r:bell});
set(ids[10],{x:'La c es falsa: en la anorexia nerviosa se describe un síndrome de T3 baja y las concentraciones tiroideas pueden ser bajas o normales, no normalmente altas. La prevalencia aproximada, la remisión a cinco años y la emaciación como hallazgo destacado son datos recogidos en el DSM.',r:dsm});
set(ids[11],{e:'Respecto al trastorno de pica, señale la opción correcta:',o:{a:'Consiste en ingerir de forma persistente sustancias nutritivas aunque sean poco habituales.',b:'Se recomienda una edad mínima de un año para diagnosticarlo.',c:'Las sustancias ingeridas suelen variar según la edad y su disponibilidad.',d:'Su frecuencia es muy superior en varones.'},x:'La c es correcta. El tipo de sustancia ingerida varía con la edad y la disponibilidad. Debe tratarse de sustancias no nutritivas y no alimentarias, se suele exigir una edad de desarrollo mínima aproximada de dos años y no existe el predominio masculino propuesto.',r:dsm});
set(ids[12],{e:'Según la CIE-11, ¿qué umbral orienta a peso significativamente bajo en la anorexia nerviosa?',o:{a:'En adultos, IMC inferior a 18,5; en menores, percentil de IMC inferior a 7.',b:'En adultos, IMC inferior a 17,5; en menores, percentil inferior a 8.',c:'En adultos, IMC inferior a 18,5; en menores, percentil de IMC inferior a 5.',d:'En adultos, IMC inferior a 18; en menores, percentil inferior a 5.'},x:'La c es correcta. La CIE-11 utiliza como orientación un IMC inferior a 18,5 kg/m² en adultos y un IMC para la edad por debajo del percentil 5 en niños y adolescentes.',r:'Organización Mundial de la Salud (2022). CIE-11, criterios diagnósticos para anorexia nerviosa.'});
set(ids[13],{e:'La anorexia nerviosa caracterizada por control estricto de la dieta, ayuno o ejercicio excesivo, sin atracones ni purgas recurrentes durante los últimos tres meses, corresponde al:',o:{a:'Trastorno dismórfico muscular.',b:'Tipo con atracones/purgas.',c:'Trastorno por purgas.',d:'Tipo restrictivo.'},x:'La d es correcta. El tipo restrictivo se define por ausencia de atracones y purgas recurrentes en los últimos tres meses, con pérdida de peso conseguida principalmente mediante dieta, ayuno o ejercicio excesivo.',r:dsm});
set(ids[15],{e:'En la evaluación de una persona con un trastorno alimentario, ¿qué elemento NO constituye por sí solo un área de evaluación bien delimitada?',o:{a:'Peso y evolución ponderal.',b:'Conductas compensatorias inapropiadas.',c:'La etiqueta inespecífica «factores conductuales», sin concretar conductas ni función.',d:'Clima y funcionamiento familiar.'},x:'La c es la opción menos adecuada por su formulación inespecífica. La evaluación debe concretar conductas alimentarias y compensatorias, antecedentes, consecuencias, peso, imagen corporal, funcionamiento emocional, social y familiar.',r:bell});
set(ids[17],{x:'La b es correcta. La sensación de pérdida de control distingue el atracón de una ingesta abundante no patológica; comer deprisa, sin hambre o experimentar malestar posterior son características asociadas, pero no bastan por sí solas.',r:dsm});
set(ids[18],{e:'Respecto a la bulimia nerviosa según el DSM-5-TR, señale la opción correcta:',o:{a:'Presenta una prevalencia semejante en la mayoría de los países industrializados.',b:'La transición desde bulimia a anorexia ocurre en el 25-35 % de los casos.',c:'La gravedad de la comorbilidad psiquiátrica no influye en la evolución.',d:'Los atracones están precedidos con igual frecuencia por emociones positivas y negativas intensas.'},x:'La a es correcta. La prevalencia es relativamente semejante entre países industrializados. La transición a anorexia ocurre en una minoría menor que la cifra propuesta; la comorbilidad se relaciona con el pronóstico y el antecedente más frecuente del atracón es el afecto negativo.',r:dsm});
const duplicateIds=[ids[14],ids[16],ids[0].replace('SmCm24PIR2025 (1)_067','SmCm25PIR2025_042')];
for(const id of duplicateIds){const i=bank.findIndex(q=>q.id===id);if(i<0)throw Error('Missing duplicate '+id);bank.splice(i,1)}
for(const id of ids.filter((_,i)=>![0,14,16].includes(i))){const q=get(id);if(!q.t?.includes(topic)||!q.e||!q.o?.[q.c]||!q.x||!q.r)throw Error('Invalid '+id);q.v='VALIDADA_ORIGINAL'}
// ids[0] sí se conserva; el tercer duplicado es SmCm25PIR2025_042.
const first=get(ids[0]);if(!first.o?.[first.c])throw Error('Invalid '+ids[0]);first.v='VALIDADA_ORIGINAL';
fs.writeFileSync(file,JSON.stringify(bank));const qs=bank.filter(q=>q.t?.includes(topic));console.log({audited:19,removedDuplicates:3,total:qs.length,validated:qs.filter(q=>q.v==='VALIDADA_ORIGINAL').length,pending:qs.filter(q=>q.v!=='VALIDADA_ORIGINAL').length});
