const fs=require('fs');
const P='public/banco/';
const adultPath=P+'clinica_adultos.json', childPath=P+'clinica_infantojuvenil.json';
let adult=JSON.parse(fs.readFileSync(adultPath,'utf8'));
let child=JSON.parse(fs.readFileSync(childPath,'utf8'));
const oldAlcohol='PERSEVER___SIMULACRO_COMENTADO_JUNIO-DOS-23_061';
const pos=adult.findIndex(q=>q.id===oldAlcohol);
if(pos<0)throw Error('No se encontró alcohol');
adult.splice(pos,1,{
 id:'R0PIR_CA_ADICCIONES_HEREDABILIDAD_ALCOHOL_20260902',s:'Clínica Adultos',t:['Trastornos adictivos y relacionados con sustancias'],origen:'creada',convocatoria:null,pa:null,
 e:'Según el metaanálisis de Verhulst, Neale y Kendler sobre estudios de gemelos y adopción, ¿qué porcentaje de la varianza del riesgo de trastorno por consumo de alcohol se atribuye aproximadamente a factores genéticos?',
 o:{a:'84 %.',b:'49 %.',c:'35 %.',d:'70 %.'},c:'b',
 x:'La opción b es correcta: la mejor estimación metaanalítica de la heredabilidad fue 0,49, es decir, aproximadamente el 49 % de la varianza de la vulnerabilidad al trastorno por consumo de alcohol. La a (84 %) y la d (70 %) sobreestiman claramente la contribución genética. La c (35 %) queda por debajo de la estimación combinada y se aproxima más a determinados componentes o diseños particulares, no al resultado global solicitado. Heredabilidad no significa que el 49 % del trastorno de una persona esté «causado por genes», sino que expresa variación poblacional.',
 r:'Verhulst, B., Neale, M. C. y Kendler, K. S. (2015). The heritability of alcohol use disorders: a meta-analysis of twin and adoption studies. Psychological Medicine, 45(5), 1061–1072. https://doi.org/10.1017/S0033291714002165.',v:'VALIDADA_ORIGINAL'
});

const U={
'PERSEVER___SIMULACRO_COMENTADO_DICIEMBRE-UNO-23_050':{e:'En el diagnóstico diferencial del TEPT, ¿con qué afección pueden solaparse síntomas como alteraciones del sueño, irritabilidad y dificultades de concentración tras una lesión?',o:{a:'Trastorno neurocognitivo debido a traumatismo cerebral.',b:'Trastorno de ansiedad por separación.',c:'Esquizofrenia.',d:'Anorexia nerviosa.'},c:'a',x:'La a es correcta: tras un traumatismo cerebral pueden coexistir TEPT y alteraciones neurocognitivas, y ambos cuadros comparten síntomas inespecíficos como irritabilidad, problemas de sueño y concentración. La b puede ser comórbida, pero no explica ese solapamiento postraumático tras una lesión. La c exige síntomas psicóticos nucleares y la d se define por alteraciones alimentarias y de imagen corporal; ninguna presenta el patrón de solapamiento preguntado.',r:'American Psychiatric Association (2022). DSM-5-TR. Trastorno de estrés postraumático, diagnóstico diferencial y comorbilidad; trastorno neurocognitivo debido a traumatismo cerebral.'},
'PERSEVER___SIMULACRO_COMENTADO_MAYO-DOS-23_038':{e:'¿Cuál de los siguientes NO constituye uno de los cuatro grupos sintomáticos del TEPT en adultos según el DSM-5-TR?',o:{a:'Apatía como grupo diagnóstico independiente.',b:'Síntomas de intrusión.',c:'Evitación persistente.',d:'Alteraciones negativas de las cogniciones y del estado de ánimo.'},c:'a',x:'La a es correcta: la apatía puede aparecer clínicamente, pero no constituye por sí misma uno de los cuatro grupos diagnósticos. La b corresponde al criterio B; la c, al criterio C; y la d, al criterio D. El cuarto grupo es la alteración de la activación y la reactividad. Se sustituye la antigua clasificación ambigua de síntomas «positivos y negativos» por los grupos DSM-5-TR.',r:'American Psychiatric Association (2022). DSM-5-TR. Trastorno de estrés postraumático, criterios B–E.'},
'SEPTIEMBRE-UNO-24_COMENTADO_147':{e:'Para diagnosticar TEPT en adultos y en niños mayores de seis años, ¿qué combinación mínima de grupos sintomáticos exige el DSM-5-TR?',o:{a:'Un síntoma de intrusión, uno de evitación, dos de alteraciones cognitivas/estado de ánimo y dos de activación/reactividad.',b:'Un síntoma de cada grupo y una duración mínima de seis meses.',c:'Un síntoma de intrusión, uno de evitación o cognición/estado de ánimo y dos de activación/reactividad.',d:'Dos síntomas de intrusión, dos de evitación y una duración superior a tres meses.'},c:'a',x:'La a es correcta: los mínimos son 1-1-2-2 para los criterios B, C, D y E. La b es falsa porque la duración exigida es superior a un mes y los umbrales no son uno por grupo. La c reproduce parcialmente la agrupación utilizada en menores de seis años, donde evitación y alteraciones negativas se combinan. La d aumenta indebidamente intrusión y evitación y fija tres meses en lugar de más de uno.',r:'American Psychiatric Association (2022). DSM-5-TR. Trastorno de estrés postraumático, criterios B–F.'},
'SM_AGOSTO_1_SOL_1_081':{e:'Respecto a la evolución clínica tras acontecimientos traumáticos, señale la afirmación correcta:',o:{a:'El TEPT es necesariamente más frecuente tras accidentes que tras violencia interpersonal.',b:'En los hombres el TEPT es siempre más grave que en las mujeres.',c:'Las manifestaciones del trauma solo pueden aparecer inmediatamente después del acontecimiento.',d:'Los traumas prolongados pueden asociarse con alteraciones persistentes de regulación emocional, autoconcepto y relaciones.'},c:'d',x:'La d es correcta: la exposición prolongada o repetida, especialmente interpersonal, puede acompañarse de dificultades persistentes de regulación afectiva, autoconcepto negativo y relaciones interpersonales. La a es falsa: la violencia interpersonal suele conferir mayor riesgo que muchos accidentes. La b es falsa porque el TEPT es, en general, más frecuente en mujeres y la gravedad depende de múltiples factores. La c es falsa: algunos síntomas pueden aparecer o alcanzar el umbral diagnóstico de forma retardada.',r:'World Health Organization (2024). ICD-11 CDDR. Complex post traumatic stress disorder (6B41); American Psychiatric Association (2022). DSM-5-TR. TEPT, desarrollo y curso.'},
'SM_AGOSTO_1_SOL_1_082':{e:'¿Qué teoría explica la reexperimentación del TEPT mediante una estructura mnésica de miedo que contiene información errónea y no ha sido procesada emocionalmente de forma adecuada?',o:{a:'Teoría de la indefensión aprendida de Seligman.',b:'Teoría del procesamiento emocional de Foa y Kozak.',c:'Teoría de la representación dual de Brewin.',d:'Modelo cognitivo de Ehlers y Clark.'},c:'b',x:'La b es correcta: Foa y Kozak proponen que la estructura de miedo patológica debe activarse y modificarse mediante información correctora. La a explica pasividad y síntomas depresivos ante incontrolabilidad. La c diferencia memoria verbalmente accesible y situacionalmente accesible, pero no es la formulación de la estructura de miedo descrita. La d explica la persistencia de una amenaza actual por valoraciones negativas y una memoria traumática poco elaborada.',r:'Foa, E. B. y Kozak, M. J. (1986). Emotional processing of fear. Psychological Bulletin, 99(1), 20–35. https://doi.org/10.1037/0033-2909.99.1.20.'},
'SM_DICIEMBRE_1_SOL_1_011':{e:'Respecto al trastorno de estrés postraumático complejo de la CIE-11, señale la afirmación correcta:',o:{a:'Puede diagnosticarse sin que se cumplan los requisitos del TEPT.',b:'Requiere cumplir los requisitos del TEPT y añade alteraciones de la autoorganización.',c:'Se clasifica fuera del capítulo de trastornos mentales.',d:'Debe diagnosticarse simultáneamente con TEPT como dos trastornos separados.'},c:'b',x:'La b es correcta: el TEPT complejo exige los núcleos del TEPT y, además, problemas persistentes de regulación afectiva, autoconcepto negativo y relaciones. La a es falsa porque los requisitos del TEPT son necesarios. La c es falsa: se incluye en los trastornos específicamente asociados con el estrés dentro del capítulo de trastornos mentales. La d es falsa porque el diagnóstico de TEPT complejo sustituye al de TEPT; no se asignan ambos simultáneamente.',r:'World Health Organization (2024). ICD-11 Clinical Descriptions and Diagnostic Requirements. Complex post traumatic stress disorder, 6B41.'},
'SM_DICIEMBRE_1_SOL_1_013':{e:'Respecto al TEPT en personas mayores, señale la afirmación correcta:',o:{a:'Se caracteriza necesariamente por más hiperactivación que en adultos jóvenes.',b:'La exposición traumática tardía produce siempre menos problemas de sueño.',c:'Se asocia con peor percepción de salud, mayor utilización de atención primaria e ideación suicida.',d:'Los cambios de humor sustituyen obligatoriamente a las alteraciones cognitivas.'},c:'c',x:'La c es correcta: en personas mayores el TEPT se relaciona con percepción negativa de la salud, mayor uso de atención primaria e ideación suicida. La a y la b contienen absolutos no respaldados: la expresión varía según el momento de exposición y otros factores. La d traslada a personas mayores una observación descrita en niños pequeños y, además, usa «obligatoriamente».',r:'American Psychiatric Association (2022). DSM-5-TR. Trastorno de estrés postraumático, desarrollo y curso y aspectos diagnósticos relacionados con la edad.'},
'SM_ENERO_1_SOL_1_088':{e:'Según el DSM-5-TR, señale la afirmación FALSA sobre el trastorno de adaptación:',o:{a:'Los síntomas aparecen dentro de los tres meses siguientes al inicio del estresor.',b:'Se especifica como persistente cuando dura menos de seis meses.',c:'Puede ser un diagnóstico frecuente en contextos de consulta hospitalaria.',d:'Tras terminar el estresor y sus consecuencias, los síntomas no persisten más de otros seis meses.'},c:'b',x:'La b es falsa y, por tanto, la respuesta: «persistente» se aplica cuando la alteración dura seis meses o más; una duración inferior corresponde a «agudo». La a reproduce el criterio temporal de inicio. La c es compatible con la elevada frecuencia del diagnóstico en determinados contextos clínicos. La d reproduce el límite temporal tras el cese del estresor o sus consecuencias.',r:'American Psychiatric Association (2022). DSM-5-TR. Trastornos de adaptación, criterios A y E y especificadores de duración.'},
'SM_JULIO_2_SOL_1_011':{e:'Teniendo en cuenta las diferencias entre el trastorno de estrés agudo y el TEPT, señale la afirmación FALSA:',o:{a:'El trastorno de estrés agudo incluye síntomas disociativos entre sus categorías posibles.',b:'El TEPT exige una duración superior a la del trastorno de estrés agudo.',c:'El TEPT debe durar como mínimo seis meses.',d:'El trastorno de estrés agudo dura de tres días a un mes tras el trauma.'},c:'c',x:'La c es falsa y constituye la respuesta: el TEPT exige que la alteración dure más de un mes, no seis meses. La a es correcta porque la disociación es una de las cinco categorías del trastorno de estrés agudo, aunque ya no es obligatoria como núcleo independiente. La b es correcta por los respectivos límites temporales. La d reproduce el criterio temporal del trastorno de estrés agudo.',r:'American Psychiatric Association (2022). DSM-5-TR. Trastorno de estrés agudo, criterio C; trastorno de estrés postraumático, criterio F.'},
'SM_JUNIO_2_SOL_1_020':{e:'Respecto al desarrollo y curso del TEPT según el DSM-5-TR, señale la afirmación correcta:',o:{a:'Solo puede diagnosticarse a partir de los seis años.',b:'Su prevalencia es necesariamente mayor en personas mayores que en la población general.',c:'Las personas con TEPT rara vez cumplen criterios de otro trastorno mental.',d:'Puede aparecer a cualquier edad, incluido el primer año de vida.'},c:'d',x:'La d es correcta: el TEPT puede aparecer a cualquier edad, desde el primer año de vida. La a es falsa porque existen criterios específicos para menores de seis años. La b es falsa: la prevalencia de cuadro completo tiende a ser menor en personas mayores. La c es falsa porque la comorbilidad con depresión, ansiedad, consumo de sustancias y otros trastornos es elevada.',r:'American Psychiatric Association (2022). DSM-5-TR. Trastorno de estrés postraumático, desarrollo y curso y comorbilidad.'},
'SM_JUNIO_2_SOL_1_061':{s:'Clínica Adultos',t:['Trastornos de ansiedad'],e:'¿En qué trastorno se ha estudiado la menor flexibilidad de la arritmia sinusal respiratoria como característica psicofisiológica transdiagnóstica?',o:{a:'Trastorno de pánico.',b:'Trastorno de estrés postraumático.',c:'Trastorno de síntomas somáticos.',d:'Trastorno de ansiedad social.'},c:'d',x:'La d es correcta: en ansiedad social se ha estudiado una menor flexibilidad de la variabilidad cardiaca vinculada a dificultades de regulación autonómica. La a presenta marcadores autonómicos relacionados con crisis de pánico, pero no es la asociación concreta solicitada. La b se relaciona con alteraciones autonómicas tras trauma, y la c con amplificación somática, pero tampoco corresponden a la formulación registrada. Se reubica en trastornos de ansiedad.',r:'Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vol. II (4.ª ed.). McGraw Hill, capítulo sobre trastorno de ansiedad social.'},
'SM_MAYO_1_SOL_1_094':{s:'Clínica Adultos',t:['Trastornos depresivos'],e:'¿Cuál de los siguientes trastornos genera, en términos globales, una mayor carga de discapacidad medida mediante años de vida ajustados por discapacidad (DALY)?',o:{a:'Fobia específica.',b:'Trastorno de estrés agudo.',c:'Trastorno de adaptación.',d:'Trastornos depresivos.'},c:'d',x:'La d es correcta: los trastornos depresivos se encuentran entre las principales causas mundiales de años vividos con discapacidad y aportan una carga de DALY muy superior a los otros cuadros enumerados. La a suele producir una discapacidad más circunscrita; b y c son, por definición, cuadros vinculados temporalmente a un estresor y presentan menor carga poblacional global. Se reubica en trastornos depresivos.',r:'GBD 2017 Disease and Injury Incidence and Prevalence Collaborators (2018). Global, regional, and national incidence, prevalence, and years lived with disability. The Lancet, 392, 1789–1858. https://doi.org/10.1016/S0140-6736(18)32279-7.'}
};
for(const [id,p] of Object.entries(U)){const q=adult.find(x=>x.id===id);if(!q)throw Error('No encontrado '+id);Object.assign(q,p,{v:'VALIDADA_ORIGINAL'});}

const childId='SM_MAYO_1_SOL_1_120';
const ci=adult.findIndex(q=>q.id===childId);if(ci<0)throw Error('No child record');
const cq=adult.splice(ci,1)[0];
Object.assign(cq,{s:'Clínica Infantojuvenil',t:['Trastornos relacionados con traumas y factores de estrés infantojuveniles'],e:'En un menor de seis años con TEPT, ¿cuál de las siguientes manifestaciones está contemplada por el DSM-5-TR?',o:{a:'No puede diagnosticarse TEPT antes de los seis años.',b:'Los recuerdos intrusivos pueden no parecer angustiosos y expresarse mediante la recreación en el juego.',c:'La exposición exclusivamente mediante televisión o fotografías siempre cumple el criterio de trauma.',d:'La irritabilidad obliga a diagnosticar un trastorno negativista desafiante.'},c:'b',x:'La b es correcta: en menores de seis años los recuerdos intrusivos pueden no manifestarse como angustiosos y aparecer como recreación en el juego. La a es falsa porque existen criterios preescolares específicos. La c es falsa: la exposición electrónica no cuenta salvo que esté relacionada con el trabajo, circunstancia impropia de este grupo. La d es falsa porque irritabilidad y rabietas extremas pueden formar parte del TEPT y no obligan a un diagnóstico de trastorno negativista desafiante.',r:'American Psychiatric Association (2022). DSM-5-TR. Trastorno de estrés postraumático en niños de seis años o menores, criterios A, B y D.',v:'VALIDADA_ORIGINAL'});
child.push(cq);

fs.writeFileSync(adultPath,JSON.stringify(adult));
fs.writeFileSync(childPath,JSON.stringify(child));
const mp=P+'manifest.json',m=JSON.parse(fs.readFileSync(mp,'utf8'));
m.subjects['Clínica Adultos'].count=adult.length;m.subjects['Clínica Infantojuvenil'].count=child.length;
fs.writeFileSync(mp,JSON.stringify(m,null,2)+'\n');
console.log(JSON.stringify({adult:adult.length,child:child.length,alcoholNew:'R0PIR_CA_ADICCIONES_HEREDABILIDAD_ALCOHOL_20260902',traumaUpdated:Object.keys(U).length,childMoved:childId}));
