const fs=require('fs');const dir='public/banco/';
const names=['psicopatologia.json','clinica_adultos.json','clinica_infantojuvenil.json','tratamientos_adultos.json','tratamientos_infantiles.json','psicologia_experimental.json','psicologia_de_la_personalidad_y_diferencial.json'];
const b=Object.fromEntries(names.map(n=>[n,JSON.parse(fs.readFileSync(dir+n,'utf8'))]));
const psy=b['psicopatologia.json'];const all=()=>Object.values(b).flat();
const dsm='American Psychiatric Association (2022). Manual diagnóstico y estadístico de los trastornos mentales, texto revisado (DSM-5-TR). Editorial Médica Panamericana.';
const bel='Belloch, A., Sandín, B. y Ramos, F. (coords.) (2024). Manual de psicopatología, vols. I-II (4.ª ed.). McGraw Hill.';
function find(id){const q=all().find(x=>x.id===id);if(!q)throw Error(id);return q;}function u(id,z){Object.assign(find(id),z,{v:'VALIDADA_ORIGINAL'});}function move(id,from,to){const i=b[from].findIndex(x=>x.id===id);if(i<0)throw Error('move '+id);const[q]=b[from].splice(i,1);if(!b[to].some(x=>x.id===id))b[to].push(q);}
u('1Simulacro02018Comentarios_020',{s:'Clínica Infantojuvenil',t:['Trastornos de eliminación infantojuveniles'],e:'Se denomina enuresis secundaria a la que:',o:{a:'Aparece después de un periodo de continencia urinaria establecida.',b:'Se desarrolla como consecuencia de la encopresis.',c:'Se explica necesariamente por otro trastorno mental.',d:'Solo aparece en menores con hermanos mayores.'},c:'a',x:'La enuresis secundaria aparece después de que el niño haya alcanzado continencia durante un periodo significativo, habitualmente al menos seis meses. La primaria existe desde que se esperaba adquirir el control.',r:dsm});move('1Simulacro02018Comentarios_020','psicopatologia.json','clinica_infantojuvenil.json');
u('SM_MAYO_1_SOL_1_083',{s:'Clínica Adultos',t:['Trastornos por síntomas somáticos y relacionados'],e:'Según el DSM-5, señale la afirmación correcta sobre el trastorno de síntomas somáticos:',o:{a:'Los síntomas deben carecer necesariamente de explicación médica.',b:'Debe existir al menos un pensamiento, sentimiento o comportamiento excesivo relacionado con los síntomas o la preocupación por la salud.',c:'El especificador persistente exige más de doce meses.',d:'En niños la duración mínima aumenta a doce meses.'},c:'b',x:'El diagnóstico no exige que el síntoma sea médicamente inexplicable. Requiere pensamientos, sentimientos o conductas excesivos y un estado sintomático persistente, normalmente superior a seis meses; el especificador persistente describe un curso grave y prolongado.',r:dsm});move('SM_MAYO_1_SOL_1_083','psicopatologia.json','clinica_adultos.json');
u('SmCm1PIR2024_084',{s:'Clínica Adultos',t:['Trastornos de ansiedad'],e:'Señale la afirmación correcta sobre el trastorno de pánico:',o:{a:'Su prevalencia anual en la población general es del 5-7 %.',b:'Las mujeres presentan exactamente el triple de riesgo que los hombres en todos los estudios.',c:'Presenta comorbilidad relevante con diversas enfermedades médicas.',d:'La comorbilidad con el trastorno bipolar es baja.'},c:'c',x:'El trastorno de pánico se asocia con patología respiratoria, cardiovascular, vestibular y otras afecciones médicas. La prevalencia anual suele situarse alrededor del 2-3 %; es más frecuente en mujeres, sin una razón fija universal de 3:1, y la comorbilidad bipolar es relevante.',r:dsm});move('SmCm1PIR2024_084','psicopatologia.json','clinica_adultos.json');
u('SmCm18PIR2025_094',{t:['Psicopatología de la sensopercepción'],e:'¿Cuál de los siguientes pares constituye variantes fenomenológicas de la experiencia alucinatoria?',o:{a:'Alucinación negativa y alucinación positiva.',b:'Alucinación funcional y alucinación refleja.',c:'Imágenes hipnagógicas e imágenes consecutivas.',d:'Dismegalopsias y dismorfopsias.'},c:'b',x:'Las alucinaciones funcionales y reflejas son variantes de la experiencia alucinatoria según la relación con un estímulo real. Las imágenes fisiológicas y consecutivas no son alucinaciones; dismegalopsias y dismorfopsias son distorsiones perceptivas.',r:bel});
u('4Simulacro02018Comentarios_001',{s:'Tratamientos Infantiles',t:['Trastorno del Espectro Autista'],e:'Señale la afirmación correcta sobre el tratamiento de un niño con trastorno del espectro autista:',o:{a:'Debe demorarse la intervención para no interferir con el desarrollo natural.',b:'Pueden emplearse antipsicóticos para reducir irritabilidad, agitación o agresividad graves, aunque no tratan los síntomas nucleares.',c:'Los fármacos están siempre contraindicados.',d:'El modelo DIR es el único tratamiento psicológico bien establecido.'},c:'b',x:'La intervención temprana es recomendable. Algunos antipsicóticos pueden utilizarse para irritabilidad y conductas agresivas graves, con valoración individual de riesgos; no modifican por sí mismos los síntomas nucleares del TEA.',r:'Fonseca Pedrero, E. (coord.) (2021). Manual de tratamientos psicológicos: Infancia y adolescencia. Pirámide.'});move('4Simulacro02018Comentarios_001','psicopatologia.json','tratamientos_infantiles.json');
u('SM_ABRIL_2_SOL_1_079',{t:['Psicopatología del pensamiento'],e:'La intuición delirante primaria se caracteriza por:',o:{a:'La reconstrucción delirante de un recuerdo.',b:'La vivencia indefinida de que el mundo ha cambiado de forma inquietante.',c:'La atribución delirante de significado a una percepción normal.',d:'La aparición súbita de una idea delirante completa, semejante formalmente a una idea que viene de pronto a la mente.'},c:'d',x:'La intuición delirante surge de forma súbita y aparentemente inmotivada. Las otras opciones corresponden a recuerdo delirante, atmósfera delirante y percepción delirante.',r:bel});
u('SmCm17PIR2025_072',{s:'Clínica Infantojuvenil',t:['Trastornos disruptivos, del control de los impulsos y de la conducta infantojuveniles'],e:'Según el DSM-5-TR, ¿cuánto deben durar los síntomas del trastorno negativista desafiante?',o:{a:'Tres meses.',b:'Seis meses.',c:'Un mes.',d:'Doce meses.'},c:'b',x:'El patrón de enfado/irritabilidad, discusiones o actitud desafiante y venganza debe mantenerse al menos seis meses.',r:dsm});move('SmCm17PIR2025_072','psicopatologia.json','clinica_infantojuvenil.json');
u('SM_JULIO_2_SOL_1_026',{t:['Psicopatología del pensamiento'],e:'¿Cuál de los siguientes no es un tipo de vivencia delirante primaria en la psicopatología de Jaspers?',o:{a:'Percepción delirante.',b:'Atmósfera delirante.',c:'Humor delirante.',d:'Creación delirante.'},c:'d',x:'Jaspers describió percepción, intuición, atmósfera o humor y recuerdo delirantes. «Creación delirante» no pertenece a esa clasificación.',r:bel});
u('SmCm17PIR2025_078',{t:['Psicopatología de la memoria'],e:'La amnesia orgánica se diferencia habitualmente de la psicógena porque:',o:{a:'Mejora específicamente con tranquilizantes.',b:'Fluctúa siempre en función del estrés.',c:'Predomina la alteración anterógrada.',d:'Predomina exclusivamente la amnesia retrógrada.'},c:'c',x:'En la amnesia orgánica suele destacar la dificultad para adquirir nueva información, mientras que la amnesia disociativa afecta típicamente a recuerdos autobiográficos retrógrados vinculados a acontecimientos traumáticos.',r:bel});
u('SM_DICIEMBRE_2_SOL_1_056',{t:['Psicopatología del pensamiento'],e:'¿Cómo se denomina clásicamente el periodo prodrómico previo a la eclosión del delirio?',o:{a:'Trema o humor delirante.',b:'Delirium tremens.',c:'Estadio conversivo.',d:'Estupor.'},c:'a',x:'Conrad denominó «trema» a la fase de tensión y extrañeza previa a la cristalización delirante. La opción original «estado asténico-apático» no era la denominación precisa.',r:bel});
u('PERSEVER___SIMULACRO_COMENTADO_MAYO-UNO-23_072',{t:['Psicopatología del pensamiento'],e:'Ante una pregunta concreta, un paciente responde repitiendo insistentemente que le gusta leer y vuelve una y otra vez al mismo contenido. ¿Qué alteración formal presenta?',o:{a:'Ecolalia.',b:'Perseveración.',c:'Circunstancialidad.',d:'Alogia.'},c:'b',x:'La perseveración consiste en mantener o repetir palabras, ideas o temas más allá del punto en que resultan pertinentes. No es ecolalia, pobreza del habla ni una respuesta circunstancial que finalmente aporta detalles relevantes.',r:bel});
u('SmCm15PIR2025_095',{s:'Tratamientos Adultos',t:['Tratamiento de las adicciones'],e:'¿Cuál de las siguientes intervenciones para el trastorno por consumo de alcohol no alcanza habitualmente un grado de recomendación A?',o:{a:'Exposición a señales o pistas.',b:'Terapia cognitivo-conductual.',c:'Terapia de aumento motivacional.',d:'Intervenciones motivacionales breves.'},c:'a',x:'La TCC, el aumento motivacional y las intervenciones motivacionales breves cuentan con respaldo robusto. La exposición a pistas presenta resultados menos consistentes y una recomendación inferior.',r:'Fonseca Pedrero, E. (coord.) (2021). Manual de tratamientos psicológicos: Adultos. Pirámide.'});move('SmCm15PIR2025_095','psicopatologia.json','tratamientos_adultos.json');
u('Simu 32 comentado hardcore 2_111',{t:['Psicopatología del lenguaje'],e:'Un paciente dice: «Ayer vi un fluricón en la calle; estaba lleno de sombretinas». ¿Qué alteración ejemplifica?',o:{a:'Ecolalia.',b:'Perseveración.',c:'Neologismos.',d:'Aproximaciones a palabras.'},c:'c',x:'«Fluricón» y «sombretinas» son palabras nuevas creadas por el paciente y sin significado convencional: neologismos.',r:bel});
u('SM_MAYO_1_SOL_1_078',{t:['Psicopatología del pensamiento'],e:'Un paciente responde con una sucesión de ideas sin conexión comprensible: «Mis padres vuelan, los pájaros corren... El control del libro es tabaco...». ¿Qué alteración formal presenta?',o:{a:'Descarrilamiento.',b:'Fuga de ideas.',c:'Paragramatismo.',d:'Ilogicidad.'},c:'a',x:'En el descarrilamiento, el discurso pasa de una idea a otra con relaciones oblicuas o inexistentes. La fuga conserva asociaciones aceleradas; el paragramatismo afecta la construcción gramatical y la ilogicidad las inferencias.',r:bel});
u('SmCm1PIR2024_085',{s:'Clínica Adultos',t:['Trastornos del espectro de la esquizofrenia'],e:'El mayor riesgo de conducta suicida en los trastornos psicóticos se concentra en:',o:{a:'La fase prodrómica aislada.',b:'Los primeros años tras el inicio del trastorno.',c:'Exclusivamente los trastornos de muy larga evolución.',d:'Los cuadros de inicio tardío entre 40 y 60 años.'},c:'b',x:'El riesgo es especialmente elevado en las primeras fases y años de evolución, en particular tras el primer episodio y durante periodos depresivos o posteriores al alta.',r:dsm});move('SmCm1PIR2024_085','psicopatologia.json','clinica_adultos.json');
u('SmCm23PIR2025 (2)_206',{s:'Clínica Adultos',t:['Trastornos del espectro de la esquizofrenia'],e:'En las teorías cognitivas de los delirios, ¿con qué se relaciona especialmente el sesgo contra la evidencia desconfirmatoria (BADE)?',o:{a:'Con el contenido temático concreto.',b:'Con la atribución interna de sucesos negativos.',c:'Con los síntomas negativos.',d:'Con la gravedad o intensidad de los delirios.'},c:'d',x:'El BADE consiste en integrar insuficientemente información que contradice una creencia y se ha relacionado con mayor convicción o gravedad delirante, más que con un contenido específico.',r:bel});move('SmCm23PIR2025 (2)_206','psicopatologia.json','clinica_adultos.json');
u('SmCm3PIR2024_092',{t:['Psicopatología de la sensopercepción'],e:'¿En qué modalidad alucinatoria es escasa o nula la convicción de realidad exterior de la imagen?',o:{a:'Pseudoalucinación.',b:'Alucinación funcional.',c:'Imagen alucinante.',d:'Imagen refleja.'},c:'a',x:'En la pseudoalucinación la experiencia suele localizarse en el espacio interno y carece de plena convicción de realidad externa.',r:bel});
u('SmCm14PIR2025_111',{t:['Psicopatología del pensamiento'],e:'¿Qué dimensión delirante describe que la creencia se mantenga pese a evidencias contrarias?',o:{a:'Convicción.',b:'Ausencia de apoyo cultural.',c:'Implausibilidad.',d:'Inmodificabilidad, incorregibilidad o fijeza.'},c:'d',x:'La inmodificabilidad es la resistencia de la creencia a cambiar incluso ante argumentos o pruebas que la contradicen.',r:bel});
u('SmCm23PIR2025 (2)_209',{s:'Psicología Experimental',t:['Método científico y experimental'],e:'Para interpretar la relación entre inteligencia y éxito profesional puede ser necesario controlar una tercera variable como:',o:{a:'Aprendizaje de sílabas.',b:'Edad.',c:'Nivel educativo.',d:'La propia puntuación de CI.'},c:'c',x:'El nivel educativo puede relacionarse tanto con las puntuaciones de inteligencia como con el éxito profesional y actuar como variable extraña o de confusión.',r:'León, O. G. y Montero, I. (2020). Métodos de investigación en psicología y educación. McGraw Hill.'});move('SmCm23PIR2025 (2)_209','psicopatologia.json','psicologia_experimental.json');
u('PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-DOS-23_035',{t:['Psicopatología del pensamiento'],e:'Señale la alternativa incorrecta sobre ideas sobrevaloradas y valores idealizados:',o:{a:'Para Veale, las ideas sobrevaloradas pueden ser secundarias a valores idealizados.',b:'Los valores idealizados son dominantes y se integran excesivamente en la identidad.',c:'La importancia concedida al control del peso en anorexia o a la apariencia en dismorfia corporal son ejemplos de ideas sobrevaloradas, no de valores idealizados.',d:'Una idea sobrevalorada no suele ser compartida por la cultura o subcultura.'},c:'c',x:'La c es incorrecta en el marco de Veale: el control del peso o la apariencia pueden funcionar como valores idealizados dominantes, de los que derivan ideas sobrevaloradas. Estas no alcanzan necesariamente la fijeza delirante.',r:bel});
u('SEPTIEMBRE-DOS-24_COMENTADO_095',{s:'Clínica Adultos',t:['Conducta suicida y autolesión'],e:'¿Qué concepto describe una conducta autoinfligida potencialmente lesiva con intención, implícita o explícita, de morir?',o:{a:'Amenaza suicida.',b:'Autolesión no suicida.',c:'Ideación suicida.',d:'Intento de suicidio.'},c:'d',x:'Un intento de suicidio es una conducta autoinfligida potencialmente lesiva realizada con alguna intención de morir. La ideación no implica necesariamente conducta y la autolesión no suicida carece de esa intención.',r:dsm});move('SEPTIEMBRE-DOS-24_COMENTADO_095','psicopatologia.json','clinica_adultos.json');
u('1Simulacro02018Comentarios_021',{s:'Tratamientos Infantiles',t:['TDAH'],e:'El entrenamiento en correspondencia, regulación, autoinstrucciones y la técnica de la tortuga se utilizan en el tratamiento de:',o:{a:'Dificultades lectoras.',b:'Problemas atencionales aislados.',c:'Trastornos del habla.',d:'TDAH y problemas de autorregulación asociados.'},c:'d',x:'Estas técnicas enseñan autocontrol, solución de problemas y regulación conductual, por lo que se emplean en intervenciones para TDAH.',r:'Fonseca Pedrero, E. (coord.) (2021). Manual de tratamientos psicológicos: Infancia y adolescencia. Pirámide.'});move('1Simulacro02018Comentarios_021','psicopatologia.json','tratamientos_infantiles.json');
u('SmCm06PIR2025_066',{t:['Psicopatología del pensamiento'],e:'¿Qué sostuvo la escuela de Heidelberg en su teoría clásica de los delirios?',o:{a:'Distinguió delirios primarios y secundarios atendiendo a la comprensibilidad psicológica de su origen.',b:'Explicó todo delirio como fracaso del razonamiento silogístico.',c:'Lo redujo al mecanismo de defensa de proyección.',d:'Lo explicó exclusivamente por debilitamiento de asociaciones.'},c:'a',x:'La escuela de Heidelberg, vinculada a Jaspers, distinguió vivencias delirantes primarias incomprensibles y delirios secundarios comprensibles a partir de otros estados psicológicos.',r:bel});
u('SmCm4PIR2024_074',{s:'Clínica Adultos',t:['TOC'],e:'¿A qué trastorno corresponde arrancarse repetidamente el vello púbico o perirrectal e intentar dejar de hacerlo sin éxito?',o:{a:'Tricotilomanía o trastorno de arrancarse el pelo.',b:'Trastorno obsesivo-compulsivo.',c:'Otro trastorno parafílico.',d:'Trastorno delirante.'},c:'a',x:'La localización del pelo no modifica el diagnóstico: el arrancamiento recurrente con intentos de disminuirlo y pérdida de pelo corresponde a tricotilomanía.',r:dsm});move('SmCm4PIR2024_074','psicopatologia.json','clinica_adultos.json');
u('PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-DOS-23_033',{s:'Clínica Infantojuvenil',t:['Trastorno obsesivo-compulsivo y relacionados infantojuveniles'],e:'¿Qué ritual puede considerarse evolutivamente normal a la edad indicada?',o:{a:'A los 2-3 años, pedir otro beso, agua o la repetición del cuento antes de dormir.',b:'A los 3-4 años, rituales complejos de no pisar juntas durante periodos prolongados.',c:'A los 7-9 años, compulsiones rígidas para neutralizar cualquier pensamiento.',d:'A los 12-18 años, juegos invariables propios de la primera infancia.'},c:'a',x:'En torno a los 2-3 años son frecuentes rituales de acostarse y peticiones repetitivas. Su carácter evolutivo se distingue del TOC por flexibilidad, ausencia de malestar intenso y escasa interferencia.',r:'Fonseca Pedrero, E. (coord.) (2021). Manual de tratamientos psicológicos: Infancia y adolescencia. Pirámide.'});move('PERSEVER___SIMULACRO_COMENTADO_SEPTIEMBRE-DOS-23_033','psicopatologia.json','clinica_infantojuvenil.json');
u('SmCm11PIR2025_079',{s:'Psicología de la Personalidad y Diferencial',t:['Teorías cognitivas de la personalidad'],e:'¿Cuál de las siguientes características de los esquemas cognitivos es incorrecta?',o:{a:'Son unidades cognitivas de alto nivel.',b:'Pueden encajarse jerárquicamente unos en otros.',c:'Pueden actualizarse con la experiencia.',d:'Poseen necesariamente un carácter unifactorial.'},c:'d',x:'Los esquemas son estructuras complejas, jerárquicas y modificables; no son necesariamente unifactoriales.',r:'Fierro, A. (coord.). Manual de psicología de la personalidad. McGraw Hill.'});
u('SmCm5PIR2024_146',{t:['Psicopatología de la sensopercepción'],e:'¿Cuál de las siguientes alteraciones es una distorsión perceptiva?',o:{a:'Dismorfopsia.',b:'Imagen hipnagógica.',c:'Pseudoalucinación.',d:'Imagen autoscópica.'},c:'a',x:'La dismorfopsia es una metamorfopsia: se percibe deformada la forma de un objeto real. Las otras opciones son engaños o imágenes perceptivas anómalas sin distorsión de un estímulo presente.',r:bel});
// Eliminamos las copias peor ubicadas de dos preguntas ya conservadas y corregidas.
for(const id of ['Simu 6 comentado__111','Simu 11 comentado_205']){const i=psy.findIndex(x=>x.id===id);if(i>=0)psy.splice(i,1);}
for(const n of names)fs.writeFileSync(dir+n,JSON.stringify(b[n]));console.log('Corregidas y reubicadas 27 preguntas mezcladas.');
