import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),bank=path.join(root,'public','banco');const m=JSON.parse(fs.readFileSync(path.join(bank,'manifest.json'),'utf8'));const ds=new Map(Object.entries(m.subjects).map(([s,v])=>[s,JSON.parse(fs.readFileSync(path.join(bank,v.slug+'.json'),'utf8'))]));const ta=ds.get('Tratamientos Adultos'),topic='Tratamiento de la psicosis y esquizofrenia';const pending=ta.filter(q=>q.t?.[0]===topic&&!['VALIDADA_ORIGINAL','CORREGIDA'].includes(q.v));if(pending.length!==142)throw Error('Esperadas 142, hay '+pending.length);
const moves={
'PERSEVER___SIMULACRO_COMENTADO_ENERO-UNO-23_189':['Tratamientos Adultos','Tratamiento de los trastornos somáticos'],
'PERSEVER___SIMULACRO_COMENTADO_JUNIO-UNO-23_174':['Psicoterapias','Terapias humanistas y existenciales'],
'PERSEVER___SIMULACRO_COMENTADO_NOVIEMBRE-DOS-23_111':['Clínica Adultos','Trastornos del espectro de la esquizofrenia'],
'SmCm1PIR2024_160':['Psicopatología','Psicopatología del pensamiento'],
'SmCm1PIR2024_175':['Tratamientos Adultos','Tratamiento de los trastornos alimentarios'],
'SmCm20PIR2024_062':['Tratamientos Adultos','Tratamiento de la depresión y trastornos del ánimo'],
'SmCm20PIR2024_142':['Tratamientos Adultos','Tratamiento de los trastornos de ansiedad'],
'SmCm20PIR2024_156':['Tratamientos Adultos','Tratamiento de las adicciones'],
'SmCm20PIR2025 (1)_154':['Clínica Adultos','Conducta suicida y autolesión'],
'SmCm20PIR2025 (1)_155':['Clínica Adultos','Conducta suicida y autolesión'],
'SmCm21PIR2025 (2)_061':['Tratamientos Adultos','Tratamiento de los trastornos de ansiedad'],
'SmCm22PIR2025 (1)_152':['Tratamientos Adultos','Tratamiento de los trastornos somáticos'],
'SmCm22PIR2025_173':['Tratamientos Adultos','Tratamiento de los trastornos somáticos'],
'SmCm23PIR2025 (2)_009':['Tratamientos Adultos','Tratamiento de los trastornos de personalidad'],
'SmCm23PIR2025 (2)_050':['Tratamientos Infantiles','Trastornos de ansiedad infantojuvenil'],
'SmCm23PIR2025 (2)_153':['Tratamientos Adultos','Tratamiento de los trastornos de personalidad'],
'SmCm23PIR2025 (2)_156':['Tratamientos Adultos','Tratamiento de los trastornos de personalidad'],
'SmCm23PIR2025 (2)_157':['Tratamientos Adultos','Tratamiento de los trastornos de personalidad'],
'SmCm23PIR2025 (2)_158':['Tratamientos Adultos','Tratamiento del TOC y relacionados'],
'SmCm23PIR2025 (2)_160':['Tratamientos Adultos','Tratamiento de las adicciones'],
'SmCm23PIR2025 (2)_172':['Tratamientos Adultos','Tratamiento de las adicciones'],
'SmCm23PIR2025 (2)_173':['Tratamientos Adultos','Tratamiento de los trastornos disociativos'],
'SmCm23PIR2025_007':['Psicología Social','Procesos de grupo'],
'SmCm23PIR2025_049':['Tratamientos Adultos','Tratamiento del TOC y relacionados'],
'SmCm23PIR2025_052':['Psicoterapias','Psicoanálisis y terapias psicodinámicas'],
'SmCm23PIR2025_147':['Tratamientos Adultos','Tratamiento de los trastornos de personalidad'],
'SmCm23PIR2025_157':['Tratamientos Adultos','Tratamiento de los trastornos alimentarios'],
'SmCm24PIR2025 (1)_002':['Tratamientos Adultos','Tratamiento del TOC y relacionados'],
'SmCm24PIR2025 (1)_082':['Tratamientos Adultos','Tratamiento de la depresión y trastornos del ánimo'],
'SmCm24PIR2025 (1)_093':['Tratamientos Adultos','Tratamiento del trauma y TEPT'],
'SmCm27PIR2025 (1)_069':['Tratamientos Adultos','Introducción'],
'SmCm27PIR2025 (1)_070':['Tratamientos Adultos','Tratamiento de las adicciones'],
'SmCm29PIR2025_057':['Tratamientos Adultos','Tratamiento del trauma y TEPT'],
'SmCm29PIR2025_158':['Tratamientos Infantiles','TDAH'],
'SmCm29PIR2025_182':['Tratamientos Infantiles','Trastornos de ansiedad infantojuvenil'],
'SmCm4PIR2024_132':['Evaluación Psicológica','La entrevista'],
'SmCm4PIR2024_134':['Tratamientos Adultos','Tratamiento de los trastornos disociativos'],
'SmCm4PIR2024_155':['Tratamientos Adultos','Tratamiento de los trastornos de personalidad'],
'SmCm7PIR2024_104':['Tratamientos Adultos','Tratamiento de los trastornos de personalidad']};
const ids=new Set(pending.map(q=>q.id));for(const id of Object.keys(moves))if(!ids.has(id))throw Error('Fuera del lote '+id);ds.set('Tratamientos Adultos',ta.filter(q=>!moves[q.id]));const moved=[];for(const q of pending){if(!moves[q.id])continue;const[s,t]=moves[q.id];if(!m.subjects[s]?.topics.includes(t))throw Error(s+' > '+t);ds.get(s).push({...q,s,t:[t],v:'REVISAR'});moved.push({id:q.id,to:s+' > '+t});}const all=[...ds.values()].flat();if(all.length!==m.total||new Set(all.map(q=>q.id)).size!==all.length)throw Error('integridad');for(const[s,d]of ds){m.subjects[s].count=d.length;fs.writeFileSync(path.join(bank,m.subjects[s].slug+'.json'),JSON.stringify(d)+'\n');}fs.writeFileSync(path.join(bank,'manifest.json'),JSON.stringify(m,null,2)+'\n');const remaining=ds.get('Tratamientos Adultos').filter(q=>q.t?.[0]===topic&&!['VALIDADA_ORIGINAL','CORREGIDA'].includes(q.v));const report={screened:142,mechanical:{missingExplanation:102,missingReference:120,ocrOrContamination:39,invalidKey:0,emptyOption:0},exactDuplicates:[['Simu 16 comentado_136','SmCm16PIR2025_138']],moved,remaining:remaining.map(q=>q.id)};fs.writeFileSync(path.join(root,'auditorias','tratamientos_psicosis_criba_142_20260902.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({screened:142,rehomed:moved.length,remaining:remaining.length,total:all.length,unique:new Set(all.map(q=>q.id)).size},null,2));
